### ISSUE TITLE
Block Logging

### ISSUE THREAD

**Issue by ghost** [LatvianModder/FTBUtilities#101]
Would be very helpful to have the option to log who breaks or places blocks. A simple log file would be great.

**Comment by Beleric** [comment]
I'd like to second that notion. Just spent a few hours researching in-game solutions to tracking griefers at the spawn point that we have laboriously cultivated and they are woefully unpromising. This would be especially helpful if you could control the log by specific chunks to preclude endless time spent sorting through data.

Thanks for your time.
