### ISSUE TITLE
Strang behaviour in loaded chunks

### ISSUE THREAD

**Issue by OberProGamerY** [LatvianModder/FTBUtilities#102]
Me and my friends currently have a Infinity Evolved 2.4.2 running, to produce RF for our city and future project I build a self sustaining power plant.
It plants trees using the MFR planter and harvest them using the MFR harvester, turning them into charcoal with two Redstone furnaces and burning it in a Railcraft HP boiler; the steam is then used to power a Big Reactor turbine.
We want this power plant to be constantly loaded on the server, so I claimed and loaded the corresponding chunks; this however caused some strange behaviour:
1. The trees get chopped down, but they appear to stop growing once you leave the server. When I entered the server this afternoon, there were only tree sapplings, so the planted and harvester both worked fine.
2. The two redstone furnaces seem to stop working aswell, they both have wood in them, but the buildcraft pipe leading to the HP boiler is empty. The moment you enter the server, you can see that they start outputting the charcoal.
3. The boiler was nearly out of fuel, which is the strangest thing. The HP boiler practically eats through charcoal and it can only store 4 stacks, where only 1 was left when I watched. It consumes a charcoal every 3.3s, so that means 3 stacks should have taken only around 600 seconds to consume; not even close enough to run 12 hours straight, without anyone entering the server.
I did a A/B test with unclaimed chunks and waited half an hour, the boiler was nearly full somehow. The buildcraft pipes still had items in them and the tree farm was half full; so the server apparently unloaded the chunks a few minutes after I left.

We se the chunkloader_type to "offline" and offline_chunkloader_timer to "24.0".

I really don't know what to make of this, is this a bug?

**Comment by LatvianModder** [comment]
You have to load all chunks, not only ones containing machines, but also the ones where you plant trees and all pipelines and machines. It could be that harvester and planter plants saplings, but they dont grow, because sapling chunks arent loaded. As for machines, it could be that some parts of pipes arent loaded

**Comment by OberProGamerY** [comment]
I did load all chunks necessary, I even tried loading the chunks around the place that needs to be loaded. The entire structure is loaded, I confirmed it with the /admin loaded_chunks command, the coordinates are all correct.
I tested something: I attached a tesseract to the turbine and then went to the nether, there I placed a redstone furnace next to another tesseract which started charging the furnace. I turned off the chunk_loading in the settings and executed /reload: the tesseract still charged the furnace, 
I then executed a /reload_client and it suddenly stopped; I replaced the furnace but it didn't charge anymore. 
I reactivated the chunk_loading and the furnace was charged again.

Could this info be of any use to you? The server was empty except for me.

**Comment by OberProGamerY** [comment]
Okay, I just found out what was going wrong, it was on OUR end:
I totally forgot, that trees won't grow in the night/dark, so whenever it was night, there was no coal produced. I didn't think about that, because whenever somebody is on the server, we always reset to day, due to that, the tree farm was running 100% during that time.
I adjusted a few things and integrated a buffer, after a test with 3h interval, the system now works correctly and the boilers (got 2 now) are filled with coal 24/7.
I can also use the energy via a tesseract, now matter wherever I am and the power plant powers everything correctly all of the time.

Sorry for wasting your time :/

PS: This is probably the best chunkloader at the moment, especially because you can simply use a map to choose which chunks to load and works flawlessly (especially compared to me here...)

**Comment by LatvianModder** [comment]
I'm glad that sorted out :)
