### ISSUE TITLE
Suggestion: Restart at specific time

### ISSUE THREAD

**Issue by Optimoos** [LatvianModder/FTBUtilities#104]
Maybe I've just missed the setting or config option to do this, but I think it'd be very helpful to have a "restart at" config option rather than "restart in" ... typically if I'm starting the server I'm awake and wanting to use it, whereas I could set restart at to be for 06:00 when people are very unlikely to be on.

I've looked around trying to figure out how to do this with FTB Utils and haven't found a way.

**Comment by Fearzu** [comment]
Optimoos,

Are you using a hosting service with Multicraft? If so you can schedule a task to do this for you pretty easily, for specific times of the day. You can even specify only to do so if the server is empty. Just a thought.

**Comment by Optimoos** [comment]
I'm hosting on my own server. I can schedule restarts via my own methods externally but that's not really the issue. My point is more along the line that as FTBUtils provides one restart method, it would be nice if it provided, what is in my opinion, a more useful version of the function.

**Comment by LatvianModder** [comment]
That's actually how it used to work, but it sometimes missed the exact time and so I just made it easier for everyone, restart after x hours.
The config would probably look smth like this: (defaults to the previous system ofc)
"restart_times": [ "00:00", "12:00", "15:00" ] and so on

**Comment by Dijkstra1** [comment]
Why don't have it read the next restart time and have it calculate that the server needs to restart x minutes.

**Comment by Optimoos** [comment]
What Dijkstra1 is suggesting is what I was thinking, seeing as the countdown to restart seems to be frustratingly accurate :)
