### ISSUE TITLE
[1.7.10] do guides need to on both sides

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#105]
I am working on my modpack with three game modes, it is currently in alpha testing just me and my sister so i have the pack running on a server, now I know that minetweaker pushes scripts from the server to clients, I though the guide work something like that but seems not I have now copied the guide to three locations (the server, my PC, my sisters, PC) and it works, I was hoping, that i could write scripts on the server and have the dynamically update likes scripts. Is this possible and if not can it be made possible, because I now some server owner would like to add a page to guide with server and things like that are not part of the pack.

**Comment by LatvianModder** [comment]
You can put server guides in /local/guide/

**Comment by Dijkstra1** [comment]
Yes but the server does not seem to push the guide out the clients or at least not when I have tried i am using FTBUtilities-1.7.10-1.0.18.3, it was the latest when i downloaded it, can not say that for sure now.

**Comment by LatvianModder** [comment]
It shows the server guide under Server Info, not the regular Guide. Or should, at least

**Comment by Dijkstra1** [comment]
Ah, I was just checking guide, will now check the other book.
