### ISSUE TITLE
How do you add players to the admin group?

### ISSUE THREAD

**Issue by rustyshakelford2** [LatvianModder/FTBUtilities#107]
I'm sorry if this is a stupid question, but how do you set players to admin? I've poured over the documentation and config and I can't find it.

**Comment by Dijkstra1** [comment]
This is not an FTBU thing this is purely vanilla stuff, as admins are just ops, and you can make an player an op by using the command /op player's Name (remember to make case) in the server, interface, or get an oped player to do it.

**Comment by Fearzu** [comment]
/op playerName  - makes player operator
/deop playerName - removes player as operator

**Comment by rustyshakelford2** [comment]
Thanks, though I was hoping there was permissions support as I have other plugins I don't want to give out OP permissions for. Perhaps this could be added?

**Comment by LatvianModder** [comment]
Admin=vanilla OP for now, but nothing new will be added in 1.7.10, its locked feature-wise. In 1.9+ there will be permission groups for configs and commands

**Comment by rustyshakelford2** [comment]
Fair enough. Thank you.
