### ISSUE TITLE
Claim/load chunks in the End

### ISSUE THREAD

**Issue by KaseiFR** [LatvianModder/FTBUtilities#108]
Hi,

Using FTB Infinity Evolved Skyblock with FTBU 1.0.18.3, as a non admin user I don't seem to be able to claim or chunkload in the End. It works fine on the normal dimension and the Nether.

Is this a config issue? If so, which one?

Thanks.

**Comment by LatvianModder** [comment]
End is blacklisted by default, because its so small. But you can remove it in config.
/edit_config ftbu permissions_player permissions_player dimension_blacklist []
or go to /local/ftbu/config.json and edit it

**Comment by KaseiFR** [comment]
Thanks for the answer.

**Comment by Amzd** [comment]
For anyone stumbling across this issue now (like me).

On SMP it's under `serverconfig/ftbchunks-server.toml`
