### ISSUE TITLE
Lost data on restart 1.7.10 FTB Infinity 2.5

### ISSUE THREAD

**Issue by instinxx** [LatvianModder/FTBUtilities#109]
1.7.10 FTB Infinity 2.5 not running evolved

Server reboots are causing chunk claims and Home destinations to no longer work. (I suspect this will also affect warps)

I noticed in my /World folder I now have a "latmod" folder that contains LMPlayers.txt AND a "LatMod" folder that contains "Claimed Chunks.json","LMPlayers.dat" and "LMWorld.json" when I looked at my server backups. I only have a LatMod folder and it contains all 4 files. Please advise?

**Comment by LatvianModder** [comment]
remove the lowercase latmod folder, leave only LatMod. That was a bug

**Comment by Mochnant** [comment]
Had this same issue, good to know it was/is a bug.

@LatvianModder Was this fixed in a recent commit, or might it reoccur?

Thank you!
