### ISSUE TITLE
Add command for claiming chunks

### ISSUE THREAD

**Issue by skarl** [LatvianModder/FTBUtilities#111]
Hi,

i was wondering if I am somehow able to open the gui for claiming and loading a chunk in the spirit world. Since I try to build a second base there, it would be perfect if I could chunkload my farms there.
I am playing FTB Infinity Evolved Skyblock on a Server and I am an admin.
Currently I am able to open the "unclaim"-gui via console but i can't seem to find a command to open the claim gui - since witchery disables all inventory extensions.

Cheers

**Comment by skarl** [comment]
Just out of curiosity... was this a stupid question, already answered or obvious?

**Comment by LatvianModder** [comment]
Woops,sorry, I just forgot to reply yesterday >.<
Im not sure, I think you can't if the buttons arent visible.. The Unclaim gui should work as claiming gui for you too, just with the exception that you can unclaim any chunk, even the ones that aren't yours. There Could be one workaround, but I have to check if it works first.. Uno momento

**Comment by LatvianModder** [comment]
First, what FTBU version you are on?

**Comment by skarl** [comment]
Its the Skyblock 1.1.0 Pack - FTBU 1.0.18.2

Thanks for the try :)

**Comment by LatvianModder** [comment]
Ok, this might work:

Create a new file, local/guide/ClaimedChunks.txt (file name doesnt matter)

And add this line to it:

{"text":"Open Claimed Chunks Gui", "click":{"type":"gui","data":"claimed_chunks"}}

Then save, /reload and under Server Info there now should be Server Info > ClaimedChunks > That line. Click on it to open the gui

Not sure how it works on servers but worked in SP for me

**Comment by skarl** [comment]
Well the line is added and works if you can click the Server Info button... but how do i open the Server Info in the spirit world if i don't have any buttons in my inventory?
In the spirit world, you just have the vanilla Inventory (no addons).

**Comment by skarl** [comment]
I am an idiot... i used the /admin server_info

Thanks a lot for your help, that works. 

Cheers

**Comment by LatvianModder** [comment]
> In the spirit world, you just have the vanilla Inventory (no addons)
Dang. Forgot about that.. Then I can't fix that :D

**Comment by skarl** [comment]
Well i thought i found the solution but it seems I can't add the line to the "/admin server_info" file as well ... darn.
Is there any way to add a button to the "/edit_config ftbu" that opens the gui?

I tried to add it in:
"permissions_admin": {
"custom_config": {}
}

But i guess it don't have the knowledge to do it the right way - or it doesn't work at all.

**Comment by LatvianModder** [comment]
Added in 1.9.4-pre2
