### ISSUE TITLE
Possible Issue, Starting Items Not Working on 1.7.10?

### ISSUE THREAD

**Issue by jasonmbrown** [LatvianModder/FTBUtilities#112]
Ive Been trying to get Starting Items Working for the past 6 hours on 1.7.10, Either It doesn't Work for anything other then Apples or I have the Syntax wrong.

Currently I set the Config to look like this:
`  "starting_items": [
    "minecraft:apple 16 0",
    "minecraft:cooked_beef 32 0",
    "infinitycoins:\"Corundum Coin\" 2 0"
  ]
}`
Which Only gives me apples, and nothing more.

**Comment by LatvianModder** [comment]
"infinitycoins:\"Corundum Coin\" 2 0"
What even is that.. is that it's real item ID? If so, that won't work and that modder must be stabbed :P

**Comment by jasonmbrown** [comment]
I think I was just failing To get the syntax correct the Original ItemID was "infinitycoins:Corundum Coin" But I tried a bunch to get it to work with the escape character in different places since It didn't work when i did "\"infinitycoins:Corundum Coin\" 2 0". Although Now Im thinking My FTP Client Failed to upload the config to my server, Since I got the Beef

**Comment by LatvianModder** [comment]
Its not the json formatting, that is fine. Its the item that has a frikin space in its ID :P

**Comment by jasonmbrown** [comment]
ya theres a few items with Spaces in they're names, Ars Magika Has one as well

**Comment by LatvianModder** [comment]
Ugh. anyway, that will probably not work. Try spawning it with /give, if that works, its magic

**Comment by jasonmbrown** [comment]
well Is there an Alternative for me to get the item as a "Starting Kit"?.. I will try /give
