### ISSUE TITLE
Add chunk claimed / unclaimed events

### ISSUE THREAD

**Issue by jasonmbrown** [LatvianModder/FTBUtilities#113]
I was wondering If it would be possible to add in a feature to Automatically show Claimed Chunks on dynmap. Or if theres an API for FTBU that includes an "On_claim" event/function so I can write a small bit of code that would automatically Create a "dynmap Marker" on a claimed area.

if there isn't anything like that in an api, if possible could you add it in? *ps: Im running v1.7.10, Although I am not sure if your still doing new features for older versions* 

alternatively, Is there anyway to run a Script when a chunk is claimed/unclaimed? 

PS: If someone can let me know where the actual code for chunk claiming is I might look into it myself, I couldnt find it when I was digging in the source although I didnt spend very long.

**Comment by patrix87** [comment]
I would also really like to see that feature added.

Thanks
