### ISSUE TITLE
[Idea] New world type

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#114]
I have had this idea bouncing about in my head for the past week now, where there is config that enables skyblocks mode so in wold type if a user pick biomes o plenty/default they will get a normal world, but if they pick skyblock wold type by default they will get 3 x 3 x 3 of dirt unless the modpack has made an skyblocks template and then that will get used. This would change the layout of the modpack folder a little instead of have the game mode in the modpack folder it would normal, shared, and skyblock of cause the names of these folders should be configurable like game modes and in each of the folder would be the game mods most of zen script would go in shared, in normal would be things removing all recipes and hiding items from mods such EX Nihilo, and in the skyblocks folder would be the recipes for all items from mods such EX Nihilo and obviously you would want to write different over world and skyblocks guides. I hope this possible I love to make my first 1.9 pack.

**Comment by LatvianModder** [comment]
Sorry, I'm not responsible for pack making, just the FTBUtilities and FTBLib mods :P You might want to make this suggestion somewhere else, FTB forums prehaps (I dont really use any of those, so I dunno)

**Comment by Dijkstra1** [comment]
I just was just thinking that it would go well with game modes in FTB tweaks, if you will not I may try make an extension for it, would you be able to point me to the code that changes zs folder(s). But I think it will have to wait until minetweaker comes for 1.9.
