### ISSUE TITLE
[suggestion] any chance to get this to 1.9.4

### ISSUE THREAD

**Issue by wackoamd1** [LatvianModder/FTBUtilities#115]
as title says , any chance to get this for 1.9.4 .
there are no chunkloaders for 1.9.4 and even if there were , this is way more easy to keep chunks loaded without even more blocks.

now i dont know how difficult it would be to update this to 1.9.4 , im no coder but this is a amazing piece of coding

**Comment by LatvianModder** [comment]
Oh, it is being updated and im on 1.9.4 right now in DevEnv. Public release should be pretty soon

![alt text](http://i.imgur.com/x20I6hO.png "Claimed Chunks")
