### ISSUE TITLE
[Bug Report] NullPointerException caught during firing event ...TickEvent$RenderTickEvent... causing hard crash/freezes [Custom Modpack 1.8.9]

### ISSUE THREAD

**Issue by WilliamLC98** [LatvianModder/FTBUtilities#116]
Log here: http://paste.ee/p/HO7k3

I run a custom mod pack server that a friend of mine and I play on, and I've been regularly hard freezing for no apparent reason. I usually kill the instance within a minute or two when it does this, but this time around I left it and it produced the log above, seems to be connected to FTBL/U. Nothing noteworthy appears in the servers console log.

MC Ver. 1.8.9
Forge Ver. 11.15.1.1902

**Comment by LatvianModder** [comment]
Sorry, I don't support 1.8.9 anymore
