### ISSUE TITLE
(MC 1.7.10) FTBU Claimed Chunk Security & Carpenter's Blocks

### ISSUE THREAD

**Issue by Vaygrim** [LatvianModder/FTBUtilities#117]
We've been having an issue for a while across several versions of FTB Utilities where it won't let players update Carpenter's Blocks within their own claimed chunks. Only 'normal' solution is "/lmplayer_settings block_security false ", and as of FTBU v1.7.10-1.0.18.3 this command isn't resolving the problem anymore.

Do we need to whitelist Carpenter's Blocks somehow, or should we just turn off chunk claiming for the time being?

**Comment by LatvianModder** [comment]
It has always been kinda.. difficult.. with Carpenter's Blocks. Also, im way over 1.7.10, and my DevEnv is a mess atm, so I probably wont fix the bug. I guess you can unclaim, update CB and then re-claim again

**Comment by Vaygrim** [comment]
Actually we can't. This problem is persisting thru all chunks on the server, claimed or not. Seems to also only affect servers. I do get that you're 'over 1.7.10', I won't push the issue further.

It's just a real hassle as big chunks of the community still exist and work on that version right now. We can always pull FTBU from the pack, as the pack is very 'builder-centric' and this makes working with Carpenter's Blocks a real pain in the back side.

**Comment by LatvianModder** [comment]
Yeah, I know that 1.7.10 is, and will be for a while, a big deal, but it's not that im over 1.7.10, I'd go back and fix bugs anytime, but I pretty much broke my DevEnv (by that I mean I rewrote the whole mod but never released it in fears of infinite bugfixes all over again :P) and I reinstalled windows, so I lost old source code too :P I'll look in dropbox, and tell if you if I can find it and fix the bug

**Comment by Vaygrim** [comment]
I would desperately LOVE love to fix this if possible, specificially because all the other features in FTBU have been a massive lifesaver on the server-side. Chunk claiming, chunkloading, property protection / security. It's made things SO easy for 'n00b administrators' (which is my primary audience).

If you need ANY kind of help that CAN be thrown at this problem, let me know and I'll start shaking the trees to see who falls out. This is a kind of a big deal bug for us, but it's in a mod we don't really want to give up. <3
