### ISSUE TITLE
Backup improvements 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#118]
Two thing that i would like to see FTBU backup system to make it just that little bit better, the first thing it a feature that I like from YABM, witch allows me save the first backup of each day in an different location, also I would like if said backup would have different keep amount, to every 30 minute one, so first back of ever day I would like to keep all of them but only day worth of, the every 30 minute ones. The second thing I would like to see is more for single player, which is have the backup timer saved with the world, so that if are not for 30 chunks for what even reason your backups will still get done.

**Comment by Dijkstra1** [comment]
I also forgot to mention, as a server owner I would like to config FTBU to backup my custom scripts, ops, white list and few other server file, so what I am asking is to config to add files to the back e.g
```json
 "other_items_to_backup": {
         "files": ["ops.json", "whitelist.json"],
         "folders": ["scripts", "modpack", "locals", "configs"]
}
`  

Sorry for bad json, I assume I have made some mistake.

Also not so import, I would like a config for the colour of the back up message, nothing fancy just the hex of colour, I wish to use

**Comment by LatvianModder** [comment]
I think other files backup is a really good idea, I will probably include that in 1.9+ version

**Comment by kreezxil** [comment]
Seems like an appropriate place to ask for another feature.

The message that appears in the middle of the screen saying when the server is going to shut down. I'd like the option to have it appear in the players chat. And I'd like the option to specify how far away from shutdown it appears and then how often it appears until the shutdown occurs. For instance I'd like it to first appear at 10 minutes prior to shutdown, then at 50% time progression (5 minutes in) announce again, go another 50% and announce until the 30 seconds is hit and that's the last warning.
