### ISSUE TITLE
Two new keybindings 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#121]
I would like to key bindings to be added to chunk claiming the first one toggle claim if the chunk is unowned claim if you own unclaim it, should say in chat to the player one of three things you now own chunk, you have unclaimed this chunk or play X own this chunk.

The second button is toggle chunk load, if the chunk is claim by the user it should turn chunk loading on or off in that chunk, it should also tell the user, if the chunk is unclaimed the chunk should be claimed and loaded, or it shoul tell user how owns the chunk and it can not be loaded.

**Comment by LatvianModder** [comment]
Chunkloading isn't something I will add a keybinding for, but claiming toggle will have a keybinding

**Comment by LatvianModder** [comment]
No longer needed, since you can drag-select chunks now in the Gui
