### ISSUE TITLE
Set backups to keep zero does just that.

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#122]
When I set backups to keep zero, do now what is does, it will not keep any backups, when it means disable this and keep them all, this needs to fixed.

**Comment by LatvianModder** [comment]
Just set backup limit to something higher, won't fix this

**Comment by Dijkstra1** [comment]
I can not set it any higher than 100

**Comment by LatvianModder** [comment]
Oh right. Well, do you need 100 backups? It was never meant to have that many anyway. Our servers were few gigabytes large and backups were together about 70 - 100 GB

**Comment by Dijkstra1** [comment]
There have been times where having the backup mod delete updates, had lost me stuff, in single player, even what you mod making chunk loading available, in early game, you still need to be online, and, i have left Minecraft running for couple days before, and when I have come back I have been killed, with full inventory, and the earliest backup is still to late, and from them, I always liked, to keep all backups, I can understand that server hosting companies give you limited space, but maybe saying backups can only take up 10GB would be better for that, or even external FTP backups, actually, I would quite like backing up to a remote FTP location.

**Comment by LatvianModder** [comment]
"Minecraft running for couple days before" - wow, thats hardcore minecrafting :D Still, 100 is a lot. make it backup every 6 hours and you can stretch it to 25 days of backups. or just run manual backup /admin backup start, every time you feel like you don't want to lose stuff. Like before going to nether n stuff

**Comment by Dijkstra1** [comment]
That was just once I, usually just leave Minecraft from about 10pm to 5pm the next day. I like my backups to be ever half hour, I like to be control on what back up are keep (delete old ones manually), I do use manual backups from time to time but they would be safe from keep last 100 backup if back 101 was done. Also I like /admin backup start to be shorted to /backup. Also if setting backups to 0 why does it still go through the motions doing the backup should that be the same as disabling backup. Also I do not see how letting people keeping all the backups is bad thing when you set the default to about 50, maybe you could warn the user when there backup folder get to a defined size.
