### ISSUE TITLE
Recipes in guide

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#124]
~~NEI~~ JEI Integration, would be nice this to show recipes in guide if just to mouse over the items in the recipes to see what they are, and even better I would need to a new screen shoot when i change recipes.

**Comment by LatvianModder** [comment]
That is already being added, yes. I will mark this as ToDo, since I already have that in my private ToDo list

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBGuides/issues/3
