### ISSUE TITLE
/tpa command

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#128]
A teleportation command for players, where the other player must accept his teleport request

/tpa <player> - Sends TP request to another player
/tpaccept - Accept TP request
/tpdeny - Deny TP request

**Comment by frenzye** [comment]
This would be great, I wouldn't have to install sponge

**Comment by OldDogy** [comment]
I know I'm pinging an old Suggestion, but something like this would be quite nice !

Not to mention being able to say Ingore all requests, or auto accept all requests coming from friends ? Ignore all requests from enemy's ?  Prompt requests from rest...

Could be a really neat feature :D

**Comment by exultanthabit** [comment]
Might be worth while to add in rtp too for a tp update. but this would totally make a lot of people happy as is 😄

**Comment by xorinzor** [comment]
I hope this could be added soon, as there doesn't seem to be any other plugin for 1.12 (using forge-only) that does this

**Comment by TheRandomLabs** [comment]
What about a config option that only allows this for players in the same team?
