### ISSUE TITLE
Guide Formatting issues

### ISSUE THREAD

**Issue by Vaygrim** [LatvianModder/FTBUtilities#131]
With FTBUtilities-1.7.10-1.0.18.3 we can no longer mix formatting on the same line of text. Basically if we want fancy formatting (like URL links) in an in-game guide.. we now have to put it on a separate line from standard text.

It has thrown all our in-game guides out of whack and requiring a rewriting. Was this an intentional change? If yes, is there a way around it?

**Comment by LatvianModder** [comment]
Wait, you could do that previously? It has always been a seperate line for links, images etc

**Comment by LatvianModder** [comment]
This is the formatting now: https://gist.github.com/LatvianModder/743d5068bcaa27c50f4a5f4aa192cdfd
