### ISSUE TITLE
When a backup is done it tells me to much

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#132]
When I back it says backup started, turning off world save, saving world, backup done turning saving back on.

All i want to know in single player is Backup complete or backup failed.

On the sever only admins should see that backup is taking place, maybe warn everyone about the lag, but I have never noticed any, but i do think it should let my know size and size of backup folder, do not care about how long it took.

**Comment by LatvianModder** [comment]
I can't turn off vanilla save command spam. Also, backups on servers usually take a lot of time, so its good to know when it starts, and when it ends
