### ISSUE TITLE
Delete all unchanged claimed chunks 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#134]
Every so often one needs to regenerate parts of the, world be it new world gen or the world is just getting to big so what if have to is get every to draw around what they want kept it cobble stone so I can see it mc edit to delete. it would be a lot easier if i could just say claim all the chunks you want kept.

**Comment by LatvianModder** [comment]
Uh.. what? How is MCEdit realted to claimed chunks? MCEdit doesnt know which chunks are claimed...

**Comment by Dijkstra1** [comment]
No that is why it need to surrounded so i can see from the sky in mc edit, i was say it would nice it could do /admin deletUnclaimedChunks, would much easier, may even not need to stop server.

**Comment by LatvianModder** [comment]
Oh, yeah, sorry, I'm not adding that command, it would mess with world too much and could cause corruption

**Comment by Dijkstra1** [comment]
mc edit it is then.
