### ISSUE TITLE
[1.9.4] Server crash trying to chunk load chunks

### ISSUE THREAD

**Issue by RealGrep** [LatvianModder/FTBUtilities#136]
Server crashed while I was testing out the new version's chunk claiming and loading. Created a new team, then claimed some chunks. I then tried to chunk load one of them (Ctrl+click) and got some errors in the console and it didn't seem to change the colour of the chunk in the map GUI. Unclaimed and reclaimed the chunk. Ctrl+clicked a couple more times to try and chunk load the chunk, and the server crashed with this:

http://pastebin.com/eSmVKTWg

This is with FTBUtilities-1.9.4-2.1.0-pre1.jar, FTBLib-1.9.4-2.1.0-pre1.jar, and Forge 12.17.0.1968 in MC 1.9.4.

Let me know if I can provide any additional information. And thank you very much for your hard work in getting this out! I appreciate it.

**Comment by DoughnutDev** [comment]
Server crashed when claiming a chunk.

http://hastebin.com/urevigizoz.coffee

This is with FTBUtilities-1.9.4-2.1.0-pre1.jar, FTBLib-1.9.4-2.1.0-pre1.jar, and Forge 12.17.0.1968 in MC 1.9.4.

**Comment by LatvianModder** [comment]
Oh bother, it's back. Might even consider disabling it for some time, until I figure out how to make chunkloaders not crash

**Comment by DoughnutDev** [comment]
@LatvianModder I don't have chunkloaders unless a machine has built in one so I am not sure what caused it on my side.

**Comment by LatvianModder** [comment]
Hm, yours is another crash. Seems like you logged out or smth

**Comment by RealGrep** [comment]
Ah yes, I didn't even think of it while filing, but I had a EU2 chunkloader already in the chunk I then tried to chunkload with FTBU. That explains the already existing chunkloading ticket, maybe.

**Comment by LatvianModder** [comment]
Fixed in pre2? Reopen the issue if this still isnt fixed
