### ISSUE TITLE
(1.9.4) client crash

### ISSUE THREAD

**Issue by knoxhack** [LatvianModder/FTBUtilities#137]
http://pastebin.com/4r2zD78c

**Comment by LatvianModder** [comment]
Gonna keep it open until I release pre2

**Comment by utoc** [comment]
Hey @LatvianModder I'm seeing this issue still in pre2 where the client crashes in SSP when doing a 'save and exit world'

See crash report here: http://pastebin.com/xnz9BNw8

Running FTBUtilities-1.9.4-2.1.0-pre2.jar and FTBLib-1.9.4-2.1.0-pre2.jar in MC 1.10.2 with FML forge-1.10.2-12.18.0.2008

Please let me know if you need any additional information or if I need to open up a new ticket
