### ISSUE TITLE
[1.8.9] /home works sporadically

### ISSUE THREAD

**Issue by KIN0025** [LatvianModder/FTBUtilities#138]
I have been having issues with the /home command sending the player to the last used warp rather than the home they are supposed to be sent to , but have only been able to replicate this sporadically. It seems to be similar to #51 - and as the last build for 1.8.9 was released before the fix was implemented for 1.7.10 I am not sure if the issue is still present.

**Comment by knoxz** [comment]
When opped it does not work for me. Its working for players on the server. Its not working for me.
It just moves me to spawn every time.

**Comment by LatvianModder** [comment]
Sorry, I don't support 1.8.9 version anymore, look forward to 1.9.4+ versions

**Comment by knoxz** [comment]
As a mention. Its the same on 1.9.4

**Comment by LatvianModder** [comment]
In pre1 everything is broken. Thats why it is pre :D
