### ISSUE TITLE
1.9.4 Config.Json reverting on minecraft startup

### ISSUE THREAD

**Issue by slidingmike** [LatvianModder/FTBUtilities#140]
Config.json resets to a default version without keeping changed values on load up. 

Also what is the syntax for adding starting items to the file?

Itemname Qty Damage Comma next item or something different?

Utils/Lib 2.1.0 Pre 1
Forge 1980

**Comment by LatvianModder** [comment]
As for items - [ "minecraft:stone 1 0", "minecraft:dye 64 4" ] - ID[space]size[space]damage

**Comment by LatvianModder** [comment]
Should be fixed in pre2
