### ISSUE TITLE
Move configs from local to config folder

### ISSUE THREAD

**Issue by TOLoneWolf** [LatvianModder/FTBUtilities#142]
Suggested improvement - move configs from local to config folder.
Why place your config outside of the config folder?
Kind of goes against standardizing file placement and is just confusing.

**Comment by slidingmike** [comment]
Seconded.

**Comment by Dijkstra1** [comment]
I think the reason the these config are in locals is because they are for the player/server owner to change not the pack creator, change any of the FTBU setting will change or unbalance the pack.

**Comment by TOLoneWolf** [comment]
That might be a reason to think that way true, but just pointing out there are tons of server side config only options that other mods change server side just fine in the config folder. Not only that but when a pack gets made the local folder will be included in that download still overriding your config settings because there are default setting the pack maker things are good or it just gets included by default because it's there. Which has happened already with the packs i have had to set servers up for.

That's the way i see it anyways so it would make more sense to me to put them in the proper place.

**Comment by LatvianModder** [comment]
So, my reason for configs being in /local is indeed because I dont want pack owners to ship these configs with pack. And you probably dont want to refresh all configs after updating pack. I might consider moving some configs to /config/ but it would cause a lot of confusion imo. And, right now, local/ftbu/ is kinda empty, but later there will be other files, like ranks.json, player_ranks.json and local/config_help.txt etc

**Comment by LatvianModder** [comment]
And, @TOLoneWolf you CAN override these configs without shipping /local/ - create Overrides.json in modpack/ folder and put your overrides there. Its a little hard to explain but it works, at least in 1.7.10. 1.9.4 version will have things a little differently

**Comment by LatvianModder** [comment]
As I said, I might consider moving some pack-specific configs to /config/FTBUtilities.json. Any specific you are interested in?

**Comment by LimeTheOn** [comment]
Nothing extremely specific just keep it clean and documented what went where that is all I can ask for. 
If you're moving stuff like you say you would that satisfies me since it separates sp and mp perfectly, for me at least :)
