### ISSUE TITLE
[1.9.4] ConfigGUI is broken

### ISSUE THREAD

**Issue by Orangeninja1** [LatvianModder/FTBUtilities#144]
While using the 1.9.4 version 2.1.0-pre1  I have not been able to use "/ftb team config" and save once I click the accept it loses the settings and reverts back to the default settings. The same thing happens when I try to use "/ftb edit_config".

**Comment by LatvianModder** [comment]
Use /ftb edit_config <ID> [value] instead. Only the gui is broken, if you <tab> trough all keys it should work

**Comment by Orangeninja1** [comment]
That worked thanks!

**Comment by LatvianModder** [comment]
Fixed in pre2
