### ISSUE TITLE
Chunkloaded chunks reset after world restart

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#147]
Most likely related to data saving/loading

**Comment by LimeTheOn** [comment]
Im guessing this is pre2?! those of us who are using FTBU on our server, should we wait for a pre3 release instead of updating to pre2?

**Comment by LatvianModder** [comment]
It doesnt do that with pre1? Im pretty sure I didnt change anything related to chunks, so I bet it does that in pre1 too. Anyway, pre2 has a lot of bugs fixed

**Comment by LimeTheOn** [comment]
I dont know i was so afraid when i saw the issue I un-chunkloaded all chunks and told everyone to do so on the server until you reply :D

**Comment by ExDomino** [comment]
I'm on FTB Infinity Evolved 2.5.0, is this bug still present ? I didn't noticed any chunk reset on my server even when my players used this functionality. I'm using "FTB Utilities 1.0.17.6". Thank in advance!

**Comment by LatvianModder** [comment]
1.7.10 is dead, we are talking about 1.9.4

**Comment by LimeTheOn** [comment]
Im copypasting and printscreening that comment, gave me a giggle! <3

**Comment by ExDomino** [comment]
Yes, you're right, let's using the 1.9.4 version that is still in devlopment. ^^
For now, we prefer play in 1.7.10 and wait a full release of a next version before to update.

**Comment by mattk926** [comment]
Running into the same issue. Chunks are still claimed but not chunkloaded once the server restarts...

**Comment by VoodooBeard** [comment]
Same problem here. FTB Unstable 1.10 pack (4.2.3) using FTBUtilities-1.9.4-2.1.0-pre2
Chunks remain claimed but are no longer chunkloaded after server restart.
FTB seem to be rather keen to have people use FTBU for their chunkloading and seem to be removing other chunkloaders from the pack, it's a shame this bug is preventing us from moving over from other methods.

**Comment by LimeTheOn** [comment]
yeah sorry @LatvianModder for bumping you like that but could you throw us some bones as to how is it going with the mod. Im genuinely very interested and excited as a little kid waiting for his ice cream! ^^

**Comment by LatvianModder** [comment]
I have a version where a lot of the bugs are fixed (including this one) on my server. Still testing out some things, shouldnt be too long before I release pre3. It wont have guides and ranks, as I planned before, but at least it wont be as buggy as before

**Comment by mattk926** [comment]
That's amazing! I'd rather have more often updates for bug fixes and worry
about adding features later :)

**Comment by LimeTheOn** [comment]
Awesome, thank you! :)

**Comment by LatvianModder** [comment]
Here's alpha builds of pre3 - this bug and some other ones fixed. http://latv.sigmahost.co.uk/public/mods/

**Comment by LimeTheOn** [comment]
Wohooo, huge thanks! Will test it tonight/tomorrow morning! Sadly even if you gave me permission i woudnt be able to push it on our live client/server, just last week we had a minor disagreement with curse about pushing content thats not yet released on their site...eve tho the hotfix was made specifically for us xD

**Comment by LatvianModder** [comment]
You should be able to use it server only side, and just tell your server players to update manually, if they want to (its not required to update, but probably some parts wont work perfectly)

**Comment by LimeTheOn** [comment]
Yes thats why im saying ill test what i can by myself then when ure rdy with the release we will test everything live, sadly we had a security breach yday so we are down until i can confirm noone is messing with my server :/ altho i have no idea what would come out of messing with an EU home-hosted server for someone from LA but better safe then sorry. They did not gain acces to anything as far as i can tell atm but yeah just that they tried raises....worry :D ...also our group loudly stated to me that they dislike manual updates so thats the reason im not pushing anything onto them but onto curse otherwise u're right, i could :D

**Comment by LimeTheOn** [comment]
So i really didnt know what to test but this particular issue seems to be fixed my chunks still chunkloaded after restart- wohooo!
/ftb back is still not too reliable, sometimes it just wont tp you- 1 out of 5 occasions it seems.
/ftb delhome x fails to recognize the home name so its not able to delete it but /ftb sethome x at new location is working as a workaround so yeah woho.
/ftb admin_home can delete homes and seems to work properly so if you have a small server thats another workaround but yeah.
/ftb inv sees my armor baubles and everything and updates to changes made to it live-no duping and such- so yehaaaa!-small suggestion is to be able to view bags' content without taking them out of players inventory if possible
setrank/getrank works just fine.
all config gui except client crashes client...but ik theyre WIP so thats fine :D
Thats all i think is daily use for us and theyre in a much better shape now. What we would really need for a full release of our modpack is ranks so when/if you have something on them feel free to bump me and we will test thoroughly.

**Comment by mjevans** [comment]
Confirmed:

pre3 fixes chunkloading across server reboots.

It also seems to have added a new bug:

When entering/leaving a chunk boundary, the screen blackens, then fixes it's self.  Did anything change in the popup render system?

**Comment by LatvianModder** [comment]
Ah, yes, that bug will be fixed soon. I tried fixing a bug with OptiFine, but it only made things worse :P
