### ISSUE TITLE
/ftb home & warp takes you to bed spawn

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#148]

**Comment by MCTyler** [comment]
I have also discovered this issue although you say its closed. I have /sethome base, but when I type /home base, it takes me to spawn instead. This happens after a home is set, then deleted, and a new home is added. Could you please look into this further?

**Comment by MCTyler** [comment]
I manually edited FMPlayers.dat, and removed all the pre-existing home entries for my character in that file and the home function is working well now. I can sethome and del home then re-set home with no problems. Possibly this file was corrupted when I had the FEssentials alias interfering with the /home command. This Alias has been removed fro FE's command.cfg Alias file. I will post any new developments here if I see any more issues but for now, it is working as intended!

**Comment by MCTyler** [comment]
This issue happened again. Deleting home and readding takes the player to the bedspawn instead of home that is set. It appears some sort of cache setting is interfering with a hard re-write of the LMPlayers.dat file and the information is not being recorded.

**Comment by LatvianModder** [comment]
"LMPlayers.dat" sounds like *not* 1.10.2 version. And I don't support any other version

**Comment by MCTyler** [comment]
Ok, yea, I still use 1.7.10 MineCraft Version. I may update when all the other Mods update to 1.10 version.
