### ISSUE TITLE
Chunk claiming mirrored in nether

### ISSUE THREAD

**Issue by tyler489** [LatvianModder/FTBUtilities#149]
so in some parts of the nether i cant build i couldnt figure it out finally i realised that the claim next to mine was 2 chunks away from my portal when i went through my portal and moved 2 chunks i couldnt build there...
is this a bug because it shows no claimed land there

**Comment by LatvianModder** [comment]
So basically, claimed chunks on overworld affect other dimensions? I assume that

**Comment by tyler489** [comment]
Yeah  say chunk id 0,0 is claimed by notch in the overworld if u go to the nether only notch can build in chunk in the nether even though it doesnt show up in the map that its claimed no one can build there.

Useing knozx 1.9 testpack on the curse launcher
