### ISSUE TITLE
Multiple Items on New Player Join

### ISSUE THREAD

**Issue by MCTyler** [LatvianModder/FTBUtilities#150]
Can you make a Wiki or something explaining the .json configuration on how to give Players Multiple Items on joining the Server? I would love to have this functionality but I can't seem to be able to figure out what the .json wants to work properly or even if it's possible. Thanks, Great Mod!

**Comment by LatvianModder** [comment]
There will be a wiki soon. The json format is

"starting_items": [
  "minecraft:apple 16 0",
  "minecraft:stone_axe 1 10"
]

Gives player 16 apples and 1 stone axe with damage 10

**Comment by jcettison** [comment]
This isn't very clear for items which have multiple name IDs. For example, how do I give them Smooth Stone (vs other versions of minecraft:stone)?

**Comment by LatvianModder** [comment]
Use their metadata/damage value - you can see that with F3+H. smoothstone is 0, other values are 1-4 I think
