### ISSUE TITLE
Sethome not set, home teleport to bed instead

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#151]
I did a "/sethome pnj" to set a home near of a pnj village, and then did "/home pnj". The mod teleported me to my last bed. What is wrong? I'm on FTB Infinity Evolved 2.5.0.

**Comment by MrPotatoGaming** [comment]
Can confirm issue still occurs in FTB Utils 1.9.4-2.1.0 on both minecraft 1.10 and 1.9.4. This can be fixed by relogging, before setting your home each time.

**Comment by LatvianModder** [comment]
This is a 1.7.10 bug, Im not fixing that. The issue for 1.9.4 version is already open

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/148
