### ISSUE TITLE
[1.10] server crash on player logout

### ISSUE THREAD

**Issue by kwpugh** [LatvianModder/FTBUtilities#152]
Forge: 2000
Mod: FTBLib-1.9.4-2.1.0-pre2.jar & FTBUtilities-1.9.4-2.1.0-pre2.jar

Server crashed when a player logout

Crash report: http://pastebin.com/raw/RU3HKb5V

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/28
