### ISSUE TITLE
Question: It is possible to claim another "Spawn Area" chunks?

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#153]
I'm wondering if I can enlarge de Spawn Area, for example to build a creative city in a large zone than just 3x3. If possible, does it exist another type of "admin chunks" like sanctuary area or no-pvp area or the like please? And how to do that? Thank.

**Comment by LatvianModder** [comment]
This is a vanilla thing. look up spawn protection server property
