### ISSUE TITLE
Question: It is possible to set the limit of claiming for an individual player?

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#154]
I would like set for each players a different limit of claiming, with a Command Computer from ComputerCraft that would modify their limit according to their connection time. And not only their chunk claiming limit but also their chunkloading limit as well. It is possible, and if so, how? Thank. ^^

**Comment by LatvianModder** [comment]
It's not possible, sorry. Definetly not in 1.7.10

**Comment by ExDomino** [comment]
It is possible in 1.7.10 to create new ranks, for example one rank per player and then set individual limits for each ranks in the mod?

**Comment by LatvianModder** [comment]
That was the plan, but 1.8+ came by too soon, and I moved to there
