### ISSUE TITLE
[1.9+] [Question] FTB libs does not contain any of the game mode stuff yet

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#155]
Am I right in understanding, the FTB Lib handled all the game mode stuff in 1.7.10 but for 1.9 it is not there yet. I am right how easy would be for an external mod to change guide location.

**Comment by LatvianModder** [comment]
Modes work the same way they did before. Its Guides that dont exist in 1.9 yet

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/125
