### ISSUE TITLE
Server crash on player logout FTBUtilities

### ISSUE THREAD

**Issue by IchigoGames** [LatvianModder/FTBUtilities#157]
im not %100 about this so if it turns out its not FTBUtilities then sorry about that 

http://pastebin.com/AGcJ9Ub6

https://www.dropbox.com/s/y60lnvwc1778exf/fml-server-latest.log?dl=0

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/152
