### ISSUE TITLE
Question: New FTBUtilities Guide System for 1.9

### ISSUE THREAD

**Issue by PaisleyP** [LatvianModder/FTBUtilities#160]
I'm interested in writing a basic server side guide in 1.10. 
I know that there is now a [new guide system](https://gist.github.com/LatvianModder/55eb7c6628bc5d19d2931bc4bc809e56) but the example link isn't working. I don't really know where to begin changing the old .txt system over to .json format without an example, bit of a novice I admit, anything you can share?

**Comment by LatvianModder** [comment]
Ah, it isn't finished yet. And yes, I moved the example, and I'm still working on the new guide system. But there will be server-side guides available, similar to what they were before
