### ISSUE TITLE
Question: How to remove the need to specify an ID for /home and /sethome ?

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#161]
My players only have one home and they have to use "/sethome home" and "/home home" instead of just "/sethome" and "/home". They can name their home "0" instead of "home" and call "/home 0" but they have to specify an ID, they cannot use "/home" alone. Does it exist a way to short the command or specify a kind of alias in order to make that a call to "/home" make a "/home home" instead? Thank you in advance. PS: On my server, ops too have only 1 home.

**Comment by LatvianModder** [comment]
I suggest MacroKey Keybinding mod then, because I can't shorten the command without adding a new one that would just mirror the longer one, which would be pointless

**Comment by ExDomino** [comment]
You cannot make that the ID is not needed?
And I'm seeking for a solution server-side only if possible.

**Comment by Cr1cket** [comment]
So make it so if they do /home, it will go to the default home, unless they specify which home it is they wish to go to. Made that change to essentials myself because it is the most annoying thing on the planet.
