### ISSUE TITLE
Add home and warp cooldown timer

### ISSUE THREAD

**Issue by mrdeadlocked** [LatvianModder/FTBUtilities#163]
It would be useful to have the option to have the following:

cooldown (time between being able to use home) Ex: 10 minutes
warmup (time to not move/take damage before home fires) Ex:15 seconds

This would help from people using home as a getaway.

**Comment by LatvianModder** [comment]
Yes, that's something I always keep forgetting to add to my ToDo list

**Comment by mavrck48** [comment]
I would like to second this to-do.  For PVP servers a warmup to cast the spells is required or as noted it just becomes a broken getaway command.
