### ISSUE TITLE
Server Guide Book Question

### ISSUE THREAD

**Issue by sourcepowered** [LatvianModder/FTBUtilities#167]
Hi, sir, I have a question.
How to hide "Commands" options? I do not want users to see this and I want to customize.
![image](https://cloud.githubusercontent.com/assets/17511838/16714510/e13a8466-46f7-11e6-86a0-3964bc90b97d.png)
This is already there and I can't find how to hide/disable it. If I also create an option called "Commands", then they will exist at the same time.
Thanks!

**Comment by LatvianModder** [comment]
You can't disable that, sorry. It's hardcoded
