### ISSUE TITLE
Question - Is there settings for chunk claiming 1.10?

### ISSUE THREAD

**Issue by TOLoneWolf** [LatvianModder/FTBUtilities#168]
Didn't see any place listing the newer layout for ftb utils configs / chunk permissions.

Is there still a way to disable the chunk locking out other players from interacting with the world?
I want the players on my server to be able to claim and load chunks just not prevent others from interacting with things there.
Also even in gamemode 1 & opped I can't look inside  chests/machines or break/place inside chunks claimed by players.

I tried some of the settings in ranks but that didn't seem to affect anything for me.
I made sure to give my self admin rank.

**Comment by LatvianModder** [comment]
Not yet, working on that for pre3 or pre4

**Comment by TOLoneWolf** [comment]
okay thanks for letting me know.
