### ISSUE TITLE
Client crash (NPE) in SSP when save/exiting world

### ISSUE THREAD

**Issue by utoc** [LatvianModder/FTBUtilities#169]
Hello!

See full client log here: http://pastebin.com/vz4rpmpT  The crash begins at line 2239

Running:
    MC 1.10.2
    forge-1.10.2-12.18.0.2008
    FTBUtilities-1.9.4-2.1.0-pre2.jar
    FTBLib-1.9.4-2.1.0-pre2.jar

Please let me know if you need any additional information.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/152
