### ISSUE TITLE
[1.10.2] Derping Light

### ISSUE THREAD

**Issue by Okimo** [LatvianModder/FTBUtilities#170]
Looks like when information about area is shown I get this lighting glitch until info dispears.
Images: http://imgur.com/a/jzmm6
When I set it to be shown in chat everything is fine.
After some research this happens when I have Installed Both: BetterFPS (1.3.2) and Optifine (HD U C2), at same time.
Just in case I will tag author of BetterFps: @Guichaguri and Optfine:  @sp614x

**Comment by sp614x** [comment]
Both screenshots have the block info area visible, what is the difference?

**Comment by LatvianModder** [comment]
The lighting - One is similar gray and another one has shadows. I just dont get how this is FTBU issue, since this mostly looks like shaders issue

**Comment by LatvianModder** [comment]
Here I render the notification. Maybe @sp614x can tell what is causing the lighting to be all weird. Probably some GL alpha / blend / color flag https://github.com/LatvianModder/FTBLib/blob/1.9/src/main/java/com/feed_the_beast/ftbl/api/notification/ClientNotifications.java#L89-L147

**Comment by sp614x** [comment]
It looks like the lightmap is wrong.
How (when) is the info rendered (as entity, as tile entity, as GUI, etc)?. 
You could also check the initial state of GlStateManager for the properties that you change (depth, lighting, color, etc) so you could restore the correct values at the end.

**Comment by LatvianModder** [comment]
That render function is called from here https://github.com/LatvianModder/FTBLib/blob/1.9/src/main/java/com/feed_the_beast/ftbl/client/FTBLibClientEventHandler.java#L310

**Comment by sp614x** [comment]
And who fires the renderTick() event?

**Comment by Guichaguri** [comment]
@sp614x It's a Forge event. It's fired by `Minecraft.runGameLoop` after `EntityRenderer.updateCameraAndRender`

**Comment by LatvianModder** [comment]
Thanks for suggestion, I will try that
