### ISSUE TITLE
[1.10] [Bug] Backup loop

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#173]
So starting play 1.10 Minecraft now and guess what, day one I found a bug for you, don't worry you are not the only person. 
[Here is the log](https://github.com/LatvianModder/FTBUtilities/files/361063/for.latvianModder.txt)

What must have happen is i went to the title screen just as it was about to backup, and when I re loaded the world, it backup, and then it backup again and again..., then I went back tot title to see if that would fix, no. Then i tiered close minecraft and reloading, and it was still doing it. I had to delete, the FTBU config file to fix it, by the way all changed was backup timer to 0.5 and backups to keep 100, since then they have been left at default values and it been fine, but I have not gone to title screen just as it been to backup.

**Comment by LatvianModder** [comment]
Low priority, since this seems to be very edge-case-y, but I will change how backup timers work anyway. Might even enable time-specific backups, if I figure this one out (backup at 6o'clock, etc)

**Comment by Zettt** [comment]
I want to report a similar issue here,  which may or may not be related, but I think it doesn't warrant a new thread.

When setting the backup timer anything lower than 1 it causes FTBU to misbehave. In my case, it's been set to `0.25`, which caused FTBU to backup every minute. I have the same `"backups_to_keep": 100,` value though. I have tried various settings, and whenever the timer is below 1, it seems to be causing issues and not behave like documented ([here](https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/java/com/feed_the_beast/ftbu/config/FTBUConfigBackups.java)).

**Comment by Ricket** [comment]
because the backup value is gotten as an int

https://github.com/LatvianModder/FTBUtilities/blob/43cfa37818cdf20066f79238958443182ceb7994/src/main/java/com/feed_the_beast/ftbu/config/FTBUConfigBackups.java#L37

**Comment by drinfernoo** [comment]
I have my number to keep specified as 1, and it keeps all the ones it takes anyway. I only want to keep one backup, should I put 1.0?

**Comment by LatvianModder** [comment]
Currecntly it saves all backups, because the old backup file scanner is broken

**Comment by Dijkstra1** [comment]
DONT FIX!!!!!!!!!!!!!
or least keep it as an option to keep all backups

**Comment by LatvianModder** [comment]
It has to be fixed lol. But setting max backups to keep as 0 will keep all of them

**Comment by Dijkstra1** [comment]
Are sure when I done that in the past in done just what i told it and kept none, if you changed it, then by all means go ahead and fix just as long as you do not delete my my backups.
