### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#174]
Teams is actually a good idea, but not in single player, by the way it took me little while to work out teams maybe put it in the guide when you get it working. Can you make it so FTBU detects it is a single player world and just lets me claims chunks as my self, also server as owner I would to be able to claim chucks of my own as mainly me vs my sister, we very rarely work together for long, and to me a one man team seems a bit silly.

**Comment by LatvianModder** [comment]
It's really not that hard to type in ONE extra command. Teams stay they way they are
