### ISSUE TITLE
Deleted Serverfiles

### ISSUE THREAD

**Issue by MiningPickaxe** [LatvianModder/FTBUtilities#177]
I changed the config to backup in the folder /home/username/mcserver/ProjectOzone2/ instead of ./backups wich should prevent the backup from backuping older backups (A backup had a size of 20GB because it backuped the "backups" folder)
When I restarted the server to apply the configs, the screen (yes, it is linux) terminated (so it crashed). I tried to find the crashlog, but there is none and my server folder does not longer include the world, only "config" "crash-reports" (empty) and "SquidAPI"
All other files got deleted.
I was using the modpack "Project Ozone 2" wich is currently in closed beta.

**Comment by LatvianModder** [comment]
Was this solved? Because Im pretty sure that had never happened before with anyone

**Comment by MiningPickaxe** [comment]
It never happened to me again. Don't exactly know why that happened.

**Comment by LatvianModder** [comment]
Ok, closing then
