### ISSUE TITLE
Mod cross-compatibility issue: Gravestones in claimed chunks unbreakable by grave owners or ops.

### ISSUE THREAD

**Issue by Insidious611** [LatvianModder/FTBUtilities#179]
Hi, Moderator on the MMD server here. Gravestones in claimed chunks seem to be unbreakable by their owners (the people who died to create the gravestone), or by ops/Admin roles. I've also been unable to use /ftb chunks unclaim as an op/Admin rank to unclaim the chunk temporarily in order to break the gravestone.

**Comment by Insidious611** [comment]
A fellow moderator is suggesting that FTB Utils should add some sort of whitelist thing that allows certain items/blocks to always be broken, no matter what the chunk permissions are.

**Comment by LatvianModder** [comment]
Its in works. It was there in 1.7.10, I just havent re-implemented it

**Comment by Gammelkebab** [comment]
My Issue was redirected here. But you say it's a thing in 1.7.10. My problem IS in 1.7.10 (#214)
