### ISSUE TITLE
[1.10.2] Issues with teams

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#181]
Me and sister in the same team on my server, I made a team, she joined we both have claimed, we can not un-claim chunks that the other ha claimed, nor can either of us make a chunk be loaded, I did get it working, in single player with the same mod pack, it did take me while to work that change the key binding, but I did manage to load chunk, but could not unload without unclaiming the chunk at the same time.

**Comment by LatvianModder** [comment]
Yes, you aren't supposed to manage other player's chunks. FTBU doesn't know if the other player is your sister, friend or someone you dont know :P
