### ISSUE TITLE
[1.10.2] Friends System

### ISSUE THREAD

**Issue by nikkimas** [LatvianModder/FTBUtilities#182]
How do I add friends? All I see is team invites, however I need to allow the fake player "[Mekanism]" to build in claimed chunks. But since it's for my Server, I need it to be in Several teams, or as I try, add it as friend. I just can't seem to find it.

**Comment by LatvianModder** [comment]
There should be a setting for fake players in /ftb team config

**Comment by nikkimas** [comment]
Thank you! Didnt know that command! That solved it.

Thanks :)
