### ISSUE TITLE
Disconects after Warping from another Dimension 

### ISSUE THREAD

**Issue by Stuart74** [LatvianModder/FTBUtilities#184]
Please refer to this issue posted on my modpack curse page

http://minecraft.curseforge.com/projects/empyrean/issues/3

Seems after warping from another dimension and using the actually additions storage crate we get disconnected. This does however not occur if using just nether portals. So I believe it has to do with something relating to how you deal with teleporting players cross dimensions. 

FTBUTils Version: FTBUtilities-1.9.4-2.1.0-pre2
Forge Version: 12.18.1.2014
Server Error:  [gist](https://gist.github.com/Stuart74/62119b025b01ac697da8146c6439cae6)

**Comment by LatvianModder** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/169
