### ISSUE TITLE
[1.10.2][BUG] Backup not creating backup.

### ISSUE THREAD

**Issue by DaemosDaen** [LatvianModder/FTBUtilities#185]
The Backup process is not creating a proper snapshot of the world. Example:
Server version; about 3-7 players at variying times.

Friday night, at about 11pm a backup occurred, from then to noon the next day we made many many changed to the world as one would expect 
Saturday morning I made many more changes.
At about Noon on Saturday something caused the server to crash (think it was quark, but not sure as it just stopped the thread and no log was generated)
On reload the world was found to be corrupted.
Restored a backup from about 10 am Saturday (according to the time stamp) Some changes were not applied but others were.. it's all kinds of weird

Things that were reverted to before 11pm Friday:
   Forestry farm had old settings (completed at about 1:30am Satur)
   RF Tools Shield system base wither room was not completed (about 1:30 am Satur)
   We swapped two Ender IO capacitors to better handle Power flow. (Midnight Fri)
   Deep resonance crystal missing (growing finished after I went to bed at 2am Sat)

Thing that were not reverted.
   Ender IO based storage system move. (from the basement to the first floor 12:30 Fri night) 
   Bee Apiarries changes were kept. (11pm Fri)
   the whole Deep resonance system was moved and still in it's new location (After 2:00am Sat, I was not awake when that was completed.)
   Blood Magic based quarry removed, but not set up at the new location, note Items are missing from that user's inventory. (After 2:00am Sat, I was not awake when that was completed.)

It is possible that the backup program is not forcing a save of the files before copying them over to the backup .zip?

**Comment by DaemosDaen** [comment]
Sorry about the wall of text, but it's a complicated issue

**Comment by LycanBlackpaw** [comment]
A group I play with (custom pack [(Mod list on Curse)](https://mods.curse.com/modpacks/minecraft/247108-dawn)) started having the exact same issue. Whole server refuses to start. Any fixes?

**Comment by LatvianModder** [comment]
Er.. Delete backup folder? Not sure

**Comment by FoxFireMC** [comment]
Is there nothing that could have caused this to happen?
