### ISSUE TITLE
Give items on death respawn

### ISSUE THREAD

**Issue by wizard1399** [LatvianModder/FTBUtilities#189]
Hey,

Feature Request:
I saw that you have a way of giving players items when they first join a server.  Could you also make a means of giving players items when respawn after death?

**Comment by LatvianModder** [comment]
I guess I can add that as a feature, yes. I cant think much of a purpose though. Like food or smth?

**Comment by wizard1399** [comment]
Actually, I have a specific use in mind. On some skyblock maps it is absolutely essential that you have a certain item to get started. If you fall into the void with your entire inventory on you, you are screwed.  You either restart and any of the building you have done is lost or you cheat in the item. 

For example, the mod Better Beginnings relies on you being able to find flint. You have to have flint before you can even get wood. 

You could balance this by only giving the death respawn items 'x' amount of times.

**Comment by LatvianModder** [comment]
Im gonna close this, there are ways to workaround. Like, set up a barrel and a timer or smth. You probably dont even need this anymore
