### ISSUE TITLE
Bring back the ability to name commands

### ISSUE THREAD

**Issue by phit** [LatvianModder/FTBUtilities#191]
This was removed in https://github.com/LatvianModder/FTBUtilities/commit/8e199451ad9cd0371811bfa0bbefefba9823acb0, I'm not quite sure why, typing /ftb spawn instead of /spawn is just terrible for users that are used to this since forever. Thanks!

**Comment by Dijkstra1** [comment]
@phit I hate the ftb prefix to all the commands it confuses me so one one day I am on 1.7.10 server and the next is 1.10.2, it took me a good five minutes on the 1.7.10 to work why /ftb back was not working (I had been playing 1.10.2 for quite some time by them), I would very much like the command names back or at least giving me the power to rename once again.

**Comment by LatvianModder** [comment]
It was removed, because it was way easier to not mess with other mods (ForgeEssentials, for example) this way and you dont ever forget any command, since you can just use /ftb <tab> to see all available ones

**Comment by phit** [comment]
the people affected by this, won't "just" do /ftb to find all commands, guess I'll have to rely on a 3rd party mod to alias the /ftb commands
