### ISSUE TITLE
Claimed chunks causing  Storage Drawers to get corrupted. 

### ISSUE THREAD

**Issue by Giovanni-NL** [LatvianModder/FTBUtilities#193]
Storage drawers placed in a chunk that has been claimed by FTB Utilities often get corrupted.  Visually they disappear, leaving behind a ghost block that cannot be interacted with by the player, but for instance connected storage drawers or EnderIO conduits still can.

Same problem happens with furnaces from the More Furnaces mod.  The furnaces disappears, leaving behind a ghost block.   

This is happening to a lot of players on our server, and has also been reported on several other servers here: https://github.com/jaquadro/StorageDrawers/issues/323 

After some experimenting this seems to be an issue with FTB Utilities, so therefore posting this issue here. 

Some of the mods used:
Forge 2027
FTBLib-1.9.4-2.1.0-pre2
FTBUtilities-1.9.4-2.1.0-pre2
StorageDrawers-1.9.4-3.2.1
MoreFurnaces-1.10-1.8.1

**Comment by Giovanni-NL** [comment]
We've upgraded to the following mods yesterday, and so far no strange have happened to storage drawers and furnaces...

Forge 2046
FTBLib-1.9.4-2.1.0-pre2
FTBUtilities-1.9.4-2.1.0-pre2
StorageDrawers-1.9.4-3.2.1
MoreFurnaces-1.10.2-1.8.2

So at this point my best guess is that the upgrade to Forge 2046 solved the problems.

**Comment by LatvianModder** [comment]
Them I'm closing this PR for now, reopen it if the problem repeats

**Comment by Giovanni-NL** [comment]
2 days later, still no problems.   :)
