### ISSUE TITLE
Tile Entities from other mods stop working in claimed chunks.

### ISSUE THREAD

**Issue by Dawgie3000** [LatvianModder/FTBUtilities#194]
Minecraft Version: 1.10.2
Forge Version: 1.10.2-12.18.1.2050
Mod Version:  1.9.4 - 2.1.0-pre2
I've noticed a few blocks from various mods (Notably the Digital Miner from Mekanism and the Mechanical User from Extra Utilities 2, there may be more, but I haven't personally found any) begin to cease working in claimed chunks.  Not at all difficult to replicate.  Just place one of the blocks, claim a chunk, and you'll see them completely stop working until the chunk is unclaimed.

**Comment by LatvianModder** [comment]
Set /ftb team config ftbu.fake_players true
