### ISSUE TITLE
Using FTBUtilities chunk claiming to prevent grieffing with mod Capsule

### ISSUE THREAD

**Issue by Lythom** [LatvianModder/FTBUtilities#195]
Hello !

I'm developping the [Capsule mod](http://imgur.com/gallery/xCWCX) which allows players to capture regions of the map (up to 31x31x31) into a capsule item, then deploy the content anywhere. Some players are concerned about grieffing issues ([reddit comments on the topic](https://www.reddit.com/r/feedthebeast/comments/4xifoj/capsule_mod_the_big_1102_update_the_modpack/d6fsbu3)) and I was wondering if I could use the chunk claming system of FTBUtilities to detect protected areas.

Is there some way for an external mod to detect if a BlockPos is in a claimed chunk ? That would allow me to prevent capturing, deploying and undeploying of contents where it's meant to be protected.

**Comment by LatvianModder** [comment]
I'm working towards getting PermissionAPI in Forge (see https://github.com/MinecraftForge/MinecraftForge/pull/3155) and once that is done, you will be able to check for permission yourself

**Comment by Lythom** [comment]
Really great, thank you !

**Comment by LatvianModder** [comment]
Now that the PR is merged, this should be possible
