### ISSUE TITLE
Crash Report: Updating Screen Events [Bug]

### ISSUE THREAD

**Issue by Zerys2424** [LatvianModder/FTBUtilities#196]
[crash-2016-08-14_16.07.31-client.txt](https://github.com/LatvianModder/FTBUtilities/files/417076/crash-2016-08-14_16.07.31-client.txt)
When changing FTB config parameters and then canceling out of them causes a client crash and an exit game. Msg me for more info if needed.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/33
