### ISSUE TITLE
/ftb back doesn't work

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#197]
Apart from FTB back not working most of the time now, it crashes the server when it used, i have a 
[crash report](https://github.com/LatvianModder/FTBUtilities/files/417756/bug.for.Latvian.txt), not that is that foretelling, but it may mean something to you, the only reason i link this to FTBU is because it happens when /ftb back is used.

**Comment by CurtisLee1994** [comment]
/back from what i have found is only working on servers for members who are OP.

**Comment by LatvianModder** [comment]
It's mostly not back/home/warp that doesnt work, but my teleportation code. I will try to fix that
