### ISSUE TITLE
Auto Restart bug & command issues.

### ISSUE THREAD

**Issue by iNightmaree** [LatvianModder/FTBUtilities#198]
First off, the VPS I'm running on is on a Debian Wheezy 64bit system, running Java 8 I believe.

The first issue presents itself where only a brief error message will show if you try executing a command wrong, such as ftbu.missing.args, ftbu.server_restart and other things similar to that. Except it'll print perfectly fine in console, where instead it should probably print perfectly fine to both the client and the server, I'm assuming.

Then on comes the second issue where the auto restart feature won't work. It will give all the signs that it's planning to work, such as posting the ftbu.server_restart message in console, whilst giving the time remaining until server restart in console - from there it's looking great. Until it comes down to stopping the server for the auto restart, it won't actually bring up the server again. It'll just stay empty at the server directory you leave it at.

I'm not too sure if this is just me, but I'd quite like some help in trying to sort this.

I'm running the following versions of the core & main utilities mod:

FTBLib-1.8.10-1.0.18.3
FTBUtilities-1.7.10-1.0.18.3

Any help is greatly appreciated.

**Comment by Dijkstra1** [comment]
I am running windows and for restart i have an empty file in server dir call restart, and in my server startup script, at the end I check if the file restart exists if so goto the top of file. Having the file restart means, to stop server i just need to rename the file. Also doing this means if the server crashes it start it self back up again (just watch out for bugs that cause the server crash on startup). On Linux you would need to write a similar script using bash, @LatvianModder correct me if i am wrong, FTBU has no way to start the server back up again, once it has stopped.

**Comment by iNightmaree** [comment]
That's one way to combat it sure, but would also mean I would potentially be dismissing severe errors which would need to be looked at which I'm not prepared to do. Even if I was to implement this though, I'd still be left with the whole odd command messages.

However I do appreciate your comments.

**Comment by LatvianModder** [comment]
1) If the mod isn't also on client, it doesn't know how to translate the chat messages

2) Mod doesn't handle the restart, the .sh or .bat script does. Check how FTBInfinity server does it with its scripts

**Comment by Dijkstra1** [comment]
@iNightmaree, I looked into this a little, on windows the line after the call run the server you can exit code with %ERRORLEVEL%, when looking it up there does seem to an equivalent in bash, so maybe something like if %ERRORLEVEL%, == 0 and the file restart exits.

[Here](https://github.com/pahimar/ForgeCraft-Script/blob/master/script/minecraft) is unix script that is used to manage(backup, restart, ...) the forgecraft, if you use it would need to change, and i would recommend using it unless you understand every line code. Also frogecraft script does it without the need for FTBU.

**Comment by iNightmaree** [comment]
> 2) Mod doesn't handle the restart, the .sh or .bat script does. Check how FTBInfinity server does it with its scripts.

I see. Surely it should come as default to do this in the .sh though?

**Comment by LatvianModder** [comment]
True. I should probably clarify that it doesnt work without a script
