### ISSUE TITLE
[1.10.2] [Inadvertent Bug] Claimed chunks place place rights 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#199]
This is kind of hard to explain what going on so i recorded it in action 
http://ss.latmod.com/pc/2016-08-24_13.13.56.mp4
I own chunk I am in the chunk on the side is own by another player
This on it own i would say is low priority, util you find out the opposite is possible and you can place a block in chunk you do not have rights in by block it against a block in chunk you do have the right to interact with.

**Comment by LatvianModder** [comment]
Interesting. Since you clicked on block that is inside the chunk, it still thinks that its the chunk. Not sure how I could fix that, it will probably stay like that. Still gonna mark as bug. Also, I reuploaded your video so its viewable from web

**Comment by Dijkstra1** [comment]
I can definitely confirm this exists in 1.9.4+ versions the video in 1.10.2 Minecraft.

P.S Thanks about making the video watchable by all, not all of have a website that we can do that with.

**Comment by Dijkstra1** [comment]
Said the opposite was possible I built a nice house and got my sister to claim, to show it off even block the door way with bedrock because another mod makes that possible, demonstrated in the video below.
[latmodder.zip](https://github.com/LatvianModder/FTBUtilities/files/442023/latmodder.zip)

**Comment by LatvianModder** [comment]
Ah, thanks for the 2nd video. I think I can fix this by offsetting checker pos depending on block face clicked
