### ISSUE TITLE
FTB Utilities - "My Server Config" button drops connection with "A fatal error has occured, this connection is terminated"

### ISSUE THREAD

**Issue by nan0bug00** [LatvianModder/FTBUtilities#200]
Issue Description:  Clicking on "My Server Config" button drops the connection with "A fatal error has occured, this connection is terminated"

What happens:  

1. Clicking "My Server Config" button drops connection with "A fatal error has occurred, this connection is terminated" (see hastebin at bottom)

What you expected to happen:  

1. Expected FTB Utilities to store it's configuration in the /config directory like any other mod.  
2. Expected "My Server Settings" button to open some kind of configuration menu instead of throwing a critical exception, since it's the only obvious way to view/modify the configuration settings and is kind of important.

Steps to reproduce:   

1.  Go into the config directory of the pack to view/modify the configuration and get frustrated because FTB Utilities disregards conventions and user expectations and doesn't store its configuration there.  
2.  Go back on the server, click on the "My Server Config" button thinking you might get somewhere and get disconnected from the server with a fatal error.

Error Log:  http://www.hastebin.com/jicogonaxa.avrasm

**Comment by ShaCraft** [comment]
Confirmed on Default Unstable pack and modded pack. Both server disconnect clients when clicking the 'My server config' button. 

RG_Sha

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/33
