### ISSUE TITLE
[1.10.2] Rendering Incompatibility

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#202]
When you potion effect (some amour give permanent effects) you can not see the bottom.

![2016-08-26_01 23 01](https://cloud.githubusercontent.com/assets/11648771/17999344/69c123dc-6b68-11e6-8247-12ef0f16f12f.png)
 line of buttons

**Comment by everseeking** [comment]
Can you not fix it by changing your GUI scale in the video options menu? I always change mine to "Normal".
