### ISSUE TITLE
Pre3 op still unable to interact with items in claims

### ISSUE THREAD

**Issue by pathways029** [LatvianModder/FTBUtilities#204]
We have updated to pre 3 however ops still cannot interact with items in claims

**Comment by Dijkstra1** [comment]
are you in creative mode, also have you set up ranks with admin with * for blocks they can change.

**Comment by pathways029** [comment]
I am in creative mode. No I have not set up ranks??? What are ranks and how are they implemented? Is there any instructions on how this is suppose to be set up?

Also will players be able to break their gravestones in others claims?

**Comment by Dijkstra1** [comment]
Look up default rank file in the local file if it helps, do not rhino they fully implemented yet and you can set blocks that player break in other chunks in the rank file, but I have not managed to get that working graves yet (have not tried in the lastest version), if you have mine tweaker installed i recommend using the command /mt hand to get the name just remember to remove angle brackets.

**Comment by Dijkstra1** [comment]
[Ranks example] (https://gist.github.com/LatvianModder/5426786c7579df0296ec)

**Comment by Dijkstra1** [comment]
Just did some quick testing on my server and can can not interact with other players chynks, but my sister was able to get her grave from my base (Different teams not allied, my block security on members), but I think that is down to grave stone mod in the pack Tomb many graves give your stuff to you when  sneak on your grave, you may want to check that at least player will be able to get there stuff. For creative intervention @LatvianModder needs to fix that.

**Comment by everseeking** [comment]
> but I think that is down to grave stone mod in the pack Tomb many graves give your stuff to you when sneak on your grave

Gravstones are probably in the rank file for being whitelisted so people's graves can be retrieved in other claims:

> "ftbu.claims.break_whitelist": [
>           "OpenBlocks:grave"
>         ],

**Comment by Dijkstra1** [comment]
That is the open blocks, not the mod ID, that is the default as back in 1.7.10, that mod that added the grave stone. But the I'd where you should put your gravestone, item name when this is fixed.

**Comment by pathways029** [comment]
On a multiuser server, OPS/Admin still unable to interact with items in others claims;
- Enabled Ranks
- Created ranks.json using ranks_example.json
- used /ftb setrank to make person admin
- Tried to open chest and destroy block in creative and survival to no avail

This is a must for this mod to viable. I wont run a public server where my ops cant control it.
