### ISSUE TITLE
Option to turn this Team stuff off and Chunkloading not working.

### ISSUE THREAD

**Issue by OldManCraft** [LatvianModder/FTBUtilities#206]
This 1.10 version is not keeping chunks loaded at all. Set the timer to -1.0 and still don't work. I'm even the  Admin on the server and the chunks are all unloaded the next morning.  The 1.7.10 version was perfect. I get wanting to improve the Mod, but at this point I have had to remove from my servers as it is pain to manage. Maybe I'm missing something ? 
Running the Pre3 version.

**Comment by LatvianModder** [comment]
Pre 3 shouldve fixed chunkloading issues that were occuring in pre2. McJty confirmed that he has been using it for few weeks and it works fine

**Comment by OldManCraft** [comment]
Is there a option planned to turn off the Team aspect of the mod? Could this be a future enhancement ? 

Thanks for your reply. I will give it a try again

**Comment by OldManCraft** [comment]
Have you been told about the lighting issue when walking in and out of claimed chunks. It turns to almost night ? if not I can create a vid and a issue..

**Comment by LatvianModder** [comment]
Ya, I know about the lighting issue, its fixed in unreleased version. Teams will not be turned off, thats replacing friends system now and is a core feature

**Comment by OldManCraft** [comment]
Ok Great thanks for the info...

**Comment by OldManCraft** [comment]
Is it possible to get the fixed version ? I would like use your mod but it's unplayable right now

**Comment by LatvianModder** [comment]
I *should* have released with Just that issue fixed, now im too many changes in and there's a lot of unfinished stuff, sorry, you'll have to wait a bit more :/
