### ISSUE TITLE
Black and white on claimed chunk borders

### ISSUE THREAD

**Issue by Ashendale** [LatvianModder/FTBUtilities#207]
I'm using the 1.9.4-2.1.0-pre3 on DonutCraft (ATLauncher, version 1.10.2-0.1.1b, Minecraft 1.10.2) and whenever I reach a limit of a claimed chunk the screen flickers it's rendering. I notice this happens whenever a notification on the top right of the screen shows up. Suddenly it's like I activated the Super Secret Settings and everything becomes black and white.

It stays that way if I remain in place, but changes back after some moving around, crossing some chunk borders.

This also happens if I leave my spawn area (even if not claimed) and go into wilderness.

Is there a workaround? Can the notifications be turned off?

**Comment by everseeking** [comment]
FTB Unstable 1.10.2 - 4.2.7
FTBUtilities-1.9.4-2.1.0-pre3
Forge 12.18.1.2073

I am also noticing this, something with the notification overlay makes my screen darker or the black/white/grey (usually when in inventories) as mentioned above. Occurs when the notification window slides into view, then goes back to normal when it fully retracts.

A bug, annoying, but not game breaking.

**Comment by everseeking** [comment]
FTB Unstable 1.10.2 - 4.2.7
FTBUtilities-1.9.4-2.1.0-pre3
Forge 12.18.1.2075

Issue still exists with latest Forge version.

Here are some screenshot examples:
- http://i.imgur.com/YJH8E9j.png

- http://i.imgur.com/mwkIe1F.png

- http://i.imgur.com/qRSFqXa.png

- http://i.imgur.com/EUWOUeA.png

However, sometimes the black/white goes away when change your view position, with the notification still being shown:

- http://i.imgur.com/95Ks1FD.png

- http://i.imgur.com/TJcTsmA.png

**Comment by everseeking** [comment]
Well, sorry for all the updates but I see that LatvianModder has addressed the issue found in another unrelated issue conversation: https://github.com/LatvianModder/FTBUtilities/issues/206#issuecomment-242906402
