### ISSUE TITLE
Pre 3 Config.json resetting

### ISSUE THREAD

**Issue by pathways029** [LatvianModder/FTBUtilities#209]
On a multiplayer server when the server resets the config.json seems to be rewritten with the default values. Editing it through the Gui crashes. How are we to change these configure settings?

**Comment by Dijkstra1** [comment]
you can edit config with commands /ftb edit_configs config_name value, tab complete works with getting names, and I was able to edit configs fine in notepad++, but the server does not stopped while external editing of configs.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/35
