### ISSUE TITLE
Need to turn of team chunk claims and enable singlelayer chunk claims

### ISSUE THREAD

**Issue by Omega696** [LatvianModder/FTBUtilities#210]
There is no options to turn the system from a Team chunk claim to a single person. We do not play on a team server, it is an singplayer SMP.
We would like a person to claim the chunks so they can protect there stuff (and define how much the can claim) without having to create individual teams.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/174#issuecomment-246140645
