### ISSUE TITLE
Players(non-op) can't perform any commands in ftbu on Cauldron 1.7.10 server.

### ISSUE THREAD

**Issue by droashen** [LatvianModder/FTBUtilities#211]
When use ftb utilities on cauldron 1.7.10 server(thermos edition,without any plugin that block commands),i bump into troubles that those commands(/back /spawn and any chunk claim in ftbu) are not allowed to be used by non-op players.Is there any things in cauldron 1.7.10 block those commands?(bukkit?)And how can i make those commands available in ftbu for non-op player?

**Comment by everseeking** [comment]
I doubt you will be getting much help here for Thermos issues, this is mostly just regular Forge + FTB Utilities. You will have to bring you issues up with Thermos devs.

**Comment by LatvianModder** [comment]
Sorry, we don't support those kind of servers
