### ISSUE TITLE
Server crash when trying to edit server settings [1.10.2]

### ISSUE THREAD

**Issue by Chryseus** [LatvianModder/FTBUtilities#212]
The client disconnects when My Server Settings is clicked or "/ftb edit_config" is used, this occurs both in singleplayer as well as on a dedicated server.
I've also had it once leak memory causing Minecraft to lock up.
Log: http://pastebin.com/pFikF8tr

**Comment by everseeking** [comment]
Issue is already open: https://github.com/LatvianModder/FTBUtilities/issues/205
