### ISSUE TITLE
Breaking Whitelist for ForgeEssentials' graves

### ISSUE THREAD

**Issue by Gammelkebab** [LatvianModder/FTBUtilities#214]
I tried whitelisting heads/skulls and fences, none of it made my people able to break their own graves within the Server spawn area. The syntax should be stated somewhere to prevent most errors with it.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/179

**Comment by LatvianModder** [comment]
Then say so, because 1.7.10 is no longer supported. But there is a break list for graves, openblocks graves added by default
