### ISSUE TITLE
[1.10.2] Crash when using /ftb team config command 

### ISSUE THREAD

**Issue by Stuart74** [LatvianModder/FTBUtilities#215]
Whenever a player on my server issues the command **/ftb team config** it will disconnect them from the server, no error comes up for them or on the server just the message a fatal error has occurred.

Forge Version:  2076
FTBUtils Version: FTBUtilities-1.9.4-2.1.0-pre3.jar

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/33
