### ISSUE TITLE
Option To Add TP for Players (Feature Request) (1.7.10)

### ISSUE THREAD

**Issue by aetherpirate** [LatvianModder/FTBUtilities#217]
I would like players to be able to use the TP command. I played with config.json and added "tp": true, as a guess to how it might work, but I do not think I am doing it right. Is there documentation as to what is possible with the configs for this mod?

  },
  "commands": {
    "back": true,
    "home": true,
    "name_admin": "admin",
    "spawn": true,
    "tplast": true,
    "warp": true
    **"tp": true,**
  },

**Comment by LatvianModder** [comment]
/tpa, /tpaccept /tpdeny is in to-do list

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/128
