### ISSUE TITLE
Pre 3 /Ftb home [ID] from the nether crashes server

### ISSUE THREAD

**Issue by pathways029** [LatvianModder/FTBUtilities#218]
Running a whitelisted server on DonutCraft. Tried to go home from nether (twice) and it crashed the server.

http://pastebin.com/aypP3Jcs

**Comment by Dijkstra1** [comment]
Looking at your crash report, it seems that crash is initiating, from a vanilla class, must likely down to fact Mojang, did think any one could leave the nether, other than through the portal, or death. @LatvianModder, will have to confirm this, but if this case the only thing that I can suggest is that he, has a look into how the nether portal works, to see how that handles it.

**Comment by LatvianModder** [comment]
Hm, it worked fine in other versions / 1.7.10. I'll have a look at this

**Comment by flagoss** [comment]
Someone was crashing my server today with the exact same crash every time he was trying to go in the nether trough the vanilla portal. Was not using /ftb...
Deleted his nether region file fixed the problem.

http://pastebin.com/beL6L43G

**Comment by ShaCraft** [comment]
Make sure that Java is updated on the Server I was having an issue on CreeperHost and did some digging only to find they were using a 2 year old Java build. I have not had a server crash after I had them update my server. Same with a few other nether portal bugs.

**Comment by LatvianModder** [comment]
FTBU/Lib needs Java 8

**Comment by pathways029** [comment]
I'm hosting from Nodecraft, I'm sure they have the latest Java :-)

**Comment by axisonegaming** [comment]
I can confirm this happens on our server as well, and we are also hosted on Nodecraft. As a workaround, I've been telling our users to use /ftb spawn and then /ftb home <id> to prevent the crash.

**Comment by LatvianModder** [comment]
Can someone try this in 3.0.0.x versions? Works fine for me in singleplayer. Reopen if the issue is still there
