### ISSUE TITLE
Ranks / permissions

### ISSUE THREAD

**Issue by blaaap** [LatvianModder/FTBUtilities#219]
using: FTBUtilities-1.9.4-2.1.0-pre3
related to: https://github.com/LatvianModder/FTBUtilities/issues/204

The whole ranks system does not seem to work for us.

In the config.json we have the following setting:
`    "chunk_loading": false,`
After testing I can confirm that chunkloading still works.

Copied the ranks_example.json to the ranks.json file and set:
`"ftbu.chunkloader.max_chunks": 0,`
after reloading client and server I confirm that Players still have the default 50 chunks to load.

Can supply additional info if required.

**Comment by LatvianModder** [comment]
Yeah no kidding. It's not implemented yet :P

**Comment by blaaap** [comment]
That explains a lot, I thought it was because of the example file. :)

Feel free to close this, I'll keep an eye on updates.
