### ISSUE TITLE
Mod Compatibility with Extra Utilities 2 (chunk loading)  

### ISSUE THREAD

**Issue by ShaCraft** [LatvianModder/FTBUtilities#220]
Might be an issue when a chunk loader from both mods are used in the same chunk?
I'm not great at reading crash logs so I could be wrong. 

http://pastebin.com/pGq0833N

**Comment by LatvianModder** [comment]
File no longer available, but I will guess that its the issue. Trying to load 2 different chunkloaders in same chunk doesnt usually end well

**Comment by LatvianModder** [comment]
Try with 3.0.0.x and re-open this issue if it still crashes
