### ISSUE TITLE
Ally teams are not saved after server restart.

### ISSUE THREAD

**Issue by flagoss** [LatvianModder/FTBUtilities#221]
We always have to re add our ally everyday. Is that normal ?

**Comment by LatvianModder** [comment]
That's not normal

**Comment by flagoss** [comment]
Where is everything saved on the server ?

**Comment by LatvianModder** [comment]
world/FTBLib.dat, I think

**Comment by flagoss** [comment]
Thanks... Just looked at the files and I can see all the information about players, chunks and team... but nothing about ally so that might be the problem.

**Comment by LatvianModder** [comment]
Must have forgotten to add that when saving team info
