### ISSUE TITLE
[1.10.2] Starting Items don't work

### ISSUE THREAD

**Issue by ulkunderscore** [LatvianModder/FTBUtilities#222]
Tested in Singleplayer with only FTB Utilities 2.1.0-pre3 and lib.
My config:

>   "login": {
    "enable_motd": true,
    "enable_starting_items": true,
    "motd": [],
    "starting_items": [
      "minecraft:stone_pickaxe 1 0"
    ]
  },

**Comment by LatvianModder** [comment]
Update to 3.0.0.x, fixed there
