### ISSUE TITLE
Chunkloading does not appear to work

### ISSUE THREAD

**Issue by utoc** [LatvianModder/FTBUtilities#228]
Greetings,

We've loaded FTBu/l into our pack and attempted to use it for chunkloading but after a lot of testing, it doesn't seem to work on SMP

FTBLib-1.10.2-3.0.0.3
FTBUtilities-1.10.2-3.0.0.2
FML 2095 in MC 1.10.2

I've tested this with both the GUI and with commands (/ftb chunks claim and /ftb chunks load).  I used a simple redstone pulse generator and a rfTools transmitter/receiver to verify whether the chunk remained loaded or not.

In the cases that we tested, 0 chunks were loaded initially.  When the server was restarted, SOME of the chunks were loaded (as seen by /ftb server_info) but not all.  We had 10 chunks ordered to load but only 4 were present and it seemed a little random.  From that point, no GUI/commands or even unclaiming would stop those chunks from being force-loaded.

Let me know if there are any additional steps I can take to help you pinpoint the issue.

**Comment by LatvianModder** [comment]
Yes, I have already rewritten the chunkloading system (see last commit history)

**Comment by mcdodge34** [comment]
I can confirm this issue, updated the mods from 1.9.4 2.1.0pre3 version that was working fine, and now with latest, it doesn't work, can we expect a new release soon or I need to go back to the old version...

**Comment by Darkosto** [comment]
Working with:
FTB Utils: 3.0.0.3
FTB Lib: 3.0.0.4
Forge: 2105

I am able to chunkload in the Overworld, nether, end, and other modded dimensions except for RFTools dimensions. I checked and other mod chunkloaders are working, but I cannot select the RFTools chunks.

**Comment by LatvianModder** [comment]
I consider this specific bug fixed

**Comment by LatvianModder** [comment]
Gonna mention some other bugs related here though:
https://github.com/LatvianModder/FTBUtilities/issues/233
https://github.com/LatvianModder/FTBUtilities/issues/229
