### ISSUE TITLE
[1.10.2] 3.x Setting backup interval < 1.0 causes an infinite loop of backups

### ISSUE THREAD

**Issue by gdude2002** [LatvianModder/FTBUtilities#230]
Pretty much as the title says; we set it to `0.5` (what I assume means half an hour) and it just kept backing up repeatedly with no delay between.

It _did_ delete the old backups as expected, at least, but the output is annoying. And I'd like half-hour backups. :(

**Comment by LatvianModder** [comment]
Fixed in commit above ^
Gonna close when I release a new version
