### ISSUE TITLE
3.0.2 master won't build 

### ISSUE THREAD

**Issue by kzkv** [LatvianModder/FTBUtilities#231]
Hi, 

First, thank you very much for your work! 

My friend @otann and I are trying to build the current master, v3.0.2, of FTBU and have no luck with that. Is there some WIP? And if that's the case, could you please point us in the direction of the last stable version commit? 

Best, 
Tom

**Comment by LatvianModder** [comment]
What error are you getting?

**Comment by LatvianModder** [comment]
Because it builds fine for me

**Comment by kzkv** [comment]
Actually, to be precise the current version builds alright and won't run, while the previous versions (3.0.0) won't build. 

Here's the output of a run attempt after successful build of the current master (3.0.2) built by `gradlew build`: https://gist.github.com/kzkv/3090da4e2ec3e9f839a89dde028ebd79

Thank you for your time!

**Comment by LatvianModder** [comment]
Ah yes, forgot about that. You have to copy-paste contents of [PermissionAPI-1.0.0.jar](http://assets.latmod.com/mods/PermissionAPI/1.0.0) into FTBLib jar. Still waiting on https://github.com/MinecraftForge/MinecraftForge/pull/3155 to be merged, so this is a little annoyting thing that has to be done, before PR is merged

**Comment by kzkv** [comment]
OK, cool, thank you, that worked! 

P.S. Sorry, I should've put this to the FTBLib ticket tracker, not here.

**Comment by LatvianModder** [comment]
It's alright

**Comment by luacs1998** [comment]
@LatvianModder LOL you can also throw PermissionsAPI-1.0.0.jar into the mods folder IIRC

**Comment by LatvianModder** [comment]
@luacs1998 I won't upload jars on github, I need a proper buildscript. I will embed the PermissionAPI in FTBLib, because *obviously* Lex isn't gonna merge that PR :P
