### ISSUE TITLE
Bug, Hermitpack 1.0.1/1.1.0 ftbu config files reset every startup

### ISSUE THREAD

**Issue by Metaz78** [LatvianModder/FTBUtilities#232]
Running a server with one FTB Inf Evol 1.7 and testing one FTB Hermitpack 1.10.2.
On every startup of the Hermitpack server, the ftbu config files are all reset back to default.
I use notepad++ to edit and only edit true/false for testing.
Nothing works to get it to stay edited.
It change during the startup sequence somewhere at the end.

**Comment by LatvianModder** [comment]
If you edit the files, use "/ftb reload" after you've edit them or edit them while the server is offline. Or you can use "/ftb edit_config [id]" from ingame

**Comment by Metaz78** [comment]
I have the server offline while editing. As soon as the server goes through startup, all the files reset back to default.

**Comment by Metaz78** [comment]
I took a closer look at the last part of the startup. I believe the error lies in these lines.
[https://gyazo.com/0bba580c1903e4d2d9fcca2c043d8061]
Before starting the server, I changed the backup folder in the config.
The server doesn't recognize it.

**Comment by Ommina** [comment]
Add _default_ranks.json_ to the list of files (in fairness, Metaz78 did say all files anyway) that are overwritten and returned to default on server start.  As above, this file **is** being edited while the server is offline.  Sometime during startup, it is reverted to the eight-line default.

FTBU v3.0.0.3
SMP
And forge 12.18.1.2095, just in case.

**Comment by Metaz78** [comment]
I think the files are re-created during the final phase of the startup.
Any update at all would be nice :)
However, I seem to recall that it is Friday and I hope you have a nice weekend LatvianModder.

**Comment by LatvianModder** [comment]
@Ommina all non config.json files in /ftbu arent functional currently

**Comment by Metaz78** [comment]
I just installed (clean install, no upgrade or overwrite) the updated Hermitpack with the same results.
All config files are recreated with default values during startup.

**Comment by Metaz78** [comment]
I did a third installment and this time I made sure not to use any spaces or . like I did before.
This time the config.json works and as you said, all others fails.

**Comment by Ommina** [comment]
@Metaz78 I would be thrilled to hear what you did to get config.json to behave, as I'm still struggling.  You say no spaces nor periods.  Where did you avoid them?  Any further detail you can offer myself and others reading this?

**Comment by Metaz78** [comment]
My first installments were in folder called "Hermitpack v.101" and "Hermitpack v.110"
The third I named HPack110 and now it works.
