### ISSUE TITLE
[1.10.2]NEI buttons overlap with FTBUtilities

### ISSUE THREAD

**Issue by Managarmr719** [LatvianModder/FTBUtilities#234]
NEI: 1.10.2-2.1.2.156
FTBUtilities: 1.10.2-3.0.0.3

![2016-10-13_23 36 51](https://cloud.githubusercontent.com/assets/7836631/19369747/31000e34-919f-11e6-9129-522955dce7dc.png)

**Comment by LatvianModder** [comment]
If you *really* want to use those together, you can always set "buttons on top" setting to false in Client Config
