### ISSUE TITLE
403 for FTBLib dependency

### ISSUE THREAD

**Issue by Otann** [LatvianModder/FTBUtilities#237]
Hi! I'm trying to bring in some fixes for latest PR, but can't build latest master:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'FTBUtilities'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve com.github.LatvianModder:FTBLib:1.9-SNAPSHOT.
     Required by:
         com.feed_the_beast.ftbutilities:FTBUtilities:1.10.2-3.1.0
      > Could not resolve com.github.LatvianModder:FTBLib:1.9-SNAPSHOT.
         > Unable to load Maven meta-data from https://libraries.minecraft.net/com/github/LatvianModder/FTBLib/1.9-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://libraries.minecraft.net/com/github/LatvianModder/FTBLib/1.9-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

Could you please help me with that?

**Comment by MCTyler** [comment]
I get the same thing and I thought I reported it but I can't find it any where....I'll post my log...

> FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'FTBUtilities-1.9'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve com.github.LatvianModder:FTBLib:1.9-SNAPSHOT.
     Required by:
         com.feed_the_beast.ftbutilities:FTBUtilities-1.9:1.10.2-3.1.2
      > Could not resolve com.github.LatvianModder:FTBLib:1.9-SNAPSHOT.
         > Unable to load Maven meta-data from https://libraries.minecraft.net/com/github/LatvianModder/FTBLib/1.9-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://libraries.minecraft.net/com/github/LatvianModder/FTBLib/1.9-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 50.009 secs

**Comment by MCTyler** [comment]
gonna open new issue, this may have slipped by...

**Comment by LatvianModder** [comment]
This will no longer happen when I move to maven. Until then, well.. jitpack.io isn't ideal

**Comment by MCTyler** [comment]
Seems that there should be a way to put in the dependencies manually...Oh well, guess we wait for the move to Maven or wait for you to release a updated build..

**Comment by LatvianModder** [comment]
Fixed

**Comment by MCTyler** [comment]
1 minute ago...
<details>
* What went wrong:
A problem occurred configuring root project 'FTBUtilities-1.9'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve Mercurius:Mercurius:1.10.2-1.0.1.
     Required by:
         com.feed_the_beast.ftbutilities:FTBUtilities-1.9:1.10.2-3.1.2 > com.github.LatvianModder:FTBLib:1.9-SNAPSHOT
      > Could not resolve Mercurius:Mercurius:1.10.2-1.0.1.
         > Could not get resource 'https://libraries.minecraft.net/Mercurius/Mercurius/1.10.2-1.0.1/Mercurius-1.10.2-1.0.1.pom'.
            > Could not GET 'https://libraries.minecraft.net/Mercurius/Mercurius/1.10.2-1.0.1/Mercurius-1.10.2-1.0.1.pom'. Received status code 403 from server: Forbidde
</details>

**Comment by MCTyler** [comment]
OOOps Sry forgot to dowload latest build...

**Comment by wadewegner** [comment]
Similar issue with this mod: https://github.com/P3pp3rF1y/AncientWarfare2/issues/585

Any thoughts on how to fix?
