### ISSUE TITLE
Rank system doesnt work (Keeps changing every time I edit)

### ISSUE THREAD

**Issue by TheQKnight** [LatvianModder/FTBUtilities#238]
Every  time I edit the ranks.json (Which I had to create myself, because it wasn't being created by the system) and change some of the permissions, it resets and changed all the "-" in front of the permission to "+"s. This is extremely annoying and I cant figure out whats wrong.

Here what I have:

{
  "default_rank": "Player",
  "ranks": {
    "Player": {
      "parent": "",
      "permissions": [
        "+ftbu.display.permissions",
        "+ftbu.display.rank",
        "+ftbu.homes.cross_dim",
        "+*"
      ]
    },
    "Admin": {
      "parent": "",
      "permissions": [
        "-*"
      ]
    }
  }
}

Whenever I change the "Admin" permissions to "+*"
 it reloads the Player permissions and negates all of them:

{
  "default_rank": "Player",
  "ranks": {
    "Player": {
      "parent": "",
      "permissions": [
        "-ftbu.display.permissions",
        "-ftbu.display.rank",
        "-ftbu.homes.cross_dim",
        "-*"
      ]
    },
    "Admin": {
      "parent": "",
      "permissions": [
        "+*"
      ]
    }
  }
}

If I am doing something wrong please let me know, it has been impossible for me to find proper documentation on how to use this ranks system. Thanks

**Comment by TheQKnight** [comment]
Please help me figure this out Asap

**Comment by TheQKnight** [comment]
even if I do a simple thing like this:

{
  "default_rank": "Player",
  "ranks": {
    "Player": {
      "parent": "",
      "permissions": [
        "-*"
      ]
    },
    "Owner": {
      "parent": "",
      "permissions": [
        "+*"
      ]
    }
  }

Every time I reload the configs it swaps both "+"s and "-"s

This is so weird

**Comment by Ommina** [comment]
@TheQKnight 

Per the comment made in #232, the ranks.json file is not working at the moment.  So you can relax, happy in the knowledge that it (probably) isn't you doing something wrong.

**Comment by MCTyler** [comment]
Ranks have not been implemented yet......
