### ISSUE TITLE
Vers 1.7.10-1.0.13.1, unknown if replicatible in later vers. can break chunk protection

### ISSUE THREAD

**Issue by Matakor** [LatvianModder/FTBUtilities#24]
Sorry for the succinct title. I've discovered that I can get around chunk protection using the dislocation foci from Thaumic Tinkerer. I'm uncertain if FTB utils can even correctly blacklist it, as it gets around even spawn protection. I'm not op on a server, and as of yet I haven't found any other way around chunk protection, but this one is major. Anything the focus can move (which is a lot) I can place or remove from a chunk protected area. For an example, I can place AE cables connecting to a chunk-protected network and access someone's AE system from outside the protection. As far as I know, minus a few very specific placeable objects, I'm able to tinker with just about everything.

This is limited to single-block per use, so process is slow, but it's entirely possible. I don't know if this has been fixed since this version, it's the only one I've tested as of yet, but unless it's known, I don't think it is fixed.

**Comment by LatvianModder** [comment]
Fixed in v1.0.17+
