### ISSUE TITLE
Suggestion / Demand :P Time Sets should skip to the next day rather then reset it.

### ISSUE THREAD

**Issue by KaneHart** [LatvianModder/FTBUtilities#240]
So when you click the day button or night button they should not reset the time back to 0 but rather skip to the next day 6am or so.

**Comment by mezz** [comment]
Yes, these button actions should match the times used by the built-in commands `time set day` and `time set night`.

**Comment by LatvianModder** [comment]
Oh? I thought it sets some relative time, instead of resetting it
