### ISSUE TITLE
[Suggestion] Make /ftb team commands accept optional target player

### ISSUE THREAD

**Issue by SharkWipf** [LatvianModder/FTBUtilities#241]
Currently, it does not seem to be possible to, as server admin, add people to someone else's team (and thus claim).
When someone forgets to add a team mate, or has to leave in a hurry before they can, the other player is currently stuck waiting for the team owner to come back. 
Even when the server admin knows they belong to the same team, there's currently nothing the server admin can do, other than deleting the claim altogether.

Related: I feel rank op should be able to bypass join restrictions and be able to join teams without invite.

**Comment by LatvianModder** [comment]
hm. admin_team command prehaps? It *could* be useful, but I don't really see why you should decide what team people go. They should choose themselves

**Comment by SharkWipf** [comment]
Of course, but sometimes the team owner can't do it themselves (forgot username of team mate and went offline, or no good understanding of how the mod works?), and when you know the players belong together anyway it would be nice if you could help 'em out.  
Beats telling players to "go build somewhere else until the claim owner is back", especially when you know the claim owner won't be back for a few days.

**Comment by LatvianModder** [comment]
Hmm, true true

**Comment by LatvianModder** [comment]
In 3.4.0+ its quite easy to add someone to another team using NBTExplorer
