### ISSUE TITLE
Can access drawers in other claims

### ISSUE THREAD

**Issue by DeathOfTime** [LatvianModder/FTBUtilities#244]
Minecraft v. 1.10.2
"pack": "Spilled Juice",
"version": "0.2.4",
StorageDrawers-1.10.2-3.2.7.jar
FTBUtilities-1.10.2-3.1.1.jar

My drawers system is completely within my claim. My little brother was able to access it and get things out of it as normal (by hitting or sneak hitting the drawer.) He isn't on my team. He has his own claim, where his base is.

Workaround: use the key in Storage Drawers to keep others from accessing them.

**Comment by LatvianModder** [comment]
Was your bro an OP? Because OPs can access chunks without being in the same team or even allies

**Comment by DeathOfTime** [comment]
no. neither of us were op. when i used the key to make the drawer private he couldn't access it any longer either. Not for sure if those are associated.

**Comment by LatvianModder** [comment]
Is that a singleplayer lan world or server? I think in Lan worlds everyone is OP

**Comment by LatvianModder** [comment]
It also could be that drawers override left/right click events, if so I can't do anything about it

**Comment by DeathOfTime** [comment]
it is the official spilled juice server. no single player.

i have no clue if it overrides events. just reporting what i find. In case the mod devs have any use for it.

**Comment by LatvianModder** [comment]
I'm guessing that StorageDrawers just override normal behaviour and I can't block it. You might need to open an issue on their end, but I don't think its fixable
