### ISSUE TITLE
Chunk claiming in RFTools dimension refuses to work

### ISSUE THREAD

**Issue by masterX244** [LatvianModder/FTBUtilities#245]
When trying to claim a chunk in a RFTools dimension nothing happens, 
Using the Hermitpack version of RFTools and the latest FTBLib/FTBUtils pair (3.1.1).
No Error message appearing in the server or the client log

**Comment by gmoff01** [comment]
Same issue here.  I tried adding the dimension number to the locked_in_dimensions array in the config, but no effect.

**Comment by monsen** [comment]
Same issue here on the DireWolf20 1.10 pack.
When trying to claim a chunk via the map GUI, nothing happens.
Trying to use the command line commands instead, the error message 'Can't modify this chunk' (text may not be exact) pops up in the upper right corner on a red background.

According to the jar filename, I am using version 1.10.2-3.2.4

**Comment by AugustoAmaral** [comment]
Same Here, using Driewolf20 1.10 pack too.

RFTools Dimensions Version: 1.1x-4.53
RFTools Version: 1.1x-5.81
RFTools Control Version: 1.1x-1.6.4
FTBUtilities Version: 1.10.1-3.2.4

**Comment by LatvianModder** [comment]
Fixed in later versions
