### ISSUE TITLE
Commands and friends Don't seem to work

### ISSUE THREAD

**Issue by tacogerbil** [LatvianModder/FTBUtilities#246]
I'm using Forge 12.18.2.2099, MC 1.10.2
The config windows show up fine, I'm able to select chunks, the guide book shows a guide for the Chisel mod and the FTBUtilities guide just shows "testing123".. My problems arise when I try to set some friends.  No one on my server (private home server for my 2 sons and their cousins) shows up on any list.  Completely blank.  All the admin commands return as unknown commands.  ftb_mode commands are also unknown.  
The Curse pages don't detail the requirement of any other mods other than the util and lib jar files.  I am Opped and am able to do all other op/admin functions on my server.  The FTB Server Info shows me as "op".
Is there a way to find a log or anything to point me in the right direction?

**Comment by LatvianModder** [comment]
It's team based now - You must invite other team members with /ftb team invite {player}, and they have to /ftb team join {yourTeamID}.

**Comment by Reignofmagic** [comment]
These commands do seem to be broken. 

Playing the FTB Hermit craft, v1.1. 

Example of what was done: 

/ftb team leave (deletes my team)
/ftb team create derp
/ftb team invite Cantalope (my friend)

Cantalope types
/ftb team join derp

He receives the following message: 
Cantalope is not a member of this team. 


Also the Gui for the Friends doesn't update with who is on the server.

**Comment by Noobsloth** [comment]
There needs to be interface options for these commands. Players are used to just using the interface for FTB utils. Just my opinion.

**Comment by LatvianModder** [comment]
Yeah, its true. Im slowly working on an interface, BUT it cant be the only option. There needs to be both with equal base possibilities - interface and commands

**Comment by LatvianModder** [comment]
Does it work now?

**Comment by scalda** [comment]
Teams are working correctly with the latest version you released i can confirm this

**Comment by NEXUS2345** [comment]
This issue appears to be occurring again in version 3.1.4 on the DW20 1.10 pack.

**Comment by NEXUS2345** [comment]
This issue also occurs with FTB Lib version 3.1.6.

**Comment by popatop15** [comment]
Any idea when this will be fixed?
Version 3.1.4

**Comment by LatvianModder** [comment]
Def 3.2.x. Maybe I will make another small 3.1.x update

**Comment by popatop15** [comment]
Yeah the interface is pretty big, but not as important as the team functions actually working :p

**Comment by LoOnyBin25** [comment]
non off the ftb commands are working on my server but i have the mod and its enabled

**Comment by Cronosus** [comment]
for me ftb commandsa not working too on server (kettle), only with OP
even if i set permissions, it still not working for players
