### ISSUE TITLE
Send backup to FTP server

### ISSUE THREAD

**Issue by Dinip12** [LatvianModder/FTBUtilities#248]
I would like to know if i do backups to my ftp server instead to save on server's folder.
I hava a VeryGames server and they provide only 5Gb, my map has 2gb and when i have 2/3 backups my disk fill.
I have a ftp server with ~100gb.

Sry for bad english :/

**Comment by LatvianModder** [comment]
Mods shouldn't handle large file transfers, that should either be done manually or by an external software
