### ISSUE TITLE
ClaimedChunkStorage.canPlayerInteract returns bad value

### ISSUE THREAD

**Issue by kayila** [LatvianModder/FTBUtilities#249]
ClaimedChunkStorage.canPlayerInteract returns true if a player is an ally to the chunk owner's team, however false if the player is a member of the team.  This is currently preventing players on my server from working in chunks as a group.

**Comment by Alaberti** [comment]
Can confirm, also experiencing this problem on a dedicated server, have not checked a LAN environment.

FTBU/L 3.1.1
Forge 2107

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/pull/250#issuecomment-256301080

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/commit/2cdc800c8bd59d85017f106bb2e334f3998651c5

**Comment by Alaberti** [comment]
I'll bite the bullet for asking - is there an eta for the next build?

**Comment by LatvianModder** [comment]
Fixed in latest version
