### ISSUE TITLE
Automated Restart causes HQM Corruption

### ISSUE THREAD

**Issue by Noobsloth** [LatvianModder/FTBUtilities#251]
Hiya,

I set up my server to reboot every 12 hours or so a good week ago with FTB Utilites. Every couple of days I'd have to rollback HQM due to crashes. I disabled FTB Utilites' restart and restart the server by hand and it resolves this issue. For now I've disabled FTB restarts, but I would love to be able to use this feature. I've narrowed it down to be caused by FTB Utilities' restart. Something is happening the the process that's causing this corruption. Some advice on how to resolve this would be appreciated. I've pastebined one of the crash logs.

I've also posted this in the HQM ghithub.

http://pastebin.com/yGwyzinj

**Comment by LatvianModder** [comment]
Sorry, 1.7.10 is no longer supported

**Comment by Noobsloth** [comment]
I already knew that, I was asking for a direction to go in to resolve this type of issue.

But hey, we can just disable the mod.
