### ISSUE TITLE
[Request] Allow chunk-loading when chunk-claiming is disabled

### ISSUE THREAD

**Issue by Mohron** [LatvianModder/FTBUtilities#252]
Currently if you disable chunk-claiming it effectively disables chunk-loading unless players have chunks claimed from prior to disabling chunk-claiming. In that case, chunk-loading can be toggled on/off for those legacy chunk claims.

If claiming is disabled in the config, can FTBUtils allow players to chunkload outside a claimed chunk up to their maximum as long as the chunk is not claimed (spawn/other player) or already chunkloaded?

**Comment by LatvianModder** [comment]
Nope, sorry, because the way its written - I store the "isLoaded" in a claimed chunk object. So if there is nothing claimed there, I can't store the value

**Comment by Mohron** [comment]
How about if chunkclaiming is disabled and chunkloading is enabled, as far as the command and map go, you can chunkload which will create a claim in that chunk automatically. The limits would just mirror and the claim would be public (no do anything but prevent other claims). If you remove the chunkload, it removes the claim. You could still store the chunkload the same way but it allows easier use of just the chunkloading feature.
