### ISSUE TITLE
Building Mod

### ISSUE THREAD

**Issue by MCTyler** [LatvianModder/FTBUtilities#253]
You have instructions for building but we are forbidden from the dependencies....

> FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'FTBUtilities-1.9'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve com.github.LatvianModder:FTBLib:1.9-SNAPSHOT.
     Required by:
         com.feed_the_beast.ftbutilities:FTBUtilities-1.9:1.10.2-3.1.2
      > Could not resolve com.github.LatvianModder:FTBLib:1.9-SNAPSHOT.
         > Unable to load Maven meta-data from https://libraries.minecraft.net/com/github/LatvianModder/FTBLib/1.9-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://libraries.minecraft.net/com/github/LatvianModder/FTBLib/1.9-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/237
