### ISSUE TITLE
Cant Build Mod

### ISSUE THREAD

**Issue by TheQKnight** [LatvianModder/FTBUtilities#254]
When I open a command window to build your mod by typing "gradlew build --stacktrace" I come up with this error:

![screenshot 1129](https://cloud.githubusercontent.com/assets/17223871/19819503/d4591966-9d09-11e6-92a7-cdb2b2742a2e.png)

**Comment by MCTyler** [comment]
You can't read that @TheQKnight , try copy and pasting the text instead of a screen shot.

**Comment by TheQKnight** [comment]
If you click it you can read it

**Comment by MCTyler** [comment]
When I try to build it, it gives me a forbidden 403 error for the dependencies....

**Comment by LatvianModder** [comment]
Fixed

**Comment by MCTyler** [comment]
1 minute ago.....
<details>
* What went wrong:
A problem occurred configuring root project 'FTBUtilities-1.9'.
> Could not resolve all dependencies for configuration ':deobfCompile'.
   > Could not resolve Mercurius:Mercurius:1.10.2-1.0.1.
     Required by:
         com.feed_the_beast.ftbutilities:FTBUtilities-1.9:1.10.2-3.1.2 > com.github.LatvianModder:FTBLib:1.9-SNAPSHOT
      > Could not resolve Mercurius:Mercurius:1.10.2-1.0.1.
         > Could not get resource 'https://libraries.minecraft.net/Mercurius/Mercurius/1.10.2-1.0.1/Mercurius-1.10.2-1.0.1.pom'.
            > Could not GET 'https://libraries.minecraft.net/Mercurius/Mercurius/1.10.2-1.0.1/Mercurius-1.10.2-1.0.1.pom'. Received status code 403 from server: Forbidde
</details>
