### ISSUE TITLE
Backups not cleaning up properly

### ISSUE THREAD

**Issue by kvgeorge1** [LatvianModder/FTBUtilities#255]
In config.json, backup_to_keep = 6, yet I currently have 67 backups shown in backup.json and 67 .zip files in the backup directory.

Currently using FTBUtilities-1.10.2-3.0.0.2.jar

**Comment by MCTyler** [comment]
Location to backup in config file and folder permissions? This is working fine on 2.3.1.1.

**Comment by kvgeorge1** [comment]
Here is the location to the backups (HermitPack/backup) and the config section.  I also have full permissions to the directory

drwxrwxr-x  3 minecraft minecraft      4096 Apr 12  2016 backup

"backups": {
    "backups_to_keep": 6,
    "display_file_size": true,
    "enabled": true,
    "compression_level": 1,
    "backup_timer": 2.0,
    "folder": "",
    "use_separate_thread": true
  },

**Comment by MCTyler** [comment]
Maybe broke in that build...2.3.1.1 works fine.
[Here...](https://minecraft.curseforge.com/projects/ftb-utilities/files/2337118)

**Comment by LatvianModder** [comment]
It works in the latest version?

**Comment by kvgeorge1** [comment]
I upgraded to 2.3.1.1 and the backup file was indeed truncated to include only 6 backups and showed on the console that it was deleting all the other backups.  But when I went into the directory, all the previous backups were still there.

**Comment by LatvianModder** [comment]
Yeah, it cleaned up only the files, can't change that anymore though. It will no longer make them however, it will only create .zip files, without placing them inside folders, so you should be able to delete all folders now. I consider this no longer an issue to be kept open
