### ISSUE TITLE
Crash Upon loading of the modpack

### ISSUE THREAD

**Issue by guitaristtom** [LatvianModder/FTBUtilities#257]
Hello FTB team,

Upon updating the FTBLib and FTBUtilites to the newest version released on Curseforge, I am crashing every time I start up the server, but the client itself is fine.  

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
>   EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
>   LoadingPlugin (NoNausea-MC1.9.4-1.0.jar)
>   NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
>   SimpleCore (Simple Quarry-1.9.4_1.0.0.jar)
>   CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
>   AppEngCore (appliedenergistics2-rv4-alpha-3.jar)
>   LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
>   LoadingPlugin (Quark-r1.0-57.jar)
>   DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
>   IC2core (industrialcraft-2-2.6.87-ex110.jar)
>   LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
>   ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.2.jar)
>   DepLoader (BrandonsCore-1.10.2-2.1.1.60-universal.jar)
>   TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
> Contact their authors BEFORE contacting forge
> 
> // Don't be sad. I'll do better next time, I promise!
> 
> Time: 11/3/16 3:30 PM
> Description: Watching Server
> 
> java.lang.Error
> 	at com.feed_the_beast.ftbu.cmd.CmdAdminHome.<init>(CmdAdminHome.java:112)
> 	at com.feed_the_beast.ftbu.handlers.FTBUServerEventHandler.onRegisterFTBCommandsEvent(FTBUServerEventHandler.java:110)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_FTBUServerEventHandler_onRegisterFTBCommandsEvent_RegisterFTBCommandsEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at com.feed_the_beast.ftbl.cmd.CmdFTB.<init>(CmdFTB.java:33)
> 	at com.feed_the_beast.ftbl.FTBLibMod.onServerStarting(FTBLibMod.java:64)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
> 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
> 	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:845)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:293)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server Watchdog
> Stacktrace:
> 	at com.feed_the_beast.ftbu.cmd.CmdAdminHome.<init>(CmdAdminHome.java:112)
> 	at com.feed_the_beast.ftbu.handlers.FTBUServerEventHandler.onRegisterFTBCommandsEvent(FTBUServerEventHandler.java:110)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_421_FTBUServerEventHandler_onRegisterFTBCommandsEvent_RegisterFTBCommandsEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at com.feed_the_beast.ftbl.cmd.CmdFTB.<init>(CmdFTB.java:33)
> 	at com.feed_the_beast.ftbl.FTBLibMod.onServerStarting(FTBLibMod.java:64)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
> 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
> 	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:845)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:293)

**Comment by guitaristtom** [comment]
Upon further checking, it seems to be a conflict between FTBU and CraftTweaker

**Comment by LatvianModder** [comment]
Never figured out what happened here, couldn't reproduce
