### ISSUE TITLE
Changelogs. Make them. Love them.

### ISSUE THREAD

**Issue by instinxx** [LatvianModder/FTBUtilities#259]
I understand that you dislike making changelogs, but for the love of all that is holy can you at least note what issues are closed in the beta changelogs? Its just cut and paste.

Please?

**Comment by LatvianModder** [comment]
Not that I don't like them, there isn't an official version out yet and I change a LOT all the time. Mostly bugfixes. Once release comes out, I will make a huge changelog from 1.7.10 -> 1.10

**Comment by hugeblank** [comment]
Okay so I commented on this in another post not realizing that this was an individual issue. 

Storytime:

Minecraft 1.12 finally gets released to everyone's surprise. Reddit goes nuts over it and everyone is thrilled to see it is out. But upon opening the launcher there is only your user, the profiles you have and the play button. There is no changelog for any of it. Mojang had stated that 1.12 was going to bring a boatload of changes to the game and that a lot of code was getting reworked and many blocks with different functionalities have been added. When you start playing you don't see any significant changes. when you go to type in '/help' the command is unavailable, and cheats were enabled! Commands are out of the question. none of them work. You open your inventory and find some new blocks, but when you go to use them, you have NO idea what they are. It's a bunch of arrows pointing in different directions and slots for blocks that seem to take only a specific item. You get so confused you decide it's best to look up the information on these blocks on the wiki. You can't find any information about them. Your next bet is to go to the forums. Nothing there, it seems that everyone is just as confused as you are. And when you go to google it all you can seem to find is third party garbage that has nothing to do with your search. 

Moral of the story: ADD CHANGELOGS

And as I stated in my previous issue/rant, It's EXTREMELY annoying when a key feature you get the mod for is broken and/or missing. I do minor amounts of programming, merely as a hobby. Sometimes when I like the code I put it up on a forum. If any feature is missing or broken, it is not fit to be released. And this is exactly why. Why even beta release it on curseforge if literally none of the major additions worked? I wouldn't be saying this if one of the 3 (Friends GUI, chunk claiming GUI, Teams GUI) key features to this mod were functioning. But they aren't. and when I went to download them there was no changelog saying "These features are missing", and when I went to find if it was a config option I was skipping, there was no documentation. It takes less than 2 seconds to type out 'bug fixes'. 

Ergo, I think a changelog addition is:
1. NOT a 'suggestion'
2. NOT 'low priority' rather 'Urgent Priority'
3. NOT 'ToDo' but rather 'Must Do'

**Comment by ktole1999** [comment]
would you rather Latvian spend hours and hours documenting or actually working on the mod? It has been stated in other posts that Gui's are in progress and command was given as a work around until the gui was finished. You can also follow the open and closed issues to confirm this. Public complains and rushes devs to release their mod and then complain more when something doesnt work. Let the devs do their non-paid contribution to the community. You could also contribute hours and hours if you wanted.

**Comment by hugeblank** [comment]
Honestly if there was any way I could contribute to documentation I would totally. I fully understand that modders work their rears off (of which I am very greatful for). The thing is, when someone works hard on something that could be amazing and there isn't a hoot or a holler about it (documentation), it destroys the practicality of the mod.

**Comment by OldDogy** [comment]
@hugeblank 
Write /ftb
hit Space
hit TAB
^ Remember it , Use it , Love it

In short all ftb commands get unwrapped by the TAB button. Doing what i suggested will show you the list of things you can type after /ftb
So lets say you want to do something with your team
ok /ftb (presses TAB
oh look 29commands...
/ftb team (presses TAB)
Oh i can do something with: allies, config, create, enemies, invite, join, kick, leave, list, set_has_permission, transfer_ownership ... hmmm

/ftb team config (presses TAB) :P

I think i made my point ^_^
Cheers

**Comment by LatvianModder** [comment]
You can also click on Server Info (book with red band in inventory), then Commands, then /ftb
