### ISSUE TITLE
Chunkloader confilicts with other chunkloaders

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#26]
One of the crash logs by frenchiveruti:
http://media-elerium.cursecdn.com/attachments/31/25/crash-2016-01-19_02.txt

This is a temporary fix until I figure out the bug: http://pastebin.com/ayJ3sMVr

**Comment by ProfessorFarnsworth** [comment]
I got this issue as well and it is pretty simple to reproduce. You just need to place a Ender Thermic Pump into a chunk that is already loaded by the ftb utilities. 

My temporary workaround was to change the forge chunk loading setting in the forgeChunkLoading.cfg and set the B:enabled=true to false. This at least let me start the server again and remove the ender thermic pump from that location.

Stack trace crash report: http://pastebin.com/AFk7Bc6x

**Comment by LatvianModder** [comment]
I've heard that FTBU's chunkloader only crashes when something is placed in already Loaded area, so I will have to look into that

**Comment by hpwebcamABLE** [comment]
Bump (if that's a thing around here)

Huge issue for me;
Placed an extrautilites quarry, thought it would load chunk, didn't for some reason.
loaded the chunk with FTBUtilites.
Didn't even load the chunk either (in the nether)
Placed World Anchor (Railcraft), didn't load chunk either.

Closed game (not related to this). Couldn't reopen the next time I tried.

FTB Utilites wasn't even in the stacktrace, but extra utilities and railcraft were.
Removing those two (one at a time, not both at the same time) didn't help.

Finally stumbled on the fix here: http://pastebin.com/ayJ3sMVr

Very annoying. Why does this conflict with other chunk loaders when no other mod has this problem? Have you looked at how other mods do it?

**Comment by LatvianModder** [comment]
The problem with my chunkloader mod is that.. I don't have a block, and I can't really use Railcraft as example (I did try though, both it and ChickenChunks) because their chunkloading code is designed for blocks. But this bug ofc has high priority, so I'm working on it

**Comment by hpwebcamABLE** [comment]
I have no idea how chunkloading works, but from the error it seems like Forge was complaining about two mods loading the same chuck. Maybe you can check to make sure each chunk you load isn't already being loaded?
Or perhaps use a fake block?

**Comment by LatvianModder** [comment]
It shoudve been ok to have 2 chunks loaded, Try version 1.0.17

**Comment by LatvianModder** [comment]
Fixed in v1.0.17+
