### ISSUE TITLE
[1.10.2] Server Crash and corruption

### ISSUE THREAD

**Issue by erindalc** [LatvianModder/FTBUtilities#260]
[From this FTB forum thread](https://forum.feed-the-beast.com/threads/server-corruption-after-wrong-shutdown-ftb-infinity-1-10-lite.193554).

**Comment by MCTyler** [comment]
I suggest posting the actual crash log in a details  (spoiler) or pasti. I'm pretty sure you won't get a response out of that report....Who knows though.

**Comment by erindalc** [comment]
> Hi everyone

I was playing with freinds in my local pc server when i shut it down 
The server has a corruption after this 
[This is the crash log](http://pastebin.com/zn3wM9DD)

I am playing FTB infinty lite 1.10

**Comment by LatvianModder** [comment]
Ok, Backups.java:81, gotta check

**Comment by SpiCraftsman** [comment]
I make the forum thread if you want any help about the world crash log etc
Tell me and be happy to help you
