### ISSUE TITLE
Backup option "need_online_players" seems to be missing from FTBUtilities-1.10.2-3.1.2

### ISSUE THREAD

**Issue by prenetic** [LatvianModder/FTBUtilities#262]
When attempting to add this option to config.json manually, it gets removed on server start. When validating options in-game with "/ftb edit_config" this no longer appears to be a valid option. Please consider porting this feature forward from 1.7.10 versions.

The goal of backups on our server is to ensure no more than a couple hours of actual in-game work are lost. Without this feature, potentially game/chunk-breaking issues would become permanent in the world as after 24 hours any "last-known good" backup would have fallen off with the default configuration -- even if players cannot log in due to a breaking bug.

Maintaining this option gives server administrators a chance to recover in the event no one can log in for longer than the configured retention period.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/439
