### ISSUE TITLE
TeamsGUI doesnt load

### ISSUE THREAD

**Issue by Hax165** [LatvianModder/FTBUtilities#265]
The loading circle just keeps spinning and nothing happens
This happens both in singleplayer and multiplayer on my SpongeForge server.
FTBLib-1.10.2-3.1.4
FTBUtilities-1.10.2-3.1.4
forge-1.10.2-12.18.2.2125-universal

**Comment by popatop15** [comment]
This happens without SpongeForge as well.

**Comment by GWYOG** [comment]
Confirmed either, using the same version of FTBL and FTBU on a forge-1.10.2-12.18.2.2123-universal server, with or without SpongeForge.
Missing the TeamsGUI is somehow very inconvenient and several players on my server have complained to me. :(

**Comment by meyer9** [comment]
@LatvianModder is this because it isn't implemented yet or is it not working?

**Comment by LatvianModder** [comment]
It's not implemented yet. I wanted to add a chat warning when clicking the button, but I forgot
