### ISSUE TITLE
Problems with teams and team commands

### ISSUE THREAD

**Issue by kaitoyuuki** [LatvianModder/FTBUtilities#266]
So there's a few issues.

First, /ftb team kick <player> removes me from my own team as well as the person I kicked from the team. Since my team had other players in it, it still exists, and I'm still set as the team owner- but I'm no longer in the team and there's no way for me to get back in on my own. In fact, my admin may have to go as far as to manually edit the teams data.
My claims all disappeared, interestingly enough, and when I made a new team my claims followed me.

Second, members of a team cannot interact with things inside of a team claim, but allies of a team are perfectly able to do so. I believe this issue has already been reported previously, but I was unable to find it in the issues list, even looking through closed issues.

**Comment by LatvianModder** [comment]
Second issue should have been fixed in latest version (3.1.4 FTBU, 3.1.5 FTBLib)

**Comment by LatvianModder** [comment]
Yep, found the issue, - instead of kicking the player from argument, I kick the player that sent the command :D

**Comment by LatvianModder** [comment]
Try this mods.latmod.com/FTBLib/1.10.2-3.1.6

**Comment by kaitoyuuki** [comment]
I mean, it kicked him as well, lol.

**Comment by kaitoyuuki** [comment]
I'll let you know how it goes once we have a chance to test it. Unfortunately our admin is out and about until Saturday I think so we can't update anything until then
