### ISSUE TITLE
Vanilla redstone stops working in loaded chunks

### ISSUE THREAD

**Issue by JentheGeek** [LatvianModder/FTBUtilities#267]
FTBU version 1.0.18.2
MC 1.7.10

An opped player set their claimed chunk to stay loaded, but their redstone didn't function when they left. They have a very basic setup to prevent the Open Crate from dumping dozens of stacks of charcoal  on the ground:
![rs setup](https://cloud.githubusercontent.com/assets/12872858/20380510/13595f9a-ac7d-11e6-8e65-cda64c70c63b.jpg)
The chunk stayed loaded, but the circuit to stop the hopper didn't work (their barrel of charcoal was on the floor).

**Comment by LatvianModder** [comment]
Sorry, I no longer support 1.7.10. And I'm pretty sure that this could be vanilla bug, rather than FTBU's, try using railcraft's or some other mods chunkloader, maybe those will work
