### ISSUE TITLE
/back command can only be used once

### ISSUE THREAD

**Issue by CourtArtanis** [LatvianModder/FTBUtilities#270]
How do I change the amount of times back can be used?
Are ranks not yet implemented in 1.7.10?

Thanks

**Comment by DaMatrix** [comment]
Ranks aren't implemented anywhere (I can't get them to do anything in 1.10.2)

**Comment by CourtArtanis** [comment]
Yeah I thought as much, I guess I was just hoping that they were!
Cheers

**Comment by Syer10** [comment]
my permissions are working on direwolf 1.10.2, the ranks options were deleted when I started the server though.
