### ISSUE TITLE
[1.10.2][Bug] Teleportatsion code getting y level wrong

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#272]
When i use /ftb back most of the time i end up 2 - 4 blocks below my death, which can guess equals me be stuck in a block, and when i use /ftb home <name> if i have a low ceiling, i end up in even though there is run for me stand. what i suggest is, in the core teleportation code to do something like this
```java
for(int i = 0;  i < 256; i++){
    if(!isBlockAt(y) && !isBlockAt(y +1){
         teleport();
         break;
    }
}

**Comment by LatvianModder** [comment]
This would allow for some hacking (getting into someone's base from below) so, no

**Comment by Dijkstra1** [comment]
I see the reason someone would do this to get into someone base is because it is and if it is claimed what can they do it, and i would rather not die when i use /ftb back or /ftb home
