### ISSUE TITLE
[1.10.2] [Bug] Jump on crops...

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#273]
You can jump on crops other peoples crop in there claimed chunks to get there crops, it one of those thing you do not learn until you go on a public server

**Comment by LatvianModder** [comment]
I will check if there is an event for that, but I'm pretty sure there isn't

**Comment by Dijkstra1** [comment]
I did not think it would be an easy fix

**Comment by LatvianModder** [comment]
Just checked, there's nothing I can do about it for now (and probably in future too)
