### ISSUE TITLE
Crash when loading chunks

### ISSUE THREAD

**Issue by Watchful1** [LatvianModder/FTBUtilities#275]
http://pastebin.com/ZDT3mYA9

FTBUtilities-1.10.2-3.1.2

**Comment by Syer10** [comment]
Try using the latest version

**Comment by ktole1999** [comment]
if ftb crashes when you update then update your forge.

**Comment by Saereth** [comment]
I'm having this same issue in a claimed chunk on a server, version 3.1.4 and forge 2151
https://dl.dropboxusercontent.com/u/28829658/crash-2016-12-04_17.36.55-server.txt

**Comment by LatvianModder** [comment]
Try now, with 3.2.0. Just make sure to backup your worlds before
