### ISSUE TITLE
Chunkloading permissions  in DW20 1.10

### ISSUE THREAD

**Issue by matthewjd3615** [LatvianModder/FTBUtilities#276]
There are several players playing on my server. The other OP and myself can claim chunks and chunkload no problem however the non OPed players claimed chunks immediately shut down when they log-off and the log shows the following code...

 [Server thread/INFO] [FTBUtilities]: Unloading Tozzy2012 chunks for being offline for too long[m> [23:52:50] [Server thread/INFO] [FTBUtilities]: Unloading Tozzy2012 chunks for being offline for too long[m>

What (and how, most importantly) can I change in the config file to eliminate this problem and give my other players chunkloading abilities?

**Comment by Ommina** [comment]
#233 and #263 

Alas, in short, you can't.  As of this writing, FTBU is not a viable chunk-loading solution for 1.10.2.

**Comment by LatvianModder** [comment]
You should be able to configure that now

**Comment by pfmoore** [comment]
I've just found this issue while trying to work out why I'm getting this message in the current DW20 pack (pack version 1.1.3, FTB Utilities 3.1.4).

You say "You should be able to configure that now" - can you explain how? I'm running a server locally for my own use, but I'm not very clear on how or where to change this in the config. I could actually just make myself op, as it's a personal server, but I'd rather know how to fix it "properly".

**Comment by Kuktar** [comment]
Yes I would like to know how to configure this as well. I'm in the same boat. Chunk loading offline as non OP seems impossible

**Comment by LatvianModder** [comment]
Oh yeah, what I meant with *now* is latest FTBU version, not latest DW20 version. I guess you just gotta wait for the pack to update its FTB mods. There will be an ingame guide explaining how to use ranks / configure everything too

**Comment by pfmoore** [comment]
Ah OK. DW20 has version 3.1.4, which looks like the latest beta version. I guess they'll update when 3.2 goes to beta. Thanks.
