### ISSUE TITLE
Server crash on login

### ISSUE THREAD

**Issue by sudrakoder** [LatvianModder/FTBUtilities#277]
I occasionally get a server crash when logging into server on DW20 1.10 mod pack. It appears to be a bug with the FTBU chunk loading.

Crash Report: http://pastebin.com/N0Tpkttc

**Comment by jc2xs** [comment]
I'm getting this as well on a white listed server with a custom mod pack made by Boqzo1.  He is getting ready to release it on Curse.  But this will cause a delay.  I have several of these crash reports I can share but they are basically identical to the one posted by sudrakoder.  Here is one of them: http://pastebin.com/ASefetUE

**Comment by LatvianModder** [comment]
I'm working on rewriting chunkloading system, as you can see that in this commit:
https://github.com/LatvianModder/FTBUtilities/commit/ae9940b32c988877dcbd5d8eadf657dcdfca015c
(And I have a ton of changed uncommitted)

**Comment by MvanRietschoten** [comment]
got the same issue indeed. when is direwolf20 1.1.5 coming with this fix? :P it is unplayable now as I can't tell my server players to not use the chunkloading right?

**Comment by LatvianModder** [comment]
This update probably wont have the new version, but next one might
