### ISSUE TITLE
NumberFormatException when starting up new DW20 1.10.x server

### ISSUE THREAD

**Issue by gmoff01** [LatvianModder/FTBUtilities#279]
I get the following NumberFormatException when trying to spin up a new DW20 1.10.X server.  If I delete FTBU, everything works, but this is obviously not ideal.

[http://pastebin.com/z3qhEwQK](http://pastebin.com/z3qhEwQK)

**Comment by LatvianModder** [comment]
Delete either /backups folder or the .json file inside
