### ISSUE TITLE
DW20 1.10.2 pack - FriendGUI is TeamGui and is not working

### ISSUE THREAD

**Issue by Pontiac76** [LatvianModder/FTBUtilities#281]
This has to be simple.  

I'm playing MC with my boys on a server on my LAN (My box, full access), I want to chunkload a couple of spots while we're offline so stuff can grow, and still allow my boys to use our stuff, but, I can't add my boys as a friend.  The UI shows the icons, but when I hover, I see TeamGUI, not FriendGUI.  And when I click on TeamGUI, I just get an icon that spins and nothing happens.

How do I switch from TeamGUI to FriendGUI?

**Comment by meyer9** [comment]
I also have this problem. Let me know if you have a fix.

**Comment by meyer9** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/265

Duplicate issue

**Comment by Pontiac76** [comment]
Is it really a dupe?  The issue reported in 265 is about the spinning wheel, which I get too, but, not the answer I wanted.  I'm looking for FriendGUI which lists the people on the server (Which I've seen in YT videos for 1.10.2).

I did mention the spinning wheel, yes, but, that isn't the issue I'm looking to resolve.

**Comment by LatvianModder** [comment]
I'm closing as duplicate, but if its your private server and security doesn't matter, you can use
```/ftb team config ftbu.blocks everyone```
And yes, the team member adding is also a little broken

**Comment by LatvianModder** [comment]
Actually, I dont think that works either. Damn. There's something that *should* work. /ftb team add_ally <player/team>

**Comment by Pontiac76** [comment]
I already did that, and my kid still can't touch anything in the areas I've claimed as mine.  I'll confirm tonight when he gets home with a random claimed area.

**Comment by OldDogy** [comment]
Pontiac, both sides have to add each other as ally.
It works confirmed.

**Comment by Pontiac76** [comment]
Ahhh.. That is the part that was missing, and I'll test tonight.  (Got busy last night)

I can't see this as being a closed though, as FriendGUI is not present, and, I don't see a list of users on the server.

**Comment by Hax165** [comment]
As LatvianModder answered onto my issue, the GUI simply hasn't been implemented yet. And TeamsGUI is a replacement for FriendsGUI.
