### ISSUE TITLE
Question: How does another mod check if a player has permission to break or place blocks at a location

### ISSUE THREAD

**Issue by PrinceOfAmber** [LatvianModder/FTBUtilities#282]
I have a mod with a bunch of tools that are used to move/break/place blocks.  And i have a bug report that they let people bypass FTB utilities permission.

What is the correct way to go about verifying the player has permission at a BlockPos before letting an action happen?  

My assumption is perhaps to use one of the built in world functions? But there are several options, and im not sure which one is right for this; maybe
 `World.canMineBlockBody(EntityPlayer player, BlockPos pos)`
or
`isBlockModifiable(EntityPlayer player, BlockPos pos)`

Just wanted to quickly check here first.

https://github.com/PrinceOfAmber/Cyclic/issues/183

**Comment by LatvianModder** [comment]
First, you should make a permission nodes for your mod actions - like "cyclic.tool.break", "...place" or just one common node like "cyclic.tool.modify" or smth like that. Register that node in PermissionAPI during INIT (probably with value ALL by default) and then just check with PermissionAPI.hasPermission(gameProfile, node, context) context should contain BlockPos

**Comment by LatvianModder** [comment]
Closing this, because its a question

**Comment by PrinceOfAmber** [comment]
Thanks for replying :)
