### ISSUE TITLE
/ftb team join no twork

### ISSUE THREAD

**Issue by MaxGaming63** [LatvianModder/FTBUtilities#283]
Hi when i want join a team whis /ftb join team ,
This message appears :

MaxGaming63 is not a member of this team!

i can't join a team.

**Comment by Saereth** [comment]
can confirm we're having the same issue, latest version of ftbu and ftblib on curseforge

**Comment by sphynx1492** [comment]
We are having the same issue here as well

**Comment by ktole1999** [comment]
last i read that feature was not finished
