### ISSUE TITLE
Backup Path Name format

### ISSUE THREAD

**Issue by GamingLexus** [LatvianModder/FTBUtilities#284]
I am currently running a FTB Infinity Evolved server with the FTB Utilities mod making automatic backups for me on a two-hourly basis.

I want to change the path of where the backup is outputted to. In the config file (\local\ftbu\config.json), the location defaults to **"folder": "./backups/"**. I want to change this location to another location on the computer. Specifically, E:\Lexus\Documents\Dropbox\Backups\MC\FTB Infinity Evolved

I have tried using /forward slashes but when it creates the next backup, it removes the forward slashes of the path and just creates a folder on the root of the drive (E:\LexusDocumentsDropboxBackupsMCFTB Infinity Evolved). I have changed the /forward slashes to \back slashes as this is how the path is displayed on the running server's command console; the same thing happens.

Can someone advise me of the format that path names need to be written in a .json file please?

Thanks

Lexus

**Comment by LatvianModder** [comment]
Try using \\? Spaces should have worked, no idea why they don't
