### ISSUE TITLE
Client get disconnected when click on Server Settings button on a server

### ISSUE THREAD

**Issue by lucasdidur** [LatvianModder/FTBUtilities#286]
Here the client log.

http://pastebin.com/F8deQyez

Obs. I'm OP on the server.

**Comment by LatvianModder** [comment]
Latest FTBLib?

**Comment by lucasdidur** [comment]
Yep, last download of curse site.

**Comment by Bitterholz** [comment]
Can confrim. Hitting Server settings disconnects players regardless of permission level with Internal Server Error
