### ISSUE TITLE
backups_to_keep forcing max to 100

### ISSUE THREAD

**Issue by Kuaku** [LatvianModder/FTBUtilities#287]
Greetings,

I've got my server setup to backup every hour. I want to keep exactly 1 week's worth of backups. With 24 hours in a day and 7 days in a week, this means I need to keep 168 backups. However, if I try to manually edit the config or try to set the value via edit_config command, the server returns "backups_to_keep set to 100".

Is there any particular reason that this value is set to cap at exactly 100 and can you per chance remove that limit? I believe I read that you can set it to 0 for unlimited, but that's an undesired result -- I only want to keep exactly 1 week's worth of backup given my backup frequency.

Thank you!

**Comment by LatvianModder** [comment]
Done https://github.com/LatvianModder/FTBUtilities/commit/1b889113e0c403974fd108e6e24a0dfe056d416d

**Comment by Kuaku** [comment]
Thank you!
