### ISSUE TITLE
Command style

### ISSUE THREAD

**Issue by TheHeroBilly** [LatvianModder/FTBUtilities#288]
I'm running the 1.10.2 version of this mod, and I have an issue, I'm probably being stupid but the only way I can get the commands to work is to do /ftb <command> is there a way I can make it so it's not like this? so I can just do /<command> ?

**Comment by LatvianModder** [comment]
Yes, there is a setting for that, look in /ftb edit_config ftbl

**Comment by TheHeroBilly** [comment]
I changed the setting but I still can't get it to run the commands like that

**Comment by LatvianModder** [comment]
Restart the server / world after changing that setting
