### ISSUE TITLE
[1.10.2] 3.2.0 FTBUtils crashing server regularly

### ISSUE THREAD

**Issue by b0bst3r** [LatvianModder/FTBUtilities#289]
http://pastebin.com/vfNDUmiV
http://pastebin.com/8bCFMv4Y

Could paste more but they are all the same error, this is a pure Forge server, no cauldron/sponge or another wrapper.

**Comment by LatvianModder** [comment]
Try updating your server to mods.latmod.com/FTBUtilities/1.10.2-3.2.1/
