### ISSUE TITLE
FTBUtilities 1.10.2-3.2.0/3.2.1 Logon Crash

### ISSUE THREAD

**Issue by StevenB83** [LatvianModder/FTBUtilities#291]
Hi, updating to 3.2.0/3.2.1 results in crash when trying to load up SP world. MP seems to work.
Forge 12.18.3.2185

[FTBUtilities 1.10.2-3.2.0/3.2.1 Logon Crash](http://pastebin.com/57SpzP7z)

**Comment by LatvianModder** [comment]
Does this still happen with the 3.2.1 version that is on curse?

**Comment by StevenB83** [comment]
Indeed it does, Updated both Lib and Utilities from curse. This only affects one of my SP worlds, which loads fine with 3.1.5 Lib and 3.1.4 Utilities.
[FTBUtilities 1.10.2-3.2.1 (curse) Logon Crash](http://pastebin.com/1F6Y0xPT)

After creating a fresh world and reloading that a couple of times my regular SP world loads just fine?.. Will report back if it happens again.

Steven.

**Comment by LatvianModder** [comment]
That's a very interesting edge case... 0L, 0L UUID, I'm pretty sure its not possible for a regular player to have that one :P
