### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by Nahhoppla** [LatvianModder/FTBUtilities#292]
here is the crash report:

https://paste.ubuntu.com/23604886/

**Comment by LatvianModder** [comment]
Disable ftb command mirroring in local/ftbl.json

**Comment by Sitherious** [comment]
i did disable and still did not work, however sponge changed to allow it 
https://github.com/SpongePowered/SpongeForge/issues/1144

i eill be testing soon to see if that fixes the issue

**Comment by Sitherious** [comment]
fixed with https://github.com/SpongePowered/SpongeForge/issues/1144 :)

**Comment by LatvianModder** [comment]
Awesome!
