### ISSUE TITLE
No command defined

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#293]
Hello. I'm on Minecraft 1.10.2 using FTB Infinity Lite 1.3.3. This modpack uses the version 3.1.4 of your mod and no command are defined. In the config file, commands like /spawn are enabled, but if I type the command in the chat, the message "Unknown command. Try /help for a list of commands" appears. The /help command returns "An unknown error occurred while attempting to perform this command".

**Comment by LatvianModder** [comment]
See /local/ftbl.json and change the setting about command prefix

**Comment by ExDomino** [comment]
What is the prefix if "use_ftb_prefix" is true? I tryed /ftb_spawn without success.

**Comment by LatvianModder** [comment]
It removes the need for /ftb
So ```/ftb spawn``` becomes ```/spawn```
