### ISSUE TITLE
[1.10.2] [Bug] /ftb team allies add name requiers being an op? 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#295]
So i am guessing that you have change your commands for adding allies for teams, but when trying this on a server we where getting an error saying we did not have the permission to use the command.

**Comment by Dijkstra1** [comment]
that is no longer a thing

**Comment by drozone69** [comment]
its still a thing dijkstra

**Comment by Dijkstra1** [comment]
![2016-12-17_03-16-38](https://cloud.githubusercontent.com/assets/11648771/21284045/7dd619a2-c407-11e6-82d9-4819ff70d2b6.gif)
are u sure u are running the latest version?

**Comment by drozone69** [comment]
i believe so

**Comment by LatvianModder** [comment]
Its ".. allies add <name>" and yes, seems like that's something I have forgotten to fix
