### ISSUE TITLE
"Server Info" button crashes game - now the world crashes on load

### ISSUE THREAD

**Issue by obuw** [LatvianModder/FTBUtilities#297]
Sorry to create a new issue, but you closed [the other one](https://github.com/LatvianModder/FTBUtilities/issues/294) and I'm not sure you get notifications for replies on closed issues.

I have updated to the latest FTBUtils & FTBLib (3.2.1) and my game is still crashing on world load.

Removing the mods does not help either.

Perhaps I need to edit a file in the save directory or change a config setting of some kind?

Or does the fix only prevent the server info button from corrupting your game, but if your world is already corrupted there is nothing you can do?

**Comment by ktole1999** [comment]
the fix should only keep it from happening. if you have a bad block as a result of the crash that is different. can you post a crash log on pastebin and share the link?

**Comment by obuw** [comment]
Okay, I guess I will just have to restore from backup. (kinda forgot I had that option earlier)

**Comment by LatvianModder** [comment]
You said removing the mod doesnt help. Well, if so, then its not FTBU/Lib, because those mods dont add any content to game. Once removed, everything is gone. Just like @ktole1999 said, it could be a corrupted block or something

**Comment by LatvianModder** [comment]
Server Info.. Hmmm. Maybe a bad command or some formatting error? I will see if I can replicate the issue using DW20 pack

**Comment by obuw** [comment]
Well I was able to replicate it by just creating a new world and pressing the "server info" button. I'm not at my comp right now so I can't verify if atm with a third test, but I'll see about it when I get back home.

**Comment by obuw** [comment]
Allright, well the latest FTBUtils definitely doesn't crash the game anymore. And I restored my world from its latest backup to solve the issue. So I guess the issue can be closed. 

I hope FTB updates the packs asap though or you might get bombarded with issues from other people, since this seems like a pretty serious problem.
