### ISSUE TITLE
Setting a team name to display with an "&" in the name will crash your client.

### ISSUE THREAD

**Issue by luckdemon** [LatvianModder/FTBUtilities#298]
As soon as you press accept on the rename window, crash to desktop while trying to rename a team's display name with an ampersand in it.
Edit: Also crashes with spaces, still testing other symbols.

**Comment by LatvianModder** [comment]
Do you have a crash report?

**Comment by LatvianModder** [comment]
Actually this can be fixed if you use ", example - "A & B" instead of A & B
