### ISSUE TITLE
Admin unclaim does not work in 1.10.2

### ISSUE THREAD

**Issue by luckdemon** [LatvianModder/FTBUtilities#299]
As title states, cannot unclaim chunks as a server admin in 1.10.2

**Comment by OldDogy** [comment]
ah was wondering about this one.
/ftb chunks admin_unclaim_all <player>
^ Works lovely except it (as stated) unclaims all of <player> chunks
And simple " /ftb chunks admin_unclaim " command doesn't exist :/
I tried a bunch of ways of doing it only way is to go in to the FTBLib.dat file and manually remove the claims...

**Comment by LatvianModder** [comment]
Instead of  /ftb chunks admin_unclaim its supposed to work for OPs just like that, from gui. It doesnt

**Comment by NeosGhost** [comment]
/ftb chunks admin_unclaim_all works in 
FTBLib 1.10.2-3.1.5
FTBUtilities 1.10.2-3.1.4

but does not in current release
![2016-12-27_20 07 17](https://cloud.githubusercontent.com/assets/16095247/21512234/387609aa-cc70-11e6-9123-f4771cf23588.png)

**Comment by OldDogy** [comment]
@NeosGhost ... that is what Latvian just said ...

**Comment by thefiz** [comment]
I can't get it to work in the GUI either :(

**Comment by thefiz** [comment]
Is there an easy way to get this done by editing a file until the GUI works?

**Comment by LatvianModder** [comment]
You have to edit it while the server is offline

**Comment by Gunner76th** [comment]
Where is FTBLib.dat located? I am having a hard time finding it on my server.

**Comment by LatvianModder** [comment]
world/data/FTBLib.dat
