### ISSUE TITLE
FTBU chunks unload regardless of options set.

### ISSUE THREAD

**Issue by Kuktar** [LatvianModder/FTBUtilities#301]
In my ftb infinity lite 1.10.2 the chunk claiming unloads chunks the very second i log off regardless of settings. 

here are my settings for ftbu

`{
  "backups": {
    "backups_to_keep": 12,
    "display_file_size": true,
    "enabled": false,
    "backup_timer": 2.0,
    "compression_level": 1,
    "folder": "",
    "use_separate_thread": true
  },
  "world": {
    "temp": {
      "max_loaded_chunks": 200,
      "max_claimed_chunks": 1000
    },
    "chunk_loading": true,
    "locked_in_dimensions": [
      1,
      0,
      -1
    ],
    "locked_in_claimed_chunks": false,
    "blocked_entities": [],
    "chunk_claiming": true,
    "safe_spawn": false,
    "spawn_area_in_sp": false
  },
  "general": {
    "auto_restart": false,
    "chat": {
      "substitutes": [
        {
          "shrug": {
            "text": "¯\\_(ツ)_/¯"
          }
        }
      ],
      "substitute_prefix": "!",
      "enable_links": true
    },
    "restart_timer": 12.0,
    "server_info": {
      "difficulty": true,
      "mode": true
    },
    "ranks": {
      "enabled": false
    }
  },
  "commands": {
    "chunks": true,
    "trash_can": true,
    "js": true,
    "warp": false,
    "tpl": true,
    "inv": true,
    "back": true,
    "server_info": true,
    "spawn": true,
    "home": true,
    "kickme": true
  },
  "webapi": {
    "port": 4509,
    "output_map": false,
    "enabled": false
  },
  "login": {
    "motd": [],
    "enable_motd": false,
    "starting_items": [],
    "enable_starting_items": false
  }
}`

`<html><head><title>Rank Configs</title>
<style>table{font-family: arial, sans-serif;border-collapse: collapse;}td,th{border:1px solid #666666;text-align: left;padding:8px;}</style>
</head><body><h1>Rank Configs</h1><table>
<tr><th>Rank Config</th><th>Def Value</th><th>Def OP Value</th><th>Info</th></tr>
<tr><td>display.badge</td><td>
Default: ""
</td><td>""</td><td>
Prefix of player's nickname
</td></tr>
<tr><td>display.color</td><td>
<ul><li>Default: 
"white"</li>
<li>Variants:<ul>
<li>aqua</li>
<li>black</li>
<li>blue</li>
<li>bold</li>
<li>dark_aqua</li>
<li>dark_blue</li>
<li>dark_gray</li>
<li>dark_green</li>
<li>dark_purple</li>
<li>dark_red</li>
<li>gold</li>
<li>gray</li>
<li>green</li>
<li>italic</li>
<li>light_purple</li>
<li>obfuscated</li>
<li>red</li>
<li>reset</li>
<li>strikethrough</li>
<li>underline</li>
<li>white</li>
<li>yellow</li>
</ul></li>
</ul>
</td><td>"green"</td><td>
Color of player's nickname
</td></tr>
<tr><td>display.prefix</td><td>
Default: ""
</td><td>""</td><td>
Prefix of player's nickname
</td></tr>
<tr><td>ftbu.chunkloader.offline_timer</td><td>
<ul><li>Default: 
24.0</li>
<li>Min: -1</li>
</ul>
</td><td>-1.0</td><td>
<ul>
<li>-1 - Chunk will always be loaded</li>
<li>0 - Disabled, will unload instantly when he disconnects</li>
<li>Max hours player can be offline until he's chunks unload</li>
</ul>
</td></tr>
<tr><td>ftbu.chunkloader.type</td><td>
<ul><li>Default: 
"offline"</li>
<li>Variants:<ul>
<li>disabled</li>
<li>offline</li>
<li>online</li>
</ul></li>
</ul>
</td><td>"offline"</td><td>
<ul>
<li>disabled: Players won't be able to chunkload</li>
<li>offline: Chunks stay loaded when player loggs off</li>
<li>online: Chunks only stay loaded while owner is online</li>
</ul>
</td></tr>
<tr><td>ftbu.claims.forced_explosions</td><td>
<ul><li>Default: 
"-"</li>
<li>Variants:<ul>
<li>-</li>
<li>disabled</li>
<li>enabled</li>
</ul></li>
</ul>
</td><td>"-"</td><td>
<ul>
<li>-: Player setting</li>
<li>disabled: Explosions will never happen in claimed chunks</li>
<li>enabled: Explosions will always happen in claimed chunks</li>
</ul>
</td></tr>
<tr><td>ftbu.homes.max</td><td>
<ul><li>Default: 
1</li>
<li>Min: 0</li>
<li>Max: 30000</li>
</ul>
</td><td>100</td><td>
Max home count
</td></tr>
</table></body></html>`

![image](https://cloud.githubusercontent.com/assets/24352734/21241876/91637baa-c2c6-11e6-8746-c024014af960.png)

**Comment by ThuCommix** [comment]
Also happens for me pack updated to the latest version.

**Comment by ThuCommix** [comment]
It seems fixed with your latest alpha build on curse, thank you.

**Comment by MvanRietschoten** [comment]
is this error related to this issue? or should I create an issue for this?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (Quark-r1.0-60.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-8.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  IC2core (industrialcraft-2-2.6.105-ex110.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/19/16 5:35 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:228)
	at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:807)
	at com.feed_the_beast.ftbu.api_impl.LoadedChunkStorage.checkChunk(LoadedChunkStorage.java:112)
	at com.feed_the_beast.ftbu.api_impl.LoadedChunkStorage.checkAll(LoadedChunkStorage.java:74)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onLoggedOut(FTBUPlayerEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_400_FTBUPlayerEventHandler_onLoggedOut_ForgePlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at com.feed_the_beast.ftbl.api_impl.ForgePlayer.onLoggedOut(ForgePlayer.java:301)
	at com.feed_the_beast.ftbl.FTBLibEventHandler.onPlayerLoggedOut(FTBLibEventHandler.java:114)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_393_FTBLibEventHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:570)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:379)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:804)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:451)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 2.6.32-5-amd64
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 343660760 bytes (327 MB) / 1962098688 bytes (1871 MB) up to 3649044480 bytes (3480 MB)
	JVM Flags: 9 total; -Xmx3600M -Xms256M -XX:PermSize=256M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=3 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.2.2171 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (FTBserver-1.10.2-12.18.2.2171-universal.jar) 
	UCHIJAAAA	Forge{12.18.2.2171} [Minecraft Forge] (FTBserver-1.10.2-12.18.2.2171-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-8} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r88} [Actually Additions] (ActuallyAdditions-1.10.2-r88.jar) 
	UCHIJAAAA	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCHIJAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-8} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-8.jar) 
	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-68} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-68.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.145} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.0} [Chameleon] (Chameleon-1.10-2.2.0.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	IC2{2.6.105-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.105-ex110.jar) 
	UCHIJAAAA	CompactSolars{5.0.5.329} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.5.329-universal.jar) 
	UCHIJAAAA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	darkutils{1.1.6.99} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.99.jar) 
	UCHIJAAAA	forestry{5.2.16.331} [Forestry] (forestry_1.10.2-5.2.16.331.jar) 
	UCHIJAAAA	eleccore{1.6.345} [ElecCore] (ElecCore-1.10.2-1.6.345.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCHIJAAAA	deepresonance{1.3.1} [DeepResonance] (deepresonance-1.10-1.3.1.jar) 
	UCHIJAAAA	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.138_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.138_beta.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.2.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.0.8.2} [Zero CORE] (zerocore-1.10.2-0.0.8.2.jar) 
	UCHIJAAAA	bigreactors{1.10.2-0.4.5.21} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.21.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJAAAA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.2.197} [Mantle] (Mantle-1.10.2-1.1.2.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	immersiveengineering{0.10-52} [Immersive Engineering] (ImmersiveEngineering-0.10-52.jar) 
	UCHIJAAAA	inventorysorter{0.10.0+42} [Simple Inventory sorting] (inventorysorter-1.10-0.10.0+42.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.19} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.19.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHIJAAAA	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.2.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCHIJAAAA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.7} [Storage Drawers] (StorageDrawers-1.10.2-3.5.7.jar) 
	UCHIJAAAA	refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJAAAA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
AppEngCore (appliedenergistics2-rv4-alpha-8.jar)
  appeng.coremod.asm.ASMIntegration
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
IC2core (industrialcraft-2-2.6.105-ex110.jar)
  
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	AE2 Version: alpha rv4-alpha-8 for Forge 12.18.2.2139
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/minecraft/Direwolf20/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, Mekanism:OFF, OpenComputers:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['AwesomePlayer'/500474, l='world', x=-722.94, y=63.00, z=171.42]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'

**Comment by Kuktar** [comment]
Yes this is definitely fixed with latest build. I hope the FTB team can update there packs with the new build. FTBU is an absolute must have mod. I don't even consider anot MP environment without it lol. Thanks for fixing this.

**Comment by LatvianModder** [comment]
The team will update packs when I mark my build as "Release", but I want to get a couple other bugs fixed before that

**Comment by Kuktar** [comment]
How come you don't have a patreon Urlacher? I love to support moders that make my minecraft amazing. My son and I play it almost religiously.

**Comment by Kuktar** [comment]
Patreon URL* stupid autocorrect.

**Comment by LatvianModder** [comment]
I do! https://www.patreon.com/LatvianModder

**Comment by Kuktar** [comment]
AWESOME! enjoy your free coffee each month :P well not really free because your earning it. You really should put your patreon on more pages. Honestly you would get a hell of a lot of support from the MC mod community if people just knew (easier) lol

**Comment by LatvianModder** [comment]
Much appreciated! It doesnt help that it says "Made by FTB" on curse and pretty much everywhere else :P
