### ISSUE TITLE
Question: How to add custom in-game guide?

### ISSUE THREAD

**Issue by davqvist** [LatvianModder/FTBUtilities#302]
I'm working on a mod pack for 1.10.2 at the moment and wanted to add a custom in-game guide. I oriented on the file and folder structure of Infinity Evolved Skyblock but it just doesn't seem to work. Is this not working for 1.10 yet?

A couple of weeks ago I found a website that explained how a mod can add info to this guide (although I can't seem to find it now anymore). Does this mean there will be no way to do that anymore through files for modpack makers? Do I have to create a mod just for that?

**Comment by LatvianModder** [comment]
http://guides.latmod.com/

I'm still writing it so only *some* of the info is true, and there will be better examples too, but you can check it in a day or two again, I will have finished by then

**Comment by davqvist** [comment]
Ah I see how that works, I'm looking forward for your update.
