### ISSUE TITLE
Guide Icon with Item Metadata crashes game

### ISSUE THREAD

**Issue by davqvist** [LatvianModder/FTBUtilities#305]
Thanks for giving me the link on how to make a guide. I used the Resourceloader mod and it worked.
But I want to use for the icon of one of my guide points a block with metadata (specifically the Pattern Storage from IC2 ic2:te:62) and the game crashes when it tries to render that icon. http://pastebin.com/BzZTms3n

Does your guide not yet support items with metadata or do I have to use a specific different syntax?

PS: Also I have a question: In my guide.json I use the "name" tag to specify the name of the root icon (just as explained on the page of the link you gave me). But it doesn't seem to work. It shows "modid.guide" instead where modid is the name of the root resource folder is that I use with the Resourceloader mod. As I'm not sure if this is a bug or an error on my side, I don't open a new issue for this.

I hope you can help me. Thanks.

Forge 12.18.2.2166
FTB Utilities 3.1.4

**Comment by LatvianModder** [comment]
Was "ic2:te:62" the string you used? Try using space or @ instead of : after item ID

P.S. You must use ```modid/lang/en_US.lang``` file for language entries - put
```modid.guide=My Mod Name```
There and that should work. It uses lang files, so it can support multiple languages

**Comment by LatvianModder** [comment]
I think the syntax for item is "modid:itemid quantity metadata [nbt but im not sure if it works]"

**Comment by davqvist** [comment]
Oh nice that worked. Thanks for your quick answer.
