### ISSUE TITLE
Server crash (can't start up after crash either)

### ISSUE THREAD

**Issue by M4thG33k** [LatvianModder/FTBUtilities#306]
My server crashed with the following report. https://gist.github.com/M4thG33k/1329b8037f95413e7f2d7f9838a22a5b

I am unable to start the server as the same crash keeps happening.

**Comment by LatvianModder** [comment]
Update FTBLib/U to latest versions and then report back if that works

**Comment by M4thG33k** [comment]
I am using the latest versions (at least available via the curse launcher). The issue seems to have resolved itself without any changes on my part though. I have no idea what caused this. Sorry to waste your time.

**Comment by M4thG33k** [comment]
You may want to re-open this. I get the crash only when a specific user logs in: 
https://gist.github.com/M4thG33k/a44b3d4d1bd8c0c678cc2e33f2bceceb

**Comment by ktole1999** [comment]
if only happens with that user then its his player file or the area he logs into. try resetting his player file and see if that fixes. if no fix then move him to spawn using nbt editor.

**Comment by M4thG33k** [comment]
Yeah, he was able to log in again after I force-unloaded all of his chunks.
