### ISSUE TITLE
Refined Storage Destructor

### ISSUE THREAD

**Issue by ThuCommix** [LatvianModder/FTBUtilities#308]
The Refined Storage Destructors are not working in claimed chunks, I'm not sure if this is intended or not?

**Comment by LatvianModder** [comment]
Try setting /ftb team config ftbu.allow_fake_players true

**Comment by ThuCommix** [comment]
Cannot find config entry if I enter the command on the client, If I'm doing so on the server it says I need to specify a player.. Any Ideas?

**Comment by LatvianModder** [comment]
Press Tab after typing ftbu. - it [or something similar] must be there
