### ISSUE TITLE
Adding team ally that is offline crashes the server

### ISSUE THREAD

**Issue by KitKat31337** [LatvianModder/FTBUtilities#309]
Sadly there was no crash report.

**Comment by LatvianModder** [comment]
What mod version, is it reproducable?

**Comment by KitKat31337** [comment]
Yes, and the latest current release.   3.2.4

**Comment by LatvianModder** [comment]
Actually, if you could test this, and tell me if it works, it would be great http://mods.latmod.com/FTBLib/1.10.2-3.2.4/
