### ISSUE TITLE
Some fake players not working/harvesting in loaded chunks when offline

### ISSUE THREAD

**Issue by Logoth** [LatvianModder/FTBUtilities#31]
Version: FTB Utilities 1.7.10-1.0.15.1.

SMP server, config is set to force public security. Players have set fake_players to true. Thaumcraft golems and steve's carts tree farms (at least) do not harvest in an area while a player is offline. Testing by loading the chunks, going offline for 1 hour with a simple steve's carts tree farm and a golem wheat farm, came back to nothing harvested and everything fully grown.

MFR harvester and Ender IO farming station appear to work normally, for comparison.

**Comment by LatvianModder** [comment]
Maybe the golem walked outside loaded area, or was pushed outside for some reason. Try expanding the loaded area

**Comment by Logoth** [comment]
The loaded area was 3x3 chunks with the golems in a 9x9 block farm in the center chunk. Assuming they should work, I'll fire up a test server with a fresh map and re-test.

**Comment by Logoth** [comment]
Re-tested on a fresh server. Only had NEI, FTB Utilities, and Thaumcraft. Trapped golems in a chunk farming and logged out for an hour. Came back and they had harvested properly. Also rebooted the server and logged on an hour later and they had also harvested properly after reboot.

So either an issue with my world data, or a cross mod problem, or something. Sorry for the false report.
