### ISSUE TITLE
Disable /ftb mirroring when sponge is loaded

### ISSUE THREAD

**Issue by TheMrCaveman** [LatvianModder/FTBUtilities#310]
http://pastebin.com/EiG76YKF

**Comment by Sitherious** [comment]
seems we have the same issue, i posted mine on spongeforge

https://github.com/SpongePowered/SpongeForge/issues/1144

**Comment by LatvianModder** [comment]
Maybe this fixes it? https://github.com/LatvianModder/FTBUtilities/issues/292

**Comment by Whazaaaaa** [comment]
Still a issue #292 did not fix it.
