### ISSUE TITLE
Crash when logging into Hermitpack Server

### ISSUE THREAD

**Issue by flintnsteel** [LatvianModder/FTBUtilities#314]
Recently we have been having a problem with our server crashing when a player logs in. Its not a specific player, it is happening both players using the server. Crash Log http://pastebin.com/ysLSwLf5

Current version of FTB hermitpack v1.5.1 and FTB utils version is 3.1.4

I believe it might be a chunkloading issue.

**Comment by LatvianModder** [comment]
Its probably because of the old version. I will ask hermitpack guys if they can update the pack
