### ISSUE TITLE
Possibility to destroy blocks in someone else's chunks

### ISSUE THREAD

**Issue by knoxhack** [LatvianModder/FTBUtilities#315]
"I thought this might be serious if it is intended to have safe area as you claim chunks.. So, with Ars Magica 2 dig spell, i only tried normal grass block so far so im not sure what other blocks it can destroy, but it can destroy at least some blocks in chunks that are claimed by someone else it seems. I don't really want to try out this as im not griefer.. I already feel bad for the grass block. :P
Using forge-12.18.3.2185
And using MMD Project Ultimate 1.3"

**Comment by knoxhack** [comment]
https://github.com/MinecraftModDevelopment/Project-Ultimate/issues/14

**Comment by knoxhack** [comment]
https://github.com/Growlith1223/ArsMagica2/issues/128

**Comment by knoxhack** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/315

**Comment by LatvianModder** [comment]
Commented on AM2 issue tracker

**Comment by LatvianModder** [comment]
Also, this isn't anything I can fix from my side, so closing this issue
