### ISSUE TITLE
FTBLib.dat randomly reset itself

### ISSUE THREAD

**Issue by Whazaaaaa** [LatvianModder/FTBUtilities#316]
Okay so somehow the FTBLib.dat file has reset itself which mean nobody has their claims anymore.
Now I was stupid enough to not keep proper backups of my serverfiles but why has this happend?

**Comment by LatvianModder** [comment]
Sorry, I have no idea. Server might have been terminated wrongly or something. It's like asking Microsoft why your computer randomly restarted :P
