### ISSUE TITLE
/help 2  corrupted my world

### ISSUE THREAD

**Issue by tatopolos** [LatvianModder/FTBUtilities#317]
After typing /help 2, to go to the second page of help, a crash happened and corrupted the world making it unloadable.

"Description: Exception in server tick loop
java.lang.NullPointerException: Exception in server tick loop"

Full crash report for the first crash
[crash-2016-12-29_18.22.19-server.txt](https://github.com/LatvianModder/FTBUtilities/files/678424/crash-2016-12-29_18.22.19-server.txt)

now when trying to load the world, it crashes with following error:
"Description: Exception while updating neighbours
java.lang.ClassCastException: crazypants.enderio.conduit.TileConduitBundle cannot be cast to com.rwtema.extrautils2.tile.XUTile"
[crash-2016-12-30_00.12.00-server.txt](https://github.com/LatvianModder/FTBUtilities/files/678426/crash-2016-12-30_00.12.00-server.txt)

thanks for helping

**Comment by LatvianModder** [comment]
This shouldnt happen again in 3.4.0+. I hope you had backup of the world, sorry or replying so late
