### ISSUE TITLE
Request for friendslist again

### ISSUE THREAD

**Issue by KamiSami** [LatvianModder/FTBUtilities#318]
Is it possible to have friendslist back again instead team? I doubt single person as i am enough for this to happen, but here i am to try..

**Comment by LatvianModder** [comment]
I already took some steps to make it 'friendlier' for users - automatically create teams for players etc. The 'old' way essentially is just using /ftb team allies add <team>, so sorry, I won't bring friends list back. I am going to add gui though, so people dont have to use commands, thats for sure
