### ISSUE TITLE
Chunks unload when a player disconnect

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#319]
I'm on FTB Infinity Lite, chunks of a player are unloading this player disconnect, even if he's a op, causing a lot of problem without all other chunkloaders are disabled. Config says I have to set "ftbu.chunkloader.offline_timer" to -1.0 but WHERE ? The only place I see this setting in my "Local" folder is in "ranks_example.json" that is supposed to be an example file. What I have to do in order to make that everyone on my server has their chunkloaders always active? I don't know what file to edit. It's really not simple to understand even with your help files and your readme. There is not "ranks.json" file!

Edit 1: I tryed to enable ranks in config.json and then rename ranks_example.json to ranks.json and the editing the section about "offline_timer" and the doing a /ftb reload but nothing happened, still have a spam of "Unloading xyz chunks for being offline for too long" when a player disconnects. What is the problem?

Edit 2: Tryed everything, nothing works! "default_ranks.json" is reset at every server start!
"player_ranks.json" is ignored, with "ranks" in config.json line 60 both true or false at each test.

**Comment by ExDomino** [comment]
I tryed to enable ranks in config.json and then rename ranks_example.json to ranks.json and the editing the section about "offline_timer" and the doing a /ftb reload but nothing happened, still have a spam of "Unloading xyz chunks for being offline for too long" when a player disconnects. What is the problem?

**Comment by LatvianModder** [comment]
Looks like Lite has outdated FTB mods versions, so I guess you just wait until they update

**Comment by OldManCraft** [comment]
Latvian, This is still not working in current version. The configs seem to be a mess. Is there a way to make configs easy to understand without being a programmer. Is there a location with a full write up on how they work ?

**Comment by LatvianModder** [comment]
Well, the main configs can be edited with /ftb edit_config [mod]. Im working on a gui for all other configs too / readme.txt to explain how this works. Documenting things is the hardest part of making mods :P

**Comment by LatvianModder** [comment]
You can delete all files in /local/ftbu/ except config.json [while server is off] and see if that fixes the problem with chunks unloading

**Comment by LatvianModder** [comment]
Update to FTBU and Lib to 3.5.0 and see if that fixes it
