### ISSUE TITLE
World Rules in claims

### ISSUE THREAD

**Issue by Goten87** [LatvianModder/FTBUtilities#32]
we can claim land will be nice if we can also set stuff up in the claims like i make a arena and the middle of the arena is 1 chunk i want to set that chunk to be pvp allowed so that people can pvp in there but no where else in my world

**Comment by LatvianModder** [comment]
That could maybe be done, but not for a while for sure

**Comment by Goten87** [comment]
that you see in the right corner like the name of the player who claimed it and under there like (PVP) or somthing

**Comment by LatvianModder** [comment]
How about an option (disabled on server by default though) for players to have PVP? But actually, that is already made in @K-4U's mod PVPToggle. Maybe I (or he) can add integration with FTBU

**Comment by K-4U** [comment]
At the moment pvptoggle doesn't have an API. However, if you have some ideas about adding integration, I'm willing to listen :) give me a shout on irc when I'm around.

**Comment by Goten87** [comment]
well i have 0 experiance with java coding xD so i have no idear how to do it

**Comment by LatvianModder** [comment]
He was talking to me :P Sure, K4U! I can add that on my end, you wont even need an API for that
