### ISSUE TITLE
Chunkloading 1.10.2 Question

### ISSUE THREAD

**Issue by Meller127** [LatvianModder/FTBUtilities#320]
Does the Claim Chunk and Chunk Loading work in 1.10.2 - 3.2.4? 
Im getting really confused searching for some info on this, some says its not working, some says its working if you are an op AND online, and Everything in between.

So does it work?
And Happy New Year  :D

**Comment by LatvianModder** [comment]
Happy New Year to you too! Latest version should have chunkloading issues fixed, some versions previously it was unloading chunks when player logged off
