### ISSUE TITLE
Server countdown when restarting 

### ISSUE THREAD

**Issue by OldManCraft** [LatvianModder/FTBUtilities#323]
All I'm getting is a 60 second warning, then nothing else. Is there a way to configure or am I missing something.

**Comment by LatvianModder** [comment]
It doesn't restart or it doesn't print anything after it?

**Comment by OldManCraft** [comment]
Sorry about getting back on this. It does restart just fine. Problem is in 1.7.10 you would get count down timer to server restart. I think 5, min, 1 min, 10,9,8,7,6,ect. In the 1.10 version you get one min only then it just restarts.

**Comment by LatvianModder** [comment]
![ ](http://ss.latmod.com/pc/2017-01-20_16.43.09.png)
Can't reproduce the issue

**Comment by OldManCraft** [comment]
I wiped out the configs, restarted and reset all configs and now it works. This could have been a bug or user issue. lol I'll take the second to make it easy. We can Close.
