### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Sitherious** [LatvianModder/FTBUtilities#326]
where do i find the permission nodes for claims, offline online ect.

**Comment by LatvianModder** [comment]
In /local/ftbu/ there are files all_configs.html and all_permissions.html files. Open them with your browser to see all of them

**Comment by Sitherious** [comment]
i added the permission to my ranks, ftbu.chunkloader.max_chunks.200 and the chunkcount didnt change, i did a restart, so my next question is does it have to use the rank system that ftbutils has? as i am using permission manager on my server.
