### ISSUE TITLE
Quantum Quarry's

### ISSUE THREAD

**Issue by Sitherious** [LatvianModder/FTBUtilities#327]
ive noticed on our server, that if there are any more then 60 quarries running it kills the tps  we have had to limit the usage of this sadly and i was curious if there is any fix to this. we have never had an issue with the old ender quary

**Comment by LatvianModder** [comment]
Is this strictly related to FTBUtilities?

**Comment by Sitherious** [comment]
yes, i can get the sponge timing reports if you like. i also created a test server to test it with nothing else in the world made 30+ quarrys and then the tps goes down, i dont know if the quarry does block updates or whatever but this can easly be reproduced if you make 30+ quarrys fully power them

**Comment by DaMatrix** [comment]
Quantum Quarries are not from FTB Utilities.

**Comment by Sitherious** [comment]
Oops sorry about that I got the utilities mods mixed up its extra utilities
