### ISSUE TITLE
Claim Chunks for Other Players. Claim Chunks for NPC. ?

### ISSUE THREAD

**Issue by FatherFury** [LatvianModder/FTBUtilities#328]
Was wondering if it is possible to claim a chunk for another player as op? if so can you give me details how?

Also was wondering if you could claim for NPC's wether it's an entity we put in game, or just a town..basically it would be a server claim, but would give name chosen by admin...like a town name might list it's name when entering area, but op's could still interact with it? If this is already possible I would love to know more. If not...It would be a great feature for adding content to server.

**Comment by LatvianModder** [comment]
There is "/ftb chunks claim_for <player> <x> <y>" command, try that

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/88
