### ISSUE TITLE
question perms

### ISSUE THREAD

**Issue by Sitherious** [LatvianModder/FTBUtilities#329]
i added the permission to my ranks, ftbu.chunkloader.max_chunks.200 and the chunkcount didnt change, i did a restart, so my next question is does it have to use the rank system that ftbutils has? as i am using permission manager on my server.

**Comment by LatvianModder** [comment]
Sorry, I forgot to reply to this :P
You have to put these in "config":{} not "permissions":[]
```
"config": {
    "ftbu.chunkloader.max_chunks":200
}
```
Try this, if it doesnt work/files revert, then that's a bug I need to fix

**Comment by Sitherious** [comment]
how would i assign players different amounts of chunks?

**Comment by LatvianModder** [comment]
You'd assign them different ranks. Say Admin has 1000 chunks, Player has 100 and VIP has 500

**Comment by Sitherious** [comment]
but does it have to be your ranks or just a permission node?

**Comment by Sitherious** [comment]
i am using https://forums.spongepowered.org/t/key-permissionmanager-v2-6-0-api-6-x-5-x-4-2-0-gb-fr-ru-and-more/12310 for my groups and ranks. i should is this compatible to add it in there? or can it be compatible?

**Comment by LatvianModder** [comment]
No, im pretty sure that anything that isnt FTBUtilities is gonna break it, unless Sponge has already adapted the Forge PermissionAPI. I know ForgeEssentials is getting there

**Comment by Sitherious** [comment]
ok last questions about perms then, if i make ftbutils groups what would be the command to add the player into the group?

**Comment by Sitherious** [comment]
thanks
