### ISSUE TITLE
Server player data export

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#33]
Exports a .json file to any location, for a web app to use or smth like that. Add config for every field, like deaths, last_seen etc.

**Comment by Goten87** [comment]
well will be nice to get that in a mysql database if thats posibol
i had made a website for forge essentials for the Logger and the user premission will be nice to have it for players as well

**Comment by LatvianModder** [comment]
I'm sure most of the web languages can parse json in some way. An example how the exported file will look like: (will be alphabetical, so users won't have to worry about sorting the list)

[
  {
    "name": "ETE",
    "deaths": 0,
    "last_seen": 0,
    "time_played": 45093,
    "first_joined": 59345
  },
  {
    "name": "LatvianModder",
    "deaths": 6,
    "last_seen": 4752809,
    "time_played": 453298599,
    "first_joined": 1453298599
  }
]

last_seen - Milliseconds after last time seen or 0 if online
time_played - Total time in milliseconds that player has been online
first_joined - Milliseconds after first login

Possible future stats - blocks_mined, entities_killed, players_killed, etc.

**Comment by Goten87** [comment]
will it not be nicer then to make it 1 for all player names and then for extra info goten87.json
sins its eazyer to load a name file then get specific info from 1 big file

**Comment by LatvianModder** [comment]
Added as webapi
