### ISSUE TITLE
[1.7.10] Crops griefable by trampling

### ISSUE THREAD

**Issue by syndicate25** [LatvianModder/FTBUtilities#331]
Crops can be griefed by trampling in claimed territory.  Also can be punched by left clicking which provides 1 of the punched food, like 1 watermelon slice, but the crop remains planted.  

Crops cannot be right clicked to harvest, as expected.

Using several mods, but the food mods used are Harvestcraft, and Agricraft. Unsure of any compatibililty issues there, if any.

**Comment by DaMatrix** [comment]
1.7.10 is not supported, to my knowledge.

**Comment by LatvianModder** [comment]
Yeah, sorry, it's unsupported.
