### ISSUE TITLE
Minor issue: Can't destroy end crystals in claimed chunk.

### ISSUE THREAD

**Issue by mickcoyne** [LatvianModder/FTBUtilities#332]
Add option to allow players to kill entities in claimed chunks? Super useful ability. I'd even be happy if this was a global option in the config if you don't want to do it per team.  (1.10.2)

**Comment by LatvianModder** [comment]
You mean to deny killing entities? Because players can kill entities in claimed chunks?

**Comment by mickcoyne** [comment]
Wait...sorry. I am running into issues with people being able to destroy end crystals. You are correct, we are able to kill entities, unable to "kill"/break the end crystal however.

**Comment by mickcoyne** [comment]
Upon further investigation, we found that the issue is with sponge and not ftbu.... Thanks for making ftbu, don't mind this bug.
