### ISSUE TITLE
Guide Book Images

### ISSUE THREAD

**Issue by Callum-MM** [LatvianModder/FTBUtilities#333]
I'm currently making a 1.10.2 modpack and looking to use the FTBU guide to help players get started with a couple of chapters. I was planning to put images and recipes in it like infinity used to have. I've mostly figured out the new guide book system but can't get any images to work. I even tried putting your examples from http://guides.latmod.com/ but can't get any of them working either. 
I can't upload json files here so i put it in pastebin for you to see. The image part is near the bottom and its not my own work. I took it from another pack just to figure out how it works to start with before making my own xD
http://pastebin.com/tLCiWPLs

Hopefully you can point out where I'm going wrong here.
Thanks :D

**Comment by LatvianModder** [comment]
Try something like this (I still have to update guides.latmod.com)

```{"id": "image", "image": "chisel:textures/items/chisel_iron.png"}```
(This is from Chisel mod)

**Comment by Callum-MM** [comment]
![chiselscreenshot](https://cloud.githubusercontent.com/assets/14040343/21962893/712d6fac-db27-11e6-9512-9a71b633f7ff.png)
Yep. That worked perfectly! Thanks a bunch :D
