### ISSUE TITLE
[1.7.10/1.0.18.3] Homes not working correctly

### ISSUE THREAD

**Issue by chaos234** [LatvianModder/FTBUtilities#335]
I don't why this happends but currently the homes are not working and I can't find them in any NBT compiled file.

Problem is that some players on my server can setup up to 10 homes, I also removed the blacklisted dimension ID 1 and saved it (server was also restarted and the JSON-File looks well).

But if some useres are setting homes they are instantly ported to the bed spawn and I can't see what
causes this problem since I don't have this problem as op and also as non-op.

I looked through the code and found an NBT-Tag called "Homes" but never found this in any file (leve.dat, <uuid>.dat, ...).

So what is the problem? I am missing one setting for it?

**Comment by LatvianModder** [comment]
Is this 1.10.2?

**Comment by chaos234** [comment]
Look in the title pls. It is 1.7.10 :)

**Comment by LatvianModder** [comment]
Oh. I wont be able to fix this, but the NBT file is saved in world/FTBLib.dat, if I remember corretly, you can take a look at that, and maybe figure out how to NBT-edit homes

**Comment by chaos234** [comment]
There is no such file :(

**Comment by LatvianModder** [comment]
Oh, sorry, its world/LatMod/LMPlayers.dat (its been a very long time :P)

**Comment by chaos234** [comment]
Ok, then we have a problem because I have to folders

latmod/LMPlayers.dat and LatMod/FMPlayers.dat so can this cause the error since it is a doublication?

**Comment by LatvianModder** [comment]
Oh, on Linux it had this problem. Delete lowercase "latmod", the real one is uppercase

**Comment by chaos234** [comment]
ok, should I then restart the server or should it work then without any restart and will it then recreated on server restart? Because if this is the problem what I described why not going to change it to lowercase to prevent it, if possible?

**Comment by LatvianModder** [comment]
You probably shouldnt edit any files while server is on. It will usually overrwrite them if its on

**Comment by chaos234** [comment]
Ok, the Problem seems to be the following:

Under latmod/ there is LMPlayers.txt with a number, the players name and the UUID
Under LatMod/ there is ClaimedChunks.json, LMPlayers.dat and LMWorld.json

So proberly smth. is going wrong with the txt file. So on which place you are generating those files if u remeber? I know it is long time ago but when this is fixed it should fix the current problem.

**Comment by LatvianModder** [comment]
LatMod/LMPlayers.dat is the real one for sure. That .txt file doesnt affect anything

**Comment by chaos234** [comment]
It writes down some IDs, usernames and UUIDs. However, I have done a full reset on it and take a look on it. Will report here soon if it's fixed/solved.
