### ISSUE TITLE
Ticking player

### ISSUE THREAD

**Issue by Sitherious** [LatvianModder/FTBUtilities#336]
https://paste.ubuntu.com/23814809/

**Comment by LatvianModder** [comment]
How did this happen? Is it a fake player?

**Comment by Sitherious** [comment]
i am unsure its the first time i have seen this and i haven't added anything new to the server

**Comment by LatvianModder** [comment]
It will be fixed in next build anyway, no worries

**Comment by Sitherious** [comment]
yes its a fake player just realized the discord bot was adding that in to use the chat template. :( i disabled it until i can figure a way to fix it

**Comment by Sitherious** [comment]
also on a side note could you reply to my other issue i opened 8 days ago about perms? pertty pls
