### ISSUE TITLE
Implement Guide Image ClickEvent

### ISSUE THREAD

**Issue by Quarris** [LatvianModder/FTBUtilities#337]
Is there a way to have an image that when clicked on it sends you to a specific UR? Or alternatively a text. I tried a bunch of options with the guide.latmod.com and the 'helpful tool' that was linked there but I can't get it to work properly. Thanks in advance!

**Comment by LatvianModder** [comment]
Looks like there isnt. It was supposed to be there, but I forgot to implement it

**Comment by Quarris** [comment]
Thanks for the response. When it gets implemented would you post it here for example so I would know? Thanks again!
