### ISSUE TITLE
Last Seen time is the same for all players

### ISSUE THREAD

**Issue by Ricket** [LatvianModder/FTBUtilities#338]
![image](https://cloud.githubusercontent.com/assets/196978/22134860/47e3f43a-de98-11e6-851e-784bee0f2661.png)

They did not log off all at the same time.

FTBUtilities-1.10.2-3.2.4.jar

Direwolf20-1.10 pack version 1.4.1

**Comment by LatvianModder** [comment]
Fixed in 3.4.0+
