### ISSUE TITLE
Crash on saving server config edits from client

### ISSUE THREAD

**Issue by Gunner76th** [LatvianModder/FTBUtilities#339]
[crash-2017-01-20_07.00.02-client.txt](https://github.com/LatvianModder/FTBUtilities/files/719273/crash-2017-01-20_07.00.02-client.txt)
Got this lovely little crash when I clicked accept on the MOTD while using the /ftb config_edit ftbu command

**Comment by Gunner76th** [comment]
This was on Sky Factory 3 in a dedicated server / client SMP setup

**Comment by LatvianModder** [comment]
You probably have to use " quotes to edit strings with spaces

**Comment by Gunner76th** [comment]
Confirmed that you have to have ["some sort of text here"] in order for it to not crash. Perhaps this should be added to the config by default, or added to the tooltip that  appears when you hover over it. Currently in the config there is just [] with no indication that " " are also required in order for it to work. 

I also found out that if I edit the config.json file directly, save it to the server, and then do /ftb reload the changes I made are reverted back to what it was before. It would appear that instead of reloading from the json, the server is reloading its current config within the working space and saving that data back to the json file. AKA Read settings in memory, save to json file.  This IMO is opposite of how a reload command should work. It should read the json file, and then load that into memory, overwriting any previous config that was in memory. AKA Read json, use new settings.

**Comment by LatvianModder** [comment]
Closing this one, as its not FTBU-specific, opened one on FTBLib: https://github.com/LatvianModder/FTBLib/issues/51
