### ISSUE TITLE
Updating from FTBUtilities 14.2 to 16 causes dedicated server to crash.

### ISSUE THREAD

**Issue by joshricker** [LatvianModder/FTBUtilities#34]
Server was running FTBUtilities-1.7.10-1.0.14.2 and FTBLib-1.7.10-1.0.14.3 and was updated to 1.0.16 of Utillties and Lib and getting this crash on startup http://pastebin.com/chE96J73 . Going back to the old versions and it can start again.

**Comment by LatvianModder** [comment]
Fixed in v1.0.17+
