### ISSUE TITLE
Chunks set to load from Claimed Chunks not loading.

### ISSUE THREAD

**Issue by BYFSartre** [LatvianModder/FTBUtilities#340]
This is on FTB Infinity 1.7.10

The config.json is this

`{`
  `"backups": {`
    `"backup_timer": 4.0,`
    `"backups_to_keep": 12,`
    `"compression_level": 1,`
    `"display_file_size": true,`
    `"enabled": true,`
    `"folder": "./backups/",`
    `"need_online_players": false,`
    `"use_separate_thread": true`
  `},`
  `"chunkloading": {`
    `"enabled": true,`
    `"max_player_offline_hours": -1.0`
  `},`
  `"commands": {`
    `"back": true,`
    `"home": true,`
    `"name_admin": "admin",`
    `"spawn": true,`
    `"tplast": true,`
    `"warp": true`
  `},`
  `"general": {`
    `"blocked_entities": [],`
    `"restart_timer": 0.0,`
    `"safe_spawn": true,`
    `"server_info_difficulty": true,`
    `"server_info_mode": true,`
    `"spawn_area_in_sp": false,`
    `"spawn_pvp": true`
  `},`
  `"login": {`
    `"motd": [`
      `"Welcome to the server!"`
    `],`
    `"starting_items": [`
      `"minecraft:apple 16 0"`
    `]`
  `},`
  `"permissions_admin": {`
    `"allow_creative_interact_secure": true,`
    `"badge": "",`
    `"break_whitelist": [`
      `"OpenBlocks:grave"`
    `],`
    `"cross_dim_homes": true,`
    `"custom_config": {},`
    `"dimension_blacklist": [],`
    `"forced_chunk_security": "-",`
    `"forced_explosions": "-",`
    `"max_claims": 1000,`
    `"max_homes": 100,`
    `"max_loaded_chunks": 50,`
    `"show_rank": true`
  `},`
  `"permissions_player": {`
    `"allow_creative_interact_secure": false,`
    `"badge": "",`
    `"break_whitelist": [`
      `"OpenBlocks:grave"`
    `],`
    `"cross_dim_homes": true,`
    `"custom_config": {},`
    `"dimension_blacklist": [`
      `1`
    `],
    `"forced_chunk_security": "-",`
    `"forced_explosions": "-",`
    `"max_claims": 100,`
    `"max_homes": 1,`
    `"max_loaded_chunks": 50,`
    `"show_rank": true`
  `},`
  `"tops": {`
    `"deaths": true,`
    `"deaths_ph": true,`
    `"first_joined": true,`
    `"last_seen": true,`
    `"time_played": true`
  `}`
`}`

Possible problems (me just brainstorming)

1. Non-OPs don't have permission to load claimed chunks.
2. Chunk loading is disabled by the host (Bisect Hosting.)
3. I am a complete noob and are missing something obvious.

Also, this is a very relaxed server, handling 10-15 people so I haven't set up permissions yet. Right now it's just OPs and players.

**Comment by LatvianModder** [comment]
So what is the problem here exactly? config file seems fine
