### ISSUE TITLE
No Controls

### ISSUE THREAD

**Issue by Box-Jockey** [LatvianModder/FTBUtilities#341]
Currently running All the Mods.  FTB_Utils and Lib are in the mods folder for the server and not set to .disabled.  None of the GUI buttons are showing up. Is there another step I am missing somewhere?

**Comment by LatvianModder** [comment]
Is it enabled/installed on client?

**Comment by Box-Jockey** [comment]
Apologies for the ineptitude.  I installed the entire All the Mods mod pack via Curse and I see the Utils and Lib mods in the mod folder, no .disabled at the end of the file name (this is in the server mod folder).  Does that count as being installed and enabled?

**Comment by LatvianModder** [comment]
Yeah, that's weird. I will have to install the pack myself and see

**Comment by Box-Jockey** [comment]
Dumb question, it is in both the client folder and the server folder.  Should it only be in one?

**Comment by LatvianModder** [comment]
No, no, it shoud be in both

**Comment by Box-Jockey** [comment]
Like I said, dumb question :)

**Comment by Box-Jockey** [comment]
Don't know if it helps, but when in the game client if I go to mod options and click FTB Utils there is a config button but it is grayed out.

**Comment by LatvianModder** [comment]
If there are still no controls showing up. try updating FTBLib/FTBU to 3.4.0+. If still nothing, reopen the issue
