### ISSUE TITLE
Next to zero OP controls

### ISSUE THREAD

**Issue by pandaman212** [LatvianModder/FTBUtilities#342]
Currently I have a stubborn user who will not log into a large Twitch Streamers sub server I am running. At the moment OP has little control over what they can manage when it comes to claims (if a user is offline) aside from removing homes. I can't even remove their data from ftblib.dat as it just creates it.

Could OP's get some control commands over claims/chunks in the future.

**Comment by Sasstraliss** [comment]
This

**Comment by LatvianModder** [comment]
Fixed in 3.4.0+. Sorta. You can easily unclaim other people chunks or delete player data completely
