### ISSUE TITLE
Protected Spawn Chunks don't show as such, can be claimed by players (not modified though)

### ISSUE THREAD

**Issue by starg09** [LatvianModder/FTBUtilities#343]
I've noticed this happening on an ATM:Lite Instance.

* Pack Version: 1.23
* FTBLib Version: 3.2.3
* FTB Utilities Version: 3.2.4

Having a dummy account as OP, checking with my main account deopped. The area is indeed protected (as desired, and set through vanilla's `server.properties`), but the claim map no longer shows the area as "Spawn Area", as it used to do in the past. Any player (no need for any special permissions) can claim those chunks, although they still cannot modify them even after the claim.

Would be nice if this were fixed, or if suggestion #88 were to be implemented soon. In any case, it would solve this issue :)

**Comment by mavrck48** [comment]
Experiencing the same thing and I also second suggestion #88.
