### ISSUE TITLE
Rank System Working?

### ISSUE THREAD

**Issue by mavrck48** [LatvianModder/FTBUtilities#344]
I cannot seem to get the rank system working.  Whether I try assigning myself to a rank or even just the default rank, I cannot seem to make the rank system work at all.

Here is my config.json with ranks enabled: [config.json](http://pastebin.com/bbimKbmc)

Here is my ranks.json with my ranks: [ranks.json](http://pastebin.com/59Q7nS3Z)

Here is my player_ranks.json assigning myself to a rank: [player_ranks.json](http://pastebin.com/LsyTZScx)

Modpack info:
FTBInfinityLite110-1.5.1-1.10.2
which includes
Minecraft 1.10.2
FTBserver-1.10.2-12.18.3.2185-universal.jar
FTBLib-1.10.2-3.2.3.jar
FTBUtilities-1.10.2-3.2.4.jar

**Comment by mavrck48** [comment]
Ok, it seems permissions and ranks are working.  However, I cannot get the following to work:

- Default Rank
- Prefix's

**Comment by LatvianModder** [comment]
Oh yeah, prefix isnt implemented yet, that will be soon.
It's weird that default rank doesn't work, it should, I will test it
admin should have guest as parent.
what's this though? ```net.minecraftforge.server.command.ForgeCommand```

**Comment by mavrck48** [comment]
I was trying to get the "/forge tps" command working so people could see if the server was lagging or not.  That perm seems to work for me.

**Comment by mavrck48** [comment]
I'll play around with Default Rank more and see if I can get it to work, thanks for the response.

**Comment by mavrck48** [comment]
Does the default_rank_config.json file matter?  I thought the default rank was covered in the ranks.json

**Comment by LatvianModder** [comment]
Oh! Yeah it doesn't, because it only adds assigned ranks to that list to a) not spam b) in case you change default rank, you dont have to change *all* players (since default rank by definition will have been assigned to more people than other ranks (like 100 players and 5 admins))

**Comment by LatvianModder** [comment]
Fixed in 3.3.0+, ranks have been added properly
