### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by O13SC3N3** [LatvianModder/FTBUtilities#35]
1.7.10 Forge 1558, Clicked on one of the books in the inventory screen and received the following.,

FTB Utilities and LIB .16

> ime: 1/28/16 2:42 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at ftb.utils.mod.client.gui.guide.GuiGuide.drawBackground(GuiGuide.java:286)
	at ftb.lib.api.gui.GuiLM.func_73863_a(GuiLM.java:146)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ftb.utils.mod.client.gui.guide.GuiGuide.drawBackground(GuiGuide.java:286)
	at ftb.lib.api.gui.GuiLM.func_73863_a(GuiLM.java:146)

-- Screen render details --
Details:
	Screen name: ftb.utils.mod.client.gui.guide.GuiGuide
	Mouse location: Scaled: (304, 193). Absolute: (609, 450)
	Screen size: Scaled: (800, 419). Absolute: (1600, 838). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['O13SC3N3'/215, l='MpServer', x=-779.27, y=5.62, z=930.53]]
	Chunk stats: MultiplayerChunkCache: 393, 393
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-804,4,947), Chunk: (at 12,0,3 in -51,59; contains blocks -816,0,944 to -801,255,959), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 7408 game time, 7408 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntityHat['unknown'/999178, l='MpServer', x=-803.84, y=4.00, z=862.50], EntityMaka['Maka'/56334, l='MpServer', x=-881.25, y=4.00, z=990.90], EntityGoblin['Hobgoblin'/56348, l='MpServer', x=-715.44, y=4.00, z=982.97], EntityCow['Cow'/56351, l='MpServer', x=-712.41, y=4.00, z=984.81], EntityCow['Cow'/56352, l='MpServer', x=-712.50, y=4.00, z=989.50], EntityCow['Cow'/56353, l='MpServer', x=-714.50, y=4.00, z=988.50], EntityCow['Cow'/56354, l='MpServer', x=-708.97, y=4.00, z=998.84], EntitySheep['Sheep'/56355, l='MpServer', x=-713.56, y=4.00, z=985.41], EntitySheep['Sheep'/56356, l='MpServer', x=-714.81, y=4.00, z=981.78], EntitySheep['Sheep'/56357, l='MpServer', x=-715.31, y=4.00, z=985.81], EntitySheep['Sheep'/56358, l='MpServer', x=-707.50, y=4.00, z=972.50], EntityHorse['Donkey'/56359, l='MpServer', x=-809.38, y=4.00, z=860.78], EntityHorse['Donkey'/56360, l='MpServer', x=-812.41, y=4.00, z=855.63], EntityHorse['Donkey'/56361, l='MpServer', x=-813.72, y=4.00, z=858.66], EntityCow['Cow'/56363, l='MpServer', x=-803.22, y=4.00, z=860.22], EntityCow['Cow'/56364, l='MpServer', x=-802.31, y=4.00, z=863.72], EntitySheep['Sheep'/56237, l='MpServer', x=-716.13, y=4.00, z=941.91], EntityCow['Cow'/56365, l='MpServer', x=-813.03, y=4.00, z=857.16], EntitySheep['Sheep'/56238, l='MpServer', x=-721.56, y=4.00, z=943.78], EntityCow['Cow'/56366, l='MpServer', x=-803.84, y=4.00, z=862.50], EntitySheep['Sheep'/56239, l='MpServer', x=-724.47, y=4.00, z=942.75], EntityChameleon['Chameleon'/56367, l='MpServer', x=-804.50, y=4.00, z=858.50], EntitySheep['Sheep'/56240, l='MpServer', x=-724.63, y=4.00, z=940.38], EntityHat['unknown'/817, l='MpServer', x=-779.27, y=5.62, z=930.53], EntityCow['Cow'/56241, l='MpServer', x=-722.97, y=4.00, z=941.38], EntityChameleon['Chameleon'/56369, l='MpServer', x=-807.06, y=4.00, z=867.13], EntityCow['Cow'/56242, l='MpServer', x=-725.81, y=4.00, z=942.50], EntityCow['Cow'/56243, l='MpServer', x=-726.50, y=4.00, z=944.50], EntityCow['Cow'/56244, l='MpServer', x=-731.50, y=4.00, z=940.50], EntitySheep['Sheep'/56250, l='MpServer', x=-722.81, y=4.00, z=946.81], EntityHat['unknown'/57277, l='MpServer', x=-724.47, y=4.00, z=942.75], EntitySheep['Sheep'/56254, l='MpServer', x=-727.50, y=4.00, z=948.50], EntityHat['unknown'/57278, l='MpServer', x=-725.81, y=4.00, z=942.50], EntitySheep['Sheep'/56257, l='MpServer', x=-728.50, y=4.00, z=950.50], EntitySheep['Sheep'/56260, l='MpServer', x=-736.91, y=4.00, z=950.97], EntityTrail['unknown'/860, l='MpServer', x=-779.27, y=5.62, z=930.53], EntityHat['unknown'/1033211, l='MpServer', x=-779.27, y=5.62, z=930.53], EntityCow['Cow'/56311, l='MpServer', x=-854.31, y=4.00, z=878.59], EntityClientPlayerMP['O13SC3N3'/215, l='MpServer', x=-779.27, y=5.62, z=930.53], EntityHat['unknown'/1003378, l='MpServer', x=-713.56, y=4.00, z=985.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1126541992 bytes (1074 MB) / 3146072064 bytes (3000 MB) up to 3723231232 bytes (3550 MB)
	JVM Flags: 7 total; -Xms256M -Xmx3584M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CICompilerCountPerCPU -XX:+TieredCompilation

**Comment by Haggle1996** [comment]
Same error I think. http://pastebin.com/q3zHCaSV

**Comment by LatvianModder** [comment]
Fixed in v1.0.17+
