### ISSUE TITLE
Crash on server launch. :<

### ISSUE THREAD

**Issue by CelticChristoph** [LatvianModder/FTBUtilities#350]
MC: 1.10.2
Forge: 12.18.3.2221

The newest update of FTBUtils (FTBUtilities-1.10.2-3.2.7.jar) crashes on server load for me.

Report:
https://gist.github.com/CelticChristoph/e35743b5d08ed321e0ca1e122cce45c5

**Comment by LatvianModder** [comment]
Did 3.2.8 fix it?

**Comment by ShadowRipper** [comment]
nope :(
tried using:
forge 2185 (recommended)
ftb utilities 3.2.8
ftb lib 3.2.8

it crashed my server

im currently using:
ftb utilities 3.2.4
ftb lib 3.2.3
and that worked for many days :) 👍 
thanks for that FTB!

**Comment by LatvianModder** [comment]
Does 3.2.9 fix this?

**Comment by ShadowRipper** [comment]
no, still crashing
ftb utilities 3.2.9
ftb lib  3.2.8

**Comment by LatvianModder** [comment]
Got a crash report?

**Comment by ShadowRipper** [comment]
sry i was gone for work 👍 
i have tried it and your awesome it works!
good job LatvianProModder ;)
thanks for the fast updates!!
