### ISSUE TITLE
No permissions for "/edit_config ftbu" when using "PermissionManager-2.6.0-API-5.X-6.X.jar"

### ISSUE THREAD

**Issue by MrMilti** [LatvianModder/FTBUtilities#353]
I am setting up a server with SpongeForge and this drives me nuts.

As soon as I install PermissionManager-2.6.0-API-5.X-6.X.jar for permission managment, it is impossible to get into the config screen for ftbu, as I always get the reply "You do not have permission to use this command"

Please clarify, which permissions I have to set to get access.

I already tried "ftbu.*" and "command.*" and both do not solve the problem.

I can temporarily disbale PermissionManager, edit the configs for ftbu and then reactivate it again, but that is ludicrous and extremly annoying.

thanks.

**Comment by LatvianModder** [comment]
In 3.3.0+ FTBUtilities adds it's own permission manager. Sponge and FTBU will conflict if both of them will be enabled (you can turn of FTBU's). And since Sponge doesn't support Forge's PermissionAPI, I can't fix this, afaik
