### ISSUE TITLE
[3.2.9] Ticking Memory Connection when creating world

### ISSUE THREAD

**Issue by GiovanniPorta** [LatvianModder/FTBUtilities#354]
Game crashes during singleplayer world creation. Bug existed on 3.2.4 and still exists after updating to 3.2.9.

Minecraft Version: 1.10.2
Operating System: Windows 10 (x64)
Java Version: 1.8.0_91
Forge Version: 1.10.2-12.18.3.2221

[Link to crash report](https://gist.github.com/GiovanniPorta/18170ab070e21235ed318fff8c61b2ec)

**Comment by LatvianModder** [comment]
Fixed in 3.3.0+
