### ISSUE TITLE
Ranks mess up names

### ISSUE THREAD

**Issue by ElectricBlue1** [LatvianModder/FTBUtilities#355]
Hello so Ive recently updated my modpaack and with that update came an update for FTBUtilities and once i updated my sever and a person came on i realized the names have been messed up. My name is green because I'm  an op and the other players name was "$(name)" and i tried to fix it by disabling ranks but it wouldn't listen to me how can i fix this?

**Comment by LatvianModder** [comment]
Temp fix is to change player rank's "syntax":"<$name> ", otherwise I will fix this shortly

**Comment by ElectricBlue1** [comment]
Ok

**Comment by ElectricBlue1** [comment]
When i entered "syntax":"<$name> ", to the players rank in rank.json and once i restarted the server is changed the syntax to the default ("syntax":"<&2$(name)&r") and the reload commands dont read the configs

**Comment by LatvianModder** [comment]
Try this as your default ranks.json:

```
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "syntax": "<$name&r> ",
      "permissions": [],
      "config": {}
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}
```

**Comment by LatvianModder** [comment]
Are you sure you are on mod versions 3.3.0?

**Comment by LatvianModder** [comment]
This should fix it, let me know if it works http://mods.latmod.com/FTBUtilities/1.10.2-3.3.1/

**Comment by LatvianModder** [comment]
Already tested, it works

**Comment by ElectricBlue1** [comment]
Thanks Latvian
