### ISSUE TITLE
Unclaim specific chunks

### ISSUE THREAD

**Issue by Autopoietico** [LatvianModder/FTBUtilities#356]
With the command /ftb chunks admin_unclaim_all you can unclaim all the chunks from a player, but no specific chunks, can be cool that this and the unclaim_all command works when the player that claim a chunk is offline.

**Comment by LatvianModder** [comment]
The regular unclaim command / unclaiming from GUI should work now. If it doesn't, its a bug

**Comment by Autopoietico** [comment]
![captura de pantalla 2017-02-13 15 22 46](https://cloud.githubusercontent.com/assets/8708366/22901671/6d14432e-f200-11e6-9aa8-9ae6901384b3.png)
If i try to unclaim a chunk that belongs to other player with the command /chunks unclaim this message appear.

**Comment by LatvianModder** [comment]
Yeah, I already figured out its a bug, fixed in my Dev, will be out with next release

**Comment by Autopoietico** [comment]
Thanks!

**Comment by LatvianModder** [comment]
Fixed in 3.4.0+
