### ISSUE TITLE
New Rank Config - No Parent?

### ISSUE THREAD

**Issue by mavrck48** [LatvianModder/FTBUtilities#357]
How can I create a rank with no parent permissions (I.E. trying to create a rank with no permissions)?

I tried:

- Deleting the parent line, it gets created back

- Changing the parent to something that doesn't exist (like "parent": "no_parents"), but it just gets changed back to bultin_player

- Leaving the quotations blank (like "parent": ""), but it just gets changed back to bultin_player

This is what my ranks.json looks like currently: [Ranks.json](http://pastebin.com/4VH8VvcD)

**Comment by LatvianModder** [comment]
Add "-*" in the end of "permissions" of that rank, if you want to have that. It can't have no parent so builtin_player is fine. Say you want to make a rank that can only use help, msg and warp:

```
"no_perms_rank": {
  "parent": "builtin_player",
  "syntax": "<$name&r> ",
  "permissions": [
    "+commands.help",
    "+commands.msg",
    "+commands.warp",
    "-*"
  ],
  "config": {}
}
```
