### ISSUE TITLE
Backups do not check for available space before writing

### ISSUE THREAD

**Issue by draeath** [LatvianModder/FTBUtilities#358]
Backups will crash the server if disk space is exhausted.

You might ask why a server should stay up when disk space is so tight - well, if the region data has been pregenned, this data can exceed 500mb easily without much future growth. When the backup runs, you can see how this can add up.

Unfortunately the log is truncated, so the last thing I see is the IOException being printed from [ThreadBackup line 163](https://github.com/LatvianModder/FTBUtilities/blob/620eb8fea57d7ffae767339d371d8b50430e1609/src/main/java/com/feed_the_beast/ftbu/world/backups/ThreadBackup.java#L163). I expect the crash is occurring somewhere else (likely not even in your mod).

However, this does bring up a point: FTBU should be able to make some sort of estimation on the backup file size, before the backup is commenced. At the very least, it's reasonable to expect the backup size to be at most the current size of the data, plus some overhead for the zip format. Action to be taken when insufficient space is available could perhaps be configurable - anything from treated-as-fatal to a warning, or rolling off older backups until space is available?

**Comment by LatvianModder** [comment]
I would probably go with deleting old backups until there is space available

**Comment by Matakor** [comment]
This is still an issue. I have it set to save only three backups, but I checked my backups folder recently and found 40, totaling over 100gb on my 400gb ssd. (1.12)

**Comment by LatvianModder** [comment]
The problem is that its easy to check when you have folder mode enabled, but quite hard when you are zipping the world. Basically would have to zip it twice. I could add this as config option, because it could double the time it takes to make backups

**Comment by Matakor** [comment]
I've set it to a specific folder, and told it to not keep more than 5 backups, but I still am getting more. Am I just setting it up wrong or something?
