### ISSUE TITLE
v3.3.1 ranks.json gets recreated everytime config loads or server starts

### ISSUE THREAD

**Issue by demfels** [LatvianModder/FTBUtilities#361]
Since we've updated I have not been able to set our chunkloading and claiming permissions.  The ranks file gets refreshed everytime it loads.

**Comment by LatvianModder** [comment]
Make sure you have enabled ranks in config,json and you are editing ranks.json

**Comment by demfels** [comment]
I found that ranks was disabled in config.json, thank you! It appears to be working again.
