### ISSUE TITLE
Buckets can be used in claimed chunks

### ISSUE THREAD

**Issue by Autopoietico** [LatvianModder/FTBUtilities#363]
Chunks that are claimed don't prevent that players can used in claimed chunks.

**Comment by LatvianModder** [comment]
Buckets are items that raytrace on item rightclick, and dont use block click. How about.. "Allow to configure item rightclicking within chunks"?

**Comment by LatvianModder** [comment]
Actually, this is a duplicate of a very old issue (https://github.com/LatvianModder/FTBUtilities/issues/55) , so im gonna close this one
