### ISSUE TITLE
Cannot use commands

### ISSUE THREAD

**Issue by Algurt** [LatvianModder/FTBUtilities#364]
Made a custom modpack and it has ftbu and ftblib in it. Trying to get a way to remove a players chunks that they have claimed. However /admin command "Does not exsist". I dont see any ftbu commands in the normal command list [pressing e, hitting server info, then going to commands]. However I am noticing that under the command "/<world name> I see the commands. But it does not allow me to use them.

The attached screenshot shows what i mean by that they only show up in the /<world name> area
![commands](https://cloud.githubusercontent.com/assets/9617368/23283366/7442a488-f9f3-11e6-9cdb-945baab9b1af.jpeg)

**Comment by LatvianModder** [comment]
It looks like you have plugins. AND this is 1.7.10, sorry, I can't help with this

**Comment by LatvianModder** [comment]
You can remove chunks from ClaimedChunks.json however, if you find the right ones
