### ISSUE TITLE
Team Description causes client crash

### ISSUE THREAD

**Issue by ThomasAunvik** [LatvianModder/FTBUtilities#365]
Issue Description:

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

Tried only in singleplayer

Client Crashes after changing Team Description with a space.

I was on an unclaimed land and i had no land claimed.

What happens:

Client crashes with a:

```
Description: Updating screen events

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8
```

After that the config will not be saved.

[Full Crashlog](http://pastebin.com/i7jpDPgH)

[All exceptions thrown](http://pastebin.com/xEPBxqKj)

What you expected to happen:

Changing Team Description withouth crashing.
And to save correctly.

Steps to reproduce:

1. Command: /ftb team config
2. Change Team Description
3. Use a space in the description.

The Version of All the Mods:

```
WARNING: coremods are present:
  literalascension (literalascension-1.10.2-1.0.1.1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.340.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.7.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.0-beta2-anarchy.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  ForgelinPlugin (Forgelin-1.3.1.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
Contact their authors BEFORE contacting forge
 

```
What modpack ive been using:
All The Mods Expert 1.0.26

Added mods (Optifine, Fastcraft, etc.):
None

**Comment by LatvianModder** [comment]
Fixed in 3.4.0+
