### ISSUE TITLE
[1.10.2] Non-vanilla items not given in starting inventory

### ISSUE THREAD

**Issue by Axebeard2025** [LatvianModder/FTBUtilities#368]
Installed mods:  
FTBLib 1.10.2-3.3.0
FTBUtilities 1.10.2-3.3.1
Tinker's Construct 1.10.2-2.6.3 1.10.2-1.1.5
Forge 1.10.2-12.18.3.2185

FTBUtilities will give the player vanilla minecraft items as starting items, but will not give modded items.  This behavior exists in single player and multi-player

I tested both using the following "/give" command to make sure I had the correct format:

`/give Axebeard minecraft:stone_sword 1 0`
`/give Axebeard tconstruct:punji 10 0`
`/give Axebeard tconstruct:soil 5 1`

Using those commands, I received 1 stone sword, 5 Green Slimy Mud, and 10 punji sticks .

However, in the following configs, I have added 1 (vanilla) stone sword 10 tinker's construct punji sticks, and 5 tinker's construct green slimy mud.  When I start a new world, players only get 1 (vanilla) stone sword.  The punji sticks and green slimy mud do not appear in player inventory.

FTBUtilities config.json:

> {
  "backups": {
    "backups_to_keep": 12,
    "display_file_size": true,
    "enabled": false,
    "backup_timer": 2.0,
    "compression_level": 1,
    "folder": "",
    "use_separate_thread": true
  },
  "commands": {
    "chunks": true,
    "trash_can": false,
    "ranks": true,
    "view_crash": true,
    "warp": true,
    "tpl": true,
    "inv": true,
    "back": true,
    "server_info": true,
    "spawn": true,
    "home": true,
    "kickme": true
  },
  "general": {
    "auto_restart": false,
    "server_info": {
      "admin_quick_access": true,
      "difficulty": true,
      "mode": true
    },
    "chat": {
      "substitutes": [
        {
          "shrug": "¯\\_(ツ)_/¯"
        }
      ],
      "substitute_prefix": "!"
    },
    "restart_timer": 12.0
  },
  "world": {
    "chunk_loading": true,
    "blocked_entities": [],
    "chunk_claiming": true,
    "safe_spawn": false,
    "spawn_area_in_sp": false
  },
  "ranks": {
    "override_chat_short_urls": true,
    "override_chat": true,
    "override_commands": true,
    "enabled": true
  },
  "webapi": {
    "update_interval": 5,
    "enabled": false,
    "file_location": ""
  },
  "login": {
    "motd": [],
    "enable_motd": true,
    "enable_starting_items": true,
    "starting_items": [
      "minecraft:stone_sword 1 0",
	  "tconstruct:punji 10 0",
	  "tconstruct:soil 5 1"
    ]
  }
}

**Comment by LatvianModder** [comment]
Not sure what could be causing that

**Comment by Axebeard2025** [comment]
1.  I've done some further testing with the latest versions of FTBLib and FTBUtilities:

- FTBLib (1.10.2-3.4.2)
- FTBUtilities (1.10.2-3.4.0)
- Tinker's Construct (1.10.2-2.6.3)
- Mantle (1.10.2-1.1.5)
- Forge (1.11.2 - 13.20.0.2252)

Result:  sword in starting inventory.  Punji sticks and Green Slimy Mud missing.

2.  I tried switching the order of items in config.json:

```
"starting_items": [
	"tconstruct:soil 5 1",
	"tconstruct:punji 10 0",
	"minecraft:stone_sword 1 0"]
```

Result:  sword in starting inventory.  Punji sticks and Green Slimy Mud missing.

3.  I ran similar tests using different mods.  They all produced the same results (vanilla minecraft items appear in starting inventory, but mod items don't.)
  
- Waystones 1.10.2-2.0.12
- Tough As Nails 1.9.4-1.0.11 (1.9.4 version supports 1.9, 1.10, and 1.10.2)   

I could keep trying different mods, but at this point, it looks like FTB Utilities is not recognizing items from any mod.

If you'd like me to do some testing for you, please let me know.  I'm happy to help.

**Comment by bobalobabingbong** [comment]
Just as a little more information with my limited testing. If I only add tough as nails water bottles ("toughasnails:water_bottle 3 1") it works. But if I try and add the water bottle and apples ("minecraft:apple 3 0"), the water bottle will be removed from the config but the apples remain.

**Comment by LatvianModder** [comment]
Maybe the order matters? Hm

**Comment by LatvianModder** [comment]
Ok, changed some code, I think it works now
[!image](http://ss.latmod.com/pc/2017-03-03_12.23.49.png)

**Comment by LatvianModder** [comment]
Try this build http://mods.latmod.com/FTBLib/1.10.2-3.4.4/

**Comment by Axebeard2025** [comment]
First, I tested FTBLib 1.10.2-3.4.4 with FTB Utilities 1.10.2-3.4.1.  

After those failed, I tested FTBLib 1.10.2-3.4.4 with FTBUtilities-1.10.2-3.4.0, and ran into crashes (I now assume that FTBLib 1.10.2-3.4.4 does not play well with FTBUtilities-1.10.2-3.4.0 

Test 1:
- forge-1.10.2-12.18.3.2239, FTBLib-1.10.2-3.4.4, FTBUtilities-1.10.2-3.4.1, ToughAsNails-1.9.4-1.0.11
- confg.json:
         `"enable_starting_items": true,`
    `"starting_items": [`
	`"minecraft:stone_sword 1 0",`
	`"toughasnails:canteen 1 2",`
	`"toughasnails:charcoal_filter 4 0"`
    `]`
- Single Player Result:  Stone sword is in inventory.  Canteen and charcoal filters are missing.  Also, canteen and charcoal filter are automatically removed from config.json
- Multi-Player Result:  Stone sword is in inventory.  Canteen and charcoal filters are missing.  Also, canteen and charcoal filter are automatically removed from config.json

Test 2:
- forge-1.10.2-12.18.3.2239, FTBLib-1.10.2-3.4.4, FTBUtilities-1.10.2-3.4.1, ToughAsNails-1.9.4-1.0.11
- confg.json:
         `"enable_starting_items": true,`
    `"starting_items": [`
	`"toughasnails:canteen 1 2",`
	`"toughasnails:charcoal_filter 4 0",`
	`"minecraft:stone_sword 1 0"`
    `]`
- Single Player Result:  No items in inventory.  Also, **ALL** starting items are removed from config.json
- Multi-Player Result:  No items in inventory.  Also, **ALL** items are removed from config.json

Test 3:
- forge-1.10.2-12.18.3.2239, FTBLib-1.10.2-3.4.4, FTBUtilities-1.10.2-3.4.1, ToughAsNails-1.9.4-1.0.11
- confg.json:
         `"enable_starting_items": true,`
    `"starting_items": [`
	`"toughasnails:canteen 1 2",`
	`"toughasnails:charcoal_filter 4 0"`
    `]`
- Single Player Result:  No items in inventory.  Also, **ALL** starting items are removed from config.json
- Multi-Player Result:  No items in inventory.  Also, **ALL** items are removed from config.json

Test 4:
- forge-1.10.2-12.18.3.2239, FTBLib-1.10.2-3.4.4, FTBUtilities-1.10.2-3.4.0, ToughAsNails-1.9.4-1.0.11
- confg.json:  Never had a chance to change configs because of crash
- Single Player Result:  Client crash.  
[crash-2017-03-03_18.35.33-client.txt](https://github.com/LatvianModder/FTBUtilities/files/818269/crash-2017-03-03_18.35.33-client.txt)

- Multi-Player Result:  Server crash.
[crash-2017-03-03_18.35.17-server.txt](https://github.com/LatvianModder/FTBUtilities/files/818270/crash-2017-03-03_18.35.17-server.txt)

**Comment by Axebeard2025** [comment]
I just deleted a couple of posts I'd made, as they were full of errors and other problems (I shoulda known better than to post stuff while I was loaded up on painkillers for a sinus infection...)

**Comment by Axebeard2025** [comment]
Ok, test results using latest FTBLib and FTBUtilities files:

Test 1:  Forge 1.10.2-12.18.3.2254 (without mercurius), FTBLib 1.10.2-3.4.4,  FTBUtilities 1.10.2-3.4.3, Tinker's Construct 1.10.2-2.6.3, Mantle 1.10.2-1.1.5

Test 1 config.json:
>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       "tconstruct:punji 10 0",
>       "tconstruct:soil 5 1"
>     ]

Test 1 Result:  Only sword appeared in inventory.  Also, config.json for client and server were changed to:
>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       null,
>       null
>     ]

Test 2:  Forge 1.10.2-12.18.3.2239 (without mercurius), FTBLib 1.10.2-3.4.4,  FTBUtilities 1.10.2-3.4.3, Tinker's Construct 1.10.2-2.6.3, Mantle 1.10.2-1.1.5

Test 2 config.json:

>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       "tconstruct:punji 10 0",
>       "tconstruct:soil 5 1"
>     ]

Test 2 Result:  Only sword appeared in inventory.  Also, config.json for client and server were changed to:

>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       null,
>       null
>     ]

Test 3:  Forge 1.10.2-12.18.3.2234 (without mercurius), FTBLib 1.10.2-3.4.4,  FTBUtilities 1.10.2-3.4.3, Tinker's Construct 1.10.2-2.6.3, Mantle 1.10.2-1.1.5

Test 3 config.json:

>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       "tconstruct:punji 10 0",
>       "tconstruct:soil 5 1"
>     ]

Test 3 Result:  Only sword appeared in inventory.  Also, config.json for client and server were changed to:

>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       null,
>       null
>     ]

Test 4:  1.10.2-12.18.3.2221 (without mercurius), FTBLib 1.10.2-3.4.4,  FTBUtilities 1.10.2-3.4.3, Tinker's Construct 1.10.2-2.6.3, Mantle 1.10.2-1.1.5

Test 4 config.json:

>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       "tconstruct:punji 10 0",
>       "tconstruct:soil 5 1"
>     ]

Test 4 Result:  Only sword appeared in inventory.  Also, config.json for client and server were changed to:

>     "enable_starting_items": true,
>     "starting_items": [
>       "minecraft:stone_sword 1 0",
>       null,
>       null
>     ]

**Comment by bobalobabingbong** [comment]
Quick update on this for the latest build, 3.4.3.

```
    ],
    "enable_motd": true,
    "enable_starting_items": true,
    "starting_items": [
      "toughasnails:water_bottle 5 1",
      "minecraft:apple 5 0"
    ]
```
Results in
```
    ],
    "enable_motd": true,
    "enable_starting_items": true,
    "starting_items": [
      null,
      "minecraft:apple 5 0"
    ]
```
This also happens with the order reversed.

**Comment by thephoenixlodge** [comment]
Bit of info I haven't seen mentioned yet: the config will revert the items to null entries only during the launch stage of the pack - if you redo your entries *after* launching the pack, but *before* loading a world, if you then start a new world, it works properly.
This suggests to me its possibly something to do with the stage at which it's trying to read that info from the config, but not a code jockey so can't say for sure

**Comment by LatvianModder** [comment]
Oh that probably is it. Humm. I guess I gotta reload config twice, in preinit and postinit

**Comment by PSILONCRAFT** [comment]
do you have a fix for that wanting to equip my players with som starter coins from thermal foundation

**Comment by LatvianModder** [comment]
Try if it works now

**Comment by PSILONCRAFT** [comment]
No it does not hers my code!

},
  "webapi": {
    "update_interval": 5,
    "enabled": false,
    "file_location": ""
  },
  "login": {
    "motd": [],
    "enable_motd": true,
    "enable_starting_items": true,
    "starting_items": [
"mod currency:banknote #12150/0 64 3"
"modcurrency:wallet 1 4"
"minecraft:apple 5 5"
]
  }
}


or do i have to use nbt
