### ISSUE TITLE
[Suggestion] Mytown intergration

### ISSUE THREAD

**Issue by profjb** [LatvianModder/FTBUtilities#369]
I'm wondering if it would be possible to make it so that FTButilities chunk claims don't override Mytown protections and vice versa.
Just a thought.

P.s. i'm referring to Mytown 2 for 1.7.10.
https://mods.curse.com/mc-mods/minecraft/224242-mytown2

**Comment by LatvianModder** [comment]
Sorry, 1.7.10 is no longer supported
