### ISSUE TITLE
ranks.json seems to reset

### ISSUE THREAD

**Issue by FreekingDean** [LatvianModder/FTBUtilities#371]
I'm on FTB Infinity Lite 1.7.0, I believe that is 3.3.1 for FTB Utilities.

It seems every time I reload ftbu or restart the server the `local/ftbu/ranks.json` file is resetting. I thought that ranks are implemented now? I could be wrong, it seems theres a bit of confusion around this.

**Comment by LatvianModder** [comment]
Maybe your JSON formatting is wrong. Paste your ranks.json here

**Comment by FreekingDean** [comment]
Yup! I think there was something wrong, I wrote it from scratch (vs copy/paste) and it works.
🎉 
Closing this :)
