### ISSUE TITLE
TeamID instance is not created in the player .dat

### ISSUE THREAD

**Issue by Autopoietico** [LatvianModder/FTBUtilities#372]
The Team file for player are created but the individual player file.dat don't have instance for the team when is created.

**Comment by LatvianModder** [comment]
I dont understand the issue, the TeamID is there in player's nbt file
!(Image)[http://ss.latmod.com/pc/2017-03-05_10.57.56.png]

**Comment by LatvianModder** [comment]
And here's code that specifically makes sure team and player instances exist before loading any data https://github.com/LatvianModder/FTBLib/blob/1.9/src/main/java/com/feed_the_beast/ftbl/api_impl/Universe.java#L116-L168

**Comment by Autopoietico** [comment]
When a new player joins a server, yes the team is created, for example randomuser.dat, but in the file that have for name her uuid, the TeamID instance don't exist.

In the server that i use i ban the use of "team" and "ftb" command because i don't want to people adds allies or similar i only want that claim chunks, maybe this can affect the creation of the TeamID instance?
