### ISSUE TITLE
[Suggestion] Partial permissions for towns

### ISSUE THREAD

**Issue by StangleKhan** [LatvianModder/FTBUtilities#374]
Basically I'd like to see the ability to use this mod for towns more easily. Team leaders would have access to all chunks fully. However, some chunks could be set to interact only (no breaking/placing) for common areas. Other chunks could be set to 'claimable' by other team members making them that member's private plot. The private plots would only allow only the team member who owned it and the team leaders to have access to it.

Right now the only way to have something like a town with this mod would be to unclaim a chunk and then let somebody else claim it. This can be an issue for someone trying to make a town since they would have zero access to that chunk anymore.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/88
