### ISSUE TITLE
ftb command allow people to skip restrictions

### ISSUE THREAD

**Issue by Autopoietico** [LatvianModder/FTBUtilities#376]
If i ban the command /warp but i allow the /ftb command, people can use /ftb warp to skip the restriction, i don't want to ban the /ftb command because people cannot access map and teams gui, is possible to ban subcommands or change that with a config rank permission?

**Comment by LatvianModder** [comment]
yes, you just add "-commands.ftb.subcommand" or "-commands.ftb.subcommand.subcommand" or "-commands.ftb.subcommand.*" to permissions

**Comment by Autopoietico** [comment]
Thanks!
