### ISSUE TITLE
Blocking Spawn Chunk Claiming by Players

### ISSUE THREAD

**Issue by IdrisDose** [LatvianModder/FTBUtilities#377]
Hi, I'm not sure how to do this without posting an issue here, but I've been trying to figure out how to block players from Claiming Spawn using the Map Claim Chunk/Chunk Load map, Is there a way to do this?

Also, Is there a Way I can disable Chunk Claiming but allow them to Chunk Load, if not, I think there would be some use for this. Regarding this point, if there is not a way, am I able to modify the code (I know how to program) to make it function like this, and not have to make users download the modified version? 

The reason I would like to Disable chunk claiming is I'm running a SpongeServer and have a Plugin that handles block protection, but in the Beyond Pack, there is no easy way of Chunk Loading apart from your impressive and neat way, aside from the dodgy IC2 Chunk Loader.

Thanks, Kind Regards,
Idris.

Useful Information:
MC Version: 1.10.2
Modpack: FTB Beyond
FTB Utils Version: 1.10.2-3.4.3

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/88
