### ISSUE TITLE
1.10.2 3.4.3 Unable to use commands in command blocks

### ISSUE THREAD

**Issue by Gunner76th** [LatvianModder/FTBUtilities#379]
I am needing to be able to set ranks using a command block for automation of assignments, however when I try, the command block output says it does not have the require permission to execute the command. Is it possible to change the command level required for the "op" commands from level 4 to level 2 so that they can be executed by the command block? Preferably to all commands not just ranks.

**Comment by Gunner76th** [comment]
Was just curious how things were going and if there was anything I/we (TeamIHOC) could do to help.

**Comment by Gunner76th** [comment]
I just wanted to mention that this is still an issue in version 3.5.1 of FTB Utilities running with version 3.5.3 of FTBLib. 

Is this still being worked on, and is there any progress update on this issue?

**Comment by Gunner76th** [comment]
The latest update has enabled the use of command blocks with ranks command. However, it is only recognizing the @a card. if you try to use "ranks set @p rank" it returns an error of [17:22:56] That player cannot be found
If you use the command "ranks set @a rank" then everyone on the server is set to that rank. 

Here is a screen shot of my command block and its output message
![2017-04-24_17 26 10](https://cloud.githubusercontent.com/assets/5566872/25359409/2d38dc52-2913-11e7-815b-7ffb5e49befc.png)

**Comment by LatvianModder** [comment]
It may work now? Not sure

**Comment by tmvkrpxl0** [comment]
> It may work now? Not sure. Reopen if it doesn't

it don't work on me
i use ftb utilities 5.4.0.96 & ftb lib 5.4.1.99 on MC 1.12.2
