### ISSUE TITLE
Ranks not denying access to commands when set to -

### ISSUE THREAD

**Issue by Gunner76th** [LatvianModder/FTBUtilities#380]
"ranks": {
    "player": {
      "parent": "builtin_player",
      "syntax": "<&6New Player &r$name> ",
      "permissions": [
        "- tpisland"
      ],
      "config": {}
    },
I have that set, yet players of that rank are still able to do the tpisland command. I am not sure where the problem is as that is the command that is added by the mod https://minecraft.curseforge.com/projects/itsbecauseuhasnogoodspawn?gameCategorySlug=mc-mods&projectID=254647

**Comment by LatvianModder** [comment]
Did you even look at all_permissions.html or all_permissions_full_list.txt? You have to use command.x for command permissions

**Comment by Gunner76th** [comment]
Those commands arent in those files.

**Comment by Gunner76th** [comment]
There is no command in them (aside from ones added by Botania) that contain the word island in either file

**Comment by Gunner76th** [comment]
so I would need to do %mod%.%command% ?

Like -ItsBecauseUHasNoGoodSpawn.createislandfore to deny access to that command?

**Comment by LatvianModder** [comment]
If the command is /tpisland, then the node for it is "command.tpisland"

**Comment by Gunner76th** [comment]
Thank you, this is now working. Now to just get my other issue on here sorted if possible. Thanks for the info
