### ISSUE TITLE
Chunkloading

### ISSUE THREAD

**Issue by wolfhound871** [LatvianModder/FTBUtilities#381]
all i want to do is disable Chunkloading first off i again cant edit it in file i must do in game then when i turn off chunkloading it still lets me load chunks ... this is very bad for servers

**Comment by LatvianModder** [comment]
You can disable all chunkloading in /local/ftbu/config.json

**Comment by wolfhound871** [comment]
nope you can not i changed that config and it defaulted so i changed it in game then restarted then it was off but i could still load chunks
