### ISSUE TITLE
Crash on opening Team GUI

### ISSUE THREAD

**Issue by Gunner76th** [LatvianModder/FTBUtilities#383]
I have a player on our server who is crashing when he tried to open the multiplayer GUI. This started happening after I unclaimed chunks he had claimed on a different players island, and then had the rightful owner claim them. 

[crash-2017-03-13_16.44.12-client.txt](https://github.com/LatvianModder/FTBUtilities/files/839931/crash-2017-03-13_16.44.12-client.txt)

**Comment by Somesite** [comment]
Also having a similar issue. When a player who has claimed chunks (haven't tested without) leaves a team the owner of said team can no longer open the team gui without crashing.

**Comment by LatvianModder** [comment]
I thought I fixed that.. Did you update to latest?

**Comment by Somesite** [comment]
The beta? I'm still on the release.

**Comment by LatvianModder** [comment]
This one, I think https://minecraft.curseforge.com/projects/ftblib/files/2397480

**Comment by LatvianModder** [comment]
Fixed in 3.5.0 if it wasnt before
