### ISSUE TITLE
1.10.2 (FTBU 3.4.0 and up): 'Claimed Chunks' button doesn't show GUI

### ISSUE THREAD

**Issue by Benie76** [LatvianModder/FTBUtilities#385]
**Issue with FTBU:** Can't view my claimed chunks; button to do so doesn't work.
**Modpack:** FTB Presents Direwolf20 1.10
**Modpack versions issue happens:** 1.7.0 & 1.8.0 (no changes to the modpack between these two)
**Versions of FTBU issue happens:** 3.4.0 and 3.4.3
**Single/Multiplayer?:** Single player (using FTB Launcher client)
**Reproducible?:** Yes (keep clicking on the Claimed Chunks button and it does nothing)

I feel like I'm the only one having this issue, as I haven't seen anyone else reporting it.

**Comment by LatvianModder** [comment]
No idea about this one. Maybe the mod is removed from server?

**Comment by Benie76** [comment]
I don't know, also... why would it be removed from the modpack? It comes with the modpack, and it came with the modpack since Day 1.
Not sure if I understand your response. Sorry. All I know is it works just fine in every version before 3.4.0.

**Comment by LatvianModder** [comment]
Oh wait, I didnt read that it's Singleplayer not multiplayer. Hummm

**Comment by Benie76** [comment]
Is there anything I can do to help you hopefully fix this issue? Like, test a beta version or something like that?

**Comment by LatvianModder** [comment]
Try updating FTBUtilities and Lib to 3.5.0+
