### ISSUE TITLE
[1.10.2] Actually Additions Block Breaker Server Crash On Launch

### ISSUE THREAD

**Issue by everseeking** [LatvianModder/FTBUtilities#386]
Description
* Upon a server restart/start, the server will oddly only crash once with this attached report but succeed the second time when launching. It was in another player's area and asked if they had enabled "Fake Players", and said they have NOT enabled fake players. Breaking the block breakers in that claim stopped the crash.

Snippet
>java.lang.NullPointerException: Exception while ticking a block
>at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:1092)
>at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onLoggedIn(FTBUPlayerEventHandler.java:70)

Details
* FTB Beyond 1.2.1
* FTBLib-1.10.2-3.4.4.jar
* FTBUtilities-1.10.2-3.4.3.jar

Full Report
* [Crash Report](http://pastebin.com/kamdbHya)

**Comment by evan1026** [comment]
I'm having the same issue except that it's crashing every time I start the server. I made a post about it on /r/FeedTheBeastCrashes [here](https://www.reddit.com/r/FeedTheBeastCrashes/comments/60774i/dw20_110_v180_actually_additions_block_breaker_in/), which I'll include here because it has steps to reproduce. Here's what it says:

> I've got an issue which started after I updated my DW20 server to version 1.8.0. The issue is that the server crashes when there's a block breaker in a claimed chunk. I was wondering if anyone else has had this issue/has a fix.
> 
> Steps to reproduce:
> 1.    Start up a new server on a new world.
> 2.    Put down a block breaker with some way of getting items in front of it (not sure if this is necessary but I put a block placer by it so that it would always have something to break).
> 3.    Claim the chunk the block breaker is in.
> 
> These steps produce this crash report: http://pastebin.com/st4hEwwZ 
>

**Comment by LatvianModder** [comment]
Enable fake players in team settings and see if that still crashes

**Comment by evan1026** [comment]
My crash happens with fake players enabled, which may be why my server crashes every time instead of succeeding on relaunch like everseeking.

**Comment by Ravix-** [comment]
I'm having a similar bug with Refined Storage's "Destructor" and was told to refer it here.

https://github.com/raoulvdberge/refinedstorage/issues/1079#issuecomment-287901669

**Comment by evan1026** [comment]
Took a look at the code and it seems that the crash happens when it tries to send the MOTD to the FakePlayer associated with the breaker:

```java
        if(FTBUConfigLogin.ENABLE_MOTD.getBoolean())
        {
            for(IConfigValue value : FTBUConfigLogin.MOTD)
            {
                ITextComponent t = ((PropertyTextComponent) value).getText();

                if(t != null)
                {
                    ep.addChatMessage(t); // THIS LINE
                }
            }
        }
```

A temporary workaround would be to disable MOTD in the config at `<server_location>/local/ftbu/config.json`. I have tested this and it does keep the server from crashing.

**Comment by LatvianModder** [comment]
Ok. Weird, fake players should ignore chat messages. I think this can be considered a forge bug. It only ignores ```addChatComponentMessage(ITextComponent component)``` but it doesn't ignore ```public void addChatMessage(ITextComponent component)```

**Comment by LatvianModder** [comment]
Sumbmitted forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/3796
