### ISSUE TITLE
Change Request

### ISSUE THREAD

**Issue by Psycholiquid71** [LatvianModder/FTBUtilities#389]
In looking for a good world pregeneration mod, I keep flip flopping around mods that also include permissions. I understand there are other mods like chunkgen, but for me they are a obscure or not supported well. 

Some require client side mod when mostly all you need are server side mod only for this type of function. With FTBUtils being a good replacement for many of the mods out there and doing it very well, I would like to request Chunk generation (or block) be built into the mod. 

Some of the good options would be to pause when players are online and resume when players leave. Pick up from where it left off if server reboots (With manual or automatic starting on load) be able to limit how many chunks (blocks) could be generated at one time (Less laggy) Be able to center on Spawn, Player, or selected coords.

I appreciate you even reading this and understand if it is a bit out of scope but figured no harm in asking. I like the fact this mod  is well maintained and even with being server / client it is still a very good candidate for this type of function.

**Comment by LordIconMC** [comment]
Same as #123?

**Comment by Psycholiquid71** [comment]
Yeah didn't see it.

**Comment by LatvianModder** [comment]
Yeah forgot about that one, gonna close this one. Though dont get your hopes up as this is something that I don't really want to mess with. Chunk pregeneration has never worked well enough
