### ISSUE TITLE
infinity evolved2.2.2-FTBUtilities-1.7.10-1.0.11.3 bug /admin invsee

### ISSUE THREAD

**Issue by Stekeblad** [LatvianModder/FTBUtilities#39]
I tested the "/admin invsee <playerName>"  command a few minutes ago on my friends server running Infinity Evolved 2.2.2 expert mode and found a problem. The sort inventory buttons from inventory tweeks are present then viewing someone else inventory, out of curiosity I tried sorting my friends inventory resulting in a error disconnected from server and items disappearing from target players inventory. The sorting moved around the items but some of them disappeared.

I think that the sort buttons should not be available then viewing someone's inventory and have a better GUI showing more clearly witch slots are for armor, hotbar and the rest of the inventory. (To support baubles etc. maybe using the normal GUI but the character image is the target player's, and above "Crafting" having the target player name in a big font?? Currently its more like a chest?)

I guess that the Items may have disappeared because they was placed in a slot in the GUI that does not link to a slot in the players inventory or a item is placed in a slot it normally cant be in and because of that disappears.

**Comment by LatvianModder** [comment]
The gui looks like a chest, because as server-only feature it doesn't support client side (it could, but then it would be more pain to make it) and I can't exclude InvTweakers buttons from a chest gui. So lesson learned, don't try to sort other player's inventory :P
