### ISSUE TITLE
Immediate request - 1.10.2 FTBU Please.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LatvianModder/FTBUtilities#395]
I need a way to increase chunk land claim size. This is my only request. It must also work for all players not just ops. Preferably via console because I may adjust the sizes a few times.

**Comment by LatvianModder** [comment]
You cant edit it from console yet, but you can already change max claimable and loadable chunks. Add
"ftbu.claims.max_chunks": 1234 in local/ftbu/ranks.json, inside rank's "config": {} section

**Comment by P3rf3ctXZer0** [comment]
Wait I tried that for hours can you add it to the front page?

**Comment by SubsterNL** [comment]
I am trying to increase the amount of chunks I can load with FTBU on a single player/LAN world but can't seem to do it. It defaults to max 64.

Ranks.json is empty. How would the file look then?

**Comment by P3rf3ctXZer0** [comment]
@LatvianModder maybe you should add those configs to ranks by default so people can just change the amount.

**Comment by LatvianModder** [comment]
I thought about it, but instead there will be a nice gui soon to do that. Adding them there by default would be complicated, especially if I changed something in code etc

**Comment by SubsterNL** [comment]
I simply want to increase the max number of chunks I can load on a SP/Local Lan world but no clue how.

This is on FTB Beyond btw and since no other chunkloaders are included I'm lost.

**Comment by P3rf3ctXZer0** [comment]
@LatvianModder after adding the parameters you recommended whenever I tried to claim chunks I got this [08:05:33] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:33] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:34] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:34] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:34] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:34] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:34] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:34] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:35] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:35] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!
[08:05:35] [Client thread/INFO]: [CHAT] Invalid subcommand 'chunks'!

**Comment by LatvianModder** [comment]
Worry not child, for it is as simple as using this as your local/ftbu/ranks.json file:

```
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 123
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 456
      }
    }
  }
}
```

**Comment by SubsterNL** [comment]
Thank you!
