### ISSUE TITLE
Help - 1.10.2 proper way to set inifnite back I tried the following 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LatvianModder/FTBUtilities#396]
"+ftbu.back.infinite" It does not appear to work @LatvianModder https://gist.github.com/P3rf3ctXZer0/db991d0578472d16368e29ed9cce0358

**Comment by LatvianModder** [comment]
That's odd, that should have worked. I will check

**Comment by LatvianModder** [comment]
Did you enable ranks in config.json? If yes, and its still not working, re-open this issue, because everything else seems fine

**Comment by P3rf3ctXZer0** [comment]
Everything seems to be fine; thank you for you help as always Lat :)
