### ISSUE TITLE
Rank File gets deleted and replace with the default file.

### ISSUE THREAD

**Issue by MindThoth** [LatvianModder/FTBUtilities#397]
Iam trying to limit the chunk loads and claims but the rank file always gets switch back to the default once I start up the server. 
I do have multiple issues tho.
I am trying to create more ranks other then player and op such as member and it doesn't seem to work. (maybe I'm not writing it properly?)
and Iam also having the difficulty of making it so op can change ranks but not player

Thanks for the help!

**Comment by LatvianModder** [comment]
It's probably incorrect syntax. Here's an example of how you can increase max claimable chunks:
https://github.com/LatvianModder/FTBUtilities/issues/395#issuecomment-289493955
If you want to add another rank, just follow "player" example, and instead of "parent": "builtin_player" use "parent": "player" (or any other rank)

**Comment by MindThoth** [comment]
Thanks a lot for the quick reply. Yeah maybe Iam not writing it properly. 
This is what I wrote : 
`{
  "default_ranks": {
    "player": "player",
“member”: "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 1,
        "ftbu.chunkloader.max_chunks": 1
      }
    },

“member”: {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 2,
        "ftbu.chunkloader.max_chunks": 2
      }
    },


    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {
      }
    }
  }
}`

And this is what the server changes it to : 

{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 1,
        "ftbu.chunkloader.max_chunks": 1
      }
    },
    "_member_": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 2,
        "ftbu.chunkloader.max_chunks": 2
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}

**Comment by LatvianModder** [comment]
It's the " before and after your ```member``` What kind of weird text editor you are using, I dont know, but use sublime 3, notepad++ or similar

**Comment by LatvianModder** [comment]
Here's fixed version as bonus:

```
{
	"default_ranks": {
		"player": "player",
		"member": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": [],
			"config": {
				"ftbu.claims.max_chunks": 1,
				"ftbu.chunkloader.max_chunks": 1
			}
		},
		"member": {
			"parent": "builtin_player",
			"permissions": [],
			"config": {
				"ftbu.claims.max_chunks": 2,
				"ftbu.chunkloader.max_chunks": 2
			}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": [],
			"config": {
			}
		}
	}
}
```

Also, pls, next time you post code/file snippets, use ``` not >

**Comment by SavageMe55iah** [comment]
Just copied and pasted what you wrote but it's still being overwritten

**Comment by LatvianModder** [comment]
Didnt notice that there is this lol

```
"default_ranks": {
	"player": "player",
	"member": "player",
	"op": "op"
},

its supposed to be

"default_ranks": {
	"player": "player",
	"op": "op"
},
```

you dont list ranks there. And yeah, whats the problem with the overriden one? It doesnt work?

**Comment by MindThoth** [comment]
Alright! Great it works perfectly with the ranks. Small question tho, how would I set it up so only the op can do the /ranks command. Because right now you can set your own rank regardless your current rank.

**Comment by KaneHart** [comment]
I'm also having this issue. I'm editing my ranks.json and no matter what I do it does not work. If I place the example one it gets defaulted if I add a new group it gets defaulted and yes my comma is right and if I in the Op display name before $name add hello it also resets it. I also taken someone else config they said it works and it resets it..

FTBUtilities-1.10.2-3.4.3.jar

Sadly I don't have control over the version using a pack.

**Comment by KaneHart** [comment]
Tested latest version still having an issue.
```
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {}
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}
```

If I removed 
```
"syntax": "<&2$name&r> ",
```

so it looks like:
```
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {}
    },
    "op": {
      "parent": "builtin_op",
      "permissions": [],
      "config": {}
    }
  }
}
```

It will reset the file. This thing is driving me insane lol.

**Comment by KaneHart** [comment]
I love spamming 👾 

Anyways I deleted the local folder and it is all working now...

👍

**Comment by LatvianModder** [comment]
Maybe you just handnt enabled the ranks in config, thats why
