### ISSUE TITLE
Chunk loading doesn't work properly on server

### ISSUE THREAD

**Issue by kofteistkofte** [LatvianModder/FTBUtilities#398]
Hi, I'm the admin of a FTB Beyond 1.2.1 server with about 10 people at the same time.
The issue I'm having is chunk loading mechanic acts really strange. Basic example is whenever I go away or go to another dimention, my mana mirror doesn't get refill, my opencomputers robots sometimes got crashs and a lot of players are also having issues with their machines too.  But this is not something happens everytime, which makes it not reliable. I tested the same thing with chunk loading ward and it works properly.

**Comment by ktole1999** [comment]
is this the only chunkloader available in the pack? some features are still being worked on. check open and closed issues.

**Comment by bound4doom** [comment]
See issue 360, this is a duplicate issue being worked on
