### ISSUE TITLE
Crash on TAB on command

### ISSUE THREAD

**Issue by frenchiveruti** [LatvianModder/FTBUtilities#40]
I was writing "/reload_client" and in the "/reload_c" I pressed TAB for autocomplete, and it crashed.  
Here's the log:  
[fml-client-latest.txt](https://github.com/LatvianModder/FTBUtilities/files/110689/fml-client-latest.txt)
And the crash report:
[crash-2016-01-30_02.58.31-client.txt](https://github.com/LatvianModder/FTBUtilities/files/110688/crash-2016-01-30_02.58.31-client.txt)
Hope it helps.

**Comment by LatvianModder** [comment]
Yeah, this was fixed a long time ago, but hasn't yet made into Infinity modpack

**Comment by frenchiveruti** [comment]
Damn it, I hate when I post an error that has already been fixed :(


Enviado desde Android






On Sat, Jan 30, 2016 at 5:53 AM -0800, "Latvian Modder" <notifications@github.com> wrote:





Closed #40.

---
Reply to this email directly or view it on GitHub:
https://github.com/LatvianModder/FTBUtilities/issues/40#event-532425213
