### ISSUE TITLE
Server Crash On Player Logout

### ISSUE THREAD

**Issue by dannydjdk** [LatvianModder/FTBUtilities#400]
We receive the following crash periodically when players who have loaded chunks with FTBU log out:
https://pastebin.com/wKunYpSd

This may or may not be related to #390 which occurs when a player logs in.

We are running FTB Beyond 1.2.1 which has FTBU 3.4.3. Our ranks.json is set up to unload a player's loaded chunks on logout (https://pastebin.com/1MFeEXj7).

**Comment by LatvianModder** [comment]
Should be fixed in 3.5.0, wait for pack to update I guess (or update yourself)

**Comment by dannydjdk** [comment]
I'm confused. Was this fixed just by disabling the ability to configure offline chunkloading? No matter how I set up the ranks file, all chunks are loaded all the time, so I've had to disable chunk loading entirely. Am I doing something wrong?

**Comment by LatvianModder** [comment]
Yes, I removed the offline chunkloader timer, but I added a new permission - "ftbu.chunkloader.load_offline"

**Comment by dannydjdk** [comment]
Thanks for the response. I did see the changelog and tried the ftbu.chunkloader.load_offline permission, but it did not seem to change anything. I assumed the syntax would be to add "-ftbu.chunkloader.load_offline" to the permissions list. But, after adding that and rebooting, all chunks remained loaded. In a moment of desperation, I even tried using ftbu.chunkloader.load_offline as a rank and setting it to false. Of course, that didn't work either.

Hmm... does this require "override_commands" to be enabled? We have it disabled because we are using ThutPerms to manage permissions.

**Comment by LatvianModder** [comment]
It doesnt require command overrides to be enabled, but it does require FTBU ranks to be enabled

**Comment by dannydjdk** [comment]
I did had ranks enabled.
Here's my config.json: https://pastebin.com/eDcij17S
Here's my ranks.json: https://pastebin.com/s64KqMcK
We're using Chicken Chunks right now, so there's no urgency for us, but if there's any info I can provide to help track down a potential bug, let me know.
