### ISSUE TITLE
Journeymap intergration casuing issues

### ISSUE THREAD

**Issue by scalda** [LatvianModder/FTBUtilities#402]
Hey,

I have updated to your latest version this morning, updated my server with the same files and I can now not connect, please see the below pastebin so see the error I am getting from the disconnect

[pastebin](https://pastebin.com/mH4pERUG)

Regards
scalda

**Comment by KaneHart** [comment]
Jmap integrations needs a toggle. Massive areas since he removed spawn protection and people can claim it..... Don't ask for that story anyways setting it up with a alt character in a big area causes me to drop about 6x my fps.

**Comment by LatvianModder** [comment]
There *is* a toggle

**Comment by KaneHart** [comment]
Any chance we can get more info on the toggle, Thanks. My spawn is killing everyone lol.

**Comment by LatvianModder** [comment]
![image](http://ss.latmod.com/pc/2017-04-04_12.06.29.png)

**Comment by KaneHart** [comment]
Ahh Thank you I keep forgetting the darn client settings like that lol.

**Comment by LatvianModder** [comment]
Fixed in 3.5.0
