### ISSUE TITLE
Crash With Tinker Construct

### ISSUE THREAD

**Issue by bookerthegeek** [LatvianModder/FTBUtilities#405]
## Heyo!
Sadly I am having a crash ([Report Here][1]) after I disabled the Tinkers Tools from the Tinkers Config.
Here is the [Mod List][2].
### Versions
- TConstruct-1.10.2-2.6.3
- FTBUtilities-1.10.2-3.3.0
- FTBLib-1.10.2-3.4.5
- Minecraft 1.10.2
#
Let me know if you need any other information. 

[1]:https://gist.github.com/bookerthegeek/6d5693a8c7435afab5272b6675df840d
[2]:https://gist.github.com/bookerthegeek/35867ab207f2119ae89a85c008ff9c3d

**Comment by LatvianModder** [comment]
Fixed in 3.5.0
