### ISSUE TITLE
[1.10.2] No items spawning when user is not whitelisted and tries to join and then joins again later when whitelisted. 

### ISSUE THREAD

**Issue by KaneHart** [LatvianModder/FTBUtilities#407]
So this is a pretty annoying one that has been happening even since 1.7.10.

When a none whitelisted player joins I guess FTBU sees that player. Once we whitelist them and they try to join again sadly they don't spawn with any of the starting items that FTBU spawns.

**Comment by LatvianModder** [comment]
Hmm. Not sure how to fix this, blame Forge for firing login event before checking if the player is allowed to join. Might have to open Forge issue

**Comment by KaneHart** [comment]
Is this something I should do or you can do? You might know a bit more then I do though I do know sort of how the events work. That being said how are other mods firing this event correctly? The ones that spam you with 100 books and such. Might be recommended check their source out to get an idea. 

This one works for sure:
https://github.com/PenguinSquad/Enchiridion

**Comment by LatvianModder** [comment]
*Probably* fixed in 1.12
