### ISSUE TITLE
[Question] Does FTBUtilities have a restore backup command/function?

### ISSUE THREAD

**Issue by GazbonicAcid** [LatvianModder/FTBUtilities#408]
Does FTBUtilities have a restore backup command/function?
I need to roll-back the server because I'm getting a client-crash due to some no such method error on Thermal Expansion augments.
However I'm only asking you about restoring FTBU backups via command.

**Comment by LatvianModder** [comment]
Nope, and there can't be a command, because you can't delete/replace an active world
