### ISSUE TITLE
Server Guide Book

### ISSUE THREAD

**Issue by LordIconMC** [LatvianModder/FTBUtilities#409]
Ok i have read through all the other issues for creating a guide book on server but can't seem to find the resolution. 

I have created a /local/guide folder. (which was not auto created)
placed in a simple .txt file 
`§1§lWelcome!`
/reloaded (Even restarted server)
No update on Guides or Server Info gui

Are there other steps?

**Comment by LatvianModder** [comment]
It's not implemented yet, but will be in next commit

**Comment by LordIconMC** [comment]
Thank you. Once 1.10.2 items are added i can try and help with the wiki if needed. Since i need to learn it for my servers.

**Comment by jlbrewer** [comment]
Is this different from putting a guide in the FTB Utils menu?

I'm having trouble getting mine to show up for the pack I'm making. I'm using json files in ResourceLoader and following the example in SkyFactory as well as the existing doc.

**Comment by LatvianModder** [comment]
It should already work in resources/ folder, maybe your syntax is wrong or smth. There's some outdated information on bottom, but top side should be the same: http://guides.latmod.com/

**Comment by jlbrewer** [comment]
I've followed that. Where should I go for additional help, since it's not related to this issue?

**Comment by LatvianModder** [comment]
That's fine, you can just ask here, doesn't really matter to me. Or on IRC espernet #LatMod or #FTB channels

**Comment by jlbrewer** [comment]
I got it working after I ran my files through a JSON validator (though I can't prove that's what fixed it). The only other question I have is that my apostrophies (') are all rendering as unknown character/question marks.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBGuides/issues/4
