### ISSUE TITLE
The chunk claiming map is all white in dimensions with ceiling

### ISSUE THREAD

**Issue by PapiDimmi** [LatvianModder/FTBUtilities#410]
In other dimensions (I’ve tried the Nether [from vanilla Minecraft] and the Deep Dark [from Extra Utilities 2]), and the map looks like this:

![2017-04-07_17 17 35](https://cloud.githubusercontent.com/assets/25916106/24806784/41c710a4-1bb6-11e7-8853-2afd4acefb67.png)

It looks fine in the overworld, however.

**Comment by LatvianModder** [comment]
It's not other dimensions, its all dimensions that have ceiling

**Comment by PapiDimmi** [comment]
Why, though?

**Comment by ktole1999** [comment]
just the way it is. why does the whole map go dark when you walk under the shade of a floating island. thats just the way it is. move along there is nothing to see here :)

**Comment by LatvianModder** [comment]
Fixed for nether. Might have to add non-local config for other dimensions

**Comment by PapiDimmi** [comment]
Neat!

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/528
