### ISSUE TITLE
Logging - 1.10.2 Sponge Notices

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LatvianModder/FTBUtilities#413]
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'minetweakerrecipemaker'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'mtrm'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'pokeadv'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friendlist'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_seefriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_viewfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_listfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_list'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'ashelp'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'as?'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_removefriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_deletefriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_unfriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_defriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'biomesoplenty'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'bop'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'biomesop'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'railcraft'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'rc'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'rail'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friendlist'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friendlist'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_seefriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_seefriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_viewfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_viewfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_listfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_listfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_list'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_list'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'forestry'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'for'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'morpheus'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'sleepvote'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_addfriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_befriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'baubles'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'baub'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'bau'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_addfriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_addfriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_befriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_befriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'minecolonies'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'mc'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'col'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'mcol'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'mcolonies'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'minecol'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'minecolonies'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'structpro'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'structpro'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'spro'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friendlist'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friendlist'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_friendlist'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_seefriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_seefriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_seefriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_viewfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_viewfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_viewfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_listfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_listfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_listfriends'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_list'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_list'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_list'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'help'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias '?'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_removefriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_removefriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_deletefriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_deletefriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_unfriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_unfriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_defriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tmg_defriend'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'tell'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'w'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'msg'. This is probably indicative of a bug.
08.04 20:38:07 [Server] Server thread/WARN [Sponge]: The mod ftbu has registered multiple commands for the alias 'minecolonies'. This is probably indicative of a bug.

**Comment by P3rf3ctXZer0** [comment]
Any thoughts @LatvianModder ?

**Comment by LatvianModder** [comment]
If it doesn't crash, its fine. If you are using some sponge permission mod, you can disable ftbu command overrides & ranks in local/ftbu/config.json
