### ISSUE TITLE
Add command to remove or edit other teams

### ISSUE THREAD

**Issue by SourcePowered** [LatvianModder/FTBUtilities#414]
Recently, some players have created some very offensive team names, such as: "My Super FU-KING Team", "Let's go to Make Some Sh-t" or "Fu-k you and Fu-k me - Fu-k EVERYONE Team".

I have no any idea about this and I want to know, how to disabled or prevent users creating team?

**Comment by LatvianModder** [comment]
Only way to prevent users from creating a team now is add "-command.team", "-command.ftb.team" permssions in "player" rank, local/ftbu/ranks.json file. Also enable ranks, and see if that fixes the problem (ops will still be able to create teams). But I will add a command for admins to delete teams, change other team configs etc

**Comment by LatvianModder** [comment]
Also just a general config option to

+ Leave team creation enabled
+ Disable team creation completely
+ Auto-create teams, but don't allow players to edit teams

**Comment by SourcePowered** [comment]
Yes, sir, need a config option like "disabled_team = true" ... Let's do it!

**Comment by MastefChief** [comment]
just curious any updates on this

**Comment by LatvianModder** [comment]
I added it to a paper sticky note earlier today, so that's a start
[!image](http://i.imgur.com/ehcCLyk.jpg?1)

**Comment by Autopoietico** [comment]
Can be cool that can edit the teams not only via a GUI, but also via commands from the console.
This can be useful to automatize certain things
