### ISSUE TITLE
FTB Beyond problems in singleplayer world with team

### ISSUE THREAD

**Issue by BpEcsta** [LatvianModder/FTBUtilities#415]
I play in singleplayer world and wanted to make a team only just for chunkloading, so i made team, claimed chunks, everything was working. And next day i joined my world and i was kicked from the team and i cant rejoin it, and now i have no premision to my items and ect. 

And when i press join team it writes "Invalid subcommand 'request_invite'!" 

Sorry for bad english

**Comment by LatvianModder** [comment]
Hmm maybe you joined in offline mode, when you had different UUID

**Comment by BpEcsta** [comment]
So what can i do to delete this team?

**Comment by LatvianModder** [comment]
If the team really was created in offline mode, you could try to log in in offline mode, a.k.a with internet turned off, then join the world, set free_to_join config option to true, and then join the team in online mode

**Comment by BpEcsta** [comment]
U see what is the problem that i am not a member of that team so i cant change that config 

http://prnt.sc/eusjdg

**Comment by LatvianModder** [comment]
I can't [find your username](https://mcuuid.net/?q=BpEcsta). If you haven't paid for the game, I ain't supporting that

**Comment by BpEcsta** [comment]
oh... so you cant help me ?

**Comment by LatvianModder** [comment]
If you haven't paid for the game, no, because then it's not my problem that your UUID is breaking

**Comment by BpEcsta** [comment]
izi, solved problem by my self, learn how to code you potato latvian fuck 


Hitler did nothing wrong

**Comment by LatvianModder** [comment]
Single best comment I have read on this issue tracker
