### ISSUE TITLE
Giving claim with command

### ISSUE THREAD

**Issue by MindThoth** [LatvianModder/FTBUtilities#419]
Is there a way to give a chunk claim and a chunk load with commands? Like giving out bonus claim and loaded chunks to members in game without restarting the server.

**Comment by LatvianModder** [comment]
Nope, there's no command like that

**Comment by MindThoth** [comment]
So what are the alternatives?

**Comment by LatvianModder** [comment]
You can claim and unclaim with /chunks command, but you can't add extra chunks to your limit with commands
