### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by vsilvar** [LatvianModder/FTBUtilities#42]
Just got this crash on the server, after some chat spam about unloading chunks for being offline for too long.

http://pastebin.com/4LhNbmhW

FTB Utilities: 1.0.16
FTB Lib: 1.0.16

**Comment by LatvianModder** [comment]
This happened some time after you logged out or while you were online? Because easy fix would be disabling the offline chunkloader timer (setting to 0)

**Comment by vsilvar** [comment]
Yes, it happened after the unload time.
I have already disabled that timer, I just reported it to let you know :)

**Comment by LatvianModder** [comment]
Ok, thanks

**Comment by LatvianModder** [comment]
Could be fixed in 1.0.17+, but in case it still happens, re-open this issue
