### ISSUE TITLE
Ranks Permissions Broken - Players Cannot Access /FTB

### ISSUE THREAD

**Issue by aelfwyne** [LatvianModder/FTBUtilities#420]
I have scoured the internet for a solution.

I upgraded FTBU to FTBUtilities-1.1x-3.5.4 with minecraft 1.10.2.

When I logged into my own (OP) account, it prompted me to join a team, which I did and reclaimed my chunks.

However, I have a player that when he logs in it gives him the same message. When he clicks that message, it denies him access to TeamsGUI completely with the error "You do not have access to /ftb". 

I have tried everything I can find to get access. Tried multiple different versions of ranks.json. Have stared at it. Have searched the net again. Have read (non existent) documentation. I deleted the player's profile and started fresh. I even opped the player, and there's still no access to /FTB for that player.

Before upgrading, the same player was able to claim chunks without issue.

At this point, either there's no instructions on how to do it, or it's a bug.

**Comment by aelfwyne** [comment]
Note: I downgraded to the version I was using before, prior to TeamsGUI.

Turns out that players never had access to /FTB. The problem occured when the chunk claimer became part of TeamsGUI. Before, they could open the Chunk Claimer and it didn't check for access to /FTB. With TeamsGui, though, it DOES check for access to /FTB.

The problem remains, how the hell do I give /FTB to players so they can open TeamsGUI?

**Comment by aelfwyne** [comment]
As a workaround I've had to disable Ranks completely and use ThutPerms.

**Comment by LatvianModder** [comment]
Most likely your problem is that you are using ThutPerms <.<

**Comment by aelfwyne** [comment]
ThutPerms works. That's something FTBU can't.

Seriously, I am only using ThutPerms because FTBU was disabling access to essential commands, and no amount of fiddling with the ranks files got it working. Lack of documentation? Possibly at fault.

Either way, ThutPerms works and FTBU Ranks didn't. Plain and simple. Sorry if you as a dev don't want to hear that.

**Comment by ktole1999** [comment]
what other server mods are you using?

**Comment by LatvianModder** [comment]
Yeah, it works just fine, it's lack of documentation, which will be fixed in next release [as you can see on bottom of this page](https://github.com/LatvianModder/FTBUtilities/commit/52c58c2d67e46fee5804cf34820ce14aee85fcfe)
