### ISSUE TITLE
[1.11.2] Crash when loading a new world

### ISSUE THREAD

**Issue by starg09** [LatvianModder/FTBUtilities#421]
So this just happened, when creating a new world.

* Forge: 2282
* FTBLib: 3.5.4
* FTBUtilities: 3.5.4

[the log with what happened](https://gist.github.com/starg09/6acce65d82cb932372e28d27126393a4), there's an error at the end mentioning FTBU. Screen hangs at "Building terrain" message.

**Comment by LatvianModder** [comment]
There isnt anything about FTBU, unless you mean
[20:42:24] [Client thread/INFO] [journeymap/journeymap]: Found @journeymap.client.api.ClientPlugin: com.feed_the_beast.ftbu.integration.JourneyMapIntegration
which is unrelated

**Comment by starg09** [comment]
Oh, wait log is incomplete? :thinking:

Give me a minute, once my computer is on I'll try to reupload it, if i can
find it again!

**Comment by starg09** [comment]
Ok, maybe I got confused and thought it didn't split as a crash report, for some reason... Sorry bout that! 😅 

[Here's the correct report](https://gist.github.com/starg09/abe68b545f007869b8dc02023b91fe9d)

**Quick Edit:** Yeah, it was on the full log, but that one had 50k lines so gist must have cut it. [Here's full log on another host](http://paste.feed-the-beast.com/view/3d94d50f)

**Comment by LatvianModder** [comment]
Ok, weird, try deleting backups.json from /backups folder
