### ISSUE TITLE
I add FTB Ultilities to my mods folder, and the server won't start?

### ISSUE THREAD

**Issue by KelphyKO** [LatvianModder/FTBUtilities#422]
I add FTB Ultilities to my mods folder, and the server won't start? I have add FTBlib and that works fine, but soon as I add Utilities, it crashes. Could someone explain? Sorry I'm new to understanding.

**Comment by LatvianModder** [comment]
Crash Report

**Comment by LatvianModder** [comment]
No crash report, no issue.
