### ISSUE TITLE
Claiming chunks for shops

### ISSUE THREAD

**Issue by clicknick64** [LatvianModder/FTBUtilities#423]
I run a survival modded server and I want to dedicate some chunks for shops so everyone can build in them. I have my own team so I cannot claim these chunks for myself and set them to public because I have my private chunks elsewhere. So in that area, I want a banner to appear in the top-right saying Shops instead of Wilderness. Is that possible?

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/88
