### ISSUE TITLE
FTBUniverseData NBT NPE

### ISSUE THREAD

**Issue by everseeking** [LatvianModder/FTBUtilities#425]
Sorry if this belongs in FTB Lib, but the NPE appears to be with FTBU. Noticed the following in the server logs during startup (no crashes or anything, just a log message you might want to know about):

> [Server thread/INFO] [STDERR/ftbl]: [com.feed_the_beast.ftbl.api_impl.Universe:load:187]: java.lang.NullPointerException
> [Server thread/INFO] [STDERR/ftbl]: [com.feed_the_beast.ftbl.api_impl.Universe:load:187]: 	at com.feed_the_beast.ftbu.world.FTBUUniverseData.deserializeNBT(FTBUUniverseData.java:411)

Full [snippet from FML Log](https://gist.github.com/everseeking/8dd1b3000eae54b36a6b89ec7c80aff5)

* [FTBL exception line](https://github.com/LatvianModder/FTBLib/blob/1.9/src/main/java/com/feed_the_beast/ftbl/api_impl/Universe.java#L187)
* [FTBU Universe NPE line](https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/java/com/feed_the_beast/ftbu/world/FTBUUniverseData.java#L411)

Details
* FTB Beyond 1.5.3
* `FTBLib-1.1x-3.5.4`
* `FTBUtilities-1.1x-3.5.4`
* World and player files existed before your recent change with chunk data storage location
* No issues in-game noticed thus far

**Comment by LatvianModder** [comment]
Should be fixed
