### ISSUE TITLE
[question] How can I stop chunk loading on a server?

### ISSUE THREAD

**Issue by Saereth** [LatvianModder/FTBUtilities#426]
setting chunkload off in the config.json just seems to stop people from being able to mark chunks to load, chunks that were currently marked to load still load. Is there anyway to stop all chunk loading and or/forcibly remove loading for all teams besides manually goign through every team one by one with the /ftb chunks unload_all command?

something like a /ftb chunks unload_all all or something?

**Comment by LatvianModder** [comment]
You can disable chunk loading in config, under 'world' section. Either by /edit_config ftbu or in local/ftbu/config.json file
