### ISSUE TITLE
Backups only start on player login

### ISSUE THREAD

**Issue by frenchiveruti** [LatvianModder/FTBUtilities#43]
Well, I have set up a world backup to 0.5h, and the backups only take place when I "log in" to my world, but **NEVER** when I'm playing on it.  
Is that intended? What's the purpose of that?  
Also, it would be nicer if we could set the backups in minutes instead of hours, or both.

**Comment by frenchiveruti** [comment]
This might be also a thing of *.14

**Comment by LatvianModder** [comment]
Yeah, this should be fixed in .17, that will be out soon

**Comment by frenchiveruti** [comment]
Great! Thanks m8, great m0d u kno

**Comment by LatvianModder** [comment]
Fixed in v1.0.17+
