### ISSUE TITLE
[1.10.2] Explosions not disabled 

### ISSUE THREAD

**Issue by ShakinBabyBacon** [LatvianModder/FTBUtilities#430]
Hosting FTB Beyond 5.3 - Minecraft 1.10.2 - FTBU 1.1x-3.5.4

The Gui for claiming chunks does say "explosions disabled", but creepers and TNT still damage claimed chunks. Am i missing something? i have searched in game, the config files and scoured the internet and have not found anything about this. 

I would really rather get this corrected than have to use a claim plugin. Anyone know whats going on?

**Comment by LatvianModder** [comment]
Damage, as in, break blocks?

**Comment by ShakinBabyBacon** [comment]
yes, sorry should have been more specific.

**Comment by LatvianModder** [comment]
And you have set ```/ftb team config ftbu.explosions false```?

**Comment by ShakinBabyBacon** [comment]
i hadn't but i just tried it it replied back "enable explosions in claim chunks set to false" set off some TNT in my claim and still breaking blocks.

**Comment by ShakinBabyBacon** [comment]
i tried toggling it to true and then back to false, blocks are still breaking from explosions inside of a claimed chunk

**Comment by stevojhall** [comment]
have you tried spawning a creeper and letting that explode command set to false as tnt set off by a member of your team may override the command

**Comment by LatvianModder** [comment]
Yeah, I can't reproduce this in any way works fine for me. Maybe you removed permission for that chunk upgrade

**Comment by Frostydeeps** [comment]
I am also having this same issue, my area is protected when i mouse over claim on map it says explosions disabled also i put in the /ftb team config ftbu.explosions false but creepers are still able to blow holes in land

**Comment by LatvianModder** [comment]
I see ClearLag there. If that is a plugin server, Im not supporting it
