### ISSUE TITLE
FTB Utilities Crashes Server (Sometimes) when users log out and right back in.

### ISSUE THREAD

**Issue by eobie** [LatvianModder/FTBUtilities#431]
It appears that FTB Utilities is trying to load chunks that are already loaded... Happens in latest release of beyond.. 1.5.3.
[crash-2017-04-25_11.55.20-server.txt](http://ss.latmod.com/pc/2017-04-27_17.58.18.txt)

**Comment by LatvianModder** [comment]
3.6.0 should fix it

**Comment by eobie** [comment]
Does this require any updates client-side or is it ok to update server-side only?

**Comment by LatvianModder** [comment]
I think it requires client update
