### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by ElectricBlue1** [LatvianModder/FTBUtilities#432]
I know this isn't an issue but this is he only place I am able to ask this. How can I edit the amount of claiming chunks or the homes and the other things?

**Comment by eobie** [comment]
ranks.json file. See my example

`{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [
        "-ftbu.chunkloader.load_offline"
      ],
      "config": {
        "ftbu.chunkloader.max_chunks": 35,
        "ftbu.homes.max": 10,
        "ftbu.claims.max_chunks": 200
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [
        "+ftbu.chunkloader.load_offline"
      ],
      "config": {
        "ftbu.chunkloader.max_chunks": 200,
        "ftbu.claims.max_chunks": 1000
      }
    },
    "donor": {
      "parent": "builtin_player",
      "syntax": "<&6$name&r> ",
      "permissions": [
        "-ftbu.chunkloader.load_offline"
      ],
      "config": {
        "ftbu.chunkloader.max_chunks": 64,
        "ftbu.homes.max": 50,
        "ftbu.claims.max_chunks": 400
      }
    }
  }
}`

**Comment by ElectricBlue1** [comment]
Ahh thanks
