### ISSUE TITLE
/inv: "you do not have permission to use this command"

### ISSUE THREAD

**Issue by macks2008** [LatvianModder/FTBUtilities#433]
first of all, I'm running [SpongeForge](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2) and [luckperms](https://forums.spongepowered.org/t/luckperms-an-advanced-permissions-plugin/14274), so that complicates things considerably... but a server of the scale I'm planning on running requires plugins, so it's necessary.
Anyway, moving on, I've tried giving myself the permission node ftbl.command.inv, synchronized permissions, even reloaded the server, but it won't let me use the command. This is the only permission I have trouble with. All the others at least take effect after a server reload if nothing else, but this doesn't work at all
I also tried running the command from the server console. I don't have permission trouble there, but instead I run into #411 ... But that's another matter...

**Comment by ShakinBabyBacon** [comment]
I'm using nucleus to override most of the ftbu commands as well as add many more. Might be a solution.

**Comment by LatvianModder** [comment]
If you only need command permissions, why not use [FTBU](https://gist.github.com/LatvianModder/54ccaee3af7a55d23831eac20f248a3f)

**Comment by Mystyfy** [comment]
A quick piggy back onto this topic even though closed - just looking for clarity on how to give permissions from other mods using FTBU as I can't get it to work.  For non op players I can get all +ftbu.claims permissions to work as they are part of how FTBU works - no problems there.  What I cannot do for the life of me is get a command from another mod to work for non op players.

Example: I run a pixelmon server and want my players to be able to check there pokemon IVs and EVs.  The default node for that is pixelmon.command.ivs and pixelmon.command.evs.  How does FTBU handle these command permissions?  I have tried every iteration and rewrite of those commands in the ranks.json file trying to allow players a basic command outside the default ones that FTBU has built-in support for.

Attempted: "+ftbu.command.ivs", "+ftb.command.ivs", "+pixelmon.command.ivs", "+command.ivs", "+ivs", etc etc...I've gone through many more but can't seem to figure out how the command override feature allows commands from other mods to be ran.

A quick example would be appreciated.  Trying to keep the server setup and mods necessary to a minimum and would like to keep FTBU as my only permission and claims mod.  Thanks!!

**Comment by LatvianModder** [comment]
All commands are "+command.x" to run /x
