### ISSUE TITLE
Permission "ftbu.back.infinite" not having any effect.

### ISSUE THREAD

**Issue by AeonLucid** [LatvianModder/FTBUtilities#434]
Hi,

I want to allow all my players to use `/back` infinitely. Using `FTBUtilities-1.1x-3.5.4.jar`.

```json
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "syntax": "[Player] $name: ",
      "permissions": [
        "+ftbu.back.infinite"
      ],
      "config": {
        "ftbu.homes.max": 100
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}
```

Why doesn't this work?

(I am using the FTB Beyond pack without modifications)

**Comment by LatvianModder** [comment]
Have you enabled ranks and command overrides in config.json?

**Comment by LatvianModder** [comment]
Welp, no answer. Re-open if you are on latest version and have enabled command overrides/ranks

**Comment by AeonLucid** [comment]
@LatvianModder Sorry, I forgot to reply. The issue magically fixed itself after a bit. 😅 

Would be great if the `/back` command worked like the one in Bukkit Essentials though. (With a possible toggle)
