### ISSUE TITLE
1.10.2 Chunkloading in other Dimensions not working

### ISSUE THREAD

**Issue by Camrais** [LatvianModder/FTBUtilities#435]
Hi,

since i cant find anything about it anywhere, i thought i hand in this issue post.

I have the following problem: I play on

Direwolf20 1.10.2 Version 1.8.0 (set myself a server up for that im op there)

with

FTB Utilities Version 3.4.3 
FTB Lib 3.4.4

I added some mods on my own but the one that im having problems with is Aroma Mining World. I used the rank system to allow myself to load a slightly larger ammount than 64 chunks, namely im allowed now to load 200 chunks, of which im using 153 (I made a huge solar farm in the aroma world because it never gets dark there by config). I added myself a team and claimed all the chunks and also chunkloaded them. When im still online it seems to work fine but when im offline for a longer time (was 8 hours now) it seems to simply unload the chunks, although i set

`"ftbu.chunkloader.offline_timer": -1`

in the ranks.json. 
I already tried updating to the newest version i found (FTB Utilities 3.5.4 and FTB Lib 3.5.4) but the problem still persisted. I then reverted back to the older versions because it seems that the offline_timer option mentioned above isn't available in the newer versions (at least it always erased it out of the ranks.json when i loaded it (sadly there is little to no documentation or guide to those points, at least on what a 5 hour google search gave me)). The weird thing is that chunkloading in the mining world worked just fine with the old version before i enabled ranks to get more chunks loaded. The chunks would stay loaded even if i wasnt online for 2 days or more.

Here a screenshot in the Overworld where it says that all 153 chunks are loaded. 

![2017-04-28_10 58 25](https://cloud.githubusercontent.com/assets/26597656/25521951/bf012d88-2c01-11e7-9931-e8dac6a6e29a.png)

Here the network for my power where you can see that no power is coming from the chunkloaded solar cells (transfer = 0)

![2017-04-28_11 00 44](https://cloud.githubusercontent.com/assets/26597656/25522078/1b8c580c-2c02-11e7-9ee1-e2574bf62573.png)

and a screen where you can see that the Solar cells aren't listed in the network (there should be green list points with the solar arrays)

![2017-04-28_11 00 49](https://cloud.githubusercontent.com/assets/26597656/25522180/4136f95e-2c02-11e7-9ce3-70d3f48abf3e.png)

It looks like this when i went into the mining world for really one sec so it would load the chunks:

![2017-04-28_11 16 23](https://cloud.githubusercontent.com/assets/26597656/25522721/3b8dc026-2c04-11e7-8d4a-e854e5cc4163.png)

(there arent all solar arrays in this network the rest of them is in a sperate network)

And here a screen of only a few chunks i loaded in the aroma world:

![2017-04-28_11 19 01](https://cloud.githubusercontent.com/assets/26597656/25522806/9152c42a-2c04-11e7-8dc7-b7eb0e9431a0.png)

Hope you can help me out there.

Greetz
Camrais

EDIT: After i was a while now afk in my world (a little more than a hour) it unloaded most of the chunks again. I only have one solar array left which is loaded the rest is unloaded. Screenshot:

![2017-04-28_12 21 33](https://cloud.githubusercontent.com/assets/26597656/25525091/7a8b78d2-2c0d-11e7-8c37-ddba1589d75a.png)

**Comment by NocturnalScream** [comment]
Can Confirm, i have the same Bug. The server is about 2 weeks old, the problems started yesterday randomly. Chunkloading worked fine till now, but now it stops working. It does seem weird though: energy is still being transmittednover rfnetworks to my builder block, but items are not getting pushed out of the builders block into the ender chest. The energy though is coming through with 0 problem since the energy storage in the quarry builds up to full 10 MRF. Same strange things with my base. when i load into the server, i now see that my big AE2 system is getting reset and has to sart new which takes a while. Allthough all the items from the quantum quarries which were chunkloaded are there too. Strangely i build up huge amounts of cobblestone since my crafter Tier 3 (dunno which mod this is) is not compressing my cobblestone which is going into the me system. it works fine when im back in the server, but the chunkloading fails completly now

**Comment by LatvianModder** [comment]
Hmmp, those are some old FTBU/Lib versions. I guess you wait until pack updates and then see what happens

**Comment by Camrais** [comment]
> I already tried updating to the newest version i found (FTB Utilities 3.5.4 and FTB Lib 3.5.4) but the problem still persisted. I then reverted back to the older versions because it seems that the offline_timer option mentioned above isn't available in the newer versions <

I already manually updated the FTB Lib and Utilities. It didn't help.

**Comment by LatvianModder** [comment]
Currently on curse latest are 1.1x-3.6.3. The 1.10.2 part is now 1.1x, because it works for both 1.10 and 1.11

**Comment by Camrais** [comment]
Hi,

i just updated to 1.1.x-3.6.3 on both FTB Utilities and FTB Lib.

Problem still persists.

A workaround seems to be to use a real chunkloader (e.g. from Extra Utilities) and just place it into the armoma dimension. Then the Chunkloading from FTB Utilities work there aswell.


Greetz Camrais.

**Comment by LatvianModder** [comment]
Chunkloading works for me on a server that isn't mine and is 'vanilla' FTB Unstable 1.12 pack. Closing this because _it works for me_

**Comment by EZKatnipz** [comment]
well, isnt that a completely different minecraft version from what the OP was using?

and are you using Sponge on the server?

**Comment by Camrais** [comment]
Yes it is a different MC version. On MC 1.10.2 and on a private Modpack it has the exact same bug, it doesnt load chunks in Aroma Mining World. Other Chunkloaders like e.g. extra utilities do work. But w.e. i just wont chunkload anything with ftb utilities over there... Using the most recent versions for 1.10.2 (1.1x-3.6.5)
But as i said since i dont use it for it anymore i just dont mind anymore.

**Comment by Siman1990** [comment]
Still a problem to this day... when will this be fixed? some mod packs only use this to keep chunks loaded... this is extremely annoying

**Comment by ktole1999** [comment]
i think the reason it was closed is that it works on vanilla with latest mc version. although i could be wrong.
