### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by ElectricBlue1** [LatvianModder/FTBUtilities#436]
I'm using FTBUtilities with JustEnoughButtons, and the buttons overlap. How can i move the buttons for FTButils, I've seen this in other packs? Is there a config change i can do?

**Comment by ktole1999** [comment]
i dont recall seeing a way to move the ftbu gui. can you move the JEB gui?

**Comment by ElectricBlue1** [comment]
FTB modpacks has their buttons on the left side of the inventory and so does foolcraft, i don't know if i can move it somewhere else, but i can move JEB buttons, i think.

**Comment by LatvianModder** [comment]
There's an option in Client Config to move the buttons to side of inventory

**Comment by ElectricBlue1** [comment]
I've looked in the local/ftbu config but found nothing. Is it the one in game or somewhere else?

**Comment by LatvianModder** [comment]
Gray gear in your inventory
