### ISSUE TITLE
[1.10.2] - Spawn Claim Area?

### ISSUE THREAD

**Issue by RobUnplanned** [LatvianModder/FTBUtilities#437]
I'm sorry if this has been asked before, Ever since updating to 1.10.2 packs, I've set up a safe spawn area in the configs. But the "spawn" claimed area doesn't show anymore? and any players can change or destroy blocks within the spawn area. I've found myself having to claim the area's for myself, but would rather the spawn claim area to come back? or where can I edit the configs to show spawn area claim, rather than my name. I only ask because running a twitch subscription server, I need to protect spawn to keep it functioning and not have people trying to be "funny" and breaking spawn.

**Comment by IdrisDose** [comment]
#88
