### ISSUE TITLE
[FTBU/L 3.6] Updating to 3.6.x breaks FTBTweaks packmodes

### ISSUE THREAD

**Issue by thephoenixlodge** [LatvianModder/FTBUtilities#438]
As per the title, since updating to 3.6.x, scripts in the relevant folders for packmodes are no longer being loaded and taking effect. The packmode commands still seem to work perfectly, so the modes still exist, they just aren't loading the scripts.

**Comment by LatvianModder** [comment]
That's on FTBTweaks then. I will see if I can update it myself, otherwise I gotta ask Jared to do it

**Comment by LatvianModder** [comment]
http://files.latmod.com/random/FTBTweaks-1.1x-2.0.2.jar
Updated it, now we wait until it gets uploaded on curse

**Comment by thephoenixlodge** [comment]
Awesome, thanks for sorting this so quickly

**Comment by thephoenixlodge** [comment]
Dang, crashed when loading the world: https://pastebin.com/wkB6B5HT

**Comment by LatvianModder** [comment]
Yeah Jared said to wait for his version to come out, nothing I can do
