### ISSUE TITLE
[0.16] FTBU doesn't create config files

### ISSUE THREAD

**Issue by frenchiveruti** [LatvianModder/FTBUtilities#44]
So, long story short, I deleted the "config.json" that I edited to get the new updated version from the 0.16, and it just creates an empty file, with no config options at all.  
I updated because FTB infinity had an older version.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/8

**Comment by frenchiveruti** [comment]
Aw dammit :/  
I can't help at all.
