### ISSUE TITLE
Warp GUI Broke after FTBUtilities-1.1x-3.6.0.jar

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LatvianModder/FTBUtilities#440]
Need some investigation.

**Comment by LatvianModder** [comment]
Fixed in https://github.com/LatvianModder/FTBUtilities/commit/a50ab86220457ed57ac22e47496259ce67f953d7#diff-588c0b66771a8a6ec74e58a5862a1180L35

**Comment by P3rf3ctXZer0** [comment]
@LatvianModder thank you let me know when its released.

**Comment by P3rf3ctXZer0** [comment]
@LatvianModder has the fixed been released yet?

**Comment by LatvianModder** [comment]
Fixed in 3.6.3
