### ISSUE TITLE
Crashes With Forge 2294

### ISSUE THREAD

**Issue by kenijey** [LatvianModder/FTBUtilities#442]
[crash-2017-05-02_18.48.11-client.txt](https://github.com/LatvianModder/FTBUtilities/files/970998/crash-2017-05-02_18.48.11-client.txt)

**Comment by kenijey** [comment]
or... i shouldn't install it to my client? :D

**Comment by kenijey** [comment]
because i doesn't crash on dedicated server. i installed only ftblib to client, i saw the 3 buttons on inventory gui, but i didn't see Map button to claim chunks. if i'm wrong about it, please help.

**Comment by ktole1999** [comment]
if its installed on server then its required by client.

**Comment by kenijey** [comment]
hmmm... but i am able to join the server without ftblib and ftb utilities, but i tried installing only ftb utilities to client, and i saw the 3 buttons, "players" "client options" "server options". only this 3 buttons, not the map button.

**Comment by kenijey** [comment]
uhm, i need an answer to a question, can admin claimed chunks be interacted by players? or can i configure it? thanks.

**Comment by ktole1999** [comment]
@kenijey not that i am aware of. we had to use grief prevention for admin claims for that purpose. I know ftbu still has a lot of functionality planned for future.

**Comment by kenijey** [comment]
oh, then it is a bug. thanks for response.

**Comment by mvsbarthen** [comment]
having same issue, just ftb-lib and ftb-utlities installed (clientside)
i tried to install `mcjtylib-1.1x-2.3.11.jar` just for the name, but doesnt solve the issue

**Comment by ktole1999** [comment]
if you install previous version ftbu and ftblib does it still crash?

**Comment by kenijey** [comment]
which version?

**Comment by kenijey** [comment]
3.5.4 right
let me try.

**Comment by kenijey** [comment]
uhm, no. it doesn't.

**Comment by kenijey** [comment]
ah wait, it crashed in my modpack, but with the vanilla.
here's the crash report:
[crash-2017-05-03_16.35.15-client.txt](https://github.com/LatvianModder/FTBUtilities/files/973479/crash-2017-05-03_16.35.15-client.txt)
please help :( at least about which mod i should delete

**Comment by kenijey** [comment]
and i just want to ask a little question, can i disable PvP in my claimed chunks as an admin? if i can't, can you add a feature for this please? thanks

**Comment by kenijey** [comment]
i hope you read my latest comments :D

**Comment by gdkite** [comment]
Not entirely sure if this should go here or in another thread, but I'm encountering much the same issue. Not at my main machine to post the crash report at the moment, but running Forges 2228-2294, I cannot get this this to run with any 1.1x build of FTBLib. The only other mods I'm using are TCon (& Mantle since it's a prereq).

**Comment by LatvianModder** [comment]
You have to install CompatTools mod

**Comment by kenijey** [comment]
what? where is that mod? can you send a link for it?

**Comment by LatvianModder** [comment]
Sorry, I meant CompatLayer

**Comment by kenijey** [comment]
uhm, it's already installed *.*

**Comment by LatvianModder** [comment]
You have an old version, this is fixed in 3.6.3+
