### ISSUE TITLE
HELP!!!  FTB Utilities not working in multiplayer

### ISSUE THREAD

**Issue by Geawy** [LatvianModder/FTBUtilities#448]
Everything seems to work great in single player, but in multiplayer I just get a spinning circular graphic when I try to do anything but read the guide.  Anyway ideas?  I'm running 1.11.2 with Forge 2294.  It's my own server and  I op'ed myself.  I don't get it.  I must be missing something.

**Comment by LatvianModder** [comment]
And you have FTBUtilities & Lib on the server the same versions as your client? (Latest 3.6.3 or smth)

**Comment by Geawy** [comment]
How do I install them on the server?  Sorry if that's a stupid question.  Do I need a mods directory on my server?  I'm just running it off a machine around the house.

**Comment by Geawy** [comment]
I'm running...

Server:
minecraft_server.1.11.2.jar

Client:
Using twitch/curse to mod with...
Forge-1.11.2-13.20.0.2294
FTBLib-1.1x-3.6.3.jar
FTBUtilities-1.1x.3.6.3.jar
OptiFine_1.11.2_HD_U_B8.jar

**Comment by Geawy** [comment]
Oh my gosh.  I hadn't installed forge on the server side.  OOOOPSTH!!!!

Now everything works great.  Thank you.

**Comment by LatvianModder** [comment]
lel
