### ISSUE TITLE
Guide Layout messed up

### ISSUE THREAD

**Issue by davqvist** [LatvianModder/FTBUtilities#450]
MC 1.10.2
Forge 2281

Upgrading FTBUtilities and FTBLib to 3.6.0 breaks the layout of the guide I made for my modpack. I specified icons for subchapters and they don't show anymore. Also it shows now the subchapters again in the content area, additionally to the menu area on the left. I had to downgrade FTBU and FTBL in my modpack for now. If you want to see it in action, you can download Age of Engineering and look in the guide and see how it's supposed to look like and then upgrade FTBU and FTBL and see the difference.

Did the syntax change in the update? I couldn't see anything regarding that in the changelog of FTBU.

**Comment by LatvianModder** [comment]
paste here what your pages.json looks like. I suspect you might have "icon_item":"<item>", I replaced that with "icon":"item:<item>". See FTBUtilities or Yabba guides as examples if that's not it

**Comment by davqvist** [comment]
```
[
  {"id": "age0", "icon_item": "minecraft:cobblestone", "lang": "00 - Stone Age"},
  {"id": "age1", "icon_item": "ic2:forge_hammer", "lang": "01 - Industrial Age"},
  {"id": "age2", "icon_item": "calculator:Calculator", "lang": "02 - Calculation Age"},
  {"id": "age3", "icon_item": "actuallyadditions:blockEmpowerer", "lang": "03 - Empowering Age"},
  {"id": "age4", "icon_item": "forestry:sturdyMachine", "lang": "04 - Farming Age"},
  {"id": "age5", "icon_item": "enderio:itemMachinePart", "lang": "05 - Ender Age"},
  {"id": "age6", "icon_item": "rftools:machine_frame", "lang": "06 - Automation Age"},
  {"id": "age7", "icon_item": "ic2:te 1 62", "lang": "07 - Nuclear Age"},
  {"id": "age8", "icon_item": "calculator:AtomicCalculator", "lang": "08 - Atomic Age"},
  {"id": "age9", "icon_item": "neotech:electricCrucible", "lang": "09 - New Age"},
  {"id": "age10", "icon_item": "techreborn:techreborn.machineFrame", "lang": "10 - Technological Age"},
  {"id": "age11", "icon_item": "libvulpes:structureMachine", "lang": "11 - Space Age"},
  {"id": "age12", "icon_item": "mekanism:BasicBlock 1 8", "lang": "12 - Mechanical Age"},
  {"id": "age13", "icon_item": "draconicevolution:draconic_core", "lang": "13 - Draconic Age"},
  {"id": "age14", "icon_item": "extrautils2:angelring", "lang": "14 - Creative Age"}
]
```

I looked at that: https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/resources/assets/ftbu/guide/ranks/pages.json

So I have to change it to 

`  {"id": "age0", "icon": "item:minecraft:cobblestone", "lang": "00 - Stone Age"},`

for example?

**Comment by LatvianModder** [comment]
That is correct. Also, you are using "lang" way wrong. It's a language key, yes it will work, as in, it will display the text, but don't do that. Use en_US.lang file for chapter names. That is the correct way, AND it allows for the guide to be translated. See https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/resources/assets/ftbu/lang/en_US.lang#L202-L296
