### ISSUE TITLE
ftbu.claims.block.break.* Has no effect?

### ISSUE THREAD

**Issue by MindThoth** [LatvianModder/FTBUtilities#451]
I am trying to give permission to my moderators to be able to interact and break blocks in a claimed chunk.

The ftbu.claims.block.interact.* works perfect but ftbu.claims.block.break.* has no effect and unable to break blocks in the claim area. Am I missing something here is the rank : 

```
 "modanthony": {
      "parent": "builtin_player",
      "permissions": [
        "+ftbu.claims.block.interact.*",
        "+ftbu.claims.block.break.*",
        "+ftbu.claims.block.cnb",
        "+ftbu.claims.modify_other_chunks"
      ],
```

**Comment by LatvianModder** [comment]
It's "edit" not "break", I think

**Comment by MindThoth** [comment]
Yup you got it! It's edit and not break, thanks!
