### ISSUE TITLE
1.10.2 Server dimension chunkloading

### ISSUE THREAD

**Issue by redcatone** [LatvianModder/FTBUtilities#452]
May be related to #435 

Age of Engineering 0.4.3
FTBLib-1.1x-3.5.4
FTBUtilities-1.1x-3.5.4

On a server I play on I experienced some strange behavior chunkloading the nether. When another player is in the nether, chunkloaded chunks in the nether seem to be unload.

Setup 

- A chunkloaded resturbed skeleton spawner (from extra utilities 2) 
- Transported with fast vector plates (dark utilities) to diamond spikes (extra utilities 2)
- Drops being picked up by an ender hopper (dark utilities) on top of a privated ender chest (enderstorage)

Entire build is contained within a single chunk, loaded using ftb utilities.

The farm will work fine sending items to the overworld but as soon as a player enters the nether, the drops no longer show up in the ender chest, I presume the area stops being chunkloaded. When the player leaves the nether everything functions as normal again. 

I am not an admin so I can't provide logs or more detailed information. And because it requires another player it is hard to test alone.

**Comment by utoc** [comment]
I am the server admin, I can provide logs but honestly his assessment is spot on and there isn't anything relevant in the server log during the times we reproduced the issue.

We're running FML 2297 (2281 + Fix MC-117087, prevent calling Class.getSimpleName on TEs unnecessarily)

**Comment by redcatone** [comment]
The server has since updated to:

Age of Engineering 1.0.0
FTBLib-1.1x-3.6.3
FTBUtilities-1.1x-3.6.3

The issue persists. When another player enters the nether, the chunks loaded by FTB Utilities seem to be unload. When the nether is empty of players everything runs as expected.

**Comment by LatvianModder** [comment]
Closing, duplicate https://github.com/LatvianModder/FTBUtilities/issues/435
