### ISSUE TITLE
removing claimed chunks as admin

### ISSUE THREAD

**Issue by JiFMike** [LatvianModder/FTBUtilities#455]
Hi, I am trying to remove claimed chunks from my server of players who haven't been on in a while. Here's what happens:

command: /ftb chunks unclaim_all player_name true
response: The player cannot be found

I have verified the player name is correct, and tried a few different players all with the same response. Is there another way to remove claimed chunks I am missing? Thanks.

Using FTBUtilities-1.1x-3.6.3

**Comment by ktole1999** [comment]
i dont recall if player data is stored in a file. if so i would think removing the player file would cause that claim to not be loaded. dont quote me.

**Comment by JiFMike** [comment]
Server is due for a restart in about 10 minutes. That is easy to try thanks.

**Comment by LatvianModder** [comment]
The chunks are stored in a file located in `world/data/ftb_lib/players/<uuid>.dat`, but the command should have worked, let me try

**Comment by JiFMike** [comment]
I have removed the files of the players I wanted to delete, and restarted the server. Chunks are no longer claimed or loaded. Thank you!
