### ISSUE TITLE
Crash on startup, 3 different forge versions. Tried with no other mods than FTB Utils and Lib.

### ISSUE THREAD

**Issue by StangleKhan** [LatvianModder/FTBUtilities#457]
[crash-2017-05-23_09.12.45-client.txt](https://github.com/LatvianModder/FTBUtilities/files/1022438/crash-2017-05-23_09.12.45-client.txt)

[crash-2017-05-23_09.10.38-client.txt](https://github.com/LatvianModder/FTBUtilities/files/1022441/crash-2017-05-23_09.10.38-client.txt)

[crash-2017-05-23_09.08.48-client.txt](https://github.com/LatvianModder/FTBUtilities/files/1022445/crash-2017-05-23_09.08.48-client.txt)

All three are the same other than the version of Forge. All three give the 

Caused by: java.lang.NoClassDefFoundError: mcjty/lib/tools/ItemStackTools

I tried also adding mcjty lib but that didn't do anything.

**Comment by StangleKhan** [comment]
I'm an idiot. Missing Compatability Layer

**Comment by LatvianModder** [comment]
How come so many people dont have it? It downloads automatically with Curse
