### ISSUE TITLE
[1.7.10/1.0.18.3] Any way to give some players more homes than others?

### ISSUE THREAD

**Issue by Schadrach** [LatvianModder/FTBUtilities#458]
Exactly what the topic says.  As I understand it you would normally do this using ranks, but I don't seem to have a ranks.json.

**Comment by ktole1999** [comment]
are you using anything other than ftbu for ranks/groups?

**Comment by Schadrach** [comment]
MyPermissions, perhaps?  I thought FTBU used it's own setup for that kind of thing?

**Comment by ktole1999** [comment]
it does but if you have more than 1 mod then there may be a conflict. does mypermissions only handle perm nodes or does it handle groups?

**Comment by Schadrach** [comment]
It can handle groups.

**Comment by ktole1999** [comment]
since mypermissions is your dominant mod for perms i would disable in ftbu.

**Comment by Schadrach** [comment]
OK, I don't see an option to disable perms in FTBU, and what permission node controls how many homes you get?  Is there a list posted somewhere?

Also to be clear, this does apply to 1.7.10 / 1.0.18.3?

**Comment by ktole1999** [comment]
you can disable the command in the config.

**Comment by Schadrach** [comment]
So, you're saying I should disable homes in FTBU entirely and find a different mod to supply that functionality?  I thought you were saying I should disable FTBU's permissions system somehow.

**Comment by ktole1999** [comment]
i am saying if you have both trying to control homes then you will have a conflict. if you can control with mypermissions then disable homes in ftbu or viceversa. both ftbu and mypermission should have a perm node for homes. ftbu controlling them using ranks and mypermissions controlling them using groups.

**Comment by LatvianModder** [comment]
Sorry, I don't support 1.7.10 anymore. And you can only set more homes for admins, in local/ftbu/config.json
