### ISSUE TITLE
Overlapping icons.

### ISSUE THREAD

**Issue by frenchiveruti** [LatvianModder/FTBUtilities#46]
Well, as a wise man said once, an image tells more than a thousand words.  
![2016-02-02_01 08 06](https://cloud.githubusercontent.com/assets/1095997/12739581/a58058a0-c949-11e5-83c7-6758409c97ad.png)
As you can see, the cog of settings and the friends gui overlaps, instead of what it did in previous versions:  
![2016-01-05_19 55 38](https://cloud.githubusercontent.com/assets/1095997/12739601/c3d32030-c949-11e5-8b37-994344d15abc.png)

**Comment by LatvianModder** [comment]
It only does that when there are effects on player, but I will fix this in 1.0.16.1

**Comment by frenchiveruti** [comment]
All right!  
Need anything else?

**Comment by LatvianModder** [comment]
Nope, thanks!

**Comment by LatvianModder** [comment]
Fixed in 1.0.17.1
