### ISSUE TITLE
[1.10.2] Chunk Loading Stops Working With Sponge Installed

### ISSUE THREAD

**Issue by EZKatnipz** [LatvianModder/FTBUtilities#461]
https://github.com/SpongePowered/SpongeForge/issues/1553

Information on the Sponge issue post.

**Comment by LatvianModder** [comment]
If this is a sponge issue, I can't fix it

**Comment by EZKatnipz** [comment]
Not sure how that whole thing works with chunk loading and whatnot, but just making sure you were aware. I 100% prefer FTB Utilities for chunk claiming almost completely because of the GUI so im not looking to replace FTB Utilities.
