### ISSUE TITLE
[1.10.2] FTB ranks config reset when server launches

### ISSUE THREAD

**Issue by Enemeez** [LatvianModder/FTBUtilities#463]
I had specific ranks typed out, such as max homes for players, but when my server restarts the config in the file gets reset.

**Comment by EZKatnipz** [comment]
I am having the same issue. Whenever I use the "/ftb reload" command the ranks.json gets reset.

**Comment by LatvianModder** [comment]
Most likely wrong json formatting, a missing comma or something. Paste your json file in a validator https://jsonlint.com/

**Comment by EZKatnipz** [comment]
ohhhh my gosh, of course a missing comma. And i thought i looked through my file. Thanks. 
Now, is there a way to allow non-ops the vanilla commands? such as /ban, /kick

**Comment by LatvianModder** [comment]
Yeah, just give them "+command.kick" permission
