### ISSUE TITLE
[Question] what is the webapi?

### ISSUE THREAD

**Issue by Adrian-Turjak** [LatvianModder/FTBUtilities#465]
In the config there is this setting:
`"webapi": {
"update_interval": 5,
"enabled": false,
"file_location": ""
},`

I'm curious as to what it is for but I can't find any info about what it actually does.

**Comment by LatvianModder** [comment]
Oh yeah, it's exporting json file of all players and their leaderboards or something. Honestly, I don't really remember myself xP

**Comment by Adrian-Turjak** [comment]
Blast, was hoping it might be something more useful!

If all it does is export data, then I might at least see what is in it. :P
