### ISSUE TITLE
Configure default for 'allow explosions'

### ISSUE THREAD

**Issue by Adrian-Turjak** [LatvianModder/FTBUtilities#468]
Sorry for all the questions I'm asking, but I'm only doing it if I can't find answers elsewhere or in some doc/readme/thread. I'm trying to setup a couple of servers, and writing/documenting some ansible to do it for me, so trying to make sense of a bunch of stuff.

With the old config structure you could force explosions in claimed chunks. At least for now, I'd like explosions to be on by default. I can't find where to set that, since right now they appear to be off by default in claimed chunks.

There appears to be no clear setting for the default state of explosions in claimed chunks, so while I can disable the editing of chunk upgrades such as explosions for normal players via ranks, it doesn't help me if they default to off anyway. :(

I've tried looking through the code, but that hasn't helped me too much. Can you possibly point me in the right direction?

Looks vaguely related, but no clue where in the config file that goes:
https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/resources/assets/ftbu/lang/en_US.lang#L90-L92

This appears to be the default:
https://github.com/LatvianModder/FTBUtilities/blob/1.9/src/main/java/com/feed_the_beast/ftbu/world/FTBUTeamData.java#L25

Cheers! And thanks!

**Comment by LatvianModder** [comment]
With default you mean forced, so that players can't change it, or not?

**Comment by Adrian-Turjak** [comment]
Forced I don't entirely need if there is a way to set the default in the config, but could be useful if not. With your rank system I can disable a player's ability to upgrade their chunk to turn off explosions if I want, the problem is that they default (see link above to code) to off, so all I'm doing then is blocking them from turning explosions on.

**Comment by Daihok41** [comment]
Is there a way to make explosions actually break blocks in claimed chunks? Been trying to find out how this can be changed. I want blocks to be able to be blown up in claimed chunks or not.

**Comment by LatvianModder** [comment]
Just enable explosions in team config...

**Comment by Daihok41** [comment]
Ahh thanks for this. Yea I searched everywhere in the actual configs folder couldnt find anything lol. appreciate the help though.
