### ISSUE TITLE
team GUI free to join

### ISSUE THREAD

**Issue by wdejonge97** [LatvianModder/FTBUtilities#469]
In our server we have teams setup. When I dissable the option "Free to Join" to false people who are allied with me are still free to join my team. Is this supposed to be so? Also the chunkloading doesn't let tree's grow when it's chunkloaded. I didn't see a post about that so I addressed it.

**Comment by LatvianModder** [comment]
Yes, allies are supposed to be able to join your team, see the order in https://github.com/LatvianModder/FTBLib/blob/78d74f7472562212c366a1a3ea13061d37f8adb0/src/main/api/com/feed_the_beast/ftbl/api/EnumTeamStatus.java#L13-L20

**Comment by LatvianModder** [comment]
About chunkloading trees, I don't think that works like that, most likely it doesn't chunkload at all, in which case I already have issues open for that
