### ISSUE TITLE
Ranks & Permissions

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#47]
This will only go in 1.9.4+ for now. Once its completed, I might backport to 1.7.10 if it won't be forgotten by then

**Comment by Goten87** [comment]
Donno if it's a nice thing to do but can u make the permissions in a MySQL database and add a block logger as well for peeps to use in a database that way we can make a website for admins to check there stuff when there not ingame just a idear and sharing it with u if u don't like it no hard feelings ^^

**Comment by Georggi** [comment]
Any chance, that it will be ported to 1.7.10 any time soon?

**Comment by LatvianModder** [comment]
1.7.10 is Mostly unsupported / no new features will be added, BUT If I have time after I release 1.9 version, and there wont be bugs for some period, I might backport it aswell. But most likely that no

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/30
