### ISSUE TITLE
backup hangs on [FTB Infinity Evolved Skyblock] modpack

### ISSUE THREAD

**Issue by matsaa93** [LatvianModder/FTBUtilities#471]
i have a problem with the backup service in the FTBUtilities on minecraft 1.7.10
it hangs on auto backup and will not do the backup. 
here is a short console output:  
[20:08:18] [Thread-26/INFO] [FTBU]: Loaded 2 badges in 13 ms!
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension -100
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension -37
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension -38
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension -39
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension -42
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension -19
[20:08:19] [Server thread/INFO] [FML]: Unloading dimension 1
[22:08:14] [Server thread/INFO]: Server Backup started!
[00:08:14] [Server thread/INFO]: Server Backup started!

i restarted it and let it run to see if that did it but no result 
here are the resent log files:

[logs.tar.gz](https://github.com/LatvianModder/FTBUtilities/files/1059516/logs.tar.gz)

i run it in a python virtualenv and i run linux i do not see that to be a problem because  it was not a problem with this on the other modpack i used in the past. 
as you see from the short log it starts but does not finish the prosess i think it is that it does not manage the "auto-saving world stop/start" correctly before trying to making the backup 
there is no file in system as i can see in the backup folder since a day ago. 
whan it should have made a back up every 2 hours or sow.

the thing is i dont know if it stops auto-saving or if it does not but that would be a problem if it does not  turn i on after i fails  
in case of backup i can manage without and run them manualy from bash when needed the only thing is if it stops auto-saving it will not work. 
a little info the server world has ones been corrupted and i needed to restore it after i restored it this happened shortly after the restoration for server world. 
maby that is the reason the backup does not work or something the server crashed 12 min after backup not because the backup but logistics pipe and thermal expasion machine that conected thru pipe plug. 

please help me fix it it would be nice to run a backup from the server and not need to stop server and then backup 
i dont think this is a bug more or less a fault some vere in the server but i have not touched the configs as far as i now i have only given it more ram and chaned the jvm-arguments to my system specs. 
here are the startup scripts if they helps they are in order of path in the file.
[scripts.tar.gz](https://github.com/LatvianModder/FTBUtilities/files/1059600/scripts.tar.gz)

any way thanks for future replies

**Comment by LatvianModder** [comment]
I can't help for 1.7, but maybe you just have to delete all backups, maybe there isn't enough room
