### ISSUE TITLE
Player inventories seem to be reset after restore from backup?

### ISSUE THREAD

**Issue by mcadude500** [LatvianModder/FTBUtilities#472]
I'm running a small FTB Infinity Evolved server, and we recently had to restore our server from a backup, however, after swapping out the corrupted world folder with one from the FTBUtilites backups folder, people logging onto the server have lost almost all their player data. Players log in and find themselves at spawn, with nothing in their inventory except for baubles, and even their achievements are reset. Does anyone know why this is/how I fix this?

**Comment by LatvianModder** [comment]
Maybe it made a corrupted backup too / the problem existed before the world was truly corrupted. Either way, I don't think this is something I can fix, since I only copy-paste the world folder

**Comment by jimmed** [comment]
Just experienced this issue on my server. I had to roll back my world to an earlier backup to fix a chunk that was crashing the server when loaded.

All player data, (inc. spawn, inventory, achievements, stats) was reset, despite being stored in the world directory (as far as I'm aware, anyway).

I realise I'm not getting that data back, but posting for posterity, in case anybody else has this problem.
