### ISSUE TITLE
Claimed Chunks / Loaded Chunks change maximum 

### ISSUE THREAD

**Issue by BrainGameFactory** [LatvianModder/FTBUtilities#473]
1000 Chunks to claim is to much for my server wehre can i edit it and the Loaded Chunks too ?

**Comment by LatvianModder** [comment]
See Inventory -> Guide -> Ranks, you have to change `"ftbu.claims.max_chunks"` and `"ftbu.chunkloader.max_chunks"` in `"config"` for player/op ranks

**Comment by BrainGameFactory** [comment]
can you describe detailed pleas tanks
