### ISSUE TITLE
Claimed Chunks / Loaded Chunks change maximum again

### ISSUE THREAD

**Issue by BrainGameFactory** [LatvianModder/FTBUtilities#474]
You give me an answer but can you describe it mor detailed  tanks

**Comment by BrainGameFactory** [comment]
![rank](https://user-images.githubusercontent.com/24873672/27138870-d7993490-5121-11e7-95c8-5eb10e3dc5a1.png)

**Comment by LatvianModder** [comment]
Just read about it here. FTBUtilities > Ranks

![image](http://ss.latmod.com/pc/2017-06-14_17.53.47.png)

**Comment by LatvianModder** [comment]
{"ftbu.claims.max_chunks": 32, "ftbu.chunkload.max_chunks": 12}
