### ISSUE TITLE
Rank.json delete problem

### ISSUE THREAD

**Issue by BrainGameFactory** [LatvianModder/FTBUtilities#475]
![grafik](https://user-images.githubusercontent.com/24873672/27227445-c83058d4-52a3-11e7-952d-4a7a36734ee2.png)

Is here somting wrong ?
When i try to play with this settings the line ""ftbu.chunkloader.offline_timer": 25.0,"
will automaticly deletet why ?

Sorry for my english skill i am german

**Comment by LatvianModder** [comment]
I removed the offline_timer config in later versions, it was causing problems. I might add it back but only in 1.12 versions

**Comment by RJ-Fynydd** [comment]
It would be nice if it was added back. :/

**Comment by PotatoSauceVFX** [comment]
It would be nice to have back.
