### ISSUE TITLE
Teams don't sync with client

### ISSUE THREAD

**Issue by egold555** [LatvianModder/FTBUtilities#476]
When playing on a server, all of out teams get randomly deleted. This is so annoying when you have claimed chunks and you half to keep re-making your team and keep re-claiming your chunks. We have not touched the configs. How do we turn this off? 

Random info about the server
Forge version: 1.10
Players: All OP
FTBLib-1.10.2-3.4.4
FTBUtilities-1.10.2-3.4.3

**Comment by egold555** [comment]
Just did a lot of testing and found a way to restore teams if anyone else is having this bug.

Make a team and then do /FTB reload 
then do /ftb reload_client

Not sure why this happends but the client does not seem to sync to the server

**Comment by LatvianModder** [comment]
So they don't get deleted, just dont sync with server properly?

**Comment by egold555** [comment]
That's what I am guessing based on my little amount of testing

**Comment by LatvianModder** [comment]
Does the server happen to have Sponge/any other plugin thing?

**Comment by egold555** [comment]
Nope. Just a normal forge server. It's a mod pack though. But it's made by the FTBTeam

**Comment by egold555** [comment]
Just logged on to out server and every team is gone. FTBReload does nothing to get the teams back
