### ISSUE TITLE
Safe_Spawn not working with skeletons

### ISSUE THREAD

**Issue by rob5251** [LatvianModder/FTBUtilities#48]
Safe_Spawn - true
Working against most mobs, but not skeletons.
Possibly because its projectile damage?

**Comment by LatvianModder** [comment]
Hmm. Safe spawn shoud've disabled mod spawning within spawn area. If the skeleton shoots arrow from outside, it won't protect you

**Comment by LatvianModder** [comment]
ToDo: Add damage checker for arrows / other entity damage

**Comment by rob5251** [comment]
Yeah, they wont spawn but can damage you via arrows from outside is what I was meaning. I just thought being inside the spawn area with safe spawn on would negate all damage.
