### ISSUE TITLE
Strange crash on 1.11.2, it appears CompatLayer is being used as a dependency of sorts

### ISSUE THREAD

**Issue by Sunconure11** [LatvianModder/FTBUtilities#486]
https://pastebin.com/bEDXVain

Is this relying on CompatLayer on 1.11.2, by any chance? Because this error only resolves itself if CompatLayer is installed.

**Comment by LatvianModder** [comment]
Yeah, 1.11 versions depend on CompatLayer but 1.12 no longer does
