### ISSUE TITLE
Pool claimable chunks by teams

### ISSUE THREAD

**Issue by IRSmoh** [LatvianModder/FTBUtilities#487]
E.g. for each player that joins a team take their chunks that they could claim by themselves and let the owner/moderator of the team claim chunks instead. So say you have 5 people that normally could claim 10 chunks, the owner/mod would be able to claim 50 chunks for the team instead of requiring every person to claim 10 chunks.

**Comment by xilni** [comment]
I would like to suggest an additional config that would allow all team members to be able to use the pooled chunks or only the creator.
