### ISSUE TITLE
FTB U & FE Teams conflict?

### ISSUE THREAD

**Issue by Jessssuhh** [LatvianModder/FTBUtilities#488]
Hello! I run a server with both FTB U and FE. For the different tools they offer - mostly the more highly configurable worldguard in FE but the player friendly gui in FTB U.

Having both on there seems to overwrite any FTB U ranks, and when I attempted to correct that by giving FE ranks FTB U permissions, it has given them admin access to teams and chunks. Unopped players can unclaim chunks of other players, and break stuff within them - but they have no other op-like commands.

I understand that people need access to commands.ftb to use the GUI, and I tried denying permission to all specific commands, but it hasn't fixed the problem.

Any idea what I could do to correct the problem (aside from "uninstall FE")?

**Comment by LatvianModder** [comment]
Make sure you have disabled everything from FTBU ranks, ranks, command overrides and chat overrides. Then, I dont know how FE permissions work, but you need to remove `ftbu.claims.modify.others` permission from players - that's what allows them to edit other claimed chunks

**Comment by Jessssuhh** [comment]
FE is a long ass, worldguard like command string, with long ass permissions names. FTB U is much nicer, haha. Yes, that permission string worked! Thank you so much
