### ISSUE TITLE
ForgeEssentials conflict

### ISSUE THREAD

**Issue by dverlik** [LatvianModder/FTBUtilities#490]
[I have run into an issue with FTBU-FE server](https://github.com/ForgeEssentials/ForgeEssentials/issues/2300), where the FTBU permission system is overwriting the FE permission system. While I don't want to remove FTBU from my server, as it provides a very nice & user-friendly team and chunk claiming system, but I can't imagine running my server without economy and scripting possibilities ForgeEssentials provides. At the same time, I need the MySQL extension FE offers, mainly because of the billing possibilities. So, is there any chance of resolving this conflict, using the FE permissions system, while still being able to use both of the mods?

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/488#issuecomment-315534128
