### ISSUE TITLE
1.12 - Can't add "Name" or "Lore" to starting items

### ISSUE THREAD

**Issue by tachometer74** [LatvianModder/FTBUtilities#491]
MC 1.12
FTB Utilities 4.0.3
FTBLib 4.0.5

This works:
"minecraft:iron_sword 1 0 {ench:[{id:16,lvl:1}]}"

This works:
"minecraft:iron_sword 1 0 {ench:[{id:16,lvl:1},{id:21,lvl:1}]}"

This does not work:
"minecraft:iron_sword 1 0 {display:{Name:"Starter Sword"},ench:[{id:16,lvl:1},{id:21,lvl:1}]}"

I've tried all sorts of different combinations of Name, Lore, Enchantments, etc.  If I add either Name or Lore I don't get the starter item.

**Comment by LatvianModder** [comment]
Ah, yes, you gotta use `\` before `"` inside JSON string, otherwise its considered broken JSON

`minecraft:iron_sword 1 0 {display:{Name:\"Starter Sword\"},ench:[{id:16,lvl:1},{id:21,lvl:1}]}`
