### ISSUE TITLE
FileNotFound during backup

### ISSUE THREAD

**Issue by linuxdaemon** [LatvianModder/FTBUtilities#500]
### Description
OpenComputers does not stop writing data to the disk when autosave is disabled, so OC computer data can be modified during a backup. In this case, I removed a file from a computer during a backup, leading to [this error](https://gist.github.com/linuxdaemon/6739a70305f2b772bb291aa07041eea2) (followed by a manual backup).

This does not crash the server, but it does cause the backup to not complete.

### Versions:
- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- FTB Utilities: 1.1x-3.6.5
- FTB Lib: 1.1x-3.6.5

**Comment by LatvianModder** [comment]
Wow, what an edge case... I guess I will add a file existance check or something?

**Comment by linuxdaemon** [comment]
Either that or just catching the error (possibly logging it) and allowing the backup to continue? I'd think doing a separate existence check before opening the file could lead to a race condition where the file may change after the check but before opening (extreme edge case, but then again, so is this).

**Comment by LatvianModder** [comment]
Btw, this won't be fixed for 1.10, just for 1.12+ versions

**Comment by linuxdaemon** [comment]
It's minor enough in my case, been using OC pretty extensively and doing backups with FTBU for quite awhile and I've never had this issue before, so I'd assume it's not all that common. Just something I noticed and figured I'd report
