### ISSUE TITLE
1.10.2 FTBUtilities not force loading more the 25 Chunks

### ISSUE THREAD

**Issue by Xavhorn** [LatvianModder/FTBUtilities#504]
Version: 1.1x-3.6.5

Currently I have 50 chunks set to force load but FTBUtilities is actually only loading 25. If I add a chunk to load after 25 chunks, another chunk gets unloaded. Don't know if this is per team or server wide. I also tested with chicken chunks and confirm that I can force load more then 1000 chunks on the server.

_**FTBUtilities**_
![chunks](https://user-images.githubusercontent.com/9772451/29290172-f4a698c8-80f3-11e7-88c5-26e49dcb0c43.png)

_**Chicken Chunks**_
![chicken chunks](https://user-images.githubusercontent.com/9772451/29291612-008a3302-80f9-11e7-935e-2e04f3183349.PNG)

**Comment by merphle** [comment]
I just noticed the same behavior - 25 chunks max loaded per dimension. Tested in-game using "/ftb loaded_chunks_list", clicked on each dimension -> "ftbu" and observed that max 25 chunks were loaded. I then force-loaded a chunk using the FTBU UI, and the loaded_chunks_list remained at 25. I unloaded a chunk, and the number dropped to 24. Max 25 is an interesting number, as that appears to be the default max number of chunks that Forge allows to load per ticket.

Now, I think I've solved the problem, at least for my server (Age of Engineering, v1.0.5).
1) I went into Mod Options -> MinecraftForge -> Config -> Forge Chunk Loader Default Settings -> Mod Overrides -> Add New -> select FTBUtilities -> set Chunks Per Ticket Limit = 1000.
2) I also changed the global (not Mod Override) Chunks Per Ticket Limit to 1000.
3) I also edited config/forgeChunkLoading.cfg to create a new "ftbu" section, with increased Chunks Per Ticket Limit, but I don't think this did anything in my existing world.
4) Restarted the server, and observed that loaded_chunks_list was about 150 for the Overworld, and 45 for Mining World -- exactly as expected. Forcing new chunks to load using the FTBU UI increased the number of chunks loaded.

Given this, I'd venture a guess that somehow the Properties being set by LoadedChunkStorage.init() aren't working as expected. I hope this write-up was helpful.

**Comment by LatvianModder** [comment]
This might be the problem. This might fix everything. I try to override those numbers manually, but apparently it doesn't work anymore, I will have to figure out something new!

**Comment by LatvianModder** [comment]
Oh my god. The `LoadedChunkStorage.init()` method doesn't get called `<.<`

**Comment by LatvianModder** [comment]
Can you test if it works now with http://mods.latmod.com/FTBLib/4.1.0/ and http://mods.latmod.com/FTBUtilities/4.1.0/ ?

**Comment by merphle** [comment]
I won't tell anyone if you don't. :)

**Comment by LatvianModder** [comment]
Can you test if the version I made now in #501 works?

**Comment by merphle** [comment]
I will when I get home from work tonight.

**Comment by merphle** [comment]
It works fine for me, using MC 1.12.1, Forge 14.22.0.2456. Brand new world, was able to claim & chunkload more than 25 chunks with no configurations or other tweaks needed. I'm not able to test this in my server's current world, as it's MC 1.10 -- any chance this could get a back-port? If not, the simple workaround for modpack authors would be to edit config/forgeChunkLoading.cfg to append the below section:

```
##########################################################################################################
# ftbu
#--------------------------------------------------------------------------------------------------------#
##########################################################################################################

ftbu {
    # Maximum chunks per ticket for the mod.
    I:maximumChunksPerTicket=1000000

    # Maximum ticket count for the mod. Zero disables chunkloading capabilities.
    I:maximumTicketCount=200
}
```

**Comment by olback** [comment]
Somewhat unrelated, but what software are you using to view loaded chunks? @Xavhorn

**Comment by LatvianModder** [comment]
Probably chickenchunks chunk viewer
