### ISSUE TITLE
loaded_chunks_list nonfunctional, dangerous

### ISSUE THREAD

**Issue by thundR** [LatvianModder/FTBUtilities#505]
4.0.3 ftbutil

Multiple issues here. 

Loaded chunks list, when clicked, teleports you, without warning or confirmation, to the bottom of what should be the clicked chunk, leaving you to instantly die from the void. 

Not only that, but it doesn't even send you to the dim you clicked on.

Not only that, but the coords it sends you to are the chunk coords, and not the actual block coords, making basically every chunk send you to the effective 0,0,0 of the overworld to die to the void.

**Comment by thundR** [comment]
Ok, looking at the code, this is just wrong:

```
int cx = MathUtils.chunk(c.x) + 8;
int cz = MathUtils.chunk(c.z) + 8;
String cmd = "/tp " + cx + " " + ep.world.getHeight(cx, cz) + " " + cz;
```

I'm looking closer at the chunk coords this generates, and they aren't even correct. They're all just variations of 6, 0, 8 or close.

https://gyazo.com/0506200bf513a0b95fe75c6a6144fa55

Either your call to math utils is giving you bad data, or your chunk object was wrong in the first place, and the call to getHeight is returning 0 every time. Since none of this code works even close to as intended, I suggest stashing it until you can work out the correct coord system.

**Comment by LatvianModder** [comment]
I think I may have mixed `MathUtils.chunk` with `MathUtils.unchunk`
