### ISSUE TITLE
Change ammount of claimed/loaded capable chunks per person per team(faction)?

### ISSUE THREAD

**Issue by Huntrex** [LatvianModder/FTBUtilities#506]
1000 is a little much for my small server. Also I need to reduce loadable chunks to something better like 5 instead of 64 where do I do this?

Also as a side question, how do I delete warps that i have set?

**Comment by Huntrex** [comment]
these things are impossible to find. Googling anything minecraft related takes hours, unlike everything else, because of all the kids who play minecraft flooding the seo with stuff they should be able to find easily on their own, or that is already otherwise obvious.

**Comment by LatvianModder** [comment]
`/delwarp <name>` for warps. There is ingame Guide for ranks, Inventory > Guide > FTBUtilities. You can find all config names in local/ftbu/all_configs.html
