### ISSUE TITLE
Files not zipping for backup

### ISSUE THREAD

**Issue by violetkitty87** [LatvianModder/FTBUtilities#507]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.
Sorry about this but i have a server that is being hugely overloaded with the backups using the version ftb utilities 1.7.10- 1.0.183 the files arent zipping what should i do in the config to fix this

**Comment by LatvianModder** [comment]
>Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version

**Comment by violetkitty87** [comment]
its more of a question than a bug or a suggestion
