### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by ClaudiusMinimus** [LatvianModder/FTBUtilities#508]
With only the latest version of FTBLib and FTBUtilities for Minecraft 1.11.2 I get the following error:

AL lib: (EE) alc_cleanup: 1 device not closed

I noticed in the log: UCHIE	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 

Here is the full log
https://pastebin.com/Gk7FjpQk

**Comment by UnPure** [comment]
Use [CompatLayer](https://minecraft.curseforge.com/projects/compatlayer) as it is a required library as you can see if you scroll down on the FTBLib download, that should probably fix your problem! ;)

**Comment by ClaudiusMinimus** [comment]
@UnPure : CompatLayer fixed this issue.
Thanks for the help!
