### ISSUE TITLE
Here's an Error  "ConfigEntryBool" [can you give me a quick reply?]

### ISSUE THREAD

**Issue by SirDuckster** [LatvianModder/FTBUtilities#511]
Here's the crash report:
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: ftb/lib/api/config/ConfigEntryBool

Game Version: 1.7.10
Mod Version: 1.7.10
Problem: **_ConfigEntryBool IS NOT FOUND_**

> **Now that is my _problem...**
I have FTBLib installed btw.

**Comment by SirDuckster** [comment]
**_I cant seem to find a solution everywhere._**

**Comment by LatvianModder** [comment]
sorry, 1.7.10 no longer supported

**Comment by SirDuckster** [comment]
Well time to move on to 1.8

**Comment by LatvianModder** [comment]
We are at 1.12.1 now... You were 5 major versions behind :P
