### ISSUE TITLE
TeamsGui should not prompt me when in single player

### ISSUE THREAD

**Issue by mezz** [LatvianModder/FTBUtilities#514]
Many packs include FTBUtilities for use on severs, but often people play single player too.
I think the message "You haven't joined or created a team yet!" should not show up in chat in single player.

**Comment by LatvianModder** [comment]
I will just make it auto-create team for singleplayer worlds

**Comment by mezz** [comment]
That sounds good

**Comment by mezz** [comment]
Thank you!
