### ISSUE TITLE
1.12.1 Crash when player joins the server.

### ISSUE THREAD

**Issue by dmodoomsirius** [LatvianModder/FTBUtilities#515]
Does not happen when every player joins, Just random, and not always the same person.

https://gist.github.com/dmodoomsirius/8a08cb5fbbe31827d0cefe9ee15aedf4

**Comment by LatvianModder** [comment]
Not the latest versions. Test if it does the same with 4.1.x versions. https://github.com/LatvianModder/FTBUtilities/issues/501

**Comment by dmodoomsirius** [comment]
```
	| UCHIJAAAA | ftbl                      | 0.0.0                           | FTBLib-4.1.0.jar                                    | None                                     |
	| UCHIJAAAA | ftbu                      | 0.0.0                           | FTBUtilities-4.1.0.jar   
```
Right from the 2nd Crash report LativanModder.
