### ISSUE TITLE
player_ranks example and permissions

### ISSUE THREAD

**Issue by Trellinane** [LatvianModder/FTBUtilities#517]
I am looking for an example of the player_ranks.json file and can you assign permissions to individual players or is it only possible to assign permissions to the ranks and then assign players to those ranks.  I understand the rank system and I have been able to set that up.  However, I think in some instances it would be nice to be able to grant specific permissions to specific players.  Please advise on this issue.

**Comment by LatvianModder** [comment]
You have to create a new rank for those players, and then assign that rank to them. The system isnt built for that, and I probably wont make individual permissions, because then it would only make the file system more confusing and performance would fall, since I cache permissions etc
