### ISSUE TITLE
FTBLib mod dependencies are not all lowercase

### ISSUE THREAD

**Issue by mezz** [LatvianModder/FTBUtilities#519]
https://github.com/LatvianModder/FTBLib/blob/703890b11611b58b3b677ffa03cf55fae0a7f3d4/src/main/lib/com/feed_the_beast/ftbl/lib/internal/FTBLibFinals.java#L12-L23

Dependencies with uppercase ModIds will not work as intended, since all modIds must be lowercase.

**Comment by LatvianModder** [comment]
Fixed in https://github.com/LatvianModder/FTBLib/commit/025b903dec342646596ab08805173d6140936de5
