### ISSUE TITLE
(Bug) FTB Utility Chunk Loading in RFTools Dimensions

### ISSUE THREAD

**Issue by dbridle** [LatvianModder/FTBUtilities#52]
Hello,

I'm using FTB Infinity and have noticed that chunk loading in RFTools dimensions doesn't seem to work right.

I have a void world (just a void terrain dimlet). I have built a small platform and stuck my AE system on there, with an ender chest and an import bus. I chunk loaded the base using FTB Utilities.

I have an enderman spawner, 500 blocks away, feeding to the ender chest linked to the one on my AE system. Again, I have chunk loaded this area too.

The items are not transferring between the ender chests, even though the area is chunk loaded. I will also report this on the RFTools issues log.
Many thanks

Tirm

**Comment by Goten87** [comment]
the chunk needs to be red not green to be chunkloaded you do this with ctrl+leftmouse click
if you have red i have sayed nothing
green is only that you have claimed that chunk

**Comment by dbridle** [comment]
Thanks for response, it is all red, just double checked it.

**Comment by LatvianModder** [comment]
Infinity hasnt got an update yet, this was fixed ages ago :)
