### ISSUE TITLE
Backup sometimes creates incomplete/corrupted zip file

### ISSUE THREAD

**Issue by brdagr** [LatvianModder/FTBUtilities#520]
Hi, I am running a FTB server on Debian 9 Stretch and recently the backup command is creating incomplete/corrupted zip files. The pack is FTB Beyond v1.11.0, unmodified.

My java version (from `java -version`) is:

> 
> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

I have created 20+ successful backups of my world (I'm the only one playing on it) without any issue, but I think now that the world file is over 100MB in size the backup command is having issues.

The exact commands I use in my backup script are:

```
save-off
save-all
backup start my_world
save-on
```

The command I am using to unzip the world files:

`/usr/bin/unzip /home/backups/my_world.zip -d /home/ftb/FTBBeyond/my_world`

Until my most recent backup the world files would unzip without an issue, but now I have gotten the error:

> Archive:  /home/backups/my_world.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of /home/backups/my_world.zip or
>         /home/backups/my_world.zip.zip, and cannot find /home/backups/my_world.zip.ZIP, period.

A workaround that I have found is to use the jar command to unzip the file, since apparently it doesn't check for an end-of-archive signature before starting to unzip.

The jar command that I used I got from [here](https://askubuntu.com/questions/54904/unzip-error-end-of-central-directory-signature-not-found) is

`jar xvf my_world.zip`

and after it unzipped a few files from my_world.zip it errored out like this:

> java.io.EOFException: Unexpected end of ZLIB input stream
> 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
> 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
> 	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
> 	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
> 	at sun.tools.jar.Main.extractFile(Main.java:1072)
> 	at sun.tools.jar.Main.extract(Main.java:981)
> 	at sun.tools.jar.Main.run(Main.java:311)
> 	at sun.tools.jar.Main.main(Main.java:1288)

Using this method I am able to extract most of the world file's data, like DIMS and regions. However some files are still missing, but a solution is to substitute the missing files with the files from the most recent working backup.  The world worked and loaded, however immediately after logging in I created another backup, and this backup had the same issue as the former did; the end-of-central-directory error when unzipping.

Oddly enough when I then used my server stop script, which creates a world backup before stopping the server, it created a backup that actually didn't have a problem unzipping. *confused face*

The list of files in the most recently working zip file:
https://imgur.com/a/L1ruq
The list of files in the non-working zip file:
https://imgur.com/a/cqERc

So, somewhere between the files/directories that both zip files share and the ones that are missing is where the error happens from the backup command.

Something I've ruled out:
Storage space is NOT an issue. The server I'm using has a 2TB hard drive, so old backups (of which there are only 23) aren't the issue.

Something I'm not sure about:
I run the FTB server jar via a "screen" terminal so I am able to exit the SSH console without causing the server to terminate. Therefore to send commands to the server console from the terminal I have to pass them through screen. The result looks likes this:

```
#!/bin/bash
screen -S ftb -X stuff 'save-off\n'
sleep 1
screen -S ftb -X stuff 'save-all\n'
sleep 5
screen -S ftb -X stuff 'backup start my_world\n'
sleep 5
cp /home/ftb/FTBBeyond/backups/my_world.zip /home/backups/
screen -S ftb -X stuff 'save-on\n'
sleep 1
```

I have the "sleep"s in there to give the server enough time to complete their tasks before the next one is executed, and this seems to be working fine. The server console output from FTB utilities shows the backup and compression completed in like 0.7 seconds. But anyways, could this be an issue? If so, is there any way to get 100% confirmation from the server that the backup is 100% completed before copying it to my backup folder?

Thank you for your time in reading, and sorry for the wall of text. Please ask for any more information if required.

**Comment by LatvianModder** [comment]
1) Its most likely creating corrupted .zip files instead of multipart/non-zip.
2) You dont have to run save-off, save-all, save-on commands, the backup command does the same thing at right times so it shouldnt be a problem (or maybe thats what the problem is?)
3) I dont support older versions of my mod, but in newest versions  I have added a couple more `try/catch` which should prevent the zip from being broken mid-compress/write in case something happens to files
