### ISSUE TITLE
When typing in chat the message cycles between Gray & White.

### ISSUE THREAD

**Issue by Gbergz** [LatvianModder/FTBUtilities#521]
^Title

Yes, when i type in chat the message color cycles between Gray & White.
I tested this without any other mods, (clean install) and then i installed FTB Utilities & Lib. And this happens.

[1.12.1]
Forge version: 14.22.1.2485

Screenshot here:
[https://i.imgur.com/uM45Ar6.png](https://i.imgur.com/uM45Ar6.png)

**Comment by LatvianModder** [comment]
That's not a bug. There is a config option for that
