### ISSUE TITLE
See which chunks are chunkloaded vs claimed chunks

### ISSUE THREAD

**Issue by mcdodge34** [LatvianModder/FTBUtilities#524]
You've made some changes in the way the chunkloading map shows us which parts are claimed and chunkloaded but now we can't tell which chunks are chunkloaded vs just claimed chunks, if its possible to change the color around chunks that are chunkloaded, that would be very helpful when you just wanna make sure your new build is correctly chunkloaded, a tooltip notification when we hover on the map could also be very useful. So far I can't be 100% sure your changes to the chunkloading are working or not cause I have no real farms or automation going on, but my manual farms are growing up nicely and power from my wind generators is accumulating along with my ore processing plan working fine while I'm not around.

**Comment by LatvianModder** [comment]
Actually, It's a bug. I discovered it today too, that loaded chunks arent visible as such in multiplayer. It works in singleplayer though

**Comment by mcdodge34** [comment]
Also, maybe at the same time, would be cool to have the option to see when we enter and exit our claimed chunk area, I barely notice it now with the new way its showing, maybe offer an option to see it like it was before and maybe customize where its on the screen so people that complained about it could place it where they want or use the new one that isn't exactly clearly visible.

**Comment by ebranson1969** [comment]
First of all, Thanks for making you code available. I am wondering if I am have the same issue. I have claimed 320 chunks and have 120 loaded chunks. The view seems to be working for me. when I enter the command /ftb loaded_chunks_list the gui opens up and it shows that only 25 chunks are loaded. Am I reading the window wrong. l have 4.0.3 and FTBLib 4.0.5. It looks like the last time I downloaded was in 8/17/2017. Thanks in advance

**Comment by LatvianModder** [comment]
You have an old version @ebranson1969. In that version, it was broken and didn't load more than 25 chunks. You have to manually set `maximumChunksPerTicket` to 1000000 for `ftbu` in forgechunkloading.cfg or something

**Comment by ebranson1969** [comment]
Can't believe I missed that. I updated 4 values in forgechunkloading.cfg. That fixed my issue. Thanks for responding.

defaults {
    # Are mod overrides enabled?
    B:enabled=true

    # The default maximum number of chunks a mod can force, per ticket, 
    # for a mod without an override. This is the maximum number of chunks a single ticket can force.
    **I:maximumChunksPerTicket=1000000 <- was 25**

    # The default maximum ticket count for a mod which does not have an override
    # in this file. This is the number of chunk loading requests a mod is allowed to make.
    **I:maximumTicketCount=500 <- was smaller**

    # The number of tickets a player can be assigned instead of a mod. This is shared across all mods and it is up to the mods to use it.
    **I:playerTicketCount=500<- was smaller**


    # Unloaded chunks can first be kept in a dormant cache for quicker
    # loading times. Specify the size (in chunks) of that cache here
    **I:dormantChunkCacheSize=5000 <- This was 0**
}
