### ISSUE TITLE
Documentation missing and/or incomplete

### ISSUE THREAD

**Issue by SethWilliamson** [LatvianModder/FTBUtilities#525]
All configuration options should be documented with an explanation of their function, acceptable range of values, and default values.

Judging from how commonly I see threads on various sites trying to figure out how to configure things like backups, I'd say this is needed.

**Comment by LatvianModder** [comment]
All that is in? Did you check local/ftbu/config.cfg or the config gui before posting this? :v

**Comment by SethWilliamson** [comment]
Apologies. It seems I was on an older version. There was no config GUI, the config was json, and thus not commented, and the included all_configs.html only had a few fields for tanks.

**Comment by LatvianModder** [comment]
Oh, the config gui is where the rest of mods have it now - from ingame Esc -> Mod Config or from main menu - Mods. Select FTBUtilities/any other mod and click Config

**Comment by ktole1999** [comment]
not sure if its just the Age of Engineering pack or not but both options are greyed out. no access to config. I can select config on some of the other mods but not for ftbu.

FTBUtilities-1.1x-3.6.5
forge 12.18.3.2477

**Comment by LatvianModder** [comment]
That wasnt in until 1.12, back then you need to use `/edit_config ftbu`
