### ISSUE TITLE
What was changed?

### ISSUE THREAD

**Issue by EmosewaGamer** [LatvianModder/FTBUtilities#527]
So my pages don't work on version 4.1.6. What do I have to change now?

**Comment by LatvianModder** [comment]
The guides will soon be moved to online repository, kinda like badges, everyone will be able to submit their guides. But for now, you can move all pages.json inside guide.json. see FTBUtilities/Yabba for example

**Comment by LatvianModder** [comment]
oh, and also removed $lang.key, replaced with vanilla's {"translate":"lang.key"}
