### ISSUE TITLE
JourneyMap <-> FTBU Integration

### ISSUE THREAD

**Issue by Goten87** [LatvianModder/FTBUtilities#53]
can you talk to the maker of journeyMap to make a API so you can implent functions to it like the chuck claiming and loading

will be nice if we can get rid of that little map u have and just select what we want on JourneyMap

**Comment by Goten87** [comment]
lol oke i just seen that you have added some support for it is that for JourneyMap or a other thing

**Comment by LatvianModder** [comment]
Aye. We have talked with JM devs about this for a long time, and I just recently started implementing claimed chunk display directly on minimap

**Comment by Goten87** [comment]
Oke nice will it be only minimap or will this extent to the full map as well also to select the chunks and stuff

**Comment by LatvianModder** [comment]
That depends on how API works, but I think it will go in both

**Comment by Goten87** [comment]
oke hope you can do all things u want to do with JM

**Comment by LatvianModder** [comment]
Was added a while ago, never closed the issue. http://imgur.com/a/EI8gj

**Comment by Dijkstra1** [comment]
What version is, I am guessing not 1.7.10, if you had linked the commit i could have check the branch.

**Comment by LatvianModder** [comment]
Nope, nothing new will be added in 1.7.10, and even bugs probably wont be fixed. Need to push 1.9.4+ asap

**Comment by kzkv** [comment]
I'm on FTBU 3.0.2 and JourneyMap 5.2.4 (Forge 2105; Minecraft 1.10.2) and this integration doesn't seem to work. Should I switch it somehow? 

I also noticed that in Allthemods pack with somewhat recent versions of the mods there's no overlay also. 

Thanks!

**Comment by LatvianModder** [comment]
Yes, the integration has been disabled for until I fix it. It will be back soon, though, don't worry, it just doesnt have high priority on my to-do list

**Comment by paintballkev812** [comment]
Is there an ETA on when this will be re-added?

**Comment by LatvianModder** [comment]
I could try to work on it for 3.2.10/3.2.11

**Comment by Mochnant** [comment]
Is there a way to disable the claimed chunks?  I find it hard to use the minimap with the blue chunks visible.

**Comment by LatvianModder** [comment]
Yes, in Client Config look for Journey Map

**Comment by Lurmey** [comment]
Has this been removed? I can't seem to find it in version 5.0.0.11. :/

**Comment by LatvianModder** [comment]
Yes, at the time I was updating, JM was quite broken, and I'm still not sure if I want to re-add integration, there were always problems with it

**Comment by aplomBomb** [comment]
Hey there Latvian, I'm having issues with FTBU claims simply not displaying on the JM minimap, I believe that falls under this issue?
