### ISSUE TITLE
NoClassDefFoundError crash

### ISSUE THREAD

**Issue by hugeblank** [LatvianModder/FTBUtilities#537]
I really am not sure what would be causing this, it looks like it's asking for something from Mcjtylib...
[crash-2017-10-01_10.55.42-client.txt](https://github.com/LatvianModder/FTBUtilities/files/1347387/crash-2017-10-01_10.55.42-client.txt)
I'm only using FTBLib, and FTBUtilities, I wanted to see exactly how they worked, and right off the bat I'm getting crashes...

**Comment by LatvianModder** [comment]
You are missing CompatLayer, it was required for 1.10/1.11 versions

**Comment by hugeblank** [comment]
ah... can you mention that somewhere in the description of the mod?

**Comment by LatvianModder** [comment]
Sure, ill add that
