### ISSUE TITLE
The FTBUtilities-1.1x-3.6.5 isn't work on 1.10.2 with the latest forge-12.18.3.2488!

### ISSUE THREAD

**Issue by N20w0** [LatvianModder/FTBUtilities#539]
Although the FTBUtilities-1.1x-3.6.5 isn't the latest version,I still want you to fix it.The 1.10.2 has many good mods,and I'm looking for a good residence plugin.The plugins of sponge are hard-to-use.So I'm looking forward you to fixing the version 3.6.5.

**Comment by LatvianModder** [comment]
Sorry, I don't backport mods. Most of the good mods are on 1.12 anyway
