### ISSUE TITLE
admin UI ingame

### ISSUE THREAD

**Issue by Goten87** [LatvianModder/FTBUtilities#54]
donno if there are plans for it alrdy but somthing to let a Admin of a server to edit stuff for the mod in a special UI
for exemple the login massage
or ranks players have

also somthing to let us select usernames in the welcome massage will be nice somting like %u that will chance to the username of the person 
so i can make somthing like Welcome %u to <servername>
and that will become for me then Welcome Goten87 to <servername>

**Comment by LatvianModder** [comment]
a) there is /edit_config ftbu
b) you Can do that with &player& IIRC
