### ISSUE TITLE
[1.10.2] FTB Utilities Crash- No Such Method error

### ISSUE THREAD

**Issue by vasillisa** [LatvianModder/FTBUtilities#540]
Hey there. I am having this crash and was hoping you could help me fix it so I can use your mod. I'd really like to be able to use it but I cant get it to work on my server.
[crash-2017-10-02_16.13.13-client.txt](https://github.com/LatvianModder/FTBUtilities/files/1353680/crash-2017-10-02_16.13.13-client.txt)

**Comment by LatvianModder** [comment]
You haven't updated FTBUtilities to latest version
