### ISSUE TITLE
Warp permissions.

### ISSUE THREAD

**Issue by Zelow79** [LatvianModder/FTBUtilities#541]
Hello, we spoke briefly on your reddit and you asked me to drop the official suggestion here. Just wanted to make the suggestion for adding some type of permissions option to allow players/ranks to be able to use specific /warp commands based from the users custom made warps. Not sure if it is helpful or not, but I was thinking a good way to make the permissions is to keep the ftb.warp, but maybe make it so you can add to it for when you want to give someone a specific warp access. Something like, if the warps name was say nether you could give a player or rank permissions to ftb.warp.nether. These are just idea's and you could probably come up with something even better, but either way, I felt this was worth the suggestion.

Zelow.

**Comment by LatvianModder** [comment]
Added special `command.ftbutilities.warp.teleport.x` permission

**Comment by Runburner** [comment]
So this permission for ranks no longer appears to work at all and isn't in the auto complete list when using tab in trying to set permissions in game.  I'm unable to fin the all_permissions.txt that is mentioned in the FTB book wiki for ranks and googling ins't giving me any proper documentation either unfortunately.

**Comment by Zelow79** [comment]
> Added special `command.ftbutilities.warp.teleport.x` permission

Maybe I am trying an outdated version, what version was this added in? I am using v5.4.1.129 from the ATM3 modpack.
