### ISSUE TITLE
Config Location Change/Reset

### ISSUE THREAD

**Issue by mrdeadlocked** [LatvianModder/FTBUtilities#542]
I'm on the newest version of FTBU and the config has changed location to /local/ftbutilities/config.cfg. Ive tried to edit this to match my old config (even copied the old config over) but on /ftb reload the config goes back to default.

**Comment by LatvianModder** [comment]
Oh. I completely forgot that there are other files than config there too, like ranks etc... Oops

**Comment by mrdeadlocked** [comment]
Its alright. I only noticed it because my server ran out of space. :-) Backups every 2 hours fills it up fast!
