### ISSUE TITLE
Chunk loading disables some blocks

### ISSUE THREAD

**Issue by NanobotZ** [LatvianModder/FTBUtilities#546]
I've set up a 7x7 chunk loading via the Claimed Chunks window. Basically every time I leave my base/server and come back later, some weird things happen to SOME (not on all chunks) blocks like:
- Mechanical User from Extra Utilities 2 - stops using any item inside, has to be destroyed and placed back, because changing settings doesn't do anything,
- Servo from Thermal Dynamics - basically disappears from the pipe it was previously attached to, had to be placed again,
- any Machine from Thermal Expansion - resets all the set up outputs/inputs, has to be manually reconfigured,
- Farmer from Actually Additions - stops working and has to be broken and placed back again,

I bet there may be more broken blocks/mods, but things like Applied Energistics 2 works all the time.

Server is hosted on my PC on clean forge (version forge-14.22.0.2469) and has 4GB of RAM allocated to it (never seen any errors with not enough memory or something), and I'm using FTB Unstable 2.0.3 modpack (FTB Utilities version is 4.0.3).
Latest logs: https://pastebin.com/KV2BxRP5

**Comment by LatvianModder** [comment]
4.0.3 is way outdated, issues have been fixed long ago
