### ISSUE TITLE
GUI dosen't show up... (1.7.10)

### ISSUE THREAD

**Issue by Khana-an** [LatvianModder/FTBUtilities#547]
I've installed FTB Utils and FTB Lib in client and server... both the same version but the 'claim chunks' and the other buttons dosen't show up... just 'Client settings' are visible.... what can i do? 
PLS HELP...

**Comment by LatvianModder** [comment]
Which versions have you installed?

**Comment by LatvianModder** [comment]
Has the server said anything about mods erroring or not loading? Are the mods even present when server runs? You can check if /admin backup works

**Comment by Khana-an** [comment]
Yeah... I already solved it... Just forgot to restart the server... Thanks for the help and sorry I didn't used my brain...
