### ISSUE TITLE
How do i make machines/tile entities from a mod compatible with claimed chunks? (compatibility question)

### ISSUE THREAD

**Issue by PrinceOfAmber** [LatvianModder/FTBUtilities#548]
I have a report/request to make my blocks compatible with claimed chunks, so if a machine is in a claim, non team members cannot access it.  https://github.com/PrinceOfAmber/Cyclic/issues/547

I tried some google searches and I looked for a wiki page or any explanations on how to do this but i couldnt find anything ( http://guides.latmod.com/guide/?id=ftbu ).

Do i have to do something in the container function

`  public boolean canInteractWith(EntityPlayer playerIn) `

Or is at the tile entity level?  Do I have to call the right vanilla function in a certain hook, or is there an API?

**Comment by LatvianModder** [comment]
Mods dont have to do anything, FTBUtilities takes care of it all, unless you open guis on client side for some reason, which you shouldn't ever do

**Comment by LatvianModder** [comment]
oh i see the problem, you have commented out world.isRemote

**Comment by PrinceOfAmber** [comment]
Oh you mean in this line, in the onBlockActivated  https://github.com/PrinceOfAmber/Cyclic/blob/3c7f24fee012bc67367ee1ba228d48011943f980/src/main/java/com/lothrazar/cyclicmagic/block/base/BlockBaseHasTile.java#L30

Which means this runs both client and server

`player.openGui(ModCyclic.instance, this.guiID, world, x, y, z); `


I forget why i removed that.  Ill add it back in and check it out, thanks for the input!

**Comment by LatvianModder** [comment]
actually, you should move it lower - check if guiId isnt -1, and inside that, open gui if !world.isRemote, but always return true

**Comment by PrinceOfAmber** [comment]
Thanks for the feedback again!

**Comment by PrinceOfAmber** [comment]
The problem with this now is that when a Hopper or pipe is connected to the inventory, client does not get updates about item slots changing. so, fill up with items, connect hopper below, open GUI, items are dissapearing but i do not see them in GUI.

So if i cant open this clientside here then, i need some other way to live-sync inventory slots i guess
