### ISSUE TITLE
Buckets bypassing claims

### ISSUE THREAD

**Issue by rob5251** [LatvianModder/FTBUtilities#55]
I'm able to use water and lava buckets within someones claim (modded liquids work too), I'm not added as a friend and the area is set to private. (also was not in OP or Creative when testing)

Version
FTBUtilities - 1.7.10 - 1.0.17.1
FTBLib - 1.7.10 - 1.0.17.2

**Comment by LatvianModder** [comment]
Marking this as suggestion, because It's not something that is implemented. I left air-right click (and bucket counts as clicking in air), so you can use some teleporter items, glider, jetpacks etc

**Comment by rob5251** [comment]
Ah, I just figured you wouldn't want someone dumping liquids inside your claim.
Good to see that it may get implemented then. :+1:

**Comment by filthyfreak** [comment]
I'd like to add that the golden lasso from Extra Utilities can be used to steal mobs from protected areas (For example, players can use it to steal custom-made villagers from player/admin shops).

Figured i'd put it here since it's pretty much the same issue.
