### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by KeyNapper** [LatvianModder/FTBUtilities#551]
I'm running a DW20 1.10.2 server updated to v.1.13 with the 3.6.5 FTBU jar.  We don't seem to have any chat functions.  The ftb.chat.* entry isn't in permissions.  Is this broken or do I need to add something to the .cfg to make chat available?

**Comment by LatvianModder** [comment]
3.6.5 is an ancient version of the mod, current one is 4.2.1

**Comment by KeyNapper** [comment]
Thanks for the reply.  I had noticed the 4.x versions out there, but they are listed as for MC 1.12.  Is the 4.21 backwards compatible with 1.10.2?  Just trying to sort this out as it’s the first time we’ve tried an FTB server and mod pack.

AMc
