### ISSUE TITLE
Players can break item frames in claimed chunks

### ISSUE THREAD

**Issue by PapiDimmi** [LatvianModder/FTBUtilities#552]
FTBU version: 4.2.0
FTBLib version: 4.2.1
Modpack: ATM 3 (version 4.3)
MC version: 1.12.2

**Comment by LatvianModder** [comment]
Hm, yeah, item frames are entities, not blocks. I guess I should add all non-living entities [boats, item frames, end crystals, minecarts, etc..] under block breaking permission...

**Comment by PapiDimmi** [comment]
@LatvianModder How about mobs as well? Players shouldn’t be able to kill your animals in your protected chunks.

**Comment by PapiDimmi** [comment]
I agree. All entities aside from hostile mobs should be protected within claimed chunks, in my opinion.

Same goes for friendly zombie pigmen and spiders.

**Comment by PapiDimmi** [comment]
Also, can you protect liquids as well so that people can’t take your liquids with a bucket in your claimed chunks?

**Comment by LatvianModder** [comment]
Isnt that already working? I tested this with buckets some time ago and it worked, dunno

**Comment by PapiDimmi** [comment]
It doesn’t. I tested on a LAN server.

**Comment by PapiDimmi** [comment]
It doesn’t. I tested on a LAN server. It was a modded liquid, though.

**Comment by PapiDimmi** [comment]
Also, you should protect from jumping on crops and harvesting them with right-click (which some mods allow you to do).

**Comment by LatvianModder** [comment]
Can't protect from those things. there is no event for breaking crops

**Comment by PapiDimmi** [comment]
Really? Okay.

But I think that as many things should be protected as possible: non-hostile mobs, other entities (item frames, minecarts, paintings, etc.), fluids, and so on.

**Comment by PapiDimmi** [comment]
Also, can you protect doors, levers, buttons, etc. in a claimed chunk?

**Comment by LatvianModder** [comment]
yes. I have added doors to whitelist by default, but you can remove them too. Doors are whitelisted, in case you get stuck in someone's claims and you need to get out. Since you can't break/open anything anyway, it shouldn't be a problem

**Comment by PapiDimmi** [comment]
>Since you can't break/open anything anyway, it shouldn't be a problem

I mean, you can break some items.

I also found a bug where you can open a chest or other protected block in a claimed chunk if there’s an item frame on top of it (i.e., an item frame lying on top of the block, a feature that Quark adds), if you right-click the item frame.

Not sure if Quark bug or FTBU bug.

**Comment by LatvianModder** [comment]
quark bug. it should fire the rightclick event, so I can catch it

**Comment by PapiDimmi** [comment]
@LatvianModder I assume that I need to edit the _all_permissions_full_list_ file in order to remove doors from the whitelist, but I’m not sure what to change exactly.

**Comment by LatvianModder** [comment]
no, you edit ranks.json, all_x files are just for you to see what permissions exist. Read the ranks guide

**Comment by PapiDimmi** [comment]
I did, but it’s confusing.

Could you please tell me what I would have to add to the ranks.json file to protect doors, trapdoors, etc. in claimed chunks?

**Comment by PapiDimmi** [comment]
Never mind. Someone else helped me.

Anyway, creepers also break item frames (and the items within them) upon exploding in claimed chunks, even though they are supposed to not break any blocks. They probably also break or kill other entities, such as minecarts, animals, etc.

**Comment by LatvianModder** [comment]
Well, I don't think I can protect explosions from destroying entities without breaking some things

**Comment by Autopoietico** [comment]
Thanks for the fix!

**Comment by PapiDimmi** [comment]
@LatvianModder Thanks.
