### ISSUE TITLE
Cheat commands available to all players

### ISSUE THREAD

**Issue by PapiDimmi** [LatvianModder/FTBUtilities#553]
/warp, /spawn, and /back are available to all players by default.

**Comment by LatvianModder** [comment]
Yes, that's intended? You can remove those commands with permissions...

**Comment by PapiDimmi** [comment]
How do you have permissions without Bukkit plugins?

**Comment by ktole1999** [comment]
you need a permissions mod.

**Comment by PapiDimmi** [comment]
I don’t think that they should be available by default.

**Comment by LatvianModder** [comment]
What? You FTBUtilities *is* a permission mod
