### ISSUE TITLE
Let us see chunks even if we aint in a team damn it

### ISSUE THREAD

**Issue by TheCodedOne** [LatvianModder/FTBUtilities#554]
Pls latvian daddy, let us see chunks even if we ain't in a team, i cant bare having to click 4 buttons to make a team to see the claimed chunks menu :(

**Comment by AmazigJj** [comment]
*3 buttons if you dont waste time picking a colour

**Comment by TheCodedOne** [comment]
2 buttons if you're latvian daddy

**Comment by AmazigJj** [comment]
1 button if they let you not need a team
