### ISSUE TITLE
Resourcepack/Future Guides?

### ISSUE THREAD

**Issue by VT-14** [LatvianModder/FTBUtilities#556]
My (currently noncommittal) idea is to start writing unofficial guides for mods that can be dropped into almost any modpack.  FTB Utilities is extremely common, and it was briefly mentioned in [some of the documentation](http://guides.latmod.com/) that guides could be "loaded from assets / resourcepacks."  So far, I've had some success in testing by overwriting one of the FTBUtilities guides, but I'm having trouble getting the same guide with a different name from appearing in-game.  I would like to avoid a dependency on Resource Loader if possible.

Specifically, I can get PackTitle/assets/writing_guides/... to show up in game, but PackTitle/assets/test/... does not

While looking around here, I also saw that Guides will be moving 'online.'  Can I get some elaboration on what that means?  I'm most curious on where guides would need to be uploaded, how the player would access them, and if multiplayer players could add guides to their clients without needing changes to a server.

**Comment by LatvianModder** [comment]
Resource Loader mod allows to load assets from resources/ folder (normally, that only happens from mod jars and addded resourcepacks), and that's where they should be loaded. If you have resourceloader, I think the path is `./resources/test/guides/...`

Online guides is still a WIP idea, but the main idea is that I will have a public repository listing all guides available on net (usually from GitHub). And you could download guides from ingame, for any mod or modpack, and update them without need to update mods/modpack
