### ISSUE TITLE
(1.12.2, server-side) poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [LatvianModder/FTBUtilities#557]
Hey ! I was launching my server, and poooooof! crashes.
Here is the crash : 
[crash-2017-10-28_14.06.13-server.txt](https://github.com/LatvianModder/FTBUtilities/files/1424237/crash-2017-10-28_14.06.13-server.txt)

**Comment by Sunconure11** [comment]
Can confirm that this error is also happening on singleplayer.

**Comment by Diamondman121314** [comment]
This is because of the new Forge version that was released, even the suggestions were made by LatvianModder, so you'll most likely see an update to this very soon.

[https://github.com/MinecraftForge/MinecraftForge/issues/4444](url) (If you're curious)

**Comment by Migmag789** [comment]
Thank you :D

**Comment by LatvianModder** [comment]
aw dang, that breaks my mod? welp

**Comment by Migmag789** [comment]
Yes :/
