### ISSUE TITLE
Can't disable backup completely.

### ISSUE THREAD

**Issue by jc2xs** [LatvianModder/FTBUtilities#559]
I want the other features of FTBU but I do my backups via a linux script.  On the older versions of FTBU this wasn't an issue I could disable FTBU's backups.  This new one all I can seem to do is tell it to keep 1 backup and increase the timer to the maximum.  There really needs to be a way to disable the backups.

**Comment by LatvianModder** [comment]
wot. there is backups.enabled option.. set that to false..

**Comment by jc2xs** [comment]
So these are the options listed in ftbu config.
    backups {
        # Timer in hours
        # 1.0 - backups every hour
        # 6.0 - backups every 6 hours
        # 0.5 - backups every 30 minutes
        # Min: 0.05
        # Max: 600.0
        D:backup_timer=2.0

        # The number of backup files to keep
        # More backups = more space used
        # 0 - Infinite
        # Min: 0
        # Max: 32000
        I:backups_to_keep=12

        # 0 - Disabled (output = folders)
        # 1 - Best speed
        # 9 - Smallest file size
        # Min: 0
        # Max: 9
        I:compression_level=1

        # Prints (current size | total size) when backup is done
        B:display_file_size=true
        B:enabled=true

        # Absolute path to backups folder
        S:folder=
        B:silent=false

        # Run backup in a separated Thread (recommended)
        B:use_separate_thread=true
    }

No where do I see that setting.

**Comment by Alaberti** [comment]
See where it says enabled=true? Set that to false. It looks like it part of another option but that's what you're looking for iirc.

**Comment by jc2xs** [comment]
Thanks!  And yeah that does look like it is part of the  print status
