### ISSUE TITLE
GUI not showing up

### ISSUE THREAD

**Issue by Enekuda** [LatvianModder/FTBUtilities#56]
I installed FTB Utilities and FTB Lib and FTB Tweaks on my server and the only thing that shows up is the Client settings "gear" when you check your inventory (to the right of the inventory) no friends list or anything. i cannot find anything to help me get the other icons to display. i can provide my other installed mods list if needed otherwise im not running into any errors or anything.

**Comment by LatvianModder** [comment]
You must have the mods on your client too to see those buttons

**Comment by Enekuda** [comment]
I will try that then! Utilities is the only one it didnt prompt me to put in my client so ill throw that in and see it it works! 

Thanks.

**Comment by Enekuda** [comment]
That fixed it! Thanks! 
The only places i saw instructions for the mod indicated it was a server side only mod so i never put it in the client.
