### ISSUE TITLE
[1.12.2] FTB Utilities 4.2.1 backups do not run on client (SSP) game

### ISSUE THREAD

**Issue by sandalle** [LatvianModder/FTBUtilities#561]
When running a client-only game (SSP) in Minecraft 1.12.2 (Forge Mod Loader 14.23.0.2515) and FTB Utilities 4.2.1 while testing unreleased [NST World of Color modpack](https://minecraft.curseforge.com/projects/nst-world-of-color), configured backups do not run. I can manually run the backups.

local/ftbutilities/config.cfg
```
 backups {
        # Timer in hours
        # 1.0 - backups every hour
        # 6.0 - backups every 6 hours
        # 0.5 - backups every 30 minutes
        # Min: 0.05
        # Max: 600.0
        D:backup_timer=0.05

        # The number of backup files to keep
        # More backups = more space used
        # 0 - Infinite
        # Min: 0
        # Max: 32000
        I:backups_to_keep=12

        # 0 - Disabled (output = folders)
        # 1 - Best speed
        # 9 - Smallest file size
        # Min: 0
        # Max: 9
        I:compression_level=1

        # Prints (current size | total size) when backup is done
        B:display_file_size=true
        B:enabled=true

        # Absolute path to backups folder
        S:folder=
        B:silent=false

        # Run backup in a separated Thread (recommended)
        B:use_separate_thread=true
    }
```

Forge in-game Config also confirms these settings are the "live" settings being used.

I should be getting a backup every 3 minutes (for testing), but I see none being created (game is not paused).

Another person on our Discord chat, I believe using [Modern Skyblock 2](https://minecraft.curseforge.com/projects/modern-skyblock-2) modpack, reports a similar issue and their frequency is set to two hours.

**Comment by LatvianModder** [comment]
Are you sure they are not happening? They are for me. The status message even is displayed with correct times etc. So im gonna close this one for now
![image](http://ss.latmod.com/pc/2017-11-03_12.47.55.png)

**Comment by sandalle** [comment]
Weird. I made a new world with default FTB Utility configs (also updated to Forge Mod Loader 1.12.2-14.23.0.2532) and in a SSP instance I also had the server backup run. It wouldn't run at all in my earlier attempted "quick" test (3 minute interval) to test what a user had reported to me when I reported this.
