### ISSUE TITLE
[1.12.2] Commands and Chat

### ISSUE THREAD

**Issue by BuilderDan** [LatvianModder/FTBUtilities#563]
Every time I click on the team things I get an internal error, it occurs with numerous other aspects of the mod, not sure why I can provide more information if necessary. 
![image](https://user-images.githubusercontent.com/19805371/32238497-27a0c5b4-be25-11e7-9f10-d453a4e98f1f.png)

**Comment by LatvianModder** [comment]
It was fixed already, you must have an old version

**Comment by BuilderDan** [comment]
Yep, sorry about the confusion!
