### ISSUE TITLE
Client crash to server list while doing /help

### ISSUE THREAD

**Issue by kreezxil** [LatvianModder/FTBUtilities#566]
While using version 1.1x-3.6.5 for 1.11.2 and typing /help <page>, when on page 3 the client crashed to server list
[![https://gyazo.com/df8dde615010e2573c85aa7167d02b95](https://i.gyazo.com/df8dde615010e2573c85aa7167d02b95.png)](https://gyazo.com/df8dde615010e2573c85aa7167d02b95)

latest.log as it didn't create a crash report from the client: https://pastebin.com/wFGQy3nA

**Comment by LatvianModder** [comment]
>1.11.2
nope
