### ISSUE TITLE
Can’t lock doors in claimed chunks

### ISSUE THREAD

**Issue by PapiDimmi** [LatvianModder/FTBUtilities#567]
This is my ranks.json file:

```
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [
        "-ftbu.claims.block.interact.minecraft.wooden_door",
        "-ftbu.claims.block.interact.biomesoplenty:fir_door_block"
      ],
      "config": {
        "ftbu.claims.max_chunks": 250,
        "ftbu.chunkloader.max_chunks": 50
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}
```

Other players can still open claimed fir doors from Biomes o’ Plenty.

Oak doors can’t be opened, though, so for some reason, it doesn’t work with Biomes o’ Plenty doors.
Also, Terraqueous doors cannot be opened in claimed chunks even though they are not listed in the permissions.

**Comment by LatvianModder** [comment]
You have `biomesoplenty:fir_door_block`, but you need `biomesoplenty.fir_door_block`

**Comment by PapiDimmi** [comment]
@LatvianModder Thank you.

Do you know if there is a way to protect all doors and trapdoors in claimed chunks, modded and vanilla, without having to list each block ID separately?

**Comment by PapiDimmi** [comment]
@LatvianModder Thank you.

By the way, do you know if there is a way to protect all doors and trapdoors in claimed chunks, modded and vanilla, without having to list each block ID separately?

**Comment by LatvianModder** [comment]
nope. You can do a domain with `ftbu.claims.block.interact.minecraft.*` but not individual doors, since the IDs are very different. Maybe in 1.13/late 1.12 it will be easier

**Comment by PapiDimmi** [comment]
What do you mean by “late 1.12”? Will there be another 1.12 version?

**Comment by LatvianModder** [comment]
There was something planned for Forge that would make it easier to distinguish between different objects.. This might be the issue https://github.com/MinecraftForge/MinecraftForge/issues/3977, not sure. I can't find the one with huge discussion. Basically, to replace OreDictionary. so all doors would have "door" or something like that (like all ingots are "ingotIron", "ingotGold" right now, they would be ["ingot", "iron"], ["ingot", "gold"]. Or at least, I think that's the idea)
