### ISSUE TITLE
Stopping FTB Utilities from restarting computer

### ISSUE THREAD

**Issue by starr274** [LatvianModder/FTBUtilities#568]
Just wondering if its possible to have a config that blocks ftb utilities from restarting a singleplayer computer, without removing or disabling the mod from ftb modpacks or others that use it, or if it exists can it be added to a config in the local/ftbu file ? The repeatable seems to be in different versions of MC and packs until FTB Utilities is deleted from the pack

**Comment by LatvianModder** [comment]
If it's latest version, you can turn off auto shutdown in `local/ftbutilities/config.cfg` `general->auto_shutdown->enabled=false`
