### ISSUE TITLE
Horizons 3 crash ftb utils

### ISSUE THREAD

**Issue by unstablecraft** [LatvianModder/FTBUtilities#569]
forge 1.12.2 version 2532
spongeforge version: 1.12.2-2529-7.0.0-BETA-2732
java8
pack version: horizons3  1.2.0 (beta)

https://pastebin.com/HKrXeAsx

**Comment by unstablecraft** [comment]
https://pastebin.com/WH3t8scC crash-report without sponge

**Comment by LatvianModder** [comment]
Might be fixed in http://mods.latmod.com/FTBUtilities/4.2.3/

**Comment by unstablecraft** [comment]
fixed you may close this

**Comment by LatvianModder** [comment]
I will when I release the file

**Comment by LatvianModder** [comment]
Possible cause: Mojang name change / something to do with how teams/players are loaded. Must test that
