### ISSUE TITLE
Guide Book

### ISSUE THREAD

**Issue by pchard** [LatvianModder/FTBUtilities#57]
Hi.

Not really an issue, but I don't know where else to ask for help..

I don't really understand how I can make a guide book..
Where do I put the pages?

**Comment by LatvianModder** [comment]
You put text files in /modpack/<mode>/guide, typically, mode = default, so, page Test.txt you'd put in
`/modpack/default/guide/Test.txt`

**Comment by pchard** [comment]
Okay, but what is the format of the pages?

And do I put something in guide_links.json?

**Comment by LatvianModder** [comment]
guide_links.json is only for pictures for now. Format of pages is plain text. You can look at FTB Infinity's guides

**Comment by pchard** [comment]
Okay, so I have a file named "test.txt" inside /modpack/default/guide

But still, the guide book is empty..

**Comment by LatvianModder** [comment]
You can place guides in server/local/guide/. Also, could be that you are using an old version

**Comment by pchard** [comment]
Oh, okay.. just in /local/guide - Got it!

Do I need to restart the entire server ?

**Comment by LatvianModder** [comment]
You only need to /reload

**Comment by pchard** [comment]
Well, somehow it didn't work.. I only got the modpack/ thing to work though.

Here's how it is now:

https://pchard.gyazo.com/348eba4f13f15ddd4d4a27e8d88aae7f

https://pchard.gyazo.com/348eba4f13f15ddd4d4a27e8d88aae7f

Is this correct?

**Comment by LatvianModder** [comment]
Hm. Not sure, it should be ok. You can try restarting the server though. What FTBU version are you on?

**Comment by pchard** [comment]
FTBUtilities-1.7.10-1.0.17.1.jar

**Comment by pchard** [comment]
Somehow I got it working on the Server Info book.. However, I get alot of "Server Info" pages:

https://pchard.gyazo.com/04a68c55b89af74c6fd787b6b7f23011

**Comment by pchard** [comment]
Another question: How do I use /ftb_notify ?

I tried:

/ftb_notify player test

but then I get: "Invalid notification: test"

**Comment by LatvianModder** [comment]
It is json formatted. You can see an example in Server Info book > Commands > /ftb_notify

**Comment by pchard** [comment]
Yes, I got that, but where do I put the .json file??

**Comment by LatvianModder** [comment]
Theres no file, its something like this
/ftb_notify PlayerName {"id":"test","title":"Some Title"} etc

**Comment by jogi01** [comment]
my guide book is still empty, too. Did it in local folder as described.. nobody can explain it clearly. Very sad
