### ISSUE TITLE
no GUI

### ISSUE THREAD

**Issue by deviraux** [LatvianModder/FTBUtilities#570]
Just put together a mod pack for a couple friends and there is no gui in game for chunk claiming or anything all of the commands work but no gui. I have ftb lib and utilites installed on both server and client.

**Comment by LatvianModder** [comment]
what does `/ftb chunks gui` do?

**Comment by deviraux** [comment]
I figured it out a mod called camping was over writing the vanilla gui a simple config change fixed it! thank you for the responce none the less love your mod!
