### ISSUE TITLE
Server Crash on Chunk Claim

### ISSUE THREAD

**Issue by Sindusk** [LatvianModder/FTBUtilities#571]
FTB Horizons 3 Modpack:

The issue occurs when issuing the "/ftb chunks claim" command or using the interface from inventory to claim chunks. Possibly unrelated, but this issue occurred after undergoing a Mojang account name change.

https://pastebin.com/FGnNWtUY

**Comment by LatvianModder** [comment]
No, I think the name change could be very related

**Comment by LatvianModder** [comment]
Same crash from here https://github.com/LatvianModder/FTBUtilities/issues/569
