### ISSUE TITLE
Wither Builder from Industrial Foregoing doesn't work

### ISSUE THREAD

**Issue by Hurifire** [LatvianModder/FTBUtilities#572]
Version: FTBUtilities-4.2.3

This new version breaks the wither builder from Industrial Foregoing.
Only works with these permissions:
https://gyazo.com/832a63e8e986a48b32e5ca88d5b5b18a
I don't know if I need to report here or on the industrial foregoing code.

**Comment by LatvianModder** [comment]
Nah, it's FTBU issue, I think

**Comment by uehlbran** [comment]
Just disable or remove this mod. It's broken beyond all hope.
