### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Omegapsychosis** [LatvianModder/FTBUtilities#573]
Currently I am running an FTB Infinity Evolved: Expert Mode server for 1.7.10 and I was looking into setting up custom ranks using FTBUtilities, however any documentation on the subject seems wildly off of what is actually available ingame. Are there any plans to backport any future ranks updates to 1.7.10?

It would be of great ebnefit to server owners who dislike using Bukkit/Spigot and would prefer to use a purely Forge based server. Thank you.

**Comment by LatvianModder** [comment]
Sorry, no backports. You can try to figure out ForgeEssentials tho
