### ISSUE TITLE
local folder location.

### ISSUE THREAD

**Issue by power-spike** [LatvianModder/FTBUtilities#576]
Greetings, 

I have an issue. 

I run a linux server, and currently have 2 instances of a mod pack running. 

To easy management I have the following stucture. 
./UPLOADS/<PACK_VERSION>
/SERVERS/<SERVER>
I use the commands 
"ln -s ../../UPLOADS/<PACK_VERISON>/config config"
"ln -s ../../UPLOADS/<PACK_VERISON>/scripts scripts"
"ln -s ../../UPLOADS/<PACK_VERISON>/mods mods"

I am not sure what is happening, however when I update the packs, I remove the symbolic links, and create new ones to the new folder in uploads. 

Ftb Utilities is creating the "local" folder in the UPLOADS/<PACK_VERSION> folder instead of the SERVER/<SERVER> folder.

The appears to be getting the physical FULL path of the mod file instead of the location it was loaded from - causing the local folder to be loaded into the wrong location - and making the configuration files shared in between the instances which it should not be doing.

**Comment by LatvianModder** [comment]
The "local" folder isnt included in modpacks, so it doesnt need updating. If you have a modpack that has that folder, you should probably report that to pack author to removr it. Just like world or options.txt, its for local use only

**Comment by power-spike** [comment]
You are misunderstanding, the above - is where it is CREATING the folder After the server is launched. It is not been downloaded with the pack, or in the folders.
