### ISSUE TITLE
Sidebar OP buttons disappear after dimension change

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#577]
https://forum.feed-the-beast.com/threads/sidebar-toggle-buttons-disappear-when-using-nether-portal.261884/

**Comment by SadChimera** [comment]
Sidebar buttons are also overwritten and forced to the top-left if you are affected by a status (potions, nutrition boosts, etc). This might be considered a request, but I prefer FTB buttons to be on the left side of my inventory regardless of status effects. May be necessary to `@override` the method in mc forge. and displace the status gui to the left screen-border.

**Comment by dncspurs** [comment]
This is still happening. It seems to be only the nether and only if you have [NetherPortalFix](https://github.com/blay09/NetherPortalFix) installed.
