### ISSUE TITLE
Backup folders

### ISSUE THREAD

**Issue by PapiDimmi** [LatvianModder/FTBUtilities#578]
Ever since I changed the backup interval to 15 minutes and made it only keep 20 backups, rather than keep all of them, it’s been creating tonnes of empty folders. For every backup folder, there’s an empty folder created at the same time, and all the old backup folders are empty. Why isn’t it deleting these folders, and why is it creating two folders for every backup?

**Minecraft version**: 1.10.2
**FTBU version**: 3.6.5

**Comment by LatvianModder** [comment]
`Minecraft version: 1.10.2`
no

**Comment by PapiDimmi** [comment]
@LatvianModder What?

**Comment by LatvianModder** [comment]
Didn't you read what the window says when you press New Issue? `Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version`
