### ISSUE TITLE
offline mode profile copies

### ISSUE THREAD

**Issue by MaksMCM** [LatvianModder/FTBUtilities#580]
After accidentally enabling offline-mode ("cracked") on my server the stats messed up and now there are copies of every player who joined while the offline-mode was active... now the fried system is all messed up and chunk claiming is broken aswell. I already removed the offline player-data and the stats from world/stats/ 
also updated /world/LatMod/ files

**Comment by MaksMCM** [comment]
forgot to mention... mc version: 1.7.10

**Comment by LatvianModder** [comment]
Yeah, nothing I can do about 1.7.10 versions, in 1.12 it automatically fixes that. Maybe you have a backup
