### ISSUE TITLE
Disable Backup in 1.12.2

### ISSUE THREAD

**Issue by shawnbyday** [LatvianModder/FTBUtilities#583]
The 1.10.2 version had a disable feature in the config file backup section. The 1.12.2 version doesn't have this feature. I see a backup_timer option but it says the minimum is .05. Would setting this to 0 disable backups? I have another system that does my backups.

**Comment by LatvianModder** [comment]
https://www.reddit.com/r/feedthebeast/comments/7jkhze/disabling_ftb_utilities_backup_on_a_server/
