### ISSUE TITLE
Please add UTF-8 support for guide again

### ISSUE THREAD

**Issue by Snownee** [LatvianModder/FTBUtilities#589]
Please add UTF-8 support for guide again..

**Comment by LatvianModder** [comment]
It does support UTF8...

**Comment by Snownee** [comment]
In fact, I have to convert my guide to ANSI, so that it can display normally.

**Comment by LatvianModder** [comment]
![image](https://user-images.githubusercontent.com/3844385/34311398-2dca2da8-e766-11e7-91ac-f8995f474ed9.png)
There is going to be a new guide format anyway :v

**Comment by Snownee** [comment]
The only wish I have is do not change so frequently, at least provide a way to convert old format to the new. I have already spent plenty of time trying to convert my guide through error with little information. :expressionless:

**Comment by LatvianModder** [comment]
I will make a tool to convert json to html guide. There will also be a tool for editing guides ingame later on. In fact, guides are a seperate mod now, that will be released somewhere in january

**Comment by LatvianModder** [comment]
Only downside is that HTML doesn't support language files, but eh, it won't need to. I have bigger plans for guides than minecraft
