### ISSUE TITLE
FTBU Permission node

### ISSUE THREAD

**Issue by berni1212** [LatvianModder/FTBUtilities#592]
How can i set the Trade-o-mat block as a claim block also to be interacted in a private claim ? 

i tryed every config but its not working can u please help me or say if its ab ug ? 

http://paste.creeperhost.net/view/2aec7fdf
Thats the Permission node i tryed so many different things

ic2:te
ic2.te
ic2.trade-o-mat

Please help me

**Comment by LatvianModder** [comment]
You have wrong json formatting: It's `"+ftbu.claims.block.edit.gravestone.gravestone"` not `+ftbu.claims.block.edit.gravestone.gravestone`. Same goes for every entry that is wrong in that list
