### ISSUE TITLE
Right clicking a bed in a claimed chunk sets the player's spawnpoint regardless of their team membership

### ISSUE THREAD

**Issue by iamtpage** [LatvianModder/FTBUtilities#595]
Minecraft Forge 1.12.2
FTBU 4.2.4

Steps to reproduce:
1. Walk into someone else's claimed chunk
2. Right click bed
3. "New spawnpoint has been set!"
4. Die
5. Respawn at bed in someone else's claimed chunk

Permissions file denies both "-ftbu.claims.item.*" and "-ftbu.claims.block.*" for the affected players.

**Comment by LatvianModder** [comment]
is the spawnpoint even vanilla thing? I thought a mod adds that

**Comment by iamtpage** [comment]
Setting the spawnpoint is vanilla: https://minecraft.gamepedia.com/Bed

**Comment by LatvianModder** [comment]
Yes, sleeping in bed, but not right-clicking afaik
