### ISSUE TITLE
Forge Mod Loader Detected missing/unknown registries

### ISSUE THREAD

**Issue by orangedrag** [LatvianModder/FTBUtilities#597]
I just installed FTB Utilities and Lib on my server.  Since then, Vanilla clients can still get in with no issues.  Forge users though get the following screen.  I've included the latest client side FML log from one of the clients as well as the screenshot of the error.  Any help would be great. Thanks.  

[fml-client-latest.log](https://github.com/LatvianModder/FTBUtilities/files/1594209/fml-client-latest.log)

![image](https://user-images.githubusercontent.com/34955799/34451924-89d1b0f2-ece9-11e7-9694-dfcaf724f5d2.png)

**Comment by LatvianModder** [comment]
Hrrrmpf. I guess im removing the registry then

**Comment by erikbozelie** [comment]
Had this issue aswell,
How to fix it: 

Get the latest version of forge ( and make sure it is running that version ). if upgrading it doesnt nessesary select the latest version, goto "launcher -> launch options -> forge" and select the latest version under version.

Then, add the FTB Utilities and FTBLib, and optifine as mods.

I still get the error, but when i press Yes it actually logs in.
