### ISSUE TITLE
Add permission node to bypass vanilla afk auto-kick mechanic

### ISSUE THREAD

**Issue by carstorm** [LatvianModder/FTBUtilities#598]
As the title says, add a permission node so that people with said permission, won't be auto-kicked by the afk timer.

**Comment by LatvianModder** [comment]
I already looked into that before, I think that would require ASM, which I really **really** dont like

**Comment by carstorm** [comment]
As a way around asm, maybe FTB Utils could implement its own afk system this way vanilla's can be disabled but servers can still get the afk functionality?

**Comment by LatvianModder** [comment]
Thought about it too, but vanilla does it very nicely, and without extra checks-each-tick. I would need to do that myself, which wouldnt be too nice

**Comment by GrantSommer** [comment]
:+1: I would also like this

**Comment by LatvianModder** [comment]
Update: It's actually pretty simple to do now, I will add this, it will be timer-per-rank, just like most things

**Comment by Dinip12** [comment]
Sorry for re-opening but is this already implemented? If so what is the permission node?

**Comment by LatvianModder** [comment]
`ftbutilities.afk.timer: "10m"` for 10 minutes or 5s for 5 seconds.
