### ISSUE TITLE
FTB Utilities, enchiridon 2 books in starting items

### ISSUE THREAD

**Issue by HAN-105** [LatvianModder/FTBUtilities#599]
Is it possible to have enchiridon 2 books when player spawning for the first time ? I know... i have looked the config of starting items in "../local/ftbu/config.json". I tried to put these
> Enchiridion2:book,1,0,{identifier:"Unify_Guide"}

But it's not working.. when i used starting inventory mod. it's working perfectly.

**Comment by LatvianModder** [comment]
What MC version is that? The syntax might be different, I think you need yo use spaces and something like `"Enchiridion2:book 1 0 {identifier:\"Unify_Guide\"}"

**Comment by HAN-105** [comment]
it's 1.7.10 mcversion

**Comment by LatvianModder** [comment]
Well, you can try the example I gave, but no idea, 1.7 was like, 3 years ago
