### ISSUE TITLE
World Border not sending to Spawn

### ISSUE THREAD

**Issue by Nephatrine** [LatvianModder/FTBUtilities#60]
I'm using FTBUtilities-1.7.10-1.0.17.3.jar. When I try to cross a world border, it says it is sending me back to spawn, but it actually sends me to the world border center instead. I have used /admin world_border center -4000 0 to move the center of the world border though so that isn't actually spawn. Which should it be sending me to - spawn or the wb center?

**Comment by LatvianModder** [comment]
Ah, yes, I should change that lang entry. It does send to world border center intentionally

**Comment by Nephatrine** [comment]
Thanks. I don't mind where it sends them - the wording just caused some confusion.
