### ISSUE TITLE
cant turn on FTB Utilities buttons after turning them off

### ISSUE THREAD

**Issue by phatpig321** [LatvianModder/FTBUtilities#600]
so I was playing around with the FTB utilities settings in the FTB Revelation pack and i turned off the FTB buttons. the problem is I cant get back to the menu to turn them back on because it turned off the settings button. i cant figure out how to get into the settings to turn the buttons back on and I cant find any config file that i could edit either. any help on how to fix this would be much appreciated :)

**Comment by LatvianModder** [comment]
Hah, yeah, there is local/client/sidebar_buttons.json I think

**Comment by phatpig321** [comment]
ah ok that helped me find the file but it was the ftblib that let me turn it back on. thanks for that... i would have not found that on my own xD

**Comment by Heliusjm** [comment]
Can you explain how you did it

**Comment by LatvianModder** [comment]
Open `local/client/sidebar_buttons.json` and change `"ftblib"/"settings"` from `false` to `true`

**Comment by Javofire** [comment]
hey should I open local in my %appdata% or in some Minecraft library

**Comment by Javofire** [comment]
thx already resolved
