### ISSUE TITLE
Feature to change dimension of /spawn

### ISSUE THREAD

**Issue by Vyraal1** [LatvianModder/FTBUtilities#601]
Searched for "dimension" to see if any already suggested this, and didn't find one. Would it be possible to set the dimension where /spawn teleports the player? Some packs and servers have a initial spawn starting in a different dimension than overworld, and /spawn brings them to the overworld, instead of the designated starter dimension.

**Comment by carstorm** [comment]
I second this, my server uses Just Enough Dimensions to have a custom spawn dimension (dim 10) that acts as a hub for the overworld and player shop dimension. Right now we have a command block and pressure plate at the overworld spawn so that people can get back to the server spawn.
