### ISSUE TITLE
Chunks set as chunkloaded after relog not be chunkloaded

### ISSUE THREAD

**Issue by NickOver** [LatvianModder/FTBUtilities#602]
Hi!
I play on 4.2.4 on DW20 1.12 modpack. I crate world which i play on another computer (but on that same modpack).  If i set any chunk as loaded and leave and enter the game chunk not be loaded.  Claimed chunks stay after relog.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/565
