### ISSUE TITLE
Using /ftb ranks set isn't working, and my player_ranks.json is empty

### ISSUE THREAD

**Issue by katubug** [LatvianModder/FTBUtilities#603]
1.12.2 Minecraft. FTB Utils is version 4.2.3.

I tried looking this up, and couldn't find similar issues either here or via google. I added a new rank "non_op_op," which is basically op, but without the ability to use /op or change game mode.

However, attempting to add people to this rank results in the error "Server thread/INFO Rank 'non_op_op' not found!" - I get the same problem whether I use the ingame chat or the console.

My ranks.json: https://pastebin.com/Ja2EME0q

My player_ranks.json is just "[]" - I don't know the syntax for it, or I'd write my own. There's no example on the wiki, either. When I tried to google it, it just brought up examples for ranks.json.

Thanks for your help!

**Comment by katubug** [comment]
I managed to add a rank via "/ftb ranks add non_op_op builtin_op" and add myself to that group via the ingame chat. However, when I added the permissions portion in ranks.json, it doesn't seem to have any effect. Once I deop myself, I have access to none of the permissions I ought to have.

And the /ftb ranks set *still* doesn't recognize the name of the rank.

I double checked my config.cfg and I *do* have ranks enabled and set to override chat and commands. I'm kind of baffled.

**Comment by LatvianModder** [comment]
The syntax is
```[
  "username": "rank",
  "username2": "rank2"
]```

**Comment by LatvianModder** [comment]
You can read more about ranks here: http://guides.latmod.com/ftbutilities/ranks/

**Comment by katubug** [comment]
I have been following the guide. I'm still having an issue with the actual creation of ranks.

Basically, I want to add a sub-op rank. All normal op permissions except for opping/deopping, /give and /gamemode.

If I add this via ranks.json (and upload and restart the server), the server doesn't recognize the rank when I try to add players to it. If I add it via the ingame chat, the server recognizes it and allows me to add players to it, but I can't change the permissions. When I edit the permissions via the newly-downloaded ranks.json with the newly-added rank, then save, upload, and restart the server, I am back to square one: the server no longer recognizes the rank or that anyone is added to it.

**Comment by LatvianModder** [comment]
can you paste your ranks.json here?

**Comment by katubug** [comment]
This is how I edited it:

> {
> 	"default_ranks": {
> 		"player": "player",
> 		"op": "op"
> 	},
> 	"ranks": {
> 		"player": {
> 			"parent": "builtin_player",
> 			"permissions": [],
> 			"config": {}
> 		},
> 		"op": {
> 			"parent": "builtin_op",
> 			"syntax": "<&2$name&r> ",
> 			"permissions": [],
> 			"config": {}
> 		},
> 		"vip": {
> 			"parent": "op",
> 			"permissions": [
> 			"-command.gamemode"
> 			"-command.give"
> 			"-command.op"
> 			"-command.deop"
> 			],
> 			"config": {}
> 		}
> 	}
> }


But when I restart the server, it changes it to:

> {
> 	"default_ranks": {
> 		"player": "player",
> 		"op": "op"
> 	},
> 	"ranks": {
> 		"player": {
> 			"parent": "builtin_player",
> 			"permissions": [],
> 			"config": {}
> 		},
> 		"op": {
> 			"parent": "builtin_op",
> 			"syntax": "<&2$name&r> ",
> 			"permissions": [],
> 			"config": {}
> 		}
> 	}
> }

**Comment by katubug** [comment]
In review, it seems I probably needed to put commas after each removed permission, right? I was also suggested via reddit to shut down the server, then edit and upload, and then start. Previously, I'd been uploading the files to the server and just resetting it via the console.

I'm trying the other method right now.

**Comment by katubug** [comment]
No dice. It still removes the rank, even when I formatted it with commas.

**Comment by LatvianModder** [comment]
That's because the formatting is wrong - you are missing commas after each "-node". It should be

```json
"permissions": [
"-command.gamemode",
"-command.give",
"-command.op",
"-command.deop"
],
```
