### ISSUE TITLE
Incompatibility with latest JourneyMap beta

### ISSUE THREAD

**Issue by gdude2002** [LatvianModder/FTBUtilities#604]
As it says. Users report that much of JM's UI disappears. Functionality severely hampered.

It's definitely an incompatibility - it doesn't happen without FTBu. I expect this of a beta, but I figured I'd give you a heads up.

How come you're never on IRC these days, by the way? :v 

Feel free to hit us up on the JM Discord server if you want to discuss. https://discord.gg/eP8gE69

**Comment by LatvianModder** [comment]
Yeah, already fixed most of it in my Dev. I think this one is on JM actually, but I did a bandaid fix.
Not on IRC because IRC is dead for me, Discord for the win :P

**Comment by gdude2002** [comment]
Come hang with us, we don't bite. Much. :P 

I lost count of how many people reported this one, lol. Glad to hear you're working on it already.

**Comment by LatvianModder** [comment]
Fixed by simply removing JM integration for now. Will re-add later

**Comment by gdude2002** [comment]
Thanks, Kristiāns - I'm sure you noticed by now but those betas have been taken down from Curse for some time now. You may be amused to hear that people are still using it, though - some modpacks even still include it.

Can't win, eh? :P
