### ISSUE TITLE
/ftb chunks unload_all [player] - error

### ISSUE THREAD

**Issue by NosajDraw** [LatvianModder/FTBUtilities#605]
The help gives the syntax

/ftb chunks unload_all [player]

But using that syntax results in the message "[player] is not true or false".

substituting a player name with true (or false) gives the message "ftb unknown error occurred while attempting to perform this command"

**Comment by LatvianModder** [comment]
Hmm that may be outdated. I think its `/ftb chunks unload_all <in all dimensions, true/false> [player]`

**Comment by NosajDraw** [comment]
That syntax also results in "An unknown error occurred while attempting to perform this command"

**Comment by Elite82pt** [comment]
I also had this problem in my server...After that, the chunks didn't show loaded in GUI but still count on the bottom right corner 
MC:1.12.2 FTB Revelation 1.4.0
