### ISSUE TITLE
I don't know how to create a new guide with subordinate guides

### ISSUE THREAD

**Issue by freaki2010** [LatvianModder/FTBUtilities#606]
Hello LatvianModder,
I can't figure out how to create a main guide with subordinate guides.
I've already looked in the [wiki](http://guides.latmod.com/). But I couldn't find anything there.
I have already created a guide with only text content, so I know how to create a "normal" guide.
The Minecraft version is 1.10.2 and the mod version is "ftb-utilities-1.10.2_3.6.5"

**Comment by freaki2010** [comment]
Can you please help me instead of ignoring me?
 I really need to know that...

**Comment by LatvianModder** [comment]
The wiki is for 1.12 version only. I actually dont even remember what 1.10.2 syntax looked like, what is your guide like?

**Comment by freaki2010** [comment]
I'm sorry, but I didn't see you answer me.
I will send you a guide page today

**Comment by freaki2010** [comment]
Here are the folders and files of the guide
https://next.unitedworldminers.com/index.php/s/Y2ncDW47zkkRtZG

**Comment by LatvianModder** [comment]
Might be this structure? https://github.com/LatvianModder/FTBUtilities/tree/b5453a1ce39762b222a9a30485e90966a84d2f1c/src/main/resources/assets/ftbu
Not sure

**Comment by Terpo** [comment]
For a 1.10 guide you can use the modpack "Age of Engineering" as an example.

**Comment by freaki2010** [comment]
@LatvianModder
I realy need to Check more often my E-Mails :D
Yes that seems to be the same structure.

@Terpo 
Okay thank you i'll take a look in it :)
