### ISSUE TITLE
Add Sunrise/Sunset buttons

### ISSUE THREAD

**Issue by cbenist** [LatvianModder/FTBUtilities#610]
My players usually want to skip night on our server. The day button is nice but it skips half the day. I spent some time looking through configs, googling, and such. Is there a way to edit the sidebar json for my server?

**Comment by LatvianModder** [comment]
Not for server, but you can make your own resource pack for client that adds whatever buttons you want

**Comment by cbenist** [comment]
I made a workable button but I have run into a couple issues. I used fanver modded universal as a base.


![norp](https://user-images.githubusercontent.com/11506380/34918161-5bd9b6e2-f91c-11e7-849d-c443788c744b.png)
![moddedrp](https://user-images.githubusercontent.com/11506380/34918162-5be5f93e-f91c-11e7-944c-1c956dcfba83.png)

I have made a texture for the button.
![toggle_sunrise](https://user-images.githubusercontent.com/11506380/34918172-79abe8de-f91c-11e7-8202-e8fee1581d31.png)

**Comment by cbenist** [comment]
Okay so i fixed the doubled buttons issue but the missing texture still vexes me.

**Comment by cbenist** [comment]
Changed to a custom resource pack that is just the buttons. I also added a sunset button.

![justbuttonsrp](https://user-images.githubusercontent.com/11506380/34919088-3c0b1fee-f92c-11e7-8e5b-e8c0940853cd.png)

**Comment by cbenist** [comment]
I figured out a workaround, in the button json where you call the ResourceLocation, I redirected it from the minecraft domain into a copy of the icons folder with the additions of sunrise and sunset.

![finishedrp](https://user-images.githubusercontent.com/11506380/34921293-15739be6-f94e-11e7-8b64-0821fc38fdde.png)

**Comment by LatvianModder** [comment]
Well, there you go, you figured it out :D
