### ISSUE TITLE
Mod prevents players from damaging passive mobs

### ISSUE THREAD

**Issue by armuell** [LatvianModder/FTBUtilities#612]
Same mod pack as https://github.com/LatvianModder/FTBUtilities/issues/611

**Comment by Sluggasaurus** [comment]
I'm experiencing this issue as well, and have little to no knowledge on how to fix it.
However it's not just passive mobs, it's every mob on my end.

**Comment by ktole1999** [comment]
did you set the pvp flag in your claim?

**Comment by armuell** [comment]
@ktole1999 This was probably the issue. I had "enable_pvp=FALSE" in local/ftbutilities/config.cfg so this was most likely the cause of the issue. I haven't tested it myself though as I was never able to reproduce the bug as I reported the issue on behalf of numerous other users.
