### ISSUE TITLE
Ranks json keeps resetting

### ISSUE THREAD

**Issue by Famulus83** [LatvianModder/FTBUtilities#613]
This issue was reported at one point but i didn't see a resolution and it was closed.
I am running a resonant rise server 4.3.0.3b MC 1.10.2, which includes FTBU. when i try and edit the ranks.json it accepts the changes (adding custom ranks)then reverts back to the original like i never changed anything at all. Is there a way I can make said changes without having it revert back? Ranks are enabled, its literally changing the content of the ranks.json back to the original on the server side of things.
I would like to add ranks and effect things like commands and homes and claim blocks but it is not lettinig me.

**Comment by BryanBoru** [comment]
May be a silly question, but are you shutting down the server before changing these files?

**Comment by Famulus83** [comment]
i have tried both shutting it down before and doing it "live"
________________________________

**Comment by Famulus83** [comment]
after some sleep i think maybe my json syntax was wrong
________________________________
