### ISSUE TITLE
/chunk attack 

### ISSUE THREAD

**Issue by Lajtmen** [LatvianModder/FTBUtilities#614]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

**Comment by LatvianModder** [comment]
what.
