### ISSUE TITLE
Is there anyway to wipe leaderboard

### ISSUE THREAD

**Issue by Explosivee** [LatvianModder/FTBUtilities#617]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

I want to wipe the leaderboard like TimePlayed,MobKills etc. Is there any way to do it?

**Comment by LatvianModder** [comment]
most of leaderboard data relies on vanilla stats. Delete player statistics files I guess
