### ISSUE TITLE
File structure for guides in 1.11.2

### ISSUE THREAD

**Issue by Terpo** [LatvianModder/FTBUtilities#618]
Finally, after hours of seaching I give up for know.
How do I supposed to create a guide in your 1.11.2 version? I look into serval modpacks (mostly Age of Engineering 1.10) and also mods (YABBA 1.11.2) to find out how it should work.

My test guide was the following
nameless/
nameless/guide/index.json (https://gist.github.com/Terpo/1a29cc11555eef355311b2f53e4847c2)
nameless/lang/en_US.lang (https://gist.github.com/Terpo/c92d185904a46d9b8123cbecf1a860cf)
nameless/guide.json  (https://gist.github.com/Terpo/cb02aa901310dabb06f06b1520c401d4)

The index is a copy of "writing guides -> colors" and I added an additional string to it.

I tried this guide package in several places like:
.minecraft\resources\nameless\
.minecraft\local\nameless\
.minecraft\local\ftbguides\nameless\
.minecraft\local\ftbguides\server\nameless\
.minecraft\config\ftbguides\nameless\
.minecraft\config\ftbguides\server\nameless\
And I created a new resourcepack, with
assets\nameless\

So, only the resourcepack folder did work, but then the localization was missing, even with the en_US.lang file filled. 

Now I am out of ideas....
I was hoping to rewrite my modpack with FTBUtilities and drop Hardcore Questing Mode.

**Comment by LatvianModder** [comment]
Maybe https://github.com/LatvianModder/FTBUtilities/issues/606#issuecomment-362278395

**Comment by Terpo** [comment]
Well, no. But I found the solution because I remembered a small thingy: en_US.lang -> en_us.lang

Put your file structure in a resource pack. Make sure the language file is lowercase. 

This is the latest 1.11.2 tree of FTBUtilities:
https://github.com/LatvianModder/FTBUtilities/tree/9b09f3adf38224c83607c86a6c3dcbb13d05eec5

The guide stuff can be found in /src/main/resources/assets
https://github.com/LatvianModder/FTBUtilities/tree/9b09f3adf38224c83607c86a6c3dcbb13d05eec5/src/main/resources/assets
