### ISSUE TITLE
Overwrite configs when starting the server.

### ISSUE THREAD

**Issue by KuangLei** [LatvianModder/FTBUtilities#619]
### Here are the two issues I met
* I've changed some configs in `/local/ftbu/all_configs.html` when the server is closed, but **when** the server is **starting**, all the **configs** I've changed go **back** **to** the **default**.
* **When** the server is **started**, I change the configs in `/local/ftbu/all_configs.html` and **type** **`ftb reload`** from console. It says the contents below **but** the **configs** in the server is **not applied**.
```
[14:09:22] [Server thread/INFO] [FTBUtilities]: Loading ranks..
[14:09:22] [Server thread/INFO]: FTBLib: Server reloaded in 10ms
[14:09:22] [Server thread/INFO] [FTBLib]: Reloaded SERVER on packmode 'default'
```

### Other infos
(Minecraft Server: 1.10.2; Forge: 1.10.2-12.18.3.2185; FTBLib: 1.1x-3.6.5; FTBUtilities: 1.1x-3.6.5; CompatLayer: 1.10-0.3.0; Java: Oracle 1.8.0_161; Operating System: Debian 8;)
The server pack can be downloaded at [here](http://wtm.nos-eastchina1.126.net/server.tar.xz).

Thanks

**Comment by LatvianModder** [comment]
http://guides.latmod.com/ftbutilities/ranks/

You must edit ranks.json, not all_* files. Those are only to list what you can use
