### ISSUE TITLE
Add support for NBT data to starting items

### ISSUE THREAD

**Issue by Anesos** [LatvianModder/FTBUtilities#62]
I'm trying to set up FTB Utilities to give my players some starting items. TFC foods and stuff require custom NBT data to handle decay rates, item size, etc... 

I can do it with the Starting Inventory mod with 
"terrafirmacraft:item.Cheese,1,0,{foodWeight:160.0f,foodDecay:-22.6649f,decayTimer:579}", 
but I'd rather not add another mod if I don't have to and feel this would be a good enhancement for FTBU

**Comment by LatvianModder** [comment]
It should now support NBT since 1.0.17.4. Just make sure to use \ whenever " or { or } is in the NBT string. Or smth. Im no formatting master!

**Comment by Anesos** [comment]
Confirmed working on 1.0.17.5 for a block of Cheese in Terrafirmacraft with string:
"terrafirmacraft:item.Cheese 1 0 {foodWeight:160.0f,foodDecay:-22.6649f,decayTimer:579}"

I had entered it with \{ and \} as you noted which also worked, but the config.json updated itself and removed the backslashes. Confirmed it still worked without the backslashes.

Thanks for the update!

**Comment by Anesos** [comment]
On further testing, it looks like this change broke the ability to specify more than 1 item.

"terrafirmacraft:LitPumpkin 6 0" used to give 6 jack-o-lanterns with meta(damage value) 0. Now it gives 1 jack-o-lantern with damage value 6.

Reversing it to       "terrafirmacraft:LitPumpkin 0 6", gives 1 jack-o-lantern with meta 0 as expected, but the 6 appears to be ignored.

**Comment by LatvianModder** [comment]
Wops. Oh well. Will fix it one day

**Comment by Kiyaku** [comment]
Should this still work in the latest 1.10.2 version? I tried it a few times with different items, with backslashes, without, with ' instead of ", etc. But it always gets removed once the game loads.

**Comment by LatvianModder** [comment]
I still havent figured out how to properly deserialize and serialize items as Json. I don't think anyone has tbh

**Comment by cha0s** [comment]
Challenge accepted: https://github.com/LatvianModder/FTBLib/pull/56
