### ISSUE TITLE
Request - Server Land Claim

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LatvianModder/FTBUtilities#620]
Okay so basically I have had an annoying issue. As an op I am unable to have a seperate claim from what I would consider server claims (A claim used to prevent players griefing claiming towns or prevent hub damage. I have been forced to live with another player and use my claims in a limited fashion. there needs to be a type of land claim that costs nothing maybe by holding leftclick+rightclick ops can do something called a server claim which costs no claim points

the default settings for none opped and fake players would be - can interact with server claim cannot place or break blocks - entities cannot grief and blocks cannot be destroyed.

Its just so annoying to know my personal cliams cannot be used for server purposes without it affect me.

**Comment by ktole1999** [comment]
are you running a forge only server?

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/88
