### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by TrueDaking** [LatvianModder/FTBUtilities#621]
When my friends enter my game they have admin and not player stuffs.
And i whas looking for the files of ranks and some more and i dont have them only have the config.
Could you help me a bit maybe e need to doe sometinhg more 
Ps:Already enabled rank.
![1point](https://user-images.githubusercontent.com/35961652/35586445-c7137384-05f2-11e8-960d-76641fc53a4a.png)
![2point](https://user-images.githubusercontent.com/35961652/35586447-c745a228-05f2-11e8-9da3-2288df8b899e.png)

**Comment by LatvianModder** [comment]
Looks like you have a very old FTBUtilities version, can't help with that

**Comment by TrueDaking** [comment]
There is a verson for 1.7.10 with ranks ?

**Comment by TrueDaking** [comment]
our at least there is a way that when my frends join the server they dont get admin and only player stuff ?

**Comment by LatvianModder** [comment]
Nope, ranks only exist since 1.10.2. I dont know why your players get OP stuff, maybe delete config.json
