### ISSUE TITLE
Team not deleted after leave

### ISSUE THREAD

**Issue by GrantSommer** [LatvianModder/FTBUtilities#624]
So I host a FTB Revelations server, and someone requested to join someone else's team, but they were offline so they just created their own team. Once the team they requested to join came online they accepted the request and the requester joined the team, without the server deleting the old team, keeping the claimed chunks.

**Comment by LatvianModder** [comment]
Huh. So they tricked the system. I guess I didnt think of that

**Comment by LatvianModder** [comment]
Reopen if you can reproduce that with 5.x versions
