### ISSUE TITLE
When are we going to get permissions?

### ISSUE THREAD

**Issue by Explosivee** [LatvianModder/FTBUtilities#625]
When are we going to get permissions?
Example; /luckperms user Luck permission set ftbu.maxclaims.10 true

I know we can also edit this from configs as well but it's much more better, usefull and totally necessary.

**Comment by ktole1999** [comment]
ftbu already has permission nodes and a method to deploy them. right?

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/533
