### ISSUE TITLE
Ranks/Config file going default 

### ISSUE THREAD

**Issue by Pullle** [LatvianModder/FTBUtilities#634]
Hello there,

I try to edit my config.cfg & ranks.json file in ./local/ftbutilities.
I edit both files with Notepad++.
If I enter /ftb reload or if I restart my server booth files go to default. 

I'm on: 
- FTBLib 4.2.5
- FTBUtilities 4.2.4
- MC 1.12.2
- FTB Revelation 1.4.0

My config file:
https://pastebin.com/1dNFMjDC

My Ranks.json:
https://pastebin.com/5WMqLZVz

**Comment by LatvianModder** [comment]
Your json was wrong, fixed that for you

```json
{
	"default_ranks": {
		"player": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": [],
			"config": {
				"ftbu.claims.max_chunks": 100,
				"ftbu.chunkloader.max_chunks": 5
			}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": [],
			"config": {}
		}
	},
	"vip_bronze": {
		"parent": "player",
		"permissions": [],
		"config": {
			"ftbu.claims.max_chunks": 150,
			"ftbu.chunkloader.max_chunks": 7
		}
	},
	"vip_silber": {
		"parent": "player",
		"permissions": [],
		"config": {
			"ftbu.claims.max_chunks": 200,
			"ftbu.chunkloader.max_chunks": 10
		}
	},
	"vip_gold": {
		"parent": "player",
		"permissions": [],
		"config": {
			"ftbu.claims.max_chunks": 250,
			"ftbu.chunkloader.max_chunks": 12
		}
	}
}
```

**Comment by Pullle** [comment]
Sorry, but it still resets to default at /ftb reload or restart of the server.

**Comment by Pullle** [comment]
Oh. I just found the error. You closed "ranks" at line 21 rather than line 45. Thats why it resettet all the time. Hope that will help other admins.

**Comment by LatvianModder** [comment]
oops :D
