### ISSUE TITLE
rank.json keeps being reverted back to default.

### ISSUE THREAD

**Issue by Skyrid3r** [LatvianModder/FTBUtilities#637]
Currently using the latest FTBUtilities-4.2.4.jar and I have to admit that adding default chunks to default players is a pain. But regardless, everytime I attempt to add chunks to the player rank, within the "config": {} block the game reverts it back to default whenever I start up the server again.

And yea. The server was shut down when I edited the file.

All I want is setting chunks for any player joining the server. But there's not any guide that shows that kind of information. But it's hard to test things out if the game keeps reverting the config.

**Comment by LatvianModder** [comment]
Your ranks.json must be wrong, check it in a JSON verifier. And there is http://guides.latmod.com
