### ISSUE TITLE
Chunk claiming: Help my Body is stuck! (Intangible)

### ISSUE THREAD

**Issue by cheriekeks** [LatvianModder/FTBUtilities#64]
Hey,

Intangible adds the possibility to build multiple bodies and switch between them, the problem with claimed chunks is: once I left my body I can't rejoin it (the body remains as some kind of frozen entity on the position, normaly one would rightclick it to take control over it but since the chunk was claimed by another person on the server I can't rightclick it)

Not sure who of you needs to implement some kind of fix I opened an issue on his side as well!
(http://minecraft.curseforge.com/projects/intangible/issues/45)

**Comment by LatvianModder** [comment]
Yeah, this is on my side.. Can you ask the person to.. err.. push your body ouside claimed area? Or maybe unclaim chunk, so you can enter it. I will add an exception for this entity on my side, but until then these are the only 2 solutions I can give :P

**Comment by cheriekeks** [comment]
Got my body back, just wanted to report it so you guys know about it. :)
