### ISSUE TITLE
Spawn Protection Area not properly shown on map?

### ISSUE THREAD

**Issue by Skyrid3r** [LatvianModder/FTBUtilities#640]
I've setup a test spawn area protection with a size of 500 (1.12.2). While the spawn protection works as I can't destroy anything within it, the map shows everything is wildernis with no spawn protection area at all.

https://imgur.com/qHeMlsK

Yet, if I check the youtube and some images.. It should show something like this:

https://imgur.com/4h670by

Am I missing something here or is this a bug?

**Comment by LatvianModder** [comment]
That's very old version, and havent been reimplemented yet

**Comment by Skyrid3r** [comment]
Video wasn't shown on the main page of FTB Utilities on curseforge, so I assumed it's something that was still around. So the spawn area is no longer shown?

**Comment by LatvianModder** [comment]
Nope
