### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by CDAGaming** [LatvianModder/FTBUtilities#643]
https://hastebin.com/enezedohem.sql

**Comment by LatvianModder** [comment]
You dont have correct formatting backup config, dont use 52H, just 52

**Comment by CDAGaming** [comment]
This is running default settings though...but Ok

**Comment by CDAGaming** [comment]
52H is not even found in the default configs (Checked both .cfg's in the local folder)...

**Comment by CDAGaming** [comment]
Found Cause: Backups previously made do not combine well with FTB's System, or at least the way i had it setup.
