### ISSUE TITLE
Digital Miner won't mine because I can't find fake player setting!

### ISSUE THREAD

**Issue by KnottyCord** [LatvianModder/FTBUtilities#644]
Issue description:
Simple the Digital Miner does not mine what so ever in Solo or Multiplier. Everything is setup properly. Filters, power, replacement block etc .... I thought it was because of the Fake player thing. So I did /mk op and nothing help. Then I though it migh be the claimed chunk so I tried in solo, same thing, then I tried removing the FTBUtils mod. Same thing the Digita Miner is stuck at Mining 0.

Version (make sure you are on the latest version before reporting):
Forge: forge-10.13.4.1614
Mekanism: Mekanism-1.7.10-9.1.0.281
Other relevant version: MekanismGenerators-1.7.10-9.1.0.281, MekanismTools-1.7.10-9.1.0.281, MDK-1.7.10-9.1.0.281

**Comment by LatvianModder** [comment]
>make sure you are on the latest version before reporting
>1.7.10
