### ISSUE TITLE
Crash on loading mods

### ISSUE THREAD

**Issue by Warrock3280** [LatvianModder/FTBUtilities#646]
Edited FTB Revelation Modpack, 1.12.2 Minecraft version. Minecraft cannot load after updating Forge to version 2611+, installing few mods:
* Charcoal Pit
* Woot
* Construct's Armory
* Consecration
* CoprseComplex

and updating some more. [Here's](https://gist.github.com/Warrock3280/39f865b2d197b9997103161319a569cd#file-crash-2018-02-19_04-42-16-client-txt) the crashlog.

**Comment by Xaikii** [comment]
Having the same Issue, the Issue is at Construct's Armory, removing it fixes it

**Comment by Warrock3280** [comment]
It fixed in last ConArm update.
