### ISSUE TITLE
The permissions do not work

### ISSUE THREAD

**Issue by babushkaLuba** [LatvianModder/FTBUtilities#647]
Hello. Recently started working with the FTB and a problem arose. Many guides write examples of adding permissions like this: "+ ftbutilities.claims.block.edit.minecraft.sand". I tried to add the same example, but nothing works for me. I ask to help or explain.

"ranks": {
		"player": {
			"parent": "vip",
			"syntax": "&2[Игрок]&a$name&r: ",
			"permissions": [
				"+ftbu.claims.block.edit.gravestone.gravestone",
				"-ftbu.claims.upgrade.no_pvp",
				"+nucleus.time.base",
				"+nucleus.home.set.base",
				"+nucleus.home.base",
				"+nucleus.ignore.base",
				"+nucleus.motd.base",
				"+nucleus.motd.login",
				"+nucleus.kit.list.base",
				"+nucleus.kit.base",
				"+nucleus.helpop.base",
				"+nucleus.message.base",
				"+nucleus.suicide.base",
				"+nucleus.rules.base",
				"+nucleus.spawn.base",
				"+nucleus.staffchat.base",
				"-ftbu.claims.block.edit.minecraft.dirt"
			],
			"config": {
				"ftbu.chunkloader.max_chunks": 0,
				"ftbu.claims.max_chunks": 45
			}

**Comment by LatvianModder** [comment]
>Nucleus

Nope, sorry, won't help with Sponge installed

**Comment by drewc5131** [comment]
thats super helpful! not like some people  need that stuff :\
