### ISSUE TITLE
Problem with configuration!

### ISSUE THREAD

**Issue by LastSpectral1** [LatvianModder/FTBUtilities#649]
First of all, I set up your mod in 1.12.2, and every time it organizes the ranks file and removes the config option, making it impossible to configure the amount of claim a user can make, making the situation very complicated .. because of it already configured for 1000 chunks and 100 loaded ... I needed to disable loaded chunks for common players ... impossible to do too, and most of the time I end up missing something in the file and it ends up restarting without even I being able to know what I did wrong in the file, so it would be nice if it had something like it has in the minetweaker which shows which line gave problem ...

**Comment by LastSpectral1** [comment]
why not put new commands to generate this config, this is better than editing directly by the configuration file, where you can put permissions directly by the command ftp addperm ftbutilities.claims.upgrade.no_pvp (group) (positive or negative )

**Comment by chaos234** [comment]
I must agree with that.

I have seted up my on ranks.json but when I load it in singleplayer it gets reseted without any notification what went wrong.

My ranks.json:

```{
	"default_ranks": {
		"player": "member",
		"op": "admin"
	},
	"ranks": {
		"member": {
			"parent": "builtin_player",
			"syntax": "<&2[Members]&6 $name&r>",
			"permissions": [],
			"config": {}
		},
		"youtube": {
			"parent": "member",
			"syntax": "<&a[Youtuber]&6 $name&r>",
			"permissions": [],
			"config": {}
		},
		"moderator": {
			"permissions": "member",
			"syntax": "<&b[Moderator]&6 $name&r>",
			"permissions": [],
			"config: {}
		},
		"admin": {
			"parent": "builtin_op",
			"syntax": "<&c[Admin]&6 $name&r> ",
			"permissions": [
				"+*"
			],
			"config": {}
		},
	}
}```

From my side nothing is wrong so why is this file permanently reseted?

**Comment by LatvianModder** [comment]
If you test your json with https://jsonlint.com/ you can see that it is in fact wrong - moderator has `permissions` instead of `parent` as first key
