### ISSUE TITLE
friendlist, guide and server info button not schowing up when connected to server

### ISSUE THREAD

**Issue by Dragonfire300** [LatvianModder/FTBUtilities#65]
I installed FTBUtilities-1.8.9-2.0.2 and FTBLib-1.8.9-2.0.2 on both my server and my client (both forge-11.15.1755).
When i'm playing in singleplayer, all the inventory buttons (server info, guide, friendlist, set day/night/rain/gamemode/, settings), but when I connect to my server, only set day/night/rain/gamemode and the settings button show up. I guess that are those not using the server side of the mod...

thank you in advance!

**Comment by Dragonfire300** [comment]
The other server-features also don't seem to work. I tried opening the firend-gui with a keybinding. It only opens in sp. The commands also only work in sp and there is no config file generated on the server. Now I'm wondering if I maybe installed it a wrong way? I just dropped FTB Lib and FTB Util in the mods folder. Forge seems fine, all other mods work....

**Comment by LatvianModder** [comment]
Nah, installation is fine. Must be some miscommunication between client and server, most likely mod's fault, not yours

**Comment by Dragonfire300** [comment]
It works now. I don't now what i changed..... but still thx!

**Comment by jogi01** [comment]
lol same problem here -.-
