### ISSUE TITLE
Sponge and Carry On + ftbLib on forge crash when interacting with chest right button + arms

### ISSUE THREAD

**Issue by ternsip** [LatvianModder/FTBUtilities#652]
https://gist.github.com/ternsip/68ba1de78f56ff792c15702bc80ea72f
Sponge and Carry On+ ftbLib forge crash when interacting with chest
I'm trying to pick chest with arms and sponge crushes
[sponge](https://github.com/SpongePowered/SpongeForge/issues/2033)

**Comment by LatvianModder** [comment]
This is carry on issue, outdated FTBU version
