### ISSUE TITLE
Integrated Tunnels Player Simulator not working within claimed chunks.

### ISSUE THREAD

**Issue by AshenGaming** [LatvianModder/FTBUtilities#653]
#### Mods Involved:
Please list all the mods involved in this issue:
- Integrated Tunnels
- Integrated Dynamics
- FTBUtilities

#### Short description:
The _Player Simulator_ from the Integrated Tunnels mod does not function within a claimed chunk.

#### Expected behaviour:

The _Player Simulator_ would be able to function correctly under a claimed chunk with the Fake Player Status set to 'Ally' if owned by the player.

#### Actual behaviour:

The _Player Simulator_ does not function while inside a claimed chunk. When the _Player Simulator_ is moved outside of a claimed chunk it functions correctly.

#### Steps to reproduce the problem:

1. Claim a few chunks using FTBUtilities.
2. Set up a small Integrated Dynamics network with a _Player Simulator_ on one side and an _Item Interface_ attached to a chest on the other. Put a set of fences around the _Player Simulator_ so that it creates a pen (which you should place a cow in).
3. Use the _Logic Programmer_ to create an _Item_ variable card and place an empty bucket in the top slot and a _Variable Card_ into the empty slot on the right-hand side.
4. Place the new variable card in the _Player Simulator_ under the white _Use item_ section (which will create a check mark).
5. Place an empty bucket in the chest.
6. At this point, in an unclaimed chunk, this will function correctly and milk a cow.
7. If in a claimed chunk, the _Player Simulator_ will do nothing with the bucket in the chest, and it will stay empty.

#### Additional Information:

I believe it is an issue with FTBUtilities not being able to recognise/not handle the Integrated Tunnels FakePlayer.
____
#### Versions:

- FTBUtilities: 4.2.4
- FTBLib: 4.2.5
- Forge: 14.23.2.2618
- Integrated Dynamics: 1.12.2-0.11.5
- Integrated Tunnels: 1.12.2-1.5.2

**Comment by Buuz135** [comment]
I have the same issue with Industrial Foregoing fake player, it all seems to work when the FakePlayer setting is in allowed, but it seems that in updates it turns off.

**Comment by Buuz135** [comment]
👌
