### ISSUE TITLE
Teleport between worlds

### ISSUE THREAD

**Issue by LastSpectral1** [LatvianModder/FTBUtilities#657]
Do not have any commands to teleport between worlds?
if you have not could put to 1.10.2 please :)

**Comment by LastSpectral1** [comment]
could you add chat channels in the game, like global and local?
updating the ranks example is interesting too (wiki)

**Comment by LatvianModder** [comment]
See
https://github.com/LatvianModder/FTBUtilities/issues/530
https://github.com/LatvianModder/FTBUtilities/issues/531
https://github.com/LatvianModder/FTBUtilities/issues/532
