### ISSUE TITLE
[Bug] No friends tab, cannot invite anyone in team

### ISSUE THREAD

**Issue by xhatz** [LatvianModder/FTBUtilities#658]
Hello. I don't know if it is a bug or what, but I am 100% sure there used to be a working friend list system in this mod.

I cannot seem to find how to add someone to my team as the members' screen appears blank, and have no plus button. And I cannot find the friends list again.

Is it just me having problems? Also, the all_configs.html and all_permissions.html seems to have the exact same content... please help me I really need this cool plugin with all its features :(

**Comment by LatvianModder** [comment]
I think the members thing is a bug, I will see if I can fix it asap. As for configs and permissions... Weird. I will check that out too

**Comment by xhatz** [comment]
Thank you ^^!

**Comment by P3rf3ctXZer0** [comment]
Thank god someone reported this. I just reverted back until the bug is fixed. Please let me know when it works @xhatz then I will update.

**Comment by LatvianModder** [comment]
Fixed
