### ISSUE TITLE
ftb utilities buttons crash

### ISSUE THREAD

**Issue by MasterSloth1** [LatvianModder/FTBUtilities#659]
- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2963.jar
- Forge version: 14.23.2.2625
- Java version: 1.8.0_161
- Operating System: Windows 7 version 6.1

please ask me any questions u need
https://cdn.discordapp.com/attachments/321806752985120789/423296484201463808/crash-2018-03-13_20.43.44-server.txt
^^crash report

**Comment by LatvianModder** [comment]
FTBU is not supported with Sponge present
