### ISSUE TITLE
When FTB Utils. claimed chunks is on it disables Industrial Foregoings Machines Plant Sower, Gatherer, etc.

### ISSUE THREAD

**Issue by Jstcreepn** [LatvianModder/FTBUtilities#662]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

**Comment by Tander** [comment]
Workaround is set "Required Level for Block Editing" to "None". Fix needed.
Also, how to attach issue ticket from IF repo https://github.com/Buuz135/Industrial-Foregoing/issues/231 ?

**Comment by LatvianModder** [comment]
Looks like it treats fake players as real players, I will need to figure out a way around this
