### ISSUE TITLE
People can use "/home home nick" to access the last home location from a player

### ISSUE THREAD

**Issue by Autopoietico** [LatvianModder/FTBUtilities#663]
If i write for example 

> /home home Player

, i can go to the last home location from a player, and find maybe secret locations he have.

**Comment by LatvianModder** [comment]
This is available for OPs, you can run that as non-OP player?

**Comment by Autopoietico** [comment]
Yes

**Comment by Autopoietico** [comment]
I try to ban in the ranks configs, but don't work

**Comment by ktole1999** [comment]
if this is perhaps a bug then ranks wont solve it. hopefully it will be addressed soon.

**Comment by LatvianModder** [comment]
Yes, found the bug, will be fixed in next version. Two bugs, actually:
1 - Registers `ftbutilities.homes.list_other` and `ftbutilities.homes.teleport_other` as ALL instead of OP by default
2 - Uses `ftbutilities.homes.list_other` instead of `ftbutilities.homes.teleport_other` for teleporting

**Comment by Autopoietico** [comment]
Thanks!!
