### ISSUE TITLE
Ranks.json resets to default every new/restart

### ISSUE THREAD

**Issue by winnetrie83** [LatvianModder/FTBUtilities#664]
I know this has been an issue reported multiple times and closed, but i have tried a whole day now to make this work without luck. Yes ranks are enabled and no syntax errors, i checked that with jsonlint to be sure. I'm setting up a 1.12.2 server.

This is what i want inside the ranks.json:
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 250,
        "ftbu.chunkloader.max_chunks": 50
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}
Yet after every restart the file has been reverted/replaced.

**Comment by Autopoietico** [comment]
For me only reset the config section, the ranks, the permitions, and other things don't change.

**Comment by winnetrie83** [comment]
I haven't used or tested the other parts of this file. I needed to increase the amount of chunks you can claim.

**Comment by LatvianModder** [comment]
Change `ftbu` to `ftbutilities`

**Comment by Autopoietico** [comment]
Changed, thanks!!!

**Comment by winnetrie83** [comment]
Worked for me. Thank you very much
