### ISSUE TITLE
Chunks No Longer Loaded when Reloading World in Singleplayer

### ISSUE THREAD

**Issue by TechnoColt** [LatvianModder/FTBUtilities#665]
My sincerest apologies if this already has a solution. I was unable to find anything that helped by searching. I'm playing FTB Revelation, and whenever I save and quit and reload my world, my loaded chunks are no longer loaded. I've had this issue on multiple modpacks, and I'm really not sure how to fix it. I read something about a config for FTBUtilities, but I can't seem to find it anywhere.

**Comment by LatvianModder** [comment]
The mod probably isnt updated in those packs, chunkloading was fixed in 5.+ versions

**Comment by TechnoColt** [comment]
Ah. I figured with Revelation being such a new pack it would have updated versions of the mods. It looks like it's running 4.2.5. I'll be sure to update. Thank you, and sorry for the pointless post. :T
