### ISSUE TITLE
Permissions when prefixing commands with /ftb

### ISSUE THREAD

**Issue by sarcastic6** [LatvianModder/FTBUtilities#666]
In ./local/ftbutilities/ranks.json I have the following set:

```{
	"default_ranks": {
		"player": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": [
				"-command.ftb.spawn",
				"-command.ftb.back",
				"-command.ftb.home"
			],
			"config": {}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": [],
			"config": {}
		}
	}
}
```
If a non-op types /spawn, /home, or /back they get the message that they don't have permission to use that command, which is what I would expect.

However, if a non-op types /ftb spawn, /ftb home, or /ftb back, the commands run successfully and teleport the player, which is not the expected behavior.

**Comment by LatvianModder** [comment]
Hummm.. those are supposed to share permissions

**Comment by YohXVII** [comment]
This is not my case, as I said the command "/ftb ranks" and the command "/ranks" does not work even if I have the "+*" permission.
