### ISSUE TITLE
[1.12.2] Backup location being ignored

### ISSUE THREAD

**Issue by notacompletemoron** [LatvianModder/FTBUtilities#668]
Using FTBUtilities-5.0.0.11 and FTBLib-5.0.0.14.

The backups are not going to the location I defined in the /local/ftbutilities/config.cfg file, which is "S:folder=/mnt/527E6F7E7E6F5A2D/Backups"

When I restart my server, it's showing the defined location as the root folder, which will not work as it's a small SSD. It's not an Ubuntu permissions issue, as I was able to write a file to that folder, without root.

Please advise.

**Comment by joeshimmo** [comment]
Getting the same problem, any solutions?

**Comment by joeshimmo** [comment]
@notacompletemoron I have a temporary fix, I created a symlink to my other drive until there is a solution.

**Comment by notacompletemoron** [comment]
Ok, cool. I'll do that when I have some free time.

**Comment by LatvianModder** [comment]
What does the log print? There should be a line that says something like `[FTBUtilities] Backups folder - <location>`

**Comment by joeshimmo** [comment]
It says: [Server thread/INFO] [FTB Utilities]: Backups folder - /home/mcserver/FTBRServerV1.7/backups

While in the config: S:folder=/ServerBackups

I also set compression to 0 but it still uses compression.

**Comment by notacompletemoron** [comment]
Mine says [Server thread/INFO] [FTBUtilities]: Backups folder - /mnt/527E6F7E7E6F5A2D/Backups

Same as the config, but saves to the root MC folder/backups.

**Comment by sarcastic6** [comment]
I think there may be a bigger problem with the config file in general.  With a clean install of just forge, ftblib, and ftbutils, it never even generates a config.cfg file, even though it does create other files in ./local/ftbutilities

**Comment by LatvianModder** [comment]
You are editing files while server is offline, right?

**Comment by joeshimmo** [comment]
Yes, it seems to ignore the config file completely.

**Comment by notacompletemoron** [comment]
Yes, editing while offline. Still ignores config.

**Comment by nullKomplex** [comment]
We've been trying to figure out why none of our chunkloading settings seem to be working, both in ranks and in the config. Admins also have 1000 claims and 64 loaded chunks available, and players are at 50 loaded chunks available, despite us having it set to 100:25 across the board for all users. So I'd say it sounds like the config file entirely is being ignored. I'll investigate further when I have someone around who can access the server files.

**Comment by notacompletemoron** [comment]
Good find. I was actually in my world for some time, tonight. I found that
JourneyMap wasn't showing loaded chunks either. I didn't think it was
related at the time, but now, it makes sense.

**Comment by notacompletemoron** [comment]
This was discovered by another user;

https://github.com/LatvianModder/FTBUtilities/commit/df1b8eded3ae5c1254853202a4c11eb899455def#diff-3a3f6adc4a70b9bdc93a602a65b94a58

Line 24 to be exact. I placed the config file in my config folder, and it's still being ignored.

**Comment by nullKomplex** [comment]
By me. I was still investigating. Ranks supposedly still stayed in /local and only the default was moved. Not sure which part of all of that was intentional, but I don't think any of it was included in the changelogs and it's weird having some of them stay in /local.

**Comment by notacompletemoron** [comment]
ftbutilities.cfg was only generated once I renamed the local folder to allow the mod to regenerate the config files.

And ftbutilities.cfg in /config works.

**Comment by LatvianModder** [comment]
Actually, yeah, I figured out that I must have changed location to `config/ftbutilities.cfg`. Never drink and program, people! I was gonna change it, but later. Welp.
