### ISSUE TITLE
Restart Timer in 1.8.9

### ISSUE THREAD

**Issue by BuckitHead** [LatvianModder/FTBUtilities#67]
I change the restart timer in config to 4.0 from the default 0.0 and the server will not boot. Change back to 0.0 and everything if fine 

Forge 1762
FTB Lib,Util 2.02

**Comment by BuckitHead** [comment]
1.8.9 version.

**Comment by LatvianModder** [comment]
Fixed in 1.7.10, will be fixed in 1.8.9 too. #28
