### ISSUE TITLE
Players Allowed on server using MCLink cannot create teams.

### ISSUE THREAD

**Issue by KitKat31337** [LatvianModder/FTBUtilities#674]
Players connecting to my server using MClink cannot make teams.

**Comment by KitKat31337** [comment]
Upon whitelisting the player, teams works normally, server.properties userWhitelist setting is FALSE

**Comment by LatvianModder** [comment]
This sounds like an MCLink issue @dries007

**Comment by dries007** [comment]
I don't think so, considering I just kick players if they are not authorized to be logged on.
I can't think of how that would interfere with anything, especially if the vanilla whitelist is off (which it's supposed to be).

**Comment by LatvianModder** [comment]
Then maybe this isn't related to MCLink at all. I thought it's one of those Discord->Minecraft mods, but looks like it just kicks players. Closing until you can prove it comes from MCLink

**Comment by KitKat31337** [comment]
I cannot prove anything as I dont have a debugger running on my server.  I know if a player is not whitelisted, they cannot make a team, once I whitelist them they can.

**Comment by KitKat31337** [comment]
The only reason MClink is mentioned is that is how they are gaining access to my server if they are not manually whitelisted.

**Comment by KitKat31337** [comment]
I reported functionality of FTB Utilities not working, not MCLink.  MCLink appears to be working properly.
@LatvianModder
