### ISSUE TITLE
Online only Chunk Loading

### ISSUE THREAD

**Issue by Rasmun** [LatvianModder/FTBUtilities#675]
I am trying to set chunkloading to only load while players are online.  Below is the ranks.json file.  When I restart our Age of Engineering server, the below file is updated and the ` "ftbu.chunkloader.type": "online" ` line is removed.

FTBLib-1.1x-3.6.5
FTBUtilities-1.1x-3.6.5

Any suggestions on how to resolve this and make player's chunkloading online only?  Thanks.

```
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.chunkloader.max_chunks": 9,
        "ftbu.claims.max_chunks": 20,
        "ftbu.chunkloader.type": "online"
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}
```

**Comment by nullKomplex** [comment]
What version of FTB Utils are you using?

For the latest version, you will need to know the following:

- The modid is `ftbutilities`, not `ftbu`
- The corrent node is `ftbutilities.chunkloader.load_offline`
- The node is a permission node and not a config one, so under permissions you will need to do `-ftbutilities.chunkloader.load_offline`

Hope this helps!

**Comment by xxlio109** [comment]
like this`			"permissions": [
				"+ftbutilities.chunkloader.load_offline"
			],`

**Comment by Rasmun** [comment]
Thanks
