### ISSUE TITLE
Add an method to load/refresh all loaded chunks

### ISSUE THREAD

**Issue by midorlo** [LatvianModder/FTBUtilities#676]
I'd propose to add a button to ftbutilities map, refreshing all loaded chunks and therefore waking up all corresponding dimensions once. I'd also propose a console command for this, which should help server owners. I believe that mechanic is yet in the mod and ackknowledge that it "may or may not" yet work depending on various modpack enviroment variables. I believe that adding a manual function call could improve the current situation.

**Comment by BryanBoru** [comment]
Vanilla feature:
```Pressing A while holding F3 will reload all chunks.```

**Comment by midorlo** [comment]
Not true for chunks in unloaded dimensions.

**Comment by LatvianModder** [comment]
Loaded chunks dont need a refresh, their entire purpose is to work in other dimensions without need to refresh
