### ISSUE TITLE
ranks.json resetting to default in FTB Revelation 1.8.0

### ISSUE THREAD

**Issue by KeithLinfoot** [LatvianModder/FTBUtilities#679]
ranks.json from our 1.6.0 FTB Revelation server copied over to 1.8.0, but keeps being reset to default file, thereby losing claims max etc.  Have checked here for similar issues and googled a lot, but cannot see that anything has changed that would affect this file.

FTBLib 5.0.0.14
FTB Utilities 5.0.0.11
Our file:

`{
	"default_ranks": {
		"player": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": [
				"+ftbu.chunkloader.load_offline"
			],
			"config": {
				"ftbu.claims.max_chunks": 1000,
				"ftbu.chunkloader.max_chunks": 100
			}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": [
				"+ftbu.chunkloader.load_offline"
			],
			"config": {
				"ftbu.claims.max_chunks": 1000,
				"ftbu.chunkloader.max_chunks": 100
			}
		}
	}
}`

Being reset to:

`{
	"default_ranks": {
		"player": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": [
				"+ftbu.chunkloader.load_offline"
			],
			"config": {}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": [
				"+ftbu.chunkloader.load_offline"
			],
			"config": {}
		}
	}
}`

**Comment by LatvianModder** [comment]
Change `ftbu.` to `ftbutilities.`
