### ISSUE TITLE
Witchery and claimed chunks

### ISSUE THREAD

**Issue by eberlort** [LatvianModder/FTBUtilities#68]
With the Witch hand any body can destroy blocks in claimed chunks....

**Comment by LatvianModder** [comment]
So you can with Thaumcraft's excavation focus. I guess I could fix that, but eeeeeeeeeeeeeeeeh fine.

**Comment by KajesLorian** [comment]
Carpenter's Blocks can also override the claimed chunk protection. Right-clicking on the garage door, for example, is protected, but the CB pressure plates and shift-right-clicking the garage doors is not.

**Comment by Belgabor** [comment]
Do you mean clicking on pressure plates? Because reacting to stepping on them should definitely not be prevented.

**Comment by LatvianModder** [comment]
I can't do anything about pressure plates
