### ISSUE TITLE
Admin Claims

### ISSUE THREAD

**Issue by FriendlySurvival** [LatvianModder/FTBUtilities#683]
Currently I has to "bind" to a team just to cover my spawn area and "semi" controls access. But I am afraid that it also risking my house and etc because they has to follow the similar controls set on spawn...  

Is there a way to have like a "admin mode" for claims? 

Thanks in advance!

**Comment by ktole1999** [comment]
are you running a forge only server?

**Comment by FriendlySurvival** [comment]
That is correct, thank you for asking.

**Comment by VankkaGithub** [comment]
#88
