### ISSUE TITLE
Crash with RefinedStorage

### ISSUE THREAD

**Issue by JoJoDeveloping** [LatvianModder/FTBUtilities#685]
Hello.
I am playing the latest (stock) version of the FTB Pyramid Reborn modpack (singleplayer). This bug has crashed my game twice. As far as I can see from the stacktrace, it happens when the Refined Storage "Constructor" places a block. The chunk the block is placed in is claimed by me (and chunkloaded, but I stand next to it while that happens so it shouldn't matter). Note that the bug only happens sometimes a block is placed, often times it works flawlessly.

RS uses the fake player created with forge's own FakePlayerFactory (net.minecraftforge.common.util), so maybe something is wrong with handling these.

Crash Log: https://pastebin.com/H29YiqkF
Issue regarding the same bug over at Refined Storage: https://github.com/raoulvdberge/refinedstorage/issues/1738

Thanks for your help.

**Comment by LatvianModder** [comment]
Latest update should fix it
