### ISSUE TITLE
FTBLib+ExtraUtilities2 Fake Player issues

### ISSUE THREAD

**Issue by dshadowwolf** [LatvianModder/FTBUtilities#687]
ExU2 has a wrapper around the Forge FakePlayer that actually has a non-null connection (see [this line](https://github.com/rwtema/Extra-Utilities-2-Source/blob/aa12f583fce65b4dfbc8818acf2a838dac2a6c00/1.10.2/src/main/java/com/rwtema/extrautils2/fakeplayer/XUFakePlayer.java#L35) in the ExU2 source)

This causes the fake-player detection to fault and actually creates an NPE in FTBLib's "Universe" object when it tries to return the player.

**Comment by TheQKnight** [comment]
Yep, in English this means that if you use a mechanical miner or mechanical user from EU it just straight up crashes the game.

**Comment by LatvianModder** [comment]
Why the **hell** does it have a connection

**Comment by sk2048** [comment]
This also appears to be the case for Random Things, see [here](https://github.com/lumien231/Random-Things/blob/master/src/main/java/lumien/randomthings/tileentity/TileEntityBlockBreaker.java#L82)
