### ISSUE TITLE
FTB Utilities not working with Technic modpacks

### ISSUE THREAD

**Issue by Mattrock607** [LatvianModder/FTBUtilities#688]
I'm trying to include FTB Utilities 5.0.1.12 and FTB Lib 5.0.1.15 in a modpack for Technic (Waywardcraft 1.12.2 Edition). The mod works fine in the vanilla launcher, but for some reason it keeps crashing when I launch using the Technic launcher. Here's a link to the pastebin of the client crash report:

https://pastebin.com/RdazUupa

I want to roll back to an older version, but I'm not sure which would work, and I'd also need to roll back YABBA which has a dependency on FTB Lib.

**Comment by LatvianModder** [comment]
Update FTBLib

**Comment by LatvianModder** [comment]
Huh.. Interesting

**Comment by LatvianModder** [comment]
Fixed

**Comment by Mattrock607** [comment]
Tested on the server and it all works great, ty so much!
