### ISSUE TITLE
FTB Utilities causes server to crash on startup

### ISSUE THREAD

**Issue by sk2048** [LatvianModder/FTBUtilities#689]
When the latest version of FTB Utilities is included in a server, the server crashes on startup due to attempt to use net.minecraft.client.resources.I18n. This appears to have been introduced [here](https://github.com/LatvianModder/FTBUtilities/commit/6e549c3d43e336a09d42c87d23acd65678eb60e2#diff-9d0602a182dd2bd0775f648b119a7a50R391)

**Comment by sk2048** [comment]
Correction, because apparently I can't read. The crash is caused by FTB Utilities.

**Comment by sk2048** [comment]
I'm sorry for spamming, I'm not very good with Github yet.

**Comment by LatvianModder** [comment]
Fixed in latest FTBU
