### ISSUE TITLE
Documentation of FTBUtilities

### ISSUE THREAD

**Issue by Carlgo11** [LatvianModder/FTBUtilities#69]
Hello,
I'd really like some form of documentation on FTBUtilities' configuration and commands.
For example, in the backups array inside the `config.json` file, what is the `backup_timer`'s time measured in? Seconds? Hours? Something else?

What's the `compression_level`'s levels? What are the allowed inputs? `0-10`? `1-5`? What do the different levels mean? Is `0` not compressed at all or is that `1`?

**Comment by LatvianModder** [comment]
This is why you use /edit_config <mod> ingame... It shows all info for config

**Comment by popatop15** [comment]
When trying to use ./edit_config I get the unknown command error. I'm pretty sure it isn't something I am doing, unless the pack I am using disabled FTBU commands, which I don't see why they would.

**Comment by LatvianModder** [comment]
Because its /ftb edit_config

**Comment by popatop15** [comment]
Oh, well no one told me this O_O Is there a complete list of command and their arguments anywhere?

**Comment by LatvianModder** [comment]
Server Info > Commands > /ftb

**Comment by popatop15** [comment]
Thank you very much!

**Comment by StarSmasher44** [comment]
Since none of the above commands work, and there is still no documentation, how does this compression level work and to what can I set it and what are the requirements?

**Comment by DaMatrix** [comment]
I'm pretty sure that 1.7.10 isn't supported anymore.

**Comment by StarSmasher44** [comment]
Well FTB Infinity is still using this mod and it still works and I'd still like to know how it works. Kinda

**Comment by Technifocal** [comment]
@StarSmasher44 Where do you see that? To me it look as though it's 0-9, 0 is uncompressed, 1-9 is the zip compression level:

https://github.com/LatvianModder/FTBUtilities/blob/620eb8fea57d7ffae767339d371d8b50430e1609/src/main/java/com/feed_the_beast/ftbu/world/backups/ThreadBackup.java#L71

https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipOutputStream.html

**Comment by LatvianModder** [comment]
yeah, 0 means it just saves direct folder copy, 1-9 is compression level, by default 1

**Comment by Dimentive** [comment]
@LatvianModder What does it mean, exactly? What does it compress? What do you lose?

**Comment by Dimentive** [comment]
@LatvianModder What does it mean, exactly? What do you lose if you choose a high compression level?

**Comment by LatvianModder** [comment]
Time only. The file compression is losless, but more compressing = more time to do so

**Comment by Dimentive** [comment]
So, the higher the compression level, the longer it takes to perform a backup?

By the way, it says in the config file that a compression level of 1 is the fastest speed, but wouldn’t that be 0?

**Comment by LatvianModder** [comment]
0 means it doesnt compress at all, just copies folder
