### ISSUE TITLE
Add ability to hide "My Team" and "Settings" icons in inventory.

### ISSUE THREAD

**Issue by Xetaxheb** [LatvianModder/FTBUtilities#690]
Preferably in "Sidebar buttons" gui. Still have command "/ftbc client_config" to get them back. Maybe put a one-time clientside message in chat after the gear gets disabled?

**Comment by Xetaxheb** [comment]
Nevermind, found the menu that already has this. Settings FTBLib>General>Action Buttons>Disabled

**Comment by Xetaxheb** [comment]
However, inventory_side isn't moving them there. I have NEI, JEI, Baubles, Cosmetic Armor, and some mod that makes potion effects not shift inventory location. (Enigmatica 2 expert)

**Comment by LatvianModder** [comment]
Why closed? Easy enough addition

**Comment by Xetaxheb** [comment]
Fair enough; I suppose having extra entries in the settings for toggling those specifically would be good. 
I just wanted the entire set of buttons gone and the FTBLib settings already has that, so I didn't think about specifically that.
