### ISSUE TITLE
Motd is not working on 1.12.2

### ISSUE THREAD

**Issue by TripleZ0** [LatvianModder/FTBUtilities#692]
I enabled motd in the config file. However it's still not sending any message when joining to the server.

**Comment by TripleZ0** [comment]
It's working but you have to restart the server everytime when you modify it.
"/ftb reload" doesn't reload the message. Can you please fix this? Thank you.

**Comment by ktole1999** [comment]
how often do you change the motd? if its a daily thing then change it while server is running. when auto restart occurs it will show the new motd.

**Comment by LatvianModder** [comment]
What do you mean not working? Works fine [!image](https://ss.latmod.com/mc/2018-04-21_14.10.53.png)

**Comment by LatvianModder** [comment]
![](https://ss.latmod.com/mc/2018-04-21_14.14.46.png) with these settings
