### ISSUE TITLE
Add 'ftbu.claiming.expires' & 'ftbu.claiming.expires_timer' to remove dead claims

### ISSUE THREAD

**Issue by patrick-hill** [LatvianModder/FTBUtilities#696]
The ability to remove dead claims is paramount for most servers. Players are constantly coming and going and some automated process to handle this would be excellent.

I'd like to see the ability to enable a claim expiration option and then further configure the timer to a specific value.

The functionality would look something like:
If timer is enabled, and timer value is now met, unload players chunks, remove players claim...
Additionally, if no other players are in this players team (or team is hosted by this player), remove players team. If there are additional players in this team, transfer ownership to next player (whomever).

**Comment by ktole1999** [comment]
i would think just disbanding the team would be more appropriate as you dont know who would be next in line to be team leader. It may assign that to someone that may not be authorized by team. I like this claim timer idea (speaking as a server owner).

**Comment by patrick-hill** [comment]
@ktole1999 , the problem with disbanding the team would be any users in that team automatically loses all their claims/loaded chunks as well.

I could totally debate that, if you're in a team with in inactive leader, then that's on you though, so either way works for me.

I just can't have hundreds of claims in the worldborder forever, I never reset the map so expiration is a must in that regard (or some other manual process I won't do).

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/585

**Comment by LatvianModder** [comment]
I dont remember where, but I also had note for "Team expiration timer" too, so the entire team gets deleted if none of the members log in for x amount of time
