### ISSUE TITLE
Claiming chunks not working on server

### ISSUE THREAD

**Issue by ExDomino** [LatvianModder/FTBUtilities#699]
The mod is installed both client side and server side. I can claim chunks on a singleplayer world, but cannot claim anything on server. There is no indicator at the bottom right corner of the screen that indicate how many chunks I have.

Minecraft version: 1.12.2
Forge version: 14.23.3.2669
FTBLib version: 5.0.2.10
FTBUtilities version: 5.0.2.10

**Comment by superfluke** [comment]
Just tested updated versions in my modpack, chunk claiming working on both single player and server. Are you sure you've joined a team on the server. If you don't create a team on the server you wont be able to claim and you wont see your chunk count in the bottom right, something different from how it works on single player.

**Comment by LatvianModder** [comment]
I added `Bug` because I had some weird, permission related issues in my test env, until I resolve those I will keep this open
