### ISSUE TITLE
Which class handles the rendering of "friends" 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#70]
I am working on mod that allows the player to change there skin in game, anyway I am testing on most modpacks I play, and on packs with FTB utils I have noticed that, it always shows the player original skins, you probably download the player skin from minecraft.net, but if you could point me to the class that handler the rendering of friends I would like to a look to see if I can do anything to my mod to the player current skin show, I have had quick look at you code but have had no luck finding the class in question, and do not have the time to look trough all your class.

**Comment by LatvianModder** [comment]
You can't really change player's skin itself anymore. I render a custom player that is not equal to actual ingame player
