### ISSUE TITLE
Config section of ranks.json gets deleted, json validator finds no error

### ISSUE THREAD

**Issue by AlHollandiyah** [LatvianModder/FTBUtilities#701]
I have a setup in ranks.json where the config section is getting removed every time I load the server / reload FTBU. I have been googling for two days trying to find examples / explanation on how this file should be set up and comparing those to mine to find what goes wrong, but I just can't seem to pinpoint it. Can anybody tell me how to fix this?

My JSON doc:

https://pastebin.com/nZe0AcB2

What is left after FTBU loads it up:

https://pastebin.com/1uPc9j9L

**Comment by LatvianModder** [comment]
It should change, however you use wrong prefix in both permissions and configs - it's `ftbutilities.` not `ftbu.`

**Comment by AlHollandiyah** [comment]
OK, but if the config section in both ranks is removed, that means the homes etc, arent changed to what I set them to. How do I do that?

**Comment by AlHollandiyah** [comment]
Addition, turns out that the homes and claims settings now belong in "permissions" rather then config. This is literally NOWHERE in ranks.json examples nor in the wiki. I hope that this will be added somewhere for others who want to do the same! Thanks!
