### ISSUE TITLE
Chunk loading/claiming suggestion

### ISSUE THREAD

**Issue by VgNation** [LatvianModder/FTBUtilities#703]
I am having an issue trying to disable the chunk loading aspect of ftb utilities for all players and admins
I really liked the old way of ftb utilities were I could go to the config and scroll down were it would say player chunk claiming/loading and admin chunk claiming/loading and just change the numbers to 0 for chunk loading and whatever for claiming is it possible to add this feature back into the config for 1.12.2 and the future release of 1.13

I think it would be beneficial to add this because it would help simplify the needs of server owners

**Comment by LatvianModder** [comment]
its already pretty simple, but it will be simplier in future, see
https://github.com/LatvianModder/FTBUtilities/issues/701#issuecomment-384011498
