### ISSUE TITLE
Wondering if the per-DIM worldborder functionality still exists?

### ISSUE THREAD

**Issue by xAlicatt** [LatvianModder/FTBUtilities#704]
This is for the 1.12 version...wondering if this functionality has been removed in this version? I can't seem to get any of the commands I found in some old documentation. We're getting a ticking entity crash with the (seemingly) abandoned WorldBorder Forge port that's up on Curse and trying to find an alternative without having to use Sponge.

**Comment by LatvianModder** [comment]
It doesn't exist, but I was gonna re-implement it at some point
