### ISSUE TITLE
Luckperms permissions

### ISSUE THREAD

**Issue by Clem-Fern-Dev** [LatvianModder/FTBUtilities#708]
Hello, I use luckperms on a forgesponge server. I would have liked to know if it is possible to put the chunk restrictions in luckperms permissions, and if so how. I searched, but I did not find anything.

Would you know me?

*Sorry for my very aproximative English, I try to apply myself.*

**Comment by LatvianModder** [comment]
I don't know. FTBUtilities won't work good with luckperms/sponge
