### ISSUE TITLE
Warps are deleted upon Server Restart

### ISSUE THREAD

**Issue by labelbuddy** [LatvianModder/FTBUtilities#71]
Set up warps for all players base, upon server restart all warps no longer work.

Ex. /warp label should warp me to my base. Works great. Upon server restart /warp label recognizes the warp label, chat says "Teleported to 'label'" but no teleporting takes place.

If i delete warp label and re-add it, resumes working until next server reset.

Home commands still work after reset.

**Comment by LatvianModder** [comment]
Which minecraft version is that?

**Comment by labelbuddy** [comment]
Opps sorry 1.7.10 running ftb infinity evolved :)

**Comment by LatvianModder** [comment]
Should be fixed in 1.0.18
