### ISSUE TITLE
Backup Settings missing, Documentation practically non existent

### ISSUE THREAD

**Issue by Pingger** [LatvianModder/FTBUtilities#710]
Hi,

double issue, (or maybe even triple ... while writing, I noticed it is even worse)
First: FTBUtilities fills the harddrive with backups. I now have more than 500 GB Backups for a server that is about 100 MB in size which in return caused Incremental Backups to drastically increase in size very quickly
Second: ingame commands don't do shit to edit the backup settings (or disable them as i want to, since i have a incremental backup solution, that WORKS unlike ftbu)
Third: Config files are non existent (search in config and local/ftbutilities)
Fourth: The 'Documentation' in the local folder doesn't document anything. what am I supposed to do with settings described there, when I don't have any information on where to store it to (config file? ingame command? something else that is against forge standards like using a different folder for configs than 'config'?)
Fifth: Revoking write access from/to the 'backups' folder crashes the server with a jvm error (no stack trace, no hs_err_pid file, just gone)
Sixth: Changing the backup target is not possible either, since no config options available at all.

Can we please get the old 1.7.10 version back? (Just made compatible with 1.12.2) ...

Versions:
Windows Server 2012
Minecraft: 1.12.2
Forge: forge-1.12.2-14.23.2.2654-universal (recommended release)
Java 9.0.4 (9.0.4+11)
FTBU, FTBLib: 5.0.2.10
Further mods irrelevant, issue persists without other mods

Greetings
Pingger

**Comment by LatvianModder** [comment]
What do you mean, no config file? Its in config/ftbutilities.cfg. Not sure about other issues but you shouldn't be using Java 9 with Minecraft, it will cause issues. Minecraft ships with its own Java 8 instance for a reason

**Comment by Pingger** [comment]
No ... there is no 'ftbutilities.cfg' but there is a 'ftblib.cfg'

**Comment by Pingger** [comment]
Java 8 did not fix the issue.
Starting the server on my home computer (Windows 7, Java 9) created the config. Coping it to the server makes the server acknowledge it and use it.

But still, the config is not created automatically. And since the Documentation is still missing, I can't create one on my own ... (Maybe I could by searching through the source code, but it is not my job to document your code properly so I can get the correct config file ... I found several jsons but these are all the wrong ones)

**Comment by Pingger** [comment]
Here's the environment I used: https://www.dropbox.com/s/9mo0ivo7lgeq3xf/test.7z?dl=0
Java jre1.8.0_161 was used. (as can be extracted from the _start.bat)

**Comment by LatvianModder** [comment]
Do your issues still occur with .11+ versions? The config simply *can't* be gone, I have tested it and it always gets created

**Comment by Pingger** [comment]
config is created and recognized now
