### ISSUE TITLE
An ability to block friends from placing/destroying your claimed blocks but still allow interaction

### ISSUE THREAD

**Issue by piks** [LatvianModder/FTBUtilities#711]
Currently using Computercraft as an access control to my base, but friends are able to just place a pressure plate infront of the door to get in instead of using the computer, this completly bypasses the security. I can't make my chunk private because that will block interaction. 

version: 1.7.10 (I read in another issue this version was feature locked though...)

**Comment by LatvianModder** [comment]
Sorry, you can only do that in 1.12 version, and yeah, 1.7.10 is dead for me

**Comment by piks** [comment]
Shame, the older versions have more mod support, but it's understandable, thanks anyway

**Comment by LatvianModder** [comment]
That's not true. It may have more mods, but support definitely goes 90% for 1.12.2. Afaik only Reika updates his mods for 1.7.10
