### ISSUE TITLE
What was changed in the last update?

### ISSUE THREAD

**Issue by TripleZ0** [LatvianModder/FTBUtilities#714]
No changelog. So what was changed in the latest update?

**Comment by choekstr** [comment]
Nothing has changed as this is the norm.  They never provide changelogs, same as for most FTB packs as well  *poke*  ;)

**Comment by LatvianModder** [comment]
oh shoot. I forgot to add changelog lol. You can partially see it here until I format that better for CF: https://jenkins.latmod.com/job/FTBUtilities/changes and https://jenkins.latmod.com/job/FTBLib/changes
