### ISSUE TITLE
LAN Chunk Claim Issue

### ISSUE THREAD

**Issue by Entorien** [LatvianModder/FTBUtilities#717]
I cannot find anyone else with this issue, so this is my last resort.

I started a world with the correct version of Forge, FTBUtilities and FTBLib, and opened the world to LAN for my wife to join me. (Yes, she has the same mods loaded). I created a one person team, made sure she was not a member, set the team settings so that you have to be a member to affect anything, claimed the chunk, and...

She can still break blocks.

We tried just about everything, reloading, setting each other to enemies, having her in a one person team of her own, (I can break blocks in her claim, too), switching between creative and survival. I've been haunting Google for over an hour trying to find someone with the same issue, no luck.

Using Java edition PC
Windows 10 OS
Latest version of Minecraft
Latest version of Forge
Latest version of both mods.

The land claim is the only part of the mod we actually want, since we play with our four year old and she likes to break things! Any help appreciated, sorry if I'm missing any data, haven't had to use Github in years!

**Comment by LatvianModder** [comment]
Humm, it could be because in LAN it may think that you are OP so you are allowed to break any block, I will look into that. Meanwhile, try commands `/ranks set_permission player ftbutilities.claims.block.edit false` and `/ranks set_permission op ftbutilities.claims.block.edit false`

**Comment by Entorien** [comment]
So, while testing those commands we found something out quite by accident: It's only wool blocks. Everything else is acting exactly as it should, we ran a load of tests with different blocks, flowers, harvesting wheat, killing mobs, etc. The only thing my wife can damage in an area claimed by me is wool. We tested wool of every colour, and carpet. It's just the full blocks.

So, as long as we don't build in wool, we should be safe from my daughter's destructive spirit! Thanks for the help! :-D

If there's any more testing I can do to help with fixing this oddity, please let me know. We have a test world now, may as well use it. :-)

**Comment by LatvianModder** [comment]
That's... *very weird*

**Comment by LatvianModder** [comment]
I guess I will do some testing in lan.. With wool blocks specifically :P

**Comment by Entorien** [comment]
We found another oddity. Turns out my daughter can still place pictures inside other people's claims. I now have some... unusual decorations. I'll let you know if we find anything else.

**Comment by LatvianModder** [comment]
Alright, then throw in some `/ranks set_permission player ftbutilities.claims.item false` and `/ranks set_permission op ftbutilities.claims.item false`
