### ISSUE TITLE
Having trouble change max chuncks players can claim...

### ISSUE THREAD

**Issue by EnderGamingFilms** [LatvianModder/FTBUtilities#719]
So, I'm trying to change the number of chuncks players can change on my server and every time I try to put the likes like "ftbu.chunckloader.max_chuncks" into the config section and do /ftb reload in console it just pushes all my settings into the permissions section. I honestly wish we could toggle this through config if we didn't want to use ranks. Because I am using sponge on my server and use Lucky Perms to do everything.

```{
	"default_ranks": {
		"player": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": {
				"command.help": true,
				"ftbu.chunkloader.max_chunks": 5,
				"ftbu.claims.forced_explosions": "-",
				"ftbu.claims.max_chunks": 50,
				"ftbu.homes.max": 2
			}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": {}
		}
	}
}

**Comment by LatvianModder** [comment]
change all `ftbu` to `ftbutilities`

**Comment by EnderGamingFilms** [comment]
That didn't work... I stopped the server, changed it. Then started it again and nothing changed.

**Comment by chouuul** [comment]
I have the same problem :/ So hard for me ... a solution please ?
