### ISSUE TITLE
Still having the same issue... (Ranks not working)

### ISSUE THREAD

**Issue by EnderGamingFilms** [LatvianModder/FTBUtilities#721]
Yes, ranks are enabled on the server. I'm on 1.12.2 Sponge - 2655. I still cannot limit the amount of chunks players can claim... Also is there any way to do this through a permissions manager like Lucky Perms? If not, it's fine as long as I can get this working...

```"default_ranks": {
		"player": "player",
		"op": "op"
	},
	"ranks": {
		"player": {
			"parent": "builtin_player",
			"permissions": {
				"command.help": true,
				"ftbutilities.chunkloader.max_chunks": 5,
				"ftbutilities.claims.forced_explosions": "-",
				"ftbutilities.claims.max_chunks": 50,
				"fftbutilities.homes.max": 2
			}
		},
		"op": {
			"parent": "builtin_op",
			"syntax": "<&2$name&r> ",
			"permissions": {}
		}
	}
}

**Comment by ktole1999** [comment]
if you want all players to have same chunks then use the config. op and non op settings are there. Other than that i am not sure.

**Comment by EnderGamingFilms** [comment]
What do you mean config, I didn't see anywhere else to change chunk claiming limits...

**Comment by SpiritCracker** [comment]
I am also having the same problem, all the permission doesn't seem to work. It only reads the defaults.

**Comment by LatvianModder** [comment]
This wont work properly with sponge. Also you got misspelled fftbtuilities, and you might need to copy same thing to OP permissions

**Comment by EnderGamingFilms** [comment]
Alright, I got everything working thnx.
