### ISSUE TITLE
Crash on world generation

### ISSUE THREAD

**Issue by Obbdot** [LatvianModder/FTBUtilities#725]
Hi. I've been redirected from forge's support to here.

You can see the error log and context, and the comment from Forge support here:

http://www.minecraftforge.net/forum/topic/64395-crash-on-world-new-world-creation/

version: 
FTBUtilities-5.0.2.12.jar
FTBLib-5.0.2.12.jar

**Comment by LatvianModder** [comment]
Argh, I blame Forge in this one. I will see if I can figure way around this issue, but I will PR forge to fix that

**Comment by LatvianModder** [comment]
Try the .13 versions anyway, they maybe have fixed it

**Comment by CraftalotReloaded** [comment]
I had the same issue on .12, .13 fixed it for me
