### ISSUE TITLE
Add BackupEvent

### ISSUE THREAD

**Issue by MinecraftXwinP** [LatvianModder/FTBUtilities#726]
I am running a private server on GCP(Google Cloud Platform). The server is run in Docker and the I/O speed of the volume is very constraint. I am thinking if it's possible to make FTBUtilities backup to S3 or Google Storage directly.

**Comment by LatvianModder** [comment]
It probably *is* possible, but I would much rather just add an event for backup so another mod can do it. I mostly only want to add features that other people could utilize, not just 0.0001% of players :P

**Comment by MinecraftXwinP** [comment]
Yeah, an event export InputStream should be enough. :+1:
