### ISSUE TITLE
RuntimeException when attempting to break Ender IO Machines With Yeta Wrench

### ISSUE THREAD

**Issue by Proaxel** [LatvianModder/FTBUtilities#727]
When Sneak-Right Clicking on Ender IO machines and conduits with a Yeta Wrench, they should immediately break and drop as an item. Instead, a java.lang.RuntimeException is thrown upon sneak right-clicking, and the game freezes and crashes shortly afterward. When logging back in after the crash the machine is not broken at all. Breaking the same machine by holding left click with a pickaxe works fine.

The first line of the Crash Log says

> "java.lang.RuntimeException: Do not check permissions on client side! Node: enderio.wrench.break.block_wireless_charger"

and the first line on the stacktrace says 

> at com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler.hasPermission(FTBUtilitiesPermissionHandler.java:44)

By this, it seems to be an issue with how block breaking permissions are handled by FTB Utilities... 

Crash Logs
https://gist.github.com/Proaxel/6aaa624a7df784320235c5d03cd320ce
https://gist.github.com/Proaxel/76d78a376f02b037d955a6da70e4f43a
https://gist.github.com/Proaxel/5669905d8e14a3dc3c42553ee59c0b24

This is on a multiplayer server running All The Mods 3 5.9.5. [I originally posted this issue on the modpack's Github issues page, and Boomflex redirected me here.](https://github.com/AllTheMods/ATM-3/issues/565)

The pack is using FTBLib 5.0.2.11, and FTBUtilities 5.0.2.11.

**Comment by LatvianModder** [comment]
Already fixed in latest
