### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CraftalotReloaded** [LatvianModder/FTBUtilities#728]
A PVPLogger would be usefull alongside the upcoming command warmup to prevent people from escaping during combat.
And perhaps something that keeps a player ingame for x seconds after they log off would also be usefull to prevent people from logging off before they even get hit.

**Comment by MinecraftXwinP** [comment]
Might able to add delay to log off, but what if they just shutdownt the game to escape XD?

**Comment by CraftalotReloaded** [comment]
Then you still keep their player in there until that amount of time has passed

**Comment by LatvianModder** [comment]
Can't do that level of hackery. But it already checks for HP changes in warmup timer

**Comment by CraftalotReloaded** [comment]
And how do i set the warmup timer?

**Comment by LatvianModder** [comment]
`"ftbutilities.spawn.warmup": 10` for example
