### ISSUE TITLE
Player_ranks.json and ranks rewriting themselves of server startup

### ISSUE THREAD

**Issue by Zang518** [LatvianModder/FTBUtilities#729]
MC Ver
-1.12.2
Forge
-14.23.3.2673
FTBUtils
-FTBUtilities-5.0.2.10

Everything editing wise is done while the server shutdown and/or running. I copy the example.json from https://guides.latmod.com/ftbutilities/ranks/example_config/.  When I start the server back up, I watch the the local\ftbutilities folder, right about when the server is completely loaded, the modified time of the ranks.json changes and when I open the rank.json up, I am left with the default rank.json. In the past, I just set the file to read only but that doesn't seems to work anymore as I get this error.

[02:02:57] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.util.JsonUtils:toJson:113]: java.io.FileNotFoundException: D:\Enigmatica+2+Server+1.35\local\ftbutilities\ranks.json (Access is denied)

And some other errors that follow such as
[02:02:57] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.util.JsonUtils:toJson:113]: 	at java.io.FileOutputStream.open0(Native Method)
[02:02:57] [File IO Thread/INFO] [STDERR]: [com.feed_the_beast.ftblib.lib.util.JsonUtils:toJson:113]: 	at java.io.FileOutputStream.open(Unknown Source)

The file is absolutately there, but when I try to assign a rank it says "this feature has been disabled" even though in the ftbutilities.cfg in the config folder under ranks "B:enabled=true" 
ranks {
    # Enables ranks and adds command.x permissions and allows ranks to control them.
    B:enabled=true
the ranks option is enabled. What I'm really trying to is allow myself more load chunks but I cannot get the ranks.json or the player_rank.json to stop rewriting themselves to default values and context upon server startup. 

Just tried again to edit while the server was running and run a /ftb reload command and says and this is not due to the file set to read only as I have disabled that. I am also opped on the server.
**These ids failed to reload:
ftbutilities:ranks**
![2018-05-14_02 45 15](https://user-images.githubusercontent.com/6557762/39982065-1e84cb2a-5721-11e8-908d-0f9be890c919.png)

I am just at a complete lost and have spent at least 3 to 4 hours trying to get ranks to work properly but anything I try, copy and paste, editing just the base default file and adding this to the config portion of the rank
"ftbutilities.chunkloader.max_chunks": 40,
"ftbutilities.claims.max_chunks": 80

As soon as I start the server back up everything gets wiped out back to default no matter if its done with or without the server running. 
Posting here is very last resort to figuring out if it's me, the server setup, or utils itself.
Thanks very much ahead of time for any info or support that can be provided. I have gone over https://guides.latmod.com/ftbutilities/ many times but both files revert back to default on startup.
This is currently my ranks before it gets wiped back to default
https://pastebin.com/F1n2wWbQ

**Comment by LatvianModder** [comment]
Oh, hah.. I probably should mention that comments arent allowed in actual ranks file xP so remove all //comments and try again

**Comment by Zang518** [comment]
Thanks Latvian for the quick response. Will remove the comments and try again. :)
