### ISSUE TITLE
/home takes player to spawn

### ISSUE THREAD

**Issue by Alaberti** [LatvianModder/FTBUtilities#73]
Using 1.7.10-1.0.17.6. After setting a home on a server, using /home took me back to the spawn. A second player confirmed.

**Comment by mainframecn** [comment]
having that same issue with FTBUtilities-1.8.9-2.0.2.jar

**Comment by Symsyr** [comment]
I am getting an error whenever I try to use the /home set command that it will not let homes be set.  The version that I am using is 1.7.10-1.0.17.6

**Comment by LatvianModder** [comment]
Should be fixed in 1.0.18
