### ISSUE TITLE
FileUtils.copyFIle might cause memory leak.

### ISSUE THREAD

**Issue by MinecraftXwinP** [LatvianModder/FTBUtilities#732]
The issue is about FTBLib.
In code [FileUtils.copyFile](https://github.com/LatvianModder/FTBLib/blob/cf7ae350540fdc31136f72185a85916d23472e62/src/main/java/com/feed_the_beast/ftblib/lib/util/FileUtils.java#L264).
`dstC.transformFrom ...` might throws IOException. If an exception is threw,it will cause `srcC.close()` and `dstC.close()` not reached right? I am not sure if it won't cause memory leak/ If it will, maybe should use try-with-resource there.
```java
	dst = newFile(dst);
	try (FileChannel srcC = new FileInputStream(src).getChannel();
	    FileChannel dstC = new FileOutputStream(dst).getChannel())
	{
		dstC.transferFrom(srcC, 0L, srcC.size());
	} catch (IOException e)
	{
		throw e;
	}
```

**Comment by LatvianModder** [comment]
But it does use try-with-resource.... look, both FileChannels are inside try()

**Comment by MinecraftXwinP** [comment]
@@ The code I posted is the suggestion. Here's the actually code at current master:
```java
public static void copyFile(File src, File dst) throws Exception
	{
		if (src.exists() && !src.equals(dst))
		{
			if (src.isDirectory() && dst.isDirectory())
			{
				for (File f : listTree(src))
				{
					File dst1 = new File(dst.getAbsolutePath() + File.separatorChar + (f.getAbsolutePath().replace(src.getAbsolutePath(), "")));
					copyFile(f, dst1);
				}
			}
			else
			{
				dst = newFile(dst);
				FileChannel srcC = new FileInputStream(src).getChannel();
				FileChannel dstC = new FileOutputStream(dst).getChannel();
				dstC.transferFrom(srcC, 0L, srcC.size());
				srcC.close();
				dstC.close();
			}
		}
}
```

**Comment by MinecraftXwinP** [comment]
Sorry. It's my bad to cause misunderstanding. I've updated my post.

**Comment by LatvianModder** [comment]
Ah, I see. I will update it then
