### ISSUE TITLE
NPE with ITeleporter

### ISSUE THREAD

**Issue by CDAGaming** [LatvianModder/FTBUtilities#733]
[crash-2018-05-20_13.03.01-client.txt](https://github.com/LatvianModder/FTBUtilities/files/2020382/crash-2018-05-20_13.03.01-client.txt)
[crash-2018-05-19_22.46.35-client.txt](https://github.com/LatvianModder/FTBUtilities/files/2020383/crash-2018-05-19_22.46.35-client.txt)
A few of my  servers users are commenting on an Issue when accessing certain GUIs in FTBUtilities

**Comment by MinecraftXwinP** [comment]
Like #730. `ITeleporter` interface was added after forge build number 2651 (you are using 2612).
Try update forge version.

**Comment by CDAGaming** [comment]
I'll let them know, thank you :)

**Comment by LatvianModder** [comment]
Yeah, I updated forge version in mod, so it should now properly warn when there is outdated Forge
