### ISSUE TITLE
Thaumcraft and ftb utilities (use seal)

### ISSUE THREAD

**Issue by larskr96** [LatvianModder/FTBUtilities#734]
Thaumcraft golem not able to Place anything ontop of the use seal when claming chunks is active.

(not sure if its ftb or thaumcraft side so i posted one for each of you
https://github.com/Azanor/thaumcraft-beta/issues/818

**Comment by LatvianModder** [comment]
I don't see azanor ever replying to issues, I'm guessing its Thaumcraft issue. Most likely not using fake players correctly, so Im gonna close it here
