### ISSUE TITLE
Question about Home Cooldown/Warmup

### ISSUE THREAD

**Issue by Hail4Gaming** [LatvianModder/FTBUtilities#735]
I was looking through the case where someone requested these and I saw it was added, but all I could find was "ftbutilities.homes.cooldown" to change how long the cooldown is. On the server I run, I want no restrictions for the cooldown or movement warmup and I cannot find how to config these, so I thought I would ask here. I have 2 questions.

1) Is cooldown time in minutes or seconds? "ftbutilities.homes.cooldown": 30, would that be seconds or minutes?
2) What is the permissions node for movement warmup for home teleport? EDIT: <As in, how can I disable it "Please do not move for 5seconds to use /home" to 0seconds>

Sorry for the inconvenience, I looked around and didn't see it, though may have missed something.
Hail

**Comment by LatvianModder** [comment]
1. I fixed the confusion problem with adding new type of config, timer. It now uses string, "5s" or "10m" for example, will be in next version.
2. `ftbutilities.homes.warmup`, set that to 0

**Comment by Twonkk** [comment]
@LatvianModder 

would this be a mod update or can we just toss the `ftbutilities.homes.warmup 0` into the current config?

**Comment by LatvianModder** [comment]
`ftbutilities.homes.warmup: 0` in ranks.txt under whatever rank you want to add that to

**Comment by alck-wang** [comment]
but what's the file name?
