### ISSUE TITLE
"/admin reset_pos <playername>" to reset an offline player's location

### ISSUE THREAD

**Issue by LoyLT** [LatvianModder/FTBUtilities#74]
feature request -- an admin level command to reset an offline player's location back to overworld spawn location, and reset the three momentum values of that player to 0,0,0

reason... sometimes a player gets bugged and can't log back in, due to a rendering or some other issue near where he's located

/admin resetPos playername
should simply send them back to overworld spawn point, which should in most cases be an acceptable safe point... once the player logs back in, admin can choose to /tp or they can choose to /home

**Comment by LoyLT** [comment]
note... make sure to set dim back to 0..... regardless of what dim they were bugged in

**Comment by Goten87** [comment]
Why not just let THE place be spawn that when he logs in it like he is just Starting only with all his stuff in his inventory

**Comment by LatvianModder** [comment]
Added in https://github.com/LatvianModder/FTBUtilities/commit/fa99bf2840aab0d9c9e257133edd50f305492c9b
Will be implemented later
