### ISSUE TITLE
Crash with newest versions

### ISSUE THREAD

**Issue by TheSnowyChickens** [LatvianModder/FTBUtilities#740]
Your newest beta versions from today + MC 1.12.2 with Forge 1.12.2 - 14.23.3.2702
Crash link : https://paste.dimdev.org/imuvajulav.txt

Crash txt : [crash-2018-05-24_21.37.55-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2036869/crash-2018-05-24_21.37.55-server.txt)

It happend, If I load or create a world.

Modlist is in the crash log link.

**Comment by LatvianModder** [comment]
Can you post your ranks.json here please?
