### ISSUE TITLE
Crash Loading Savegame

### ISSUE THREAD

**Issue by MokahTGS** [LatvianModder/FTBUtilities#744]
FTBU 5.1.0.23
Forge 2702

Crash Log: https://paste.dimdev.org/zexilumafu.txt

Getting a crash loading a previous savegame after updating to the new version.

Full mod list: https://paste.dimdev.org/ataqaruviv.md

You closed this issue...but the fix didn't fix the crash: https://github.com/LatvianModder/FTBUtilities/issues/742

Rolled back to FTBU 5.1.0.14 and it works fine.

**Comment by LatvianModder** [comment]
I did in https://minecraft.curseforge.com/projects/ftb-utilities/files/2566378
