### ISSUE TITLE
command block and home / sethome

### ISSUE THREAD

**Issue by jaz000** [LatvianModder/FTBUtilities#749]
should I be able to use these commands in command blocks?

1.12.2
FTBLib-5.1.0.17.jar
FTBUtilities-5.1.0.19.jar

console command:
/execute @a[score_toSpread=1] ~ ~ ~ sethome tspawn
output:
[23:38:39] Failed to execute 'sethome tspawn' as jaz000

console command:
/execute @a[score_toSpread=1] ~ ~ ~ home tspawn
output:
[23:38:39] Failed to execute 'home tspawn' as jaz000

**Comment by LatvianModder** [comment]
Uh... Wtf? Why not just use warps...

**Comment by jaz000** [comment]
I'm trying to send each player to a unique place and then save it.

This follows a spreadplayers command

I'm trying to simulate each player having a unique spawn point

**Comment by LatvianModder** [comment]
Use vanilla /spawnpoint command for that then...

**Comment by jaz000** [comment]
Yeah that mostly works, but is overridden by a bed which could then be lost sending the user back to world spawn. I'd feel I have to tell everyone to write down their co-ordinates and admin tp them back in an emergency
