### ISSUE TITLE
crash on server start. Exception in server tick loop

### ISSUE THREAD

**Issue by catchra** [LatvianModder/FTBUtilities#754]
[crash-2018-05-31_22.13.18-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2060775/crash-2018-05-31_22.13.18-server.txt)
[debug.log](https://github.com/LatvianModder/FTBUtilities/files/2060776/debug.log)
[latest.log](https://github.com/LatvianModder/FTBUtilities/files/2060777/latest.log)

**Comment by LatvianModder** [comment]
Update mods and reopen if the same still happens
