### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by projdarkmoon** [LatvianModder/FTBUtilities#755]
![image](https://user-images.githubusercontent.com/14205729/40823658-1e17e97a-653f-11e8-9515-8e636dae9004.png)

While in admin Rank this is all i see when i chat (rapid changing letters). i have attempted to search for a resolution but unable to find one.
How can this be fixed. Thank you.
Running Minecraft 1.12.2

+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

**Comment by LatvianModder** [comment]
That's because you gave admin rank `*: true`. Add `ftbutilities.chat: false` and it should fix the problem
