### ISSUE TITLE
rank name format does not change when changing ranks.

### ISSUE THREAD

**Issue by TheQKnight** [LatvianModder/FTBUtilities#756]
I created a few ranks that include a default player rank and a default op rank. They each have a different name format in chat assigned to them. When I open a singleplayer world and enable cheats, the one that i assigned the default op rank appears in chat. The weird thing is that when i type /ranks set (my name) player, it just keeps my same name formatting for the op rank and just changes the chat color.

**Comment by LatvianModder** [comment]
paste your `ranks.txt` here

**Comment by TheQKnight** [comment]
[ranks.txt](https://github.com/LatvianModder/FTBUtilities/files/2064747/ranks.txt)
