### ISSUE TITLE
Number of claims chunks 1.12.2

### ISSUE THREAD

**Issue by BaentyServ** [LatvianModder/FTBUtilities#758]
Hello,
I have a problem, at stake chunks claims are at 100 and loads at 50. I do not understand, can you tell me if the file is valid and if so what is the problem. 
Cordially
> [ranks.json](https://pastebin.com/t0SV8PKj)

**Comment by BaentyServ** [comment]
it's on "permissions" because "config" has deleted

**Comment by LatvianModder** [comment]
Change `ftbu` to `ftbutilities`

**Comment by LatvianModder** [comment]
You should also consider updating the mods - [new format is much easier to use](https://guides.latmod.com/ftbutilities/ranks/config/)
