### ISSUE TITLE
dofiretick gamerule / Claimed Chunks

### ISSUE THREAD

**Issue by O13SC3N3** [LatvianModder/FTBUtilities#76]
Is it possible like disabling explosions in your claimed chunks to disable the firetick rule as well? I got a few people up in arms cuz they keep burning their house down -.- And yet I want to keep the firetick true for other world aspects...

**Comment by Goten87** [comment]
I think its a good idear to have all game rules to be togebol in claimed chunks

**Comment by LatvianModder** [comment]
Yeah, I can't do that, forge doesn't allow per-chunk / block fire tick, that is per-world

**Comment by Dijkstra1** [comment]
I do not claim to know full forge api so do not if this is possible, but I do know that blocks can be fire proof if the instances all of the blocks in claimed where made fire proof, then this type of griefing would not be able to happen.

**Comment by LatvianModder** [comment]
Nah, that would be waaay to hacky and risky to do. I try to use as few hacks as possible

**Comment by O13SC3N3** [comment]
Yeah I'm trying to stay away from essentials so I'm telling people deal with it ;p least creepers don't blow your house up. I do know the ic2 nuke or reactor meltdown bypasses the protection tho. Had someone test it out on their own base thinking it be safe... Rather Amusing.
