### ISSUE TITLE
[Question] Spawn Protection Node

### ISSUE THREAD

**Issue by Hail4Gaming** [LatvianModder/FTBUtilities#760]
Hey, I was looking through and didnt see anything, but is there a permission node where I can make a non-op have rights to build in the Spawn? Spawn protection is a helpful tool, but I have a trusted rank that I would like to be able to build there, however, I do not want many ops lol. I was just wanting to know if I could turn off Spawn Protect for those specific ranks, and if so, how?

Thanks for reading,
Hail

**Comment by LatvianModder** [comment]
Will be in this: https://github.com/LatvianModder/FTBUtilities/issues/88
