### ISSUE TITLE
player_ranks.txt resets on server restart.

### ISSUE THREAD

**Issue by antonia1986** [LatvianModder/FTBUtilities#761]
I am allowed to add players to the ranks using commands on the server but everytime the server restarts the player_ranks.txt is blank again. Rank is turned on in config file and the ranks.txt does not reset. 

Playing on Minecraft 1.12.2, forge version 14.23.4.2705, FTBu 5.1.0.24.

**Comment by ProxyNeko** [comment]
This was fixed in a newer version according to [Lat's post on Reddit](https://www.reddit.com/r/latmod/comments/8nmldq/june_news/)
