### ISSUE TITLE
Total Backup's Size is calculated every backup | Causes Server to Hang for large number of backups

### ISSUE THREAD

**Issue by Inrixia** [LatvianModder/FTBUtilities#763]
We have over 400 backups for our Continuum server and recently ran into a issue where it would finish copying the files for a backup but then would sit at 100% eventually causing the server to hang and world rollback (As world saving is disabled at the beginning of a backup).

After a lot of investigation I found that FTBU calculates the size of all backups from the filesystem after each  backup instead of just using the backup size that it stores in the backups.json.

We don't have FTBU store our backups in zip's so we can use DeDupe meaning that with each new backup its another 8k+ files FTBU has to calculate the sizes for. At 400+ backups it gets to the point where it cant finish calculating the size of all the backups and just hangs. Spitting out this:
[![Screenshot from Gyazo](https://gyazo.com/263d11dc098f735b062fa89f9d4b98af/raw)](https://gyazo.com/263d11dc098f735b062fa89f9d4b98af)

Disabling the option to print the size of archives after a backup in the config seems to stop this from happening. A easy fix for this should be to just aggregate the "size" of each backup from the backups.json.

**Comment by LatvianModder** [comment]
That's what it already does in later versions, wait for continuum update I guess

**Comment by LatvianModder** [comment]
Hmm, https://github.com/LatvianModder/FTBUtilities/blob/master/src/main/java/com/feed_the_beast/ftbutilities/data/backups/Backups.java#L278-L281 Maybe something else is taking that long? Or prehaps I havent updated the mod with those changes, but I'm pretty sure I did

**Comment by Inrixia** [comment]
I'll do more testing tomorrow to double check then. It could have hung for a bit due to another reason.

**Comment by Inrixia** [comment]
Just did some more testing. Sorry for the delay, but can confirm this issue still happens on the latest version.

**Comment by LatvianModder** [comment]
What is weirder is that it displays `0 | NaN%` several times before backup <.<

**Comment by Inrixia** [comment]
^ It does it a little on older versions. I just presumed it was printing before it properly started backing up. Eg getting the list of files its gonna backup or something but printing status before the main backup function starts.

**Comment by LatvianModder** [comment]
Yeah, most likely. NaN happens when you do `0/0` so I guess it displays that while its compressing/idling. That's minor issue. My guess the real issue happens when its trying to free up space for new backup/deleting old backups. Why do you keep 400 backups? What does the backups config section look like?

**Comment by Inrixia** [comment]
We actually keep up to 1024 at the moment. Backups done hourly, we dont set a limit because we have the space to store loads so why delete extras. When testing with the latest version I set the max size to be 50TB and max backups to 1024. So I dobut the lag is a issue with it removing old backups. It actually finishes backing up the server, its only after it finishes that it stalls. Basically the same as the image I posted above. Neverending printing that last line in console.

**Comment by LatvianModder** [comment]
Oh I see. ~~That's very weird because after that `Created x from y` basically nothing happens in code.~~ Ah, found the issue. Should be easy fix

**Comment by Inrixia** [comment]
Sweet

**Comment by LatvianModder** [comment]
If you disable display_file_size in config, it should be fine until I update the mod

**Comment by Inrixia** [comment]
Yep thats what ive done for now. Thanks

**Comment by Possemaster** [comment]
Disabling **display_file_size** does not fix my issue I posted in #767 .
The backup starts and immediately the server does not respond untill the backup is completely finished after 8 minutes.

![start](https://user-images.githubusercontent.com/7541145/41164086-9d983f1e-6b3a-11e8-8dc0-a12283b1bfbc.PNG)

**Comment by LatvianModder** [comment]
Im not sure anymore what else I changed, so you will have to wait until I push an update to test again if I fixed it
