### ISSUE TITLE
[1.12.2] [5.1.0.26] FTB Utilities and Thaumcrafts Use seal

### ISSUE THREAD

**Issue by wamc2017** [LatvianModder/FTBUtilities#764]
Hi,

don't know if this is related to #734 but if FTB Utilities is present (the area don't need to be claimed) the use seal doesn't work and the log throws the following error every time the golem tries to right click a block (in this case a cauldron with a bucket, filled with water):

https://gist.github.com/wamc2017/5985748b1db25115413711fb59cfb040

Everything works fine if FTB Utilities is not present. Also tried other blocks (like the lightwell from Astral Sorcery with aquamarines) with the same result.

Mods I used to test this issue (no other mods installed):
Baubles-1.12-1.5.2
FTBLib-5.1.0.21
FTBUtilities-5.1.0.26
jei_1.12.2-4.9.2.196
Thaumcraft-1.12.2-6.1.BETA16
Forge-14.23.4.2707

Issue on Thaumcraft's tracker: https://github.com/Azanor/thaumcraft-beta/issues/956

Thanks for looking into it.

Best regards,
wamc

**Comment by LatvianModder** [comment]
Oh.. so he didn't fix it... :/
