### ISSUE TITLE
[1.12.2] [5.1.0.26] FTB Utilities Large Backup Waiting for Server

### ISSUE THREAD

**Issue by Possemaster** [LatvianModder/FTBUtilities#767]
I have tested this issue on several Modpacks. (All the Mods 3, FTB Continium, FTB Revelation)
I always tend to pregenerate my servers, and so a lot of servers are 20+GB in world folder size.

Now I have the issue that FTBU Backup is causing a 10 minute unresponsive server during this backup.
In game the users are seeing "Waiting for Server" and disconnect after 30 seconds. My console is locked as well, I can type commands but they will not show untill the backup is done.

I tried anything in the settings;
1. Move backup to another drive (2 NVME discs Samsung 960 Pro)
2. Disable compression (CPU 8700k usage with compression is only 10%)
3. Config (Use different thread = on) No difference

None of these solves my issue
Does anyone else experience this issue and is there a solution for this problem?

Thanks

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/763

**Comment by Possemaster** [comment]
Same issue is still present in 5.1.0.27.
Could you reopen this post?

**Comment by LatvianModder** [comment]
Humm. Is it better at least?

**Comment by Possemaster** [comment]
Hi @LatvianModder .
For me nothing changed.
I tested it on a clean install of the modpack, and than it works fine only my official server has a WORLD folder that is 20+GB as I prerendered all dimensions.
So it immediately freezes during backup untill the backup is done.

As mentioned , I already turned all display options off. And tried compressed vs non compressed and tried different drives. non will fix the issue or make it better.

**Comment by Saereth** [comment]
I am having this issue on our servers as well. Our world size is about 12gb and I'm having the issue even after deleting all existing backups, fresh directly. Checking warmroast just results in showing a hang at the time sleeping waiting on io. https://imgur.com/a/EtdSgMp  

https://media.discordapp.net/attachments/134686202715439105/456839896611422209/unknown.png?width=1079&height=153

**Comment by LatvianModder** [comment]
Humm, so it seems like issue is from completely different side. I knew I fixed the size thing so it couldn't be it. The IO thread isnt supposed to block normal game, I will have to investigate that

**Comment by Possemaster** [comment]
The mod pack I use has updated to All the Mods 3-v5.9.7b wich updated to Forge 2707 and this solved my issue. FTBU 5.1.0.27 with older forge caused the IO issue.
