### ISSUE TITLE
Suggestion: Spawn Area claiming

### ISSUE THREAD

**Issue by Possemaster** [LatvianModder/FTBUtilities#768]
Is it possible to have the OP or Admin rank be able to Chunk Claim the Spawn Area as a "Spawn team".
So you see it as Spawn Area.
I know we have spawn protection "area", but it would be nicer to have it look like the other claims, like a color on the map as the other team claims are. And the OP/Admin can Expand and change it, or enable chunk loading on a claim in the spawn.

Now I have to do it under my own team, but as a Server Admin I would love this to be seperate.
You could even expand on this to be able to enable/diable PvP on a claim etc...

Keep up the good work , I love this MOD.

**Comment by LatvianModder** [comment]
#88
