### ISSUE TITLE
in-game guide not showing text, only graphics

### ISSUE THREAD

**Issue by LoyLT** [LatvianModder/FTBUtilities#77]
http://i.imgur.com/yi05Egb.png
This is infinity v2.4.2,.. both normal and expert mode are hiding the text

**Comment by Dijkstra1** [comment]
Have try the command /reload

**Comment by MJRamon** [comment]
How do you even write guides? FTBUtilities-1.7.10-1.0.17.6

**Comment by Dijkstra1** [comment]
Go to your minecrart dir then goto modpack then choose a mode, go into the guide folder then make a folder for your section and in that make text files for the pages you can apply formating as well I suggest having a look at the infinity expert guide to see how it works.

**Comment by LoyLT** [comment]
Dijkstra1 -- /reload is a minetweaker command, it has nothing to do with this problem..... go download a fresh version of FTB Infinity v2.4.2, and enter a singleplayer world, and open inventory and go to the guide book and try to pull up any info in the book

**Comment by Dijkstra1** [comment]
LoyLT /mt reload is the minetweaker command, /reload is FTBU it reloads the minetweaker stuff and the guide and i have noticed the guide does not look the best, but it does load or at least time i tried.

**Comment by LatvianModder** [comment]
Fixed in https://github.com/LatvianModder/FTBUtilities/commit/d17c497d78f288709e31b8a25657c137b5373cc5
