### ISSUE TITLE
[1.12.2] [5.1.0.27] [client] crash

### ISSUE THREAD

**Issue by watdafawx** [LatvianModder/FTBUtilities#770]
https://paste.dimdev.org/raw/ezilohijaz

**Comment by Oleksandrigo** [comment]
same error

**Comment by Oleksandrigo** [comment]
I was helped by the rollback of Shadowfacts' Forgelin to the version below.

**Comment by watdafawx** [comment]
Shadowfacts' Forgelin is the problem < not sure if i should close this & report it there or what
