### ISSUE TITLE
Suggestion - Admin Button - Allowing a moderator to set spawn point to /spawn for a players next login

### ISSUE THREAD

**Issue by 0Chameleon0** [LatvianModder/FTBUtilities#771]
This is a suggested enhancement.

Add a button that edits the nbt data of a player to set their next login to /spawn.

Why?
When a player crashes on login due to a bugged block in a region, a moderator can set them to login at spawn easily, not keep crashing in the bugged region on a community server.
Moderators generally don't have access to NBT Explorer and possibly not the knowledge to modify the playerdata.
This option will allow the player to login, then the administrator / moderator can look into the issue in the bugged region, while the player can still play elsewhere on the server.

**Comment by LatvianModder** [comment]
You can do that now, /nbtedit player <name>
