### ISSUE TITLE
Crash on startup (latest versions)

### ISSUE THREAD

**Issue by CommanderTvis** [LatvianModder/FTBUtilities#772]
Game crashes when I try to launch the game... Here's log, report, versions...

https://gist.github.com/CommanderTvis/614195050a8827251ec371146caeabe8

Versions: 
Minecraft 1.12.2
Minecraft Forge 14.23.4.2707
FTBLib 5.1.0.22
FTBUtilities 5.1.0.27

**Comment by LatvianModder** [comment]
Looks like it's same as this: https://github.com/LatvianModder/FTBUtilities/issues/770
