### ISSUE TITLE
Older LMPlayers file reset after update

### ISSUE THREAD

**Issue by phit** [LatvianModder/FTBUtilities#78]
Any config file created with an older version than 1.0.15.x gets reset on world save after updating

reproduction:

make a world folder with this file in the "LatMod" folder
[LMPlayers.zip](https://github.com/LatvianModder/FTBUtilities/files/170357/LMPlayers.zip)

use any mod version > 1.0.14.x

the file will get overwitten with an empty .dat file after world save

errors in log
http://vpaste.net/KOelP

[probably responsible commit](https://github.com/LatvianModder/FTBLib/commit/b26256c99a7a0e49d15e08b51ed3731baf790187#diff-11176455260049810cd41b463d124096L4)

workaround:
open the old file in nbt explorer copy all entries and paste them in a LMPlayers.dat created by a newer mod version
the file size will be about double of the old one

**Comment by LatvianModder** [comment]
Fixed in https://github.com/LatvianModder/FTBLib/commit/8994f7750a6f95efd88f441d25b0b214781bc473
