### ISSUE TITLE
Unclaiming in DIM's after 

### ISSUE THREAD

**Issue by KingDan27** [LatvianModder/FTBUtilities#781]
So my problem I am having is that on my server i previous allowed claiming in the nether which has proved to be an issue for us so i disabled it however now that claiming is disabled OPS cant even remove the old claims which in my mind they should be able too. If there is a way to do this please let me know cause ive tried all the commands i could find related to unclaiming.

So I have 2 suggestions either:
1. allow ops to still unclaim even if claiming is disabled
2. have the mod remove all claims in dims that are disabled

**Comment by LatvianModder** [comment]
Humm, I should instead make them disappear, there shouldn't be a need to unclaim them
