### ISSUE TITLE
FTBLib and Forgelin issue

### ISSUE THREAD

**Issue by dodgythoughts** [LatvianModder/FTBUtilities#782]
Please read before just closing

this is related to issue #780 

the Forgelin suggestion, https://github.com/shadowfacts/Forgelin/issues/38
is to go back to v1.6.0 

but that is the version that sevtech 3.0.8 uses.

here is a crash report from my test server. i nuked the world, so this is a freshly generated world, no users have ever logged in.

FTBLib-5.1.0.22.jar
FTBUtilities-5.0.1.12.jar
Forgelin-1.6.0.jar

[crash-2018-06-15_09.52.02-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2104133/crash-2018-06-15_09.52.02-server.txt)

FTBLib-5.1.0.21.jar
FTBUtilities-5.1.0.26.jar
Forgelin-1.6.0.jar

server boots correctly.

**Comment by LatvianModder** [comment]
#770
