### ISSUE TITLE
SpongeForge breaking /tpa

### ISSUE THREAD

**Issue by Ahniwake** [LatvianModder/FTBUtilities#787]
When I have SpongeForge installed the /tpa command returns null. I have no idea why this is happening, but it frustrates me not being able to install plugins due to the fact that I need /tpa functioning on my server. 

Note. I do not have any plugins installed, meaning that there is nothing that would be overriding the command such as a different plugins that included /tpa

Error: java.lang.NullPointerException

**Comment by Bennyboy1695** [comment]
You'll need to post the log with the whole stacktrace of the error. But i have to ask why are you using ftbutils with spongeforge when theres sponge plugins that do everything ftbutils does ?

**Comment by LatvianModder** [comment]
That or the other way - what can't you do with forge mods that sponge has?

**Comment by Ahniwake** [comment]
One example is /vanish. But there is a bunch of different aspects, like economy plugins, and overall plugins that help the server. And I dont use only sponge because I love FTB Utils Claiming and Permissions.

**Comment by LatvianModder** [comment]
If you dont have any plugins installed, why do you need sponge anyway? I still need that log to tell if there is any error

**Comment by ryantheleach** [comment]
Without logs, all I can assume is that you had another plugin that was also offering /tpa .

IF this is the case, you can find the instructions for choosing which of 2 commands to use for a given alias, here: https://docs.spongepowered.org/stable/en/server/spongineer/commands.html?highlight=conflicts#operator-commands
