### ISSUE TITLE
Backup does not work

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#79]
My server will not backup using your mod, YABM works fine single player however backups fine you using your mod, I can only put it down to my server I set the backup location to my backup drive instead of same one as the server, when I set the backup location "B:\Minecraft\Backups\FTBInfinity", it crashes while loading saying that it can not clean the backup folder, so then I tried "B:/Minecraft/Backups/FTBInfinity" and the server loaded and I thought that was it but when it can to backup time it told me backup complete size 0, and there was nothing in the backup folder, on single player however, I just left as default and it does seem to work give me the size and is putting stuff in the backup folder. Also is it at all possible to change the colour of the backup messages when I see it make me think I got warp from Thaumcraft.

**Comment by LatvianModder** [comment]
Try deleting all existing backups / rename the folder. Worked for someone else with that problem

**Comment by Dijkstra1** [comment]
I have tried changing the backup location to "B:\Minecraft\Backups\FTBInfinity\FTBU" still wont work (FTBU is new empty folder), as for deleting existing backups do not relay want to, may have to move them to another folder at lest the last few.

**Comment by LatvianModder** [comment]
You can't use \ in path. Use /

**Comment by Dijkstra1** [comment]
Ok so I just updated my server, and gave FTBU backup another go it has been while since I read this last so  tired, "B:\Minecraft\Backups\FTBInfinity\FTBU" and "B:/Minecraft/Backups/FTBInfinity/FTBU", one way it is crashes and says it can not clean the back folder, the other says it is backing up, but does not. A also deleted the FTBU folder to see if FTBU would make it it did not seem to then I recreated but no luck. 
Maybe you should do 
'''java
backupPath.replace('\', '/'));  
'''
just that is not a issues, but backup still does not work for me
