### ISSUE TITLE
How to set the cap for claiming chunks?

### ISSUE THREAD

**Issue by H3roDude** [LatvianModder/FTBUtilities#790]
I tried everythink with changing ranks but the config always resets.. is there some way i can change the max claimed chunk size with luckperms?

Forge Version: 14.23.4.2705
FTBU Version: 5.1.0.27

**Comment by LatvianModder** [comment]
>Luckperms

Well there is your problem. If [this](https://guides.latmod.com/ftbutilities/faq/) doesn't work, it just won't work together with that

**Comment by H3roDude** [comment]
yeah but if i add this to the rank config it just resets

**Comment by H3roDude** [comment]
i tried it multiplie times now..
