### ISSUE TITLE
Rank format

### ISSUE THREAD

**Issue by Ravy17** [LatvianModder/FTBUtilities#793]
Heyo been trying to set up an FTB revelation server and it seems no matter what I add to the ranks nothing ever changes in game. I could really use the most dumbed down explanation there is on this subject because I've started over from scratch multiple times trying to set this thing up.  I've copy/pasted in other peoples setups, I've tried typing them out in what I thought was the proper format going by any and all information I could get my hands on. I double check to make sure all commas and crap are in the right place and nothing ever changes. I just want people to have a prefix, 2 homes, tpa, and some claimable chunks. Please dear master of this mod help me. <3

**Comment by LatvianModder** [comment]
Not sure if rev has updated FTBU but this is how you do it in latest: https://guides.latmod.com/ftbutilities/faq/

**Comment by Ravy17** [comment]
the link you gave me gives a 404 error

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/tree/master/guide/faq
