### ISSUE TITLE
Default rank single player makes chat unreadable

### ISSUE THREAD

**Issue by AlHollandiyah** [LatvianModder/FTBUtilities#794]
When I am playing single player with FTBU in my pack, the OP gets all permissions by default. And as I am the only player, I am defaulted to OP. This has a side effect making the chat unreadable, because it also gives me (the OP) the permissions of every possible text format in both my name, prefix, suffix and chat. Including bold, italic, underline, strikethrough and magic. I sometimes use chat to write something down that I need to remember in the coming 10 minutes, but because of this I only get a very unreadable message. Now I did manage to negate those permissions as a workaround, but I believe it might be better if they were negated by default! [These](https://pastebin.com/uLwH1dkw) are the permissions that I am talking about, as taken from all_permissions_full_list.txt

**Comment by LatvianModder** [comment]
Oof
