### ISSUE TITLE
Chat Rank Missing Open Bracket

### ISSUE THREAD

**Issue by Hail4Gaming** [LatvianModder/FTBUtilities#795]
I am currently playing the Enigmatica 2 modpack and I just updated the pack and my server to v1.4 E2. Upon updating this, I noticed that the open-bracket (well, less-than symbol) is missing from the name of the players talking.
https://i.imgur.com/y2MQuQX.png

As you can see, I decided to try to add it to the prefix, however it was recolored. I do realize that this isn't that big of a deal, but OCD prevailed and had me post a report lol. I am sure there are others who find this a tad bit annoying.

Here are the op ranks just to show them to make sure there is no bug in my permissions causing it.
https://i.imgur.com/KKV1s2X.png

Thanks for reading,
Hail

P.S. I didn't add the prefix.part_count -- I assume it did it on its own.
P.P.S. I imagine it is probably a super-simple fix lol, I just thought I would point it out.

EDIT: I would like to add that this pack has Chat Tweaks and I was thinking there is a possibility it could be related to that--having said that, I apologize if this is the case. It could also be some discrepancy between the two.

**Comment by LatvianModder** [comment]
Yep, rank chat formatting changed to simplier but I couldnt convert it properly. If it is one of latest FTBU versions (if not, you can update it yourself on server), here is how you do it now http://guidetest.latmod.com/ftbutilities/ranks/config/ (sorry for weird guides link, main one is down for tonight)
