### ISSUE TITLE
Crash when making team

### ISSUE THREAD

**Issue by phit** [LatvianModder/FTBUtilities#796]
I think it happens during team creation

https://gist.github.com/phit/34bbeebed0548e8f4771fa8b44f78d0d

FTBLib-5.2.0.23.jar
FTBUtilities-5.2.0.28.jar

**Comment by wormzjl** [comment]
https://gist.github.com/wormzjl/658d21a5c9ce2ea606e0bf5c1fd55394
Got the same problem here, players reported that they can't make teams

**Comment by xxlio109** [comment]
The same problem
https://gist.github.com/xxlio109/0e559f829c4f045ea6742bf80cab1a79

FTBLib-5.2.0.24.jar
FTBUtilities-5.2.0.29.jar

**Comment by wormzjl** [comment]
Ok it seems that I'm getting a lot of "BrokenFormatting" player names which are just alphabetic characters, maybe this is related.

**Comment by SimplyLime** [comment]
Am I able to update my server file versions and still have clients connect? Having this same issue on the 29 version of utils on the foolcraft 3 pack. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
