### ISSUE TITLE
/rtp

### ISSUE THREAD

**Issue by MavDarkness** [LatvianModder/FTBUtilities#797]
an /rtp command that will teleport a player to a random location anywhere in the world even if the area isnt generated yet.

**Comment by LatvianModder** [comment]
https://minecraft.gamepedia.com/Commands/spreadplayers 😕

**Comment by MavDarkness** [comment]
ok yes but players cant use that comman unless they are OP.

**Comment by MavDarkness** [comment]
i can confirm that if one players uses /spreadplayers they can target the other players on the server. so having that command enabled for players would be very bad. thats why i asked about an /rtp command that only works on self and not other players

**Comment by Entoarox** [comment]
Button on command block that uses spreadplayers on @p, aka - nearest player.

Put it at the world spawn, and blam - no /rtp needed ;)

**Comment by MavDarkness** [comment]
this is true i didnt think of that lol, though having the command would stop players from saying things like "aw no /rtp" as soon as they join. guess for now ill set spawn point to be right in front of that.

**Comment by ktole1999** [comment]
rtp just requires permission. i use it on my server just fine.
