### ISSUE TITLE
/Back command

### ISSUE THREAD

**Issue by MeinKraft** [LatvianModder/FTBUtilities#799]
Forge 2712, FTB Utilities 5.2.0.28

on a server using the /Back command, several people have reported client crashes
I dont know if its FTB Utilities for sure?  but they cant log in after the crash. We have to re-edit their player data.dat file or delete it

https://pastebin.com/NdaWixsY

**Comment by LatvianModder** [comment]
this doesnt look like ftbu issue at all, maybe its related to something that happens after death? Can they still walk to their last death location without crashing?

**Comment by MeinKraft** [comment]
so you can log into the server, its starts with the respawn screen. so click respawn and all is good,
you can walk back to the death location

I think its because im using Erebus mod. it puts a grave where you die. So technically im teleported back into the same block as the gravestone when using /Back

could we have a config maybe to teleport to block next to grave or check that its air? maybe?

**Comment by LatvianModder** [comment]
it doesnt matter if it teleports in block or not, but the crash report doesnt say anything useful, so I don't know what to fix

**Comment by MeinKraft** [comment]
ok.  Ive reported to Erebus, without that mod /Back is fine

thank you for your time
