### ISSUE TITLE
Chunk claiming/loading interface

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#80]
To claim a chunk you have to click, but usual your is no chunk boundaries or takes up more than one chunk and you have to click each one individually, it would be nice if you click on chunk and keeping your mouse done pull it over the rest of the chunks you would like claim and when you let go you have claim all the chunks in that range, also the same thing for loading chunks would be good.

**Comment by LatvianModder** [comment]
I had that ages ago, I was thinking on re-implementing it too

**Comment by Dijkstra1** [comment]
That would be great it's be kinda bugging me since I been using it.

**Comment by LatvianModder** [comment]
Fixed in 3.0.0.x versions
