### ISSUE TITLE
Totally disable teleport commands

### ISSUE THREAD

**Issue by JonasMK1** [LatvianModder/FTBUtilities#801]
Hi, I would like to know if there's a way to fully disable and to avoid the players in my server to use teleport commands such as /home, /back and /ftb tpa. Thanks

**Comment by F3UR10** [comment]
I think you can define that in the ranks file with:
command.ftbutilties.tp: false

There is an example of deny commands in the guide:
[Guide Ranks](https://github.com/LatvianModder/FTBUtilities/tree/master/guide/ranks/example_config)

**Comment by LatvianModder** [comment]
Or in config, in commands section
