### ISSUE TITLE
player's name issue 

### ISSUE THREAD

**Issue by 879492767** [LatvianModder/FTBUtilities#802]
hi, I found your mod can't distinguish player's name with same prefix but suffix different, like player xxx and player xxx1. this leads to some  unavoidable problem. it's better use player's uuid distinguish them.

**Comment by LatvianModder** [comment]
yes they can, specific name is stronger than name containing part. e.g.if there is Latvian and LatvianModder on server, if you type `lat` it might select LatvianModder, but `latvian` will always be `Latvian`

**Comment by 879492767** [comment]
I have two player name like that in server, but their chunk is shared, One player's operation of ftbu can affect another player

**Comment by 879492767** [comment]
@LatvianModder

**Comment by 879492767** [comment]
how to use uuid? I go to try this name problem agin

**Comment by 879492767** [comment]
it's strange, because I create two player id is _callme and _callme1 before, their chunk is shared, has same in rank list, and when I click one Client ftb gui, another one will open. but now this problem is gone

**Comment by 10935336** [comment]
I encountered the same problem, In FTBUtilities-5.4.0.97.
One player is called `yaohuom`and the other player is called `yaoh`. FTBUtilities sees them as the same player.
You mentioned using UUID, how to make FTBUtilities use UUID to identify players?
