### ISSUE TITLE
Game crashes when launching world if Chop Down Updated is installed

### ISSUE THREAD

**Issue by ZapikCZ** [LatvianModder/FTBUtilities#803]
[Crashlog](https://pastebin.com/kcEY8dvg)
Forge: forge-1.12.2-14.23.4.2713
FTBLib: FTBLib-5.2.0.23
FTB Utilities: FTBUtilities-5.2.0.28
Chop Down Updated: ChopDown+Updated+(1.12.2+)-1.0.12

[Chop Down Updated Github](https://github.com/Shovinus/ChopDownUpdated)

**Comment by LatvianModder** [comment]
Not an FTBU issue

**Comment by Shovinus** [comment]
XD why would he even think this was an FTBU issue :P It is fixed btw ZapikCZ

**Comment by ZapikCZ** [comment]
IDK I don't understand it, forge catches an exception in a mod, whatever that means, I report it

**Comment by LatvianModder** [comment]
There's nothing wrong with reporting issues when it says big "Caught exception from FTB Utilities" :P
