### ISSUE TITLE
Niche (but fitting) feature request

### ISSUE THREAD

**Issue by theCorvid** [LatvianModder/FTBUtilities#807]
I've been building a modpack based around non-procedural, hand-crafted worlds, but these can quickly get messy after a server's been up for a while and I want to make the pack persistence-friendly, so I looked around for a mod that could allow me to re-generate specific chunks automatically, while saving others.

There was nothing out there that I could find to make this process easy (know which chunks to keep and which to save on busy servers) but I am familiar with the chunk-claiming feature of FTB Utilities, so suggest a feature that allows un-claimed chunks to be re-generated, either manually, or at a specified interval, so that terrain can be refreshed while still allowing players to preserve their bases.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/348
