### ISSUE TITLE
AFK Spam frustration

### ISSUE THREAD

**Issue by ShadwDrgn** [LatvianModder/FTBUtilities#809]
It's a bit frustrating that movement doesn't constitute a player as returning from or prevent a player from going AFK. I understand there may not be sufficient hooks server-side for to detect this kind of thing without performance issues, but couldn't the client side of the mod determine or help determine a players state. The client knows the player is moving and when a player is idle. It could be responsible for sending a packet when the player is actually AFK or returning. I imagine one of your latest commits helps solve this by detecting movement between chunks or something along those lines, but hopefully this idea can get this to be a true AFK timer.

**Comment by LatvianModder** [comment]
Yeah, this was fixed
