### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#81]
I would quite like the idea of move than ranks than just user and admin, and at each rank level user would have the ability run certain commands can own/load x amount of chunks, there would be no set limit on of many ranks you could have or what commands each rank can run it should be all defined by server owner, should hopefully get an in game GUI by the end.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/47
