### ISSUE TITLE
Player NBTEdit - Payload no larger than 32k

### ISSUE THREAD

**Issue by generrosity** [LatvianModder/FTBUtilities#814]
FTBUtilities-5.0.2.14.jar on server - apologies if fixes have been applied since this date, i am progressing through mod compatibility. Did a quick test with .28 in a single player world and had a similar result.

Unfortunately looks like his NBT is larger than I expected, and I have no idea how much I needed to trim.  Morph has made some player NBT very, very large. I was looking to trim one user as I thought it might have been causing issues for another mod touching his inventory. If I trim the entire morph data tree from his data it saves fine. The limitation threshold isn't apparent, and the crash is quick unexpected.

Crash from NBTEdit - https://pastebin.com/LQTwr2TM
Crash from inventory access, revealing the full player NBT - https://pastebin.com/ZvWQ9W5f

Obviously working through issues with other mods and logging issues, but may be of interested that I can't use this tool to temporarily resolve these issues.

**Comment by LatvianModder** [comment]
Hm.. I didn't know there is a limit to how much data you can send over packet, I will look into this. If you search `Morph` in that file you will see that large portion of keys contains that, maybe you should report that to them, to use a different save method, because the player dat file also has limit of how large it can be

**Comment by generrosity** [comment]
I have reported it and working through issues with the other mods and logging issues, but yea unless I clear the whole tag is crashes instead of fails or warns.

It's certainly something I have suggested that they earn when they have generated far too many with morph, and might be causing issues with 'change cubes' accessing the nbt inventory data.

Thanks for having a look. I do have a workaround if needed, so will keep the test case data around.

**Comment by generrosity** [comment]
Sorry - been out of the loop, only relooked at this recently.

If I'm reading the change right, it only stops from opening a oversized, rather than preventing a crash from saving. The opening wasn't a problem, and is a useful way to reduce the oversized-ness.

**Comment by LatvianModder** [comment]
Uh.. does this help? https://github.com/LatvianModder/FTBUtilities/commit/e1ce57498f8f0a8cfdc012f06753eee692e1ef70

**Comment by generrosity** [comment]
Thanks Latvian! That looks right to me (especially if you can revert the previous change).

Thank you for you patience :) always love your work

**Comment by LatvianModder** [comment]
I won't revert previous one, it's needed too. If player already has more than 30KB of data, and you request it, it will crash, because 32KB network limit goes both ways

**Comment by generrosity** [comment]
Totally can respect that. 

I'm not too sure why my server only had issues one way/saving (loading was fine for my particular situation, immediately crashed only on save), but I'm starting to get used to using nbtexplorer instead.
