### ISSUE TITLE
Duplicate Language key with some mods

### ISSUE THREAD

**Issue by TartaricAcid** [LatvianModder/FTBUtilities#815]
`gui.active`
- ftblib `Active`
- mekanism `Water-Cooled`

`gui.search`
- ftblib `Search...` 
- pneumaticcraft `Search:` 

`commands.reload.usage`
- ftblib `/reload [*|domain:*|domain:id]`
- minecraft `/reload`

**Comment by LatvianModder** [comment]
wtf mekanism.. I think you should report this to them to change it to something like `gui.water_cooled`, because how the heck `gui.active` == Water-Cooled lol. Last one is intentional, because it replaces vanilla command, and `Search...` vs `Search:` isn't that bad but I will change it
