### ISSUE TITLE
[1.12.2] /ftb loaded_chunks_list not working.

### ISSUE THREAD

**Issue by scalda** [LatvianModder/FTBUtilities#816]
+ See if the issue isn't already reported / suggestion been made by looking up some keywords.
+ If it is, don't comment that you have the same issue, just press :+1:
+ Bugs and Suggestions will only be accepted and implemented/fixed for latest minecraft version, unless it's compatible with older one.
+ Do not add versions or "[Bug]" or "[Suggestion]" in issue title, I will tag them.

Hey this was a command we used alot in the 1.10.2 version of your mod, and i have only just found the correct wording for the command and it doesn't seem to work in the 1.12.2 version of the mods.

Was it not included or is there a different command to show active chunk loaders?

Regards

Scalda

**Comment by LatvianModder** [comment]
This feature was removed and will be eventually coming back in admin panel under server chunk administration
