### ISSUE TITLE
Looking for autorestart and backup guides

### ISSUE THREAD

**Issue by Sunconure11** [LatvianModder/FTBUtilities#817]
Its pretty obvious you changed these functionalities again. Do you have any info detailing this, so I can properly implement them once more on my own servers? Either that, or I screwed up.

**Comment by LatvianModder** [comment]
Hmm, what did I change?

**Comment by Sunconure11** [comment]
Nvm, I figured out what was happening. It turns out I had forgotten to install it on the server-end.
