### ISSUE TITLE
ranks.txt and friends get overwritten by default ones on server start

### ISSUE THREAD

**Issue by bastetfurry** [LatvianModder/FTBUtilities#819]
**Current behaviour:** Whenever the server starts the configuration files at local/ftbutilities get overwritten by the default ones.

**Expected behaviour:** Files stick to their content, loading the settings within.

**Comment by MelanX** [comment]
Do you start the server after change the file or do you restart the server?

**Comment by bastetfurry** [comment]
I have tried all variants that i know of:
- Editing in situ
- Using /reload
- Stopping the server, saving ranks.txt and then restarting
None of those work.
Even "better", if you try the ingame command it still gets overwritten with the empty defaults on restart of the server.

**Comment by LatvianModder** [comment]
Have you tried using commands under /ranks?

**Comment by bastetfurry** [comment]
All of that in any combination you can think of. If i had the time i would try to fix it myself, maybe this sunday.

**Comment by LatvianModder** [comment]
No idea what the error is without a log/crash report, and noone else has experienced this to my knowledge. Maybe file permission error or smth?

**Comment by Rikio2k** [comment]
I'm having this exact same issue on my FTB Revelation Server, and I have tried all the same things as bastetfurry

**Comment by PorPit** [comment]
i have the same issue

**Comment by bastetfurry** [comment]
Thats the problem, i can't make out any errors out of the usual [WARNING] stuff that modded servers have a galore of at startup. I can send you the logs of my custom server this evening if you think it helps. :)

**Comment by MelanX** [comment]
Did you tried with newest forge version or recommended?
Also try only with FTBLib and FTB Utilities
If it works add another mod. If it works add another mod.
while(itWorks) {
add mod;
try again;
}
lol

**Comment by PorPit** [comment]
Just one line:
[21:54:42] [Server thread/WARN] [FTBLib]: Replacing com.feed_the_beast.ftblib.lib.config.DefaultRankConfigHandler with com.feed_the_beast.ftbutilities.ranks.FTBUtilitiesPermissionHandler
