### ISSUE TITLE
Server crashes on FTB Foolcraft version 1.4.5 when using ftbutils teams

### ISSUE THREAD

**Issue by SimplyLime** [LatvianModder/FTBUtilities#820]
So i have had a few crashes in regards to ftb utils on foolcraft. the first one is when players claim chunks for the first time, the server crashes instantly. have been able to reproduce this 2 seperate times with new players.
https://gist.github.com/SimplyLime/cf2a0cc63c769fc9ac5c2164a3d3430b

Also when inviting someone to a team it seems to crash. Any help would be greatly appreciated :)
https://gist.github.com/SimplyLime/5c2696b74c0e1d2438d05460e9f813d3

**Comment by LatvianModder** [comment]
Second issue was fixed already, and maybe first one too, update your mods
