### ISSUE TITLE
[v5.2.0.31] Ranks.txt - several permissions broken

### ISSUE THREAD

**Issue by Frosthaven** [LatvianModder/FTBUtilities#821]
Recently updated our server installation of FTB Mods:
**FTBLib-5.2.0.26
FTBUtilities-5.2.0.31**

Upon doing so I noticed that practically all permissions stored in ranks.txt are no longer working. Example excerpt:
```
[player is default_player_rank]
ftbutilities.chat.name_format: "[{name}]:"
ftbutilities.chunkloader.max_chunks: 55
ftbutilities.claims.max_chunks: 150
ftbutilities.homes.max: 4
ftbutilities.homes.warmup: "10s"
ftbutilities.homes.cooldown: "0s"
ftbutilities.spawn.warmup: "10s"
ftbutilities.spawn.cooldown: "0s"
ftbutilities.tpa.warmup: "10s"
ftbutilities.tpa.cooldown: "0s"
ftbutilities.warps.warmup: "10s"
ftbutilities.warps.cooldown: "0s"
```

Results in:
 - Usernames not appearing at all in chat
 - Home maximum being set to 1
 - All time-based entries being set to 0s.

*Notes:*
 - Removing each permission line still allows the game to use the default values
 - The ranks.txt file itself is not changed and retains my defined values

Downgrading to the following versions corrects the issue:
**FTBLib-5.2.0.25
FTBUtilities-5.2.0.30**

**Comment by LatvianModder** [comment]
Well at least it doesnt reset the file anymore

**Comment by LatvianModder** [comment]
Fixed
