### ISSUE TITLE
Button loss

### ISSUE THREAD

**Issue by luenlin** [LatvianModder/FTBUtilities#823]
![image](https://user-images.githubusercontent.com/27433283/43389731-04111236-941f-11e8-9176-1bd649a9ea6c.png)
![image](https://user-images.githubusercontent.com/27433283/43389764-144b0d82-941f-11e8-9af2-248a90a95ba0.png)

It looks like my buttons are gone

**Comment by LatvianModder** [comment]
Does console/log say anything about it?

**Comment by LatvianModder** [comment]
I can't reproduce. Been playing on server with no issues too
![img1](https://ss.latmod.com/pc/2018-08-02_03.29.19.png)
![img2](https://ss.latmod.com/pc/2018-08-02_03.29.28.png)
