### ISSUE TITLE
Offline chunkloading permission not working

### ISSUE THREAD

**Issue by NLBlacky** [LatvianModder/FTBUtilities#831]
I assume that this is a issue related with the plugin as I've tried alot of things and so far nothing works.

Our server is having issues with the offline chunkloading. We want offline chunkloading to be disabled, but for a unknown reason it is still loading chunks when the player is offline even when the settings are set to not offline chunk load.

Beside FTBU there are no other mods/plugins that we use for chunkloading except Foxguard to protect our spawns. We're using Nucleus and Luckypermissions for the ranks that are displayed below.

Below you see our **ranks.txt** file in /local/ftbutilities. Each rank has a different amount of sethomes, chunks and online chunks they can claim. For some reason **ftbutilities.chunkloader.load_offline: false** does not stop offline chunk loading.

```
// This file stores rank definitions.
// 
// [name]
// permission: value
// 
// Add [name extends parent_name] to make this rank include all permissions from parent_name rank.
// Add [name is default_player_rank] or [name is default_op_rank] to make this rank default for players/ops that don't have a rank set explicitly.
// 
// For more info visit https://guides.latmod.com/ftbutilities/ranks/
// To see the list of permission nodes, open all_permissions.html in browser or all_permissions_full_list.txt

[unranked is default_player_rank]
ftbutilities.claims.max_chunks: 4
ftbutilities.chunkloader.max_chunks: 0
ftbutilities.chunkloader.load_offline: false

[copper]
ftbutilities.claims.max_chunks: 8
ftbutilities.chunkloader.max_chunks: 0
ftbutilities.chunkloader.load_offline: false

[iron]
ftbutilities.claims.max_chunks: 12
ftbutilities.chunkloader.max_chunks: 1
ftbutilities.chunkloader.load_offline: false

[gold]
ftbutilities.claims.max_chunks: 16
ftbutilities.chunkloader.max_chunks: 1
ftbutilities.chunkloader.load_offline: false

[obsidian]
ftbutilities.claims.max_chunks: 20
ftbutilities.chunkloader.max_chunks: 2
ftbutilities.chunkloader.load_offline: false

[diamond]
ftbutilities.claims.max_chunks: 25
ftbutilities.chunkloader.max_chunks: 3
ftbutilities.chunkloader.load_offline: false

[electrum]
ftbutilities.claims.max_chunks: 35
ftbutilities.chunkloader.max_chunks: 4
ftbutilities.chunkloader.load_offline: false

[darksteel]
ftbutilities.claims.max_chunks: 45
ftbutilities.chunkloader.max_chunks: 5
ftbutilities.chunkloader.load_offline: false

[manyullyn]
ftbutilities.claims.max_chunks: 50
ftbutilities.chunkloader.max_chunks: 6
ftbutilities.chunkloader.load_offline: false

[draconium]
ftbutilities.claims.max_chunks: 100
ftbutilities.chunkloader.max_chunks: 8
ftbutilities.chunkloader.load_offline: false

[awakened]
ftbutilities.claims.max_chunks: 200
ftbutilities.chunkloader.max_chunks: 10
ftbutilities.chunkloader.load_offline: false

[builder]
ftbutilities.claims.max_chunks: 50
ftbutilities.chunkloader.max_chunks: 6
ftbutilities.chunkloader.load_offline: false

[moderator]
ftbutilities.claims.max_chunks: 200
ftbutilities.chunkloader.max_chunks: 10
ftbutilities.chunkloader.load_offline: false

[admin]
ftbutilities.chunkloader.load_offline: false
ftbutilities.claims.max_chunks: 250
ftbutilities.chunkloader.max_chunks: 15
minecraft.command.gamemode: true

[highcouncil is default_op_rank]
ftbutilities.chunkloader.load_offline: false
ftbutilities.claims.max_chunks: 10000
ftbutilities.chunkloader.max_chunks: 10000
minecraft.command.gamemode: true
```

Server has the mod Revelation 2.3 running however we noticed that in Revelation 2.2 it was also not working. We're running the following versions: **FTBUtilities-5.2.0.30** and **FTBLib-5.2.0.25**

I do not know what causes it, but since the permission is not working I'm assuming it is FTBU which is why I'm posting this here and I hope that someone can give me a little more insight in where the issues lays. Thank you

**Comment by LatvianModder** [comment]
Try lib 29+ and utils 35+, I think I messed up permissions somewhere in between but fixed later

**Comment by NLBlacky** [comment]
Got Revelation 2.4 on the server now which has the latest versions of FTBU and FTBLib. Online chunks are still offline chunk loaded. 

We're still using the following: `ftbutilities.chunkloader.load_offline: false`

We however also tried to completely remove the permission, or set the value to true, however that did not do anything. It is still getting chunkloaded.

Tried changing this value however it didn't change anything either:     
```
# Enables chunk loading. If chunk_claiming is set to false, changing this won't do anything.
    B:chunk_loading=false
```

I did not touch this setting however in case it might be the reason I decided to post it here:
```
    # Unloads erroring chunks if dimension isn't loaded or some other problem occurs.
    B:unload_erroring_chunks=false
```

Or maybe it has something to do with one of these lines in the config?
```
    logging {
        # Logs block breaking.
        B:block_broken=true

        # Logs block placement.
        B:block_placed=true

        # Enables world logging.
        B:enabled=false

        # Includes creative players in world logging.
        B:include_creative_players=false

        # Includes fake players in world logging.
        B:include_fake_players=false

        # Logs item clicking in air.
        B:item_clicked_in_air=true
```
Our `ftbutilitues.cfg` in configs folder: https://pastebin.com/rkemiQ2a
and our `ranks.txt` in local/ftbutilities: https://pastebin.com/HZXLPfK6

In case it has any effect, our server is using the following plugins:
```
Aurionvotelistener
Buycraft
Catclearlag
DailyRewards
FoxGuard
HuskyCrates
LagGoggles
LuckyPerms
MMCReboot
MMCRestrict
MMCRules
MMCTickets
```

Permissions are defined in `local/ftbutilities/ranks.txt` in our server.

**Comment by LatvianModder** [comment]
Yeeeeah, LuckyPerms is probably breaking it

**Comment by phit** [comment]
luckperms doesnt do anything to ftbu, it doesnt use forge permissions it uses sponge's and sponge _still_ doesn't support forge perms sadly

**Comment by LatvianModder** [comment]
Sponge shouldn't, but for some reason it still messes up FTBU permissions, im guessing the command system is changed or something

**Comment by ktole1999** [comment]
How did you narrow down to ftbu causing offline chunkloading? Just curious.
