### ISSUE TITLE
How to use other_player.see_info

### ISSUE THREAD

**Issue by galaxy119** [LatvianModder/FTBUtilities#833]
So, not per-say an issue, but finding documentation on commands is painfully IMPOSSIBLE to find a solid answer somewhere, most of the 'guides' are outdated and half the commands have since changed. 

How do I make use of the ftbutilities.other_player options? like heal, see_info, etc?  Particularly see_info is what I need though.

**Comment by LatvianModder** [comment]
You can always check all_permissions.html. `ftbutilities.other_player.claims.see_info` is what you are looking for, I guess?

**Comment by galaxy119** [comment]
I know where to find the permission nodes, and how to give permissions to use the commands to people, the problem is.. I can't actually find the commands? Or see anywhere in the GUI that gives me info about other peoples claims?

I was also wondering, there's a permission to claim chunks for other players, but again, I find no way to *actually* do this, and there's no documentation that I can find on it.
