### ISSUE TITLE
Crash with YABBA and FTB Lib

### ISSUE THREAD

**Issue by angelnc1989** [LatvianModder/FTBUtilities#836]
Minecraft 1.12.2
Forge 14.23.4.2750
FTB Lib 5.2.0.32
FTB Utilities 5.2.0.38
YABBA 1.1.2.14
[log](https://pastebin.com/eG1peswk)

The game crashes on startup

**Comment by AznDrizzy** [comment]
same here

**Comment by AznDrizzy** [comment]
EDIT : i solved the problem by using YABBA 1.1.2.12 and FTBLib 5.2.0.25

**Comment by angelnc1989** [comment]
Yea, that solves it. Wasn't released when I tried.
