### ISSUE TITLE
Use UUIDs in player rank files

### ISSUE THREAD

**Issue by 132ikl** [LatvianModder/FTBUtilities#839]
Player name changes allow players to lose their ranks. Player ranks should be stored as UUIDs.

**Comment by LatvianModder** [comment]
Actually, the way FTBLib stores names and uuids, player names can only change *after* ranks have been loaded, so its fine

**Comment by LatvianModder** [comment]
FTBLib stores names and UUIDs. 
When ranks are loaded (on server start, with noone online) it assigns rank to uuid internally, but can use the username from FTBLib cache.
When player logs in with different username, it updates it and will save with different name. Its impossible to log in before ranks/ftblib is loaded
