### ISSUE TITLE
World Logging Not Working

### ISSUE THREAD

**Issue by MCEventHorizon** [LatvianModder/FTBUtilities#840]
Hosting a Foolcraft 3 server, version: Release-1.4.5. World logging is enabled but world.log file isn't created.
FTB Utilities version: 5.2.0.29
FTB Lib version: 5.2.0.24
![screenshot_1](https://user-images.githubusercontent.com/15619786/44570716-074d6d00-a77f-11e8-8e03-135b0eebab1f.png)

**Comment by LatvianModder** [comment]
So its working now or what

**Comment by MCEventHorizon** [comment]
Yes but the world.log wasn't in the location the config specified(local/ftbutilities/world.log), it was in logs folder.

**Comment by LatvianModder** [comment]
Oh, I gotta update that then
