### ISSUE TITLE
example_config in rank.txt resets at startup

### ISSUE THREAD

**Issue by Goten87** [LatvianModder/FTBUtilities#841]
ok sorry i cannot find this one yet so here it is
i just stopped my FTB Revelation 2.3.0 server to change the rank.txt file to have the premissions in there that i found on here the `example_config` for ranks
when i start up my server then it resets the settings back to default
```// This file stores rank definitions.
// 
// [name]
// permission: value
// 
// Add [name extends parent_name] to make this rank include all permissions from parent_name rank.
// Add [name is default_player_rank] or [name is default_op_rank] to make this rank default for players/ops that don't have a rank set explicitly.
// 
// For more info visit https://guides.latmod.com/ftbutilities/ranks/
// To see the list of permission nodes, open all_permissions.html in browser or all_permissions_full_list.txt
``` 
so this what im i doing wrong PS i leave the thing above in there as well so i start the `Example_config` after the last rule 
`// To see the list of permission nodes, open all_permissions.html in browser or all_permissions_full_list.txt` with a blank space betwen them

Sorry for my crappy english its not my main lang

**Comment by PorPit** [comment]
set load_from_config_folder to false in ftbutilities.cfg

**Comment by LatvianModder** [comment]
Yeah, example is supposed to reset..
