### ISSUE TITLE
Some little suggests～～

### ISSUE THREAD

**Issue by OldKingisdie** [LatvianModder/FTBUtilities#842]
1、If player not for a long time to log on to the server ，His claim will be cancel and terrain will be reduction，Use permission group to set this.
2、And add a Claim-mode.player can‘t break and place every block even thought in his claim.In other words,Player can do any things only in his claim.To prevent some players from destroying the survival world.It's make survival world too ugly.

Reference resources：https://github.com/MinecraftPortCentral/GriefPrevention/wiki

**Comment by TheSpicePhantom** [comment]
That's useless imo, you could easily go, claim a bit of land, erase it and unclaim, move on and leave a trail of destruction

**Comment by generrosity** [comment]
Thats a bit of an edge case, but not if you can't unclaim chunks, and you still have a chunk limit. Interesting concept tho.
