### ISSUE TITLE
Having problems with spawn protection

### ISSUE THREAD

**Issue by Sluggasaurus** [LatvianModder/FTBUtilities#845]
I cannot seem to get spawn protection to work. I've tried on both my server and single player, with and without the mod pack I use.
Myself and other players can claim things just fine, but no matter what I do, the spawn area just doesn't show up, we are also completely able to claim area in what is supposed to be the spawn area.

https://pastebin.com/D6db91QC this is a snippet of the world section of the config, am I doing something wrong or is this a bug?

**Comment by LatvianModder** [comment]
Spawn area doesn't show up in the map, it hasn't been re-added
