### ISSUE TITLE
Change minimum required forge version 

### ISSUE THREAD

**Issue by gollariel** [LatvianModder/FTBUtilities#847]
Hello. I was going to update mods on my own server, and I got stuck. FTB Utilities use latest, but the not recommended version of forge. Do you use something from the latest version? If not, could you change the required version to 2705?

Many thanks

**Comment by LatvianModder** [comment]
I updated mostly because of this bug:
```
Build 1.12.2-14.23.4.2727:
bs2609: Fix ItemHandlerHelper.giveItemToPlayer creating item entities with incorrect contents (#5007)
```
Because I use that a lot, so, no. But there's a ton of other bug fixes, you should update forge too imo
