### ISSUE TITLE
Spaces not displayed in Guides when Optifine is loaded

### ISSUE THREAD

**Issue by SteveGodwin** [LatvianModder/FTBUtilities#85]
On Windows it appears that loading Optifine along with FTBUtilities means space characters don't appear in modpack Guides or 'Server Info'.

Tested using Optifine 1.7.10_HD_U_D3 on Windows 8.1 with JRE-x64 1.8.0_25, Minecraft 1.7.10, Forge-10.13.4.1614 and FTBUtilities + FTBLib 1.7.10-1.0.17.6

Have recreated in a Curse custom profile with just these mods installed.

**Comment by SteveGodwin** [comment]
Looks like Immersive Engineering (0.7.4) has a similar problem with its in game Manual when Optifine is loaded. I assume the problem is on the Optifine side and it won't be possible to fix on the FTBU side.

May be worth an FAQ entry.

**Comment by LatvianModder** [comment]
Yeah, modders also don't really support Optifine :P
Also, can't / won't fix this bug, since it's not on my side
