### ISSUE TITLE
How to enable Ranks in FTBUtilities-1.7.10-1.0.18.3

### ISSUE THREAD

**Issue by pthoelken** [LatvianModder/FTBUtilities#850]
Hello, 

We're using the latest FTB-IE server version which was released. In this modpack the FTBU version "FTBUtilities-1.7.10-1.0.18.3.jar" is installed. So, how can I enable and use Ranks für my players in this mod version? I can't find this setting in local/ftbu/config.json, also I can't find player_ranks.json.

But, surprising, I can find the option "show_rank" in the ftbu/config.json file. I'm a little bit cofused. Is the Rank-System available in my mod version or not? 

![image](https://user-images.githubusercontent.com/12643853/45435824-a7792080-b6b1-11e8-96e9-28dc8980cc8a.png)

Thanks in advanced.

**Comment by LatvianModder** [comment]
There are no ranks in 1.7.10

**Comment by pthoelken** [comment]
Thanks for these information. :-)
