### ISSUE TITLE
Possible to enable block protection for specific rank

### ISSUE THREAD

**Issue by pthoelken** [LatvianModder/FTBUtilities#858]
Simple question: How can I enable block protection for guest player rank? 

**FTBG/L/U Verions**
- FTBGuides-1.0.2.14.jar     
- FTBLib-5.2.0.31.jar        
- FTBUtilities-5.2.0.37.jar

**Currently guest rank**
![image](https://user-images.githubusercontent.com/12643853/45738163-01b53c80-bbf0-11e8-8e2a-4aa3f2639abb.png)

Thanks in advanced for your help.

**Comment by LatvianModder** [comment]
Not yet. https://github.com/LatvianModder/FTBUtilities/issues/673
