### ISSUE TITLE
RTP teleports players into world border

### ISSUE THREAD

**Issue by 132ikl** [LatvianModder/FTBUtilities#859]
When running /rtp, it does not check if the player will be teleported into the worldborder.
Minecraft Version: 1.12.2
Version: 5.3.0.48
Operating System: Ubuntu 16.04 LTS GNU/Linux

Steps to Reproduce:
/worldborder center 0 0
/worldborder set 1000
/rtp

You have a very high chance of being teleported into the border, killing the player.

**Comment by LatvianModder** [comment]
Actually, there shouldn't be an issue - you can configure rtp_min_distance and rtp_max_distance

**Comment by 132ikl** [comment]
But that is relative to the player's position, not the world center, correct? Because if a player is standing right next to the world border and runs the command they will be teleported outside even with the options set.

**Comment by ktole1999** [comment]
i thought it was relative to world spawn.

**Comment by LatvianModder** [comment]
Its supposed to be
