### ISSUE TITLE
/reload_client loads common first

### ISSUE THREAD

**Issue by cblair91** [LatvianModder/FTBUtilities#86]
When running /reload_client, it loads the common scripts first.
However, when doing /reload it loads the difficulty scripts and then the common scripts after.

It should load common scripts last as allows servers to have override recipes for things.

**Comment by LatvianModder** [comment]
I think I could remove common folder completely, that would make things easier for FTB Tweaks

**Comment by cblair91** [comment]
How'd we go about doing server overrides then? Because I tried a script in the modpack diffuculty, scripts directory. All of them caused it to show, but be disabled from clicking? Common seemed the only one to work

**Comment by LatvianModder** [comment]
The scripts should match client and server side. Not even sure what happens when they don't, because my mod overrides normal MineTweaker behaviour

**Comment by cblair91** [comment]
Well if I do a /reload, clients get sent the common file and all works magically with custom server recipes, but logging out/in, and doing /reload_client causes it to not load (as one of the recipes we do is removed/overrided by a script in the modpacks dir)

**Comment by LatvianModder** [comment]
Alright. But after player joins, if you do /reload, does the player see the new recipes?

**Comment by cblair91** [comment]
Yup, as the server reloads the modpack difficulty, then common and sends it to the client as expected.

**Comment by LatvianModder** [comment]
Then this is the same issue as
https://github.com/LatvianModder/FTBUtilities/issues/84
This is being worked on
