### ISSUE TITLE
Server Crashing IDK why

### ISSUE THREAD

**Issue by CrankySupertoon01** [LatvianModder/FTBUtilities#860]
Server is crashing. Crash log and debug log say nothing. except this error

**Comment by CrankySupertoon01** [comment]
[debug-5.log](https://github.com/LatvianModder/FTBUtilities/files/2408124/debug-5.log)
[2018-09-22-2.log](https://github.com/LatvianModder/FTBUtilities/files/2408125/2018-09-22-2.log)
[crash-2018-09-22_20.28.52-server.txt](https://github.com/LatvianModder/FTBUtilities/files/2408126/crash-2018-09-22_20.28.52-server.txt)

**Comment by LatvianModder** [comment]
You are many versions behind, update mods first
