### ISSUE TITLE
What would happen in this chunkload scenario?

### ISSUE THREAD

**Issue by 132ikl** [LatvianModder/FTBUtilities#861]
This isn't quite an issue, but it's something that should be addressed nonetheless.

Let's say three players are on a team.

One player has `ftbutilities.chunkloader.load_offline: true` in their rank, and the two others have `ftbutilities.chunkloader.load_offline: false` set in their ranks. Would all of the team's chunks be loaded offline, because one person has load_offline: true? Or is it based off a majority? What if the team only had two players, and one had load_offline set to true.

Thanks

**Comment by LatvianModder** [comment]
Even if one player has that permission, all chunks will be loaded offline
