### ISSUE TITLE
Team not creating

### ISSUE THREAD

**Issue by Cainpain** [LatvianModder/FTBUtilities#865]
Trying out FTB utility on new server. Cant create team. It says its been created in chat but when i exit the UI and go back in its gone. So then i cant clam blocks since i'm not in a team.

**Comment by Alaberti** [comment]
What's your modlist? I'm seeing something similar where players can't join a team unless you set it to free to join.

**Comment by LatvianModder** [comment]
I think this was fixed already in latest versions. If you updated to latest FTBU and lib and it still happens, reopen issue
