### ISSUE TITLE
Unable to register an event handler on BackupEvent

### ISSUE THREAD

**Issue by csdivad** [LatvianModder/FTBUtilities#869]
I created an [event handler](https://gist.github.com/csdivad/ebc6ef9f8c5ea695b09b0a91babde585) for BackupEvent.
But I got this [exception](https://gist.github.com/csdivad/b7b5b2851a2fa6d866923053d8069c6a) during initialization.

Tried with Forge 2765 and 2770.

I fooled around with the whole forge event system and it looks broken. But maybe I'm doing something wrong.

**Comment by LatvianModder** [comment]
You must listen to either `BackupEvent.Pre` or `BackupEvent.Post`, not `BackupEvent` itself
