### ISSUE TITLE
Please provide instructions for editing the normal mode guide

### ISSUE THREAD

**Issue by Fearzu** [LatvianModder/FTBUtilities#87]
When editing the normal mode guide - I add folders and text files server side. After doing this, I perform a /reload for both server and client. None of my changes are ever updated on the server - it remains the same even after a restart, showing only "Admin Commands" and "Expert Mode".

**Comment by LatvianModder** [comment]
Because on server side you must put guides in /local/guide/...
And you will only see the server guides from "Server Info" button

**Comment by Fearzu** [comment]
Worked, thanks for the reply Lat!
