### ISSUE TITLE
Deleting commands in ranks.txt

### ISSUE THREAD

**Issue by BrenBlaze** [LatvianModder/FTBUtilities#871]
Attempting to give people more homes, having endless trouble. I confirmed the changes are working by modifying the name tag, but when I add homes and fly they get deleted by the server resetting the file. The home number is also ineffective. Below is what I try and save before its overwritten.

// This file stores rank definitions.
// 
// [name]
// permission: value
// 
// Add [name extends parent_name] to make this rank include all permissions from parent_name rank.
// Add [name is default_player_rank] or [name is default_op_rank] to make this rank default for players/ops that don't have a rank set explicitly.
// 
// For more info visit https://guides.latmod.com/ftbutilities/ranks/
// To see the list of permission nodes, open all_permissions.html in browser or all_permissions_full_list.txt

[player is default_player_rank]
command.ftbutilities.fly
commad.ftbutilities.home
command.ftbutilities.home.max_homes: 70

[admin is default_op_rank]
*: true
ftbutilities.chat.name_format: "<&2{name}&r>"

**Comment by LatvianModder** [comment]
`commad.ftbutilities.home`... `commad`
Also I'm guessing you *didn't* check out all_permissions.html where `ftbutilities.homes.max` is written, not `command.ftbutilities.home.max_homes`

**Comment by BrenBlaze** [comment]
Yes I did but it's confusing how its seperated . Really don't know what the goal of half of that is.
