### ISSUE TITLE
FTB Ranks Config Not Sticking

### ISSUE THREAD

**Issue by carbotaniuman** [LatvianModder/FTBUtilities#872]
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [
      "ftbu.claims.max_chunks": 30,
      "ftbu.chunkloader.max_chunks": 5
      ],
      "config": {}
    },
    "vip": {
      "parent": "player",
      "permissions": [
      "+ftbu.chunkloader.load_offline",
      "ftbutilities.homes.max": 2,
      "ftbu.claims.max_chunks": 50,
      "ftbu.chunkloader.max_chunks": 50
      ],
      "config": {}
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}

This config is not sticking. Is there a syntax error somewhere?

**Comment by LatvianModder** [comment]
This is old and unsupported. Use newer version of the mod https://github.com/LatvianModder/FTBUtilities/tree/master/guide/ranks/config
