### ISSUE TITLE
Starting Items being given multiple times to players

### ISSUE THREAD

**Issue by terrapin47** [LatvianModder/FTBUtilities#874]
Version: 5.3.0.52

I'm not sure how to give helpful information on this, but this was something that one of my users reported to me intermittently, and ( after a long time of not experiencing it through normal play ) I recently have been experiencing it myself.  Rarely when logging into singleplayer or a server of a world already previously joined, I will receive the starting items set in the cfg a second time.

If it helps, here are my starting items:
```
    S:starting_items <
        {id:"minecraft:stone_sword",Count:1,Damage:0,tag:{display:{Name:"Stonesbane"}}}
        {id:"minecraft:wooden_axe",Count:1,Damage:0,tag:{display:{Name:"Woody"}}}
        {id:"minecraft:wheat_seeds",Count:16,Damage:0}
        {id:"minecraft:torch",Count:16,Damage:0}
        {id:"harvestcraft:friedchickenitem",Count:1,Damage:0}
        {id:"naturescompass:NaturesCompass",Count:1,Damage:0}
        {id:"natura:respawn_obelisk",Count:1,Damage:0}
     >
```

I am using my modpack when this happens ( https://minecraft.curseforge.com/projects/chris-quest )

**Comment by LatvianModder** [comment]
I changed the way items are given in one of FTBU releases, it shouldn't happen again
