### ISSUE TITLE
PortalAgent Bug

### ISSUE THREAD

**Issue by Master-Jynx** [LatvianModder/FTBUtilities#877]
This will be a little wordy, I apologize in advance.
This is about a bug with FTB Teams, FTB Quests, Sky Claims, ForgeSponge and FTB Sky Adventures Modpack
I'm just a player on the FTB Complex Gaming Network and have been trying to play on their
FTB Sky Adventures server.
They use ForgeSponge because it has the plugins needed to manage their servers, diagnose crashes and profile server performance to deal with lag issues.
They use 2 overworlds to make world resets easier and faster.
Spawn is in 1 dim and the entire 2nd dim is reserved for player islands.
Sky Claim is used because of the bug i'll be writing about.

The Modpack was made so that normally when a player joined the server they would use the 
"Create Team" Button on the FTB Team GUI to create their own team or to join another.
If they made their own team,they would be teleported to world spawn , an island would be created for them, their Quests would be reset, they would be given the starter items and teleported to their island.
If they needed to reset their island, they would use the "Exit Team" button on the 
FTB Team Gui.
This would teleport them to world spawn, delete their island, remove from from any team and clear their inventory and quests.
They would have to join someone elses team or create a new on using the FTB Team GUI.

But the FTB Team GUI reports an error in the chat window when the Create Team button is used.
java.lang.ClassCastException: com.feed_the_beast.ftblib.lib.math.TeleporterDimPos cannot be cast to org.spongepowered.api.world.PortalAgent
The following link is for an issue posted on Sponge's Github a few month's ago, by someone else.
It's the response and discussion of the cause and fix that i want to refer you to.
https://github.com/SpongePowered/SpongeForge/issues/2266

The GC network has tried using Sky Claims to get around this error.
It has its own commands for creating , deleting and reseting islands.
FTB Teams, is not verifying which dimension it is teleporting players to.
Because of Sky Claims the Create Button will try to TP the player to the other Dim, which is correct,
but its using methods intended for tp'ing to the same Dim.

It also causes other very serious bugs, which i wont go into, since fixing the tp bug would eliminate the other bugs

**Comment by LatvianModder** [comment]
There always is the Team Islands mod which seems to do the same - teleport players to islands (that can be created from template). But otherwise, this is a sponge bug and I can't really fix it.
