### ISSUE TITLE
Crash on startup 1.10.2

### ISSUE THREAD

**Issue by DeinAlbtraumTV** [LatvianModder/FTBUtilities#879]
Hey, i´m creating a modpack, but when i start it, the game crashes at the end of 2/7. I have this  forge version installed: 12.18.1.2084 ! Crashreport added!
[crash-2018-11-12_17.44.23-client.txt](https://github.com/LatvianModder/FTBUtilities/files/2572835/crash-2018-11-12_17.44.23-client.txt)

**Comment by DeinAlbtraumTV** [comment]
Changing to a stable forge version didn´t solved my problem! :sob:

**Comment by DeinAlbtraumTV** [comment]
here the crashreport
[crash-2018-11-12_18.30.39-client.txt](https://github.com/LatvianModder/FTBUtilities/files/2572938/crash-2018-11-12_18.30.39-client.txt)

**Comment by DeinAlbtraumTV** [comment]
and now, last update i hope, i got a new exception at 6/7
[crash-2018-11-12_18.51.08-client.txt](https://github.com/LatvianModder/FTBUtilities/files/2573025/crash-2018-11-12_18.51.08-client.txt)

**Comment by LatvianModder** [comment]
Sorry, 1.10.2 is no longer supported
