### ISSUE TITLE
Ranks.txt reset upon server restart

### ISSUE THREAD

**Issue by BlackjackMKV** [LatvianModder/FTBUtilities#880]
I've been trying to get FTBUtilities set up, specifically the ranks and permissions, but any time I start the server or reload it, it wipes the ranks.txt back to default. It's driving me nuts. Here's what I am trying to put in it(Yes, I know the permissions are awful, this is just me testing it before dumping hours into it): https://pastebin.com/J9dn30kb

I'm running with FTBUtilities 5.3.0.53 and FTBLib 5.3.1.57. Forge version is 14.23.4.2765.

Anyone know what I'm doing wrong? Up until now, I've used Thermos, MCPC+, or Cauldron, so I'm familiar with the Bukkit/Spigot style perms, but less so with the Forge ones.

**Comment by BlackjackMKV** [comment]
I assume the new bug label means it relates less to me and more to the version I'm using? If so, what would be a good version to downgrade to? Ideally one that uses the txt file, but I don't mind JSON if necessary. Just hoping I can copypaste what I have already done in.

**Comment by LatvianModder** [comment]
Your ranks file seemed fine, I still have to check it on my side, but this looked more like a bug. It will be easier for me to fix it than you to find a proper FTBLib and FTBU version combo :P

**Comment by BlackjackMKV** [comment]
New version is still resetting it with the same config.

**Comment by BlackjackMKV** [comment]
Running version FTBUtilities-5.3.0.56 and FTBLib-5.3.1.60, but still experiencing the issue. Resets upon startup every time. What exactly is wrong with it? I've attached my latest.log and debug.log in hopes it might help you track it down.
[latest.log](https://github.com/LatvianModder/FTBUtilities/files/2612995/latest.log)
[debug.log](https://github.com/LatvianModder/FTBUtilities/files/2612996/debug.log)

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/891

**Comment by BlackjackMKV** [comment]
Is the issue solved now then?

**Comment by BlackjackMKV** [comment]
Updated to newest version of FTBLib(5.4.0.73) and FTBUtilities(5.3.0.68), still experiencing data resets for the ranks.

**Comment by LatvianModder** [comment]
There was a bug where badges would reset but thats about it, everything else worked fine, not sure whats not working here. Maybe you have some other mod, like Thut or Sponge, then its not gonna work properly
