### ISSUE TITLE
FTB lib crashes with FTB quest

### ISSUE THREAD

**Issue by catcd1w3r5** [LatvianModder/FTBUtilities#881]
FTB lib 5.3.1.57 crashes when FTB quest 1.2.1.62 on forge 14.23.5.2775
(Currently all latest versions)

steps to duplicate
get forge 
add FTB lib and FTB quest
will crash during initialization

Crash Report >   [crash-2018-11-16_19.03.13-client.txt](https://github.com/LatvianModder/FTBUtilities/files/2588987/crash-2018-11-16_19.03.13-client.txt)

I posted on FTBUtilities issue page as the "Report a bug" link on curseforge for FTB Lib directed me here

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBQuests/issues/81#issuecomment-439366123
