### ISSUE TITLE
Can not set permissions as I wish

### ISSUE THREAD

**Issue by Aathoss** [LatvianModder/FTBUtilities#886]
[player is default_player_rank]
ftbutilities.back.cooldown: "0s"
ftbutilities.homes.cooldown: "0s"
ftbutilities.rtp.cooldown: "1m"
ftbutilities.spawn.cooldown: "0s"
ftbutilities.tpa.cooldown: "0s"
ftbutilities.warps.cooldown: "0s"
ftbutilities.chunkloader.max_chunks: 15
ftbutilities.claims.max_chunks: 50
ftbutilities.homes.max: 3
ftbutilities.chat.name_format: "&aMember &r{name}:"

Can not decrease cooldown less than 5
Can not decrease the claims max less than 300
Can not decrease max chunkloader below 60

Forge 1.12.2-14.23.5.2768
FTBUtilities 5.3.0.53

These are the most important configuration that does not work as it should

**Comment by LatvianModder** [comment]
Probably related with #880
