### ISSUE TITLE
Make hyperlinks in login motd clickable

### ISSUE THREAD

**Issue by phit** [LatvianModder/FTBUtilities#89]
Pretty much title would be nice to be able to link your servers website etc. in the server login motd.

**Comment by LatvianModder** [comment]
Easy. Consider it done :P

**Comment by LatvianModder** [comment]
Except it won't be the regular "Text http://link.com more text", but it will use Vanilla's IChatComponent formatting
http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/351959-1-9-json-text-component-for-tellraw-title-books

**Comment by phit** [comment]
sounds good :)

**Comment by LatvianModder** [comment]
Aw, dang. I released 18.1 and forgot about this :/ Will add in next version :P

**Comment by LatvianModder** [comment]
Added in https://github.com/LatvianModder/FTBUtilities/commit/515a7f66f174d6ae7eec3e1d43178e983b429095

**Comment by phit** [comment]
thanks!

**Comment by phit** [comment]
could you provide an example of the formatting please?

**Comment by LatvianModder** [comment]
http://pastebin.com/BdvEkQf9

**Comment by LatvianModder** [comment]
This is for 1.0.18+ versions of the mod
