### ISSUE TITLE
Rank file not working

### ISSUE THREAD

**Issue by Goten87** [LatvianModder/FTBUtilities#894]
hello sorry if this is posted already (i was not able to find anything about it)
so i did add some info to ranks.txt to test how it works

```
[player is default_player_rank]
ftbu.claims.max_chunks: 1000
ftbu.chunkloader.max_chunks: 1000

[op is default_op_rank]
ftbu.claims.max_chunks: 2000
ftbu.chunkloader.max_chunks: 2000
```
and its not loading at all
when i go to my server (as op) i only have 1100 claimed chunks max and 114 loaded chunks max
what im a doing wrong

**Comment by LatvianModder** [comment]
Wrong permission node name, change `ftbu.` to `ftbutilities.`

**Comment by Woody-0w0** [comment]
What ever i do could not change max_chunks for admin. It is aiways 1000 .

**Comment by Woody-0w0** [comment]
[admin]
power: 100
default_op_rank: true
ftbutilities.chat.name_format: <&2{name}&r>
example.permission_with_value: 100
ftbutilities.claims.max_chunks: 99999
ftbutilities.chunkloader.max_chunks: 10

**Comment by Woody-0w0** [comment]
But max_chunks for Player works
