### ISSUE TITLE
JEI Bookmarks Covered by FTBUtil Interface

### ISSUE THREAD

**Issue by SalmonSays** [LatvianModder/FTBUtilities#897]
I assume this is known, but I couldn't find an open ticket so I figured it couldn't hurt to make sure one gets made. JEI releases (jei_1.12.2-4.13.1.226.jar) and onward introduce a Bookmarks list to the left side of the screen. This currently conflicts with the FTBUtils interface and results in certain functions not being properly click-able.

![ydjxuba](https://user-images.githubusercontent.com/11697389/49346150-ad98f080-f653-11e8-8ac8-283054a2cf05.png)

**Comment by Gyffen1971** [comment]
@SalmonSays I have both installed and the JEI releases(jei_1.12.2-4.14.0.231.jar) and FTBUtilites (FTBUtilities-5.3.0.67.jar) and MineCraft 1.12.2 and FTBUtil is not interfering with JEI Bookmarks and vice-a-versa.  I beleave it could be that you are using an older version of MineCraft.
![minecraft 1 12 2 13-dec-18 3_04_51 am](https://user-images.githubusercontent.com/44150440/49924964-95ac4280-fe85-11e8-860a-2e18a10fe86d.png)

**Comment by LatvianModder** [comment]
It's been fixed in later versions
