### ISSUE TITLE
enable_pvp is case sensitive. 

### ISSUE THREAD

**Issue by KaneHart** [LatvianModder/FTBUtilities#904]
FTBUtilities-5.3.0.67.jar

So in my ftbutilities.cfg I set S:enable_pvp=TRUE to S:enable_pvp=false and encountered the following error:
https://pastebin.com/pgFAwtxa

Clearly it's related to casing but the rest the file (or so far) seems to be all lowercase or allows lowercase. Where this has to be Uppercase. 

Just a small derp bug :)

**Comment by LatvianModder** [comment]
This is not really a bug or anything I can fix, because it's an Enum with values TRUE, FALSE and DEFAULT and forge doesn't ignore case for configs
