### ISSUE TITLE
Confusion... Installation?

### ISSUE THREAD

**Issue by Darkcl0ud** [LatvianModder/FTBUtilities#905]
A little confused. I added FTBUtils and Lib to my server, though I only have access to a single FTB command, ftblibsimulatebutton.

Any help? Running 1.12.2

**Comment by thetakodev** [comment]
Many commands don't start with "ftb". For example, you should have "/home", "/warp", "/spawn" and many more. Also you can install these mods on client to get an awesome fancy GUI.

**Comment by Darkcl0ud** [comment]
Ah yes... I have gotten that sorted out... My new issue is Chunkloading isn't working at all on my server. I have it set to load chunks in the map, however I am not receiving drops from the farm I have set up when I am not in that chunk... I have actually tried multiple mods to achieve this and no luck. Going to try with FTBUtils by itself and report back.
