### ISSUE TITLE
Add a button to world creation for game mode 

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#92]
When making a world with more than one game is detected there should be an extra button which goes through all of the game modes, that way single player world do not need cheats enabled (yes I know open to lan with cheat enables lets you but not every one does).

**Comment by LatvianModder** [comment]
Actually, Im pretty sure you dont need cheats enabled in singleplayer world anymore to use /ftb_mode. If you still do, its a bug, but I think I disabled that long time ago :P
I MIGHT consider a button, but I promise nothing :P
