### ISSUE TITLE
Get game mode from other mod

### ISSUE THREAD

**Issue by Dijkstra1** [LatvianModder/FTBUtilities#93]
There are some things that mine tweaker just can not control, so is there a way for me to make mod that can get the game mode and say e.g. 

```java
if(ftb_game_mode == "Easy"){
      //do easy stuff
}
else if (ftb_game_mode == "Expert"){
     //do expert stuff
}
```

I understand such a mod would have just for the one pack or ones with same mods, and game modes, but it would be nice to change more than just recipes. Like mobs are stronger, machines need more RF to work you get the picture.  

Edit: Need to learn Markdown

**Comment by LatvianModder** [comment]
If you want to make a mod that depends on gamemodes, you can either directly depend on FTBLib and read the mode from API (doesnt have to be a hard dependency, check how [Jared does it](https://github.com/jaredlll08/FTBTweaks/blob/master/src/main/java/ftb/ReloadHandler.java#L19) or you can check if world/ftb_gamemode.txt exists (or smth, I dont even remember :P) and work from there. I recommend the API way
