### ISSUE TITLE
/jail command

### ISSUE THREAD

**Issue by ghost** [LatvianModder/FTBUtilities#95]
Suggestion to add a few commands. This would make it possible to jail a player temporarily on a server instead of banning them for minor rule breaks. Currently they can use commands to simply warp away:

/set jail
Sets the chunk you are standing in as the jail chunk and protects it.

/del jail
Removes the current jail chunk.

/jail <player>
TP's player to jail chunk and removes ability to use /warp, /home, /back, etc. (Could be ability to use any commands)

/release <player>
Restores ability for jailed player to use /warp, /home, /back, etc. Player could then warp home.

**Comment by Dijkstra1** [comment]
Probably a good idea to go with this is while in jail you can not use /home or /back

**Comment by Fearzu** [comment]
any commands really - warp & /spawn too.

**Comment by Fearzu** [comment]
This could be further simplified by just adding the ability to remove a players capability to use commands. To be honest a jail could be constructed in many ways without needing a chunk or release command etc.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/645
