### ISSUE TITLE
No guides about this mod?

### ISSUE THREAD

**Issue by Zaflis** [LatvianModder/FTBUtilities#97]
I'm a server admin and would like to know how to use this mod. I can't use command like this in FTB's infinity skyblock, it tells it's unknown command:

    /setwarp 0

Also is it possible to set world spawn for each player individually? I've tried to search for list of available commands, but all links have expired, such as:

You can view all commands here: http://pastebin.com/59Ffhn4W

**Comment by Zaflis** [comment]
I found a /spawnpoint [name]  command after watching one tutorial video i found, which pointed to a ingame list of commands.

About the /setwarp, i assume it's something that was only just removed and being replaced with some other UI way later?

**Comment by LatvianModder** [comment]
Fixed the link. New info links are

https://github.com/LatvianModder/ModGuides/blob/ftbl/guide/common/cmds.txt
and
https://github.com/LatvianModder/ModGuides/blob/ftbu/guide/common/cmds.txt
