### ISSUE TITLE
Allow block usage, but not placement/destruction

### ISSUE THREAD

**Issue by rkelbley** [LatvianModder/FTBUtilities#98]
I was hoping there was something in the configs to allow this, but haven't been able to find anything. Essentially, I'd like to allow players to *use* blocks within my claimed chunk (e.g. opening doors and chests, pressing levers or buttons, etc.), but just be unable to place or break any blocks within the chunk. Is this possible already and I just haven't figured it out?

**Comment by LatvianModder** [comment]
Currently, its a common setting, because placing = rightclicking and I can't tell if player wants to open door or place block, because that is the same action. In future, there might be a whitelist setting for blocks that can be right-clicked, but there isn't currently
