### ISSUE TITLE
Make chunk explosions only cancel block damage, not entity damage

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#99]

**Comment by Dijkstra1** [comment]
Yes that would nice when ever i see creeper I do not care because I know he can not do any thing to me.

**Comment by TheBrain0110** [comment]
Can I give this a bump?

It would be great if it worked the same way `/gamerule mobGriefing false` does in claimed chunks, so explosions can still happen, just not create holes. As it is, watching a creeper simply vanish when it's about to go boom is just silly :p

**Comment by LatvianModder** [comment]
Is this good? https://youtu.be/YE4YB7w-Fdk

**Comment by TheBrain0110** [comment]
Yeah, looks great!
